Neos.Flow/Classes/ObjectManagement/CompileTimeObjectManager.php
Neos.Flow/Configuration/Settings.Object.yaml

The setting ``Neos.Flow.excludeClasses`` was deprecated since a while
but the code handling it was not removed until now.

TASK: Remove references to excludeClasses from object management

---

Neos.Flow/Classes/Http/Component/TrustedProxiesComponent.php
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Http.rst
Neos.Flow/Resources/Private/Schema/Settings/Neos.Flow.http.schema.yaml
Neos.Flow/Tests/Unit/Http/Component/TrustedProxiesComponentTest.php

This adds support for setting the standardized `Forwarded` Header as described in RFC 7239 Section 4 (https://tools.ietf.org/html/rfc7239#section-4), as the `headers` trusted proxy setting.
Also, this change allows to set a single header value for the `headers`, so that working with the single `Forwarded` header is more convenient:
```
Neos:
Flow:
http:
trustedProxies:
headers: 'Forwarded'
```
Resolves: #1060

FEATURE: Add Forwarded Header support

---

Neos.Flow/Classes/Persistence/Doctrine/Query.php
Neos.Flow/Tests/Functional/Persistence/Doctrine/QueryTest.php

Before it was possible that a query with implicit joins created a result set with duplicate entries.
This change sets the `distinct` flag on the query object to true when an implicit join is created.
This is breaking, as it might change the result sets of your queries, if you used implicit joins (dot notation subproperty queries).
Resolves #552

!!!TASK: Implicit joins in a query makes the result set distinct by default

---

Neos.FluidAdaptor/Classes/ViewHelpers/Form/CheckboxViewHelper.php
Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Form/CheckboxViewHelperTest.php

When a collection property with objects is bound to a checkbox VH,
this change makes sure to check object identifiers against the passed
value when automatically determining the `checked` state.
Fixes #1229

BUGFIX: Detect checked state for bound object collections

---

Neos.Flow/Classes/Http/Request.php
Neos.Flow/Tests/Unit/Http/Component/TrustedProxiesComponentTest.php

This in turn will actually make the method take the trusted proxy settings into account instead
of a hardcoded list of headers.
Also, this change removes the test for the `Forwarded` header, because the test had wrong expectations
on the actual formatting of the header value. See #1060

TASK: Make HTTP Request getClientIpAddress() use the request attribute value

---

Neos.Flow/Classes/Configuration/ConfigurationManager.php
Neos.Flow/Tests/Unit/Configuration/ConfigurationManagerTest.php

The configurationManager.replacePlaceholder() method must not use a
string type hint for the subject, since in fact that can be an array.

BUGFIX: Wrong type hint on replacePlaceholders

---

Neos.Flow/Classes/Error/Debugger.php

The styles for rendering the debug-output are now rendered with the
first output itself instead of being echoed.
The direct echo solution caused trouble whenever non html-data like
json was rendered because the styles were rendered outside the json-structure 
and thus caused invalid json.

BUGFIX: Render debugger-styles directly with first debug-output

---

Neos.Flow/Configuration/Settings.Reflection.yaml
Neos.Flow/Tests/Functional/Persistence/PersistenceTest.php
Neos.Flow/Tests/Functional/Reflection/ReflectionServiceTest.php
Neos.Flow/Tests/Functional/Session/SessionManagementTest.php
Neos.Flow/Tests/Unit/Error/DebuggerTest.php
Neos.Flow/Tests/Unit/Http/Component/ComponentChainTest.php
Neos.Flow/Tests/Unit/Http/HeadersTest.php
Neos.Flow/Tests/Unit/Http/RequestTest.php
Neos.Flow/Tests/Unit/Mvc/Controller/MvcPropertyMappingConfigurationServiceTest.php
Neos.Flow/Tests/Unit/Property/PropertyMapperTest.php
Neos.Flow/Tests/Unit/Reflection/ClassSchemaTest.php
Neos.Flow/Tests/Unit/ResourceManagement/Storage/WritableFileSystemStorageTest.php
Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Form/AbstractFormFieldViewHelperTest.php

This replaces dummy assertions used to silence PHPUnit warnings with the
use of the `@doesNotPerformAssertions` annotation.

TASK: Remove dummy assertions from tests

---

Neos.Cache/Classes/Backend/RedisBackend.php

The type hints broke correct detection of hits/misses in the cache
backend.

BUGFIX: Fix broken cache get/set in RedisBackend

---

Neos.Flow/Classes/Error/ProductionExceptionHandler.php

Just a few lines above the reference code may be set to null, and two lines
down the file a check against null is made. So, null is to be tolerated!

BUGFIX: Make $referenceCode nullable in ProductionExceptionHandler

---

Neos.Kickstarter/Resources/Private/Generator/View/DefaultLayout.html

Removes the f:base viewhelper from kickstarted Layout template file since the viewhelper does no longer exist.

BUGFIX: Remove usage of removed f:base viewhelper from kickstarter

---

Neos.Eel/Classes/CompilingEelParser.php
Neos.Eel/Classes/EelParser.php
Neos.Eel/Resources/Private/Grammar/Eel.peg.inc
Neos.Eel/Tests/Unit/CompilingEvaluatorTest.php

Adds support to parse and evaluate arrow function expressions in Eel.
This is only implemented for the CompilingEelEvaluator, since
expression evaluation need to be deferred in functions.
Arrow function arguments can be specified with or without parentheses.
The body must be an expression and not a block.
Example:
map(items, (x) => x * x)

FEATURE: Arrow function expressions in Eel

---

Neos.Cache/Classes/Backend/RedisBackend.php

TASK: Don’t set return type for RedisBackend->key()

---

TYPO3.Flow/Classes/TYPO3/Flow/Package.php
TYPO3.Flow/Classes/TYPO3/Flow/Resource/ResourceManager.php
TYPO3.Flow/Classes/TYPO3/Flow/Resource/ResourceRepository.php
TYPO3.Flow/Configuration/Testing/Settings.yaml
TYPO3.Flow/Tests/Functional/Resource/ResourceManagerTest.php
TYPO3.Flow/Tests/FunctionalTestCase.php

This solves the following case…
Given these settings:
resource:
collections:
readableFilenames:
storage: 'readableFilenameResourcesStorage'
target: 'readableFilenameResourcesTarget'
storages:
readableFilenameResourcesStorage:
storage: 'TYPO3\Flow\Resource\Storage\WritableFileSystemStorage'
storageOptions:
path: '%FLOW_PATH_DATA%Persistent/ReadableResources/'
targets:
readableFilenameResourcesTarget:
target: 'Acme\AcmeCom\FilenameFileSystemSymlinkTarget'
targetOptions:
path: '%FLOW_PATH_WEB%Files/'
baseUri: 'Files/'
I want to "move" a resource from the `persistent` to the `readableFilenames` collection. To do this, I get an asset, fetch the resource and import it into the `readableFilenames` collection. After that the newly imported resource is published, assigned to the asset and then the …

BUGFIX: Allow to delete "used" resources from a storage

---

TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/RedisBackend.php

The `exists()` method returned TRUE or FALSE in phpredis versions < 4.0.0, now it
returns the number of keys tested that do exist.

BUGFIX: Adjust has() to phpredis >= 4.0.0

---

Neos.Flow/Classes/Log/LoggerFactory.php

As discussed[1] - set third parameter to "true" to do the correct comparison.
If this parameter is set to true, a class name string as "object" is allowed.
[1] https://neos-project.slack.com/archives/C04PYL8H3/p1526288487000147

BUGFIX: Fix distinction between PSR and legacy loggers in the LoggerFactory

---

Neos.Flow/Classes/Configuration/ConfigurationManager.php
Neos.Flow/Tests/Unit/Configuration/ConfigurationManagerTest.php

**What I did**
Allowed usage of multiple '%env:NAME%' per Settings. In Flow versions below 4.0, this used to work fine. Since 4.0 the ConfigurationManager uses a different regular expression which
only matches the last environment variable used in a Setting.
Modified the regex used to parse the Configuration of Environment Variables.
Run tests or add Setting that has two Environment Variables in it (`something: '%env:VAR1% something else %env:VAR2%'`).
**Checklist**

BUGFIX: Allow usage of multiple '%env:' replacements per Setting

---

Neos.Kickstarter/Classes/Service/GeneratorService.php

This fixes fatal error when running kickstart:model command
When running ./flow kickstart:model Test.Me Event "title:string" found fatal error 
Class 'Neos\Kickstarter\Service\FlowPackageInterface' not found
Imported missing interface to fix this
To verify run kickstart:model and it should work without errors!
**Checklist**

[BUGFIX] Interface used is not imported

---

Neos.Flow/Classes/Core/Booting/Scripts.php

While building sub commands via ``Scripts::buildSubprocessCommand``
the arguments are not build in a syntax that is sensible for parsing
by Flow later. Specifically an argument is build like this:
'--argumentName' 'argumentValue'
The missing equals sign (=) makes this problematic to parse if the
value contains an equal sign itself as that will then be identified
as separator between argument name and value. With this change those
arguments are now build like this:
'--argumentName'='argumentValue'

BUGFIX: Correctly build sub process command arguments

---

Neos.Flow/Tests/Unit/Property/PropertyMapperTest.php

… because the test does in fact assert something. So PhpUnit complained:
`This test is annotated with "@doesNotPerformAssertions" but performed 1 assertions`

TASK: Remove doesNotPerformAssertions from a test

---

Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Validation.rst

A last reference to `FLOW3` was present in the Validation chapter. This change updates the document to use `Flow`.
Did a search through the Documentation folder and found no other references to FLOW3

Correct `FLOW3` reference to `Flow`

---

Neos.Flow/Classes/Validation/Validator/AbstractValidator.php
Neos.Flow/Classes/Validation/Validator/AggregateBoundaryValidator.php
Neos.Flow/Classes/Validation/Validator/CollectionValidator.php
Neos.Flow/Classes/Validation/Validator/GenericObjectValidator.php
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Validation.rst
Neos.Flow/Tests/Functional/Mvc/ActionControllerTest.php
Neos.Flow/Tests/Functional/Mvc/Fixtures/Controller/ActionControllerTestBController.php
Neos.Flow/Tests/Functional/Mvc/Fixtures/Controller/TestObjectArgument.php

This changes uses a stack inside Validators to store results of previous
calls, so that results are not lost when a validator is called in a cycle.
This may happen for any Object or Collection validators, since the Validator
instances chain is built per class and hence cyclic relations (A -> * -> A)
may lead to incorrect validation results otherwise.
Note: This bugfix is only breaking if you implemented your own Validator, extending `GenericObjectValidator` or `CollectionValidator`, overriding the `validate()` method and setting `$this->result` inside. In that case you are required to change the code to make use of `pushResult()`/`popResult()` like it is done inside `AbstractValidator::validate()`.
This is an exception to the otherwise semantic versioning we strive for. It was decided …

!!!BUGFIX: Cyclic validator calls don't lose previous results

---

Neos.Flow/Classes/Mvc/Routing/ObjectPathMapping.php
Neos.Flow/Migrations/Mysql/Version20180827132710.php
Neos.Flow/Migrations/Postgresql/Version20180827132221.php

This adds a second index to the database table in which the
ObjectPathMapping instances are stored. It speeds up find operations
for which the existing primary key does not help.
With enough data (250k entries for ObjectPathMapping) this speeds up
page delivery by about 60%.

TASK: Speed up lookups in IdentityRoutePart

---

Neos.FluidAdaptor/Classes/View/Exception/InvalidSectionException.php
Neos.FluidAdaptor/Classes/View/Exception/InvalidTemplateResourceException.php

typo3fluid/fluid expects specific exceptions to be thrown to implement
the feature of optional sections and partials. Neos.FluidAdaptor has to
throw these exceptions or derivates of them. Otherwise the exceptions won't
be catched and displayed to the user.
fixes: #1347
**What I did**
I implemented solution 1 from the issue
I made the exceptions shipped with FluidAdaptor inherit from the expected ones from typo3fluid/fluid
Try to reproduce the issue after applying the patch
**Checklist**

BUGFIX: Extend the expected exceptions for missing templates and sections

---

Neos.Flow/Classes/Property/PropertyMapper.php
Neos.Flow/Classes/Property/TypeConverter/ObjectConverter.php
Neos.Flow/Classes/Reflection/ReflectionService.php
Neos.Flow/Tests/Functional/Reflection/Fixtures/AnnotatedClass.php
Neos.Flow/Tests/Functional/Reflection/Fixtures/Model/EntityWithUseStatements.php
Neos.Flow/Tests/Functional/Reflection/ReflectionServiceTest.php
Neos.Flow/Tests/Unit/Property/PropertyMapperTest.php

In PropertyMapper checks if the $targetType is nullable and the given source, too. If this is true, return null. Also, in ReflectionService, the annotated type is properly expanded when annotated with '|null' or 'null|'.
**Checklist**
Alternative push for #1353
Fixes #1361

BUGFIX: Allow nullable constructor arguments

---

Neos.Eel/Classes/FlowQuery/Operations/Object/FilterOperation.php
Neos.Eel/Documentation/README.md
Neos.Eel/Tests/Unit/FlowQuery/FlowQueryTest.php

This commit amends the implementation for the ``^=``, ``$=`` and ``*=`` fizzle operators by checking if the given property is an array and if so, checking whether the filter matches in the following way:
* ``*=`` matches if the array contains an item that matches the filter string exactly.
* ``^=`` matches if the array's first item matches the filter string exactly.
* ``$=`` matches if the array's last item matches the filter string exactly.
If the given property is not an array the filter operations behave the same way as before.
This commit also contains unit tests for the array-based filter operations with the following test cases:
* a) one array item matches the filter string with the filter operator -> filter should match
* b) multiple items match the filter string with the filter …

FEATURE: Make fizzle filter operations capable of dealing with arrays

---

Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/PackageManagement.rst

The `Object Management` chapter contained two examples of the former `Classes` file structure, that included *VendorName* and *PackageName*.

[TASK] Remove incorrect folder structure example

---

Neos.Flow/Classes/Cli/ConsoleOutput.php
Neos.Flow/Classes/Command/DoctrineCommandController.php
Neos.Flow/Tests/Unit/Cli/ConsoleOutputTest.php

Fixes an issue where running doctrine:migrationgenerate would never move the migration-file to the selected package. After doctrine:migrationgenerate has generated a migration, it asks whether the migration-file should be moved to a specific package. No matter what you choose, it would assume you chose "Don't Move".
Also fixes two related issues in the ConsoleOutput's select method:
- Wrong typehint on $default, breaking the default answer functionality
- Wrong phpdoc typehint on $attempts, as it is an integer, not a boolean.
I added a testcase and modified a couple of other testcases for the ConsoleOutput as well.

 BUGFIX: doctrine:migrationgenerate won't move file to selected package 

---

Neos.Flow/Classes/Core/Bootstrap.php
Neos.Flow/Resources/Private/Installer/Distribution/Defaults/Web/index.php
Neos.Flow/Scripts/flow.php

Instead of requiring the bootstrap class file and
then requiring Composer autoloader in the Bootstrap constructor,
we can require the autoloader early in the two entry scripts.
This makes it possible to set FLOW_CONTEXT through .env files
e.g with packages like helhum/dotenv-connector

TASK: Require composer autoloader in entry scripts

---

Neos.Flow/Classes/Log/LoggerFactory.php
Neos.Flow/Classes/Log/ThrowableLoggerInterface.php

Both are just consequences of already existing deprecations and were
overseen when the rest was deprecated. They should be removed with the
rest of the legacy logging in the next major.

TASK: Deprecate LoggerFactory and ThrowableLoggerInterface

---

Neos.Flow.Log/Tests/Unit/Psr/LoggerTest.php
Neos.Flow/Classes/Log/Utility/LogEnvironment.php
Neos.Flow/Classes/Monitor/FileMonitor.php
Neos.Flow/Tests/Functional/Log/Utility/LogEnvironmentTest.php

This utility can be used to easily add the log environment to log
messages using the PSR compatible logger.
Example:
```
$logger->debug('Running sub process loop.', LogEnvironment::fromMethodName(__METHOD__));
```

FEATURE: Introduce an utility to add log environment from method name

---

Neos.Flow/Classes/Http/ContentStream.php
Neos.Flow/Classes/Http/Helper/ArgumentsHelper.php
Neos.Flow/Tests/Unit/Http/ContentStreamTest.php

This adds a new named constructor `fromContents()` to the `ContentStream` class making
it easier to instantiate it from a given string.

TASK: Make ContentStream easier to use

---

Neos.FluidAdaptor/Classes/ViewHelpers/Form/TextareaViewHelper.php

Bugfix because it is possible to configure a maxlength in the form framework, but this leads to an exception. I didn't realize there was no maxlength when I put it in form framework and the reviewers didn't notice either, so now it is required to have it in the viewhelper.
maxlength in textarea is possible since html5 and is supported by all major browsers including IE since 10 ;)
**Checklist**

BUGFIX: Enable maxlength for the form.textarea viewhelper

---

Neos.FluidAdaptor/Classes/ViewHelpers/FormViewHelper.php

Update to support 'dialog' method used in HTML5 <dialog> element
eg. `<form method="dialog" ...>`
See form submission point 20.
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#form-submission-2 
(note I am not sure if any change required  for` protected function renderCsrfTokenField()`
**What I did**
**Checklist**

FEATURE: Support HTML5 dialog method

---

Neos.Flow/Classes/Property/TypeConverter/DateTimeConverter.php

This change adds support for converting values that are received from serializing a DateTimeInterface object with `json_serialize`.
If the source array contains a property 'timezone_type' the source date string is assumed to be in the internal serialization format, which is "Y-m-d\TH:i:s.v" without timezone information, since the timezone is provided in the additional 'timezone' property.
Related to https://github.com/neos/Neos.EventSourcing/issues/181
TODO: Add tests

TASK: Support converting from json_serialized DateTime

---

Neos.Flow/Classes/I18n/Cldr/Reader/PluralsReader.php
Neos.Flow/Tests/Unit/I18n/Cldr/Reader/PluralsReaderTest.php

The line `$quantity = fmod($quantity, $subrule['modulo']);` used to mutate the $quantity variable, so if there were two `mod` operations in the same rule the second operation would apply to the result of the previous operation.

BUGFIX: prevent mutations in PluralsReader

---

Neos.Flow/Classes/ObjectManagement/Proxy/ProxyMethod.php
Neos.Flow/Tests/Unit/ObjectManagement/Proxy/ProxyMethodTest.php

Nullable paramters (type prepended with `?`) were introduced with PHP 7.1
see https://secure.php.net/manual/en/migration71.new-features.php#migration71.new-features.nullable-types
We need to support a syntax like `functionName(?string $param)`. Without this fix, this function will get extended as `functionName(string $param)`, which is incompatible.
Starting with PHP 7.1 `functionName(string $param = null)` can also be written as `functionName(?string $param = null)` (but not as ~~`functionName(?string $param)`~~).
For the upmerge with Flow >= 5.0, the PHP version check in line 275 can be removed since at least PHP 7.1 is required there.

BUGFIX: Add nullable parameter detection

---

Neos.Cache/Classes/Backend/RedisBackend.php

At least when running unit tests for the `MultiBackend` the `connect()`
call raises an error that circumvents exception handling and breaks
correct execution.

BUGFIX: Avoid "wrong" error if Redis is unavailable

---

Neos.Flow/Classes/Command/DoctrineCommandController.php
Neos.Flow/Classes/Persistence/Doctrine/Service.php

The abstract doctrine migration class changed, the generated classes
used the deprecated abstract class.
Actual change in: https://github.com/neos/flow-development-collection/commit/572d63a38198d35ef68a9e6e0a2473e55bd5006d
Code cleanup in: https://github.com/neos/flow-development-collection/commit/32420b7fe34d1801178f4e7a2722842b040b50bf

TASK: Generate doctrine migrations with new abstractclass

---

Neos.FluidAdaptor/Classes/Command/DocumentationCommandController.php

The XSD file generator still uses typo3.org instead of neos.io
Resolves: #1186

TASK: Adjust XSD domain to neos.io

---

Neos.Flow/Classes/Package/PackageManager.php

If the composer file has a local distribution folder identified by type "path" and
a local folder reference in the "url" new packages are created in the
distributionFolder and are required via 'composer require ... @dev'.

FEATURE: Use localDistributionFolders on ``package:create``

---

Neos.Eel/Classes/Helper/ArrayHelper.php
Neos.Eel/Tests/Unit/Helper/ArrayHelperTest.php

This allows to set keys which are calculated at runtime in Eel. A possible use case for this
is the ``Neos.Fusion:Reduce`` prototype that can be used for grouping with ``set``.

FEATURE: Add ``set`` method to ``Array`` Eel-helper

---

Neos.Flow/Classes/ResourceManagement/Target/FileSystemTarget.php

After switching from `FileSystemSymlinkTarget` to `FileSystemTarget`
the symlinks are still present in the `targetPath` and therefore Flow
tries to copy the stream content in the symlink (original file, same
stream) which results in a 0 byte file.
We handle this issue by removing the symlinks if present.
FLOW-384 #close

BUGFIX: Prevent overwriting source files

---

Neos.Flow/Classes/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php

When no class schema can be found in `loadMetaDataForClass`, a Doctrine
`MappingException` is now thrown. This makes our code work nicely with the
change in https://github.com/doctrine/doctrine2/pull/7471/ that otherwise
leads to errors like this as of ORM 2.6.3:
```
FlowAnnotationDriver.php: No class schema found for "some-non-mapped-class".
89 …\FlowAnnotationDriver_Original::getClassSchema("some-non-mapped-class")
88 …\FlowAnnotationDriver_Original::loadMetadataForClass("some-non-mapped-class", Neos\Flow\Persistence\Doctrine\Mapping\ClassMetadata)
```
Fixes #1453

BUGFIX: Throw MappingException in loadMetaDataForClass

---

Neos.Flow/Tests/Unit/Package/PackageManagerTest.php
Neos.Flow/Tests/Unit/ResourceManagement/Target/FileSystemTargetTest.php

The ``PackageManager::createPackage`` method now can create
packages into a possibly existing ``DistributionPackages``
directory "automagically", which then triggers a composer update.
While this is a good idea to push the idea of distribution packages
it also breaks tests that clearly do not want to run composer
update. This can be fixed by providing a defined package path.
Related #1433

BUGFIX: Tests adapted to new behavior in PackageManger

---

Neos.Flow/Classes/Log/Utility/LogEnvironment.php

If LogEnvironment::fromMethodName was used in a closure
the given methodName does not contain ::
and the explode fails.

BUGFIX: Fix log environment when used in a closure

---

Neos.FluidAdaptor/Classes/Core/Rendering/RenderingContext.php

This adds the missing template pre-processor to the Neos.FluidAdaptor RenderingContext.
(Actually it is not missing but gets removed upon setting the template pre-processors.)
Fixes #1449

BUGFIX: Support the parser halt fluid token

---

Neos.Flow/Classes/Property/TypeConverter/DateTimeConverter.php
Neos.Flow/Tests/Unit/Property/TypeConverter/DateTimeConverterTest.php

The format for converting from json_encode'd DateTime was wrong. The format doesn't use the `\T` separator, but a whitespace and as it seems, `v` is not a valid format specifier for `DateTime::createFromFormat` while it is for `date()`.
http://php.net/manual/en/datetime.createfromformat.php
"In **most cases**, the same letters as for the [date()](http://php.net/manual/en/function.date.php) can be used." [emphasis by me]
Also, this provides a test to actually verify the functionality.
Related to #1415

BUGFIX: Fix format for json_encoded DateTime conversion

---

Neos.Utility.ObjectHandling/Classes/TypeHandling.php
Neos.Utility.ObjectHandling/Tests/Unit/TypeHandlingTest.php

Currently, a type string of `DateTimeImmutable` will be parsed as `DateTime`. This for example leads to any entity properties annotated as `@var DateTimeImmutable` to be hydrated into a `DateTime` class instead.
Note that this is a hotfix at most, because the real issue is, that the regex does not check for a type ending character, like whitespace, line end or other non-word character. Therefore, it eagerly parses `DateTimeImmutable` by matching the `DateTime` prefix and taking that as the parsed type, which is wrong.
I'd rather change the regex to end with `(?:\b|$)`, but I'm unsure how breaking that would be.

BUGFIX: Properly parse `DateTimeImmutable` types

---

Neos.Flow/Classes/Core/Bootstrap.php

A duplicate declaration of FLOW_VERSION_BRANCH slipped in while upmerging from 4.3

TASK: Fix duplicate FLOW_VERSION_BRANCH declaration after upmerge

---

Neos.Flow/Classes/Command/CacheCommandController.php
Neos.Flow/Classes/Command/SessionCommandController.php
Neos.Flow/Configuration/Caches.yaml
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Caching.rst
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/SessionHandling.rst

Previously the sessions would be flushed whenever caches get flushed. This sometimes leads to unexpectedly logging out users, as happens for example in the neos setup in the last step.
This is only breaking in the sense, that you need to take care when deploying code that changes classes or data stored in the session. In those cases you need to flush the session caches manually via the new CLI command `./flow flow:session:destroyAll`. Also see the documentation https://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/SessionHandling.html#session-storage
Resolves #1390

BUGFIX: Make session caches persistent by default

---

Neos.Flow/Classes/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php
Neos.Flow/Tests/Functional/Persistence/Fixtures/ExtendedTypesEntity.php
Neos.Flow/Tests/Functional/Persistence/PersistenceTest.php

This change correctly maps `DateTimeImmutable` property types with doctrine.
Depends on #1442

TASK: Add support for DateTimeImmutable classes mapping with doctrine

---

Neos.Flow/Classes/Cli/RequestBuilder.php
Neos.Flow/Classes/Command/CacheCommandController.php
Neos.Flow/Classes/Command/DoctrineCommandController.php
Neos.Flow/Classes/Command/HelpCommandController.php
Neos.Flow/Classes/Command/ResourceCommandController.php
Neos.Flow/Classes/Command/SchemaCommandController.php
Neos.Flow/Classes/Core/Booting/Scripts.php
Neos.Flow/Classes/Http/RequestHandler.php
Neos.Flow/Classes/Log/Utility/LogEnvironment.php
Neos.Flow/Classes/Mvc/ActionRequest.php
Neos.Flow/Classes/Package.php
Neos.Flow/Classes/Package/PackageManagerInterface.php
Neos.Flow/Classes/Persistence/Doctrine/Service.php
Neos.Flow/Classes/Reflection/ReflectionService.php
Neos.Flow/Classes/Reflection/ReflectionServiceFactory.php
Neos.Flow/Classes/ResourceManagement/Streams/ResourceStreamWrapper.php
Neos.Flow/Tests/Functional/Configuration/ConfigurationValidationTest.php
Neos.Flow/Tests/Functional/Configuration/SchemaValidationTest.php
Neos.Flow/Tests/Functional/Mvc/ViewsConfiguration/ViewsConfigurationTest.php
Neos.Flow/Tests/Unit/Mvc/ActionRequestTest.php
Neos.Flow/Tests/Unit/ResourceManagement/Streams/ResourceStreamWrapperTest.php
Neos.FluidAdaptor/Classes/Core/ViewHelper/ViewHelperResolver.php
Neos.FluidAdaptor/Classes/Package.php
Neos.FluidAdaptor/Classes/View/TemplatePaths.php
Neos.Kickstarter/Classes/Command/KickstartCommandController.php
Neos.Kickstarter/Classes/Service/GeneratorService.php
Neos.Utility.Schema/Tests/Unit/SchemaValidatorTest.php

As the package manager cannot be overwritten the interface is purely
cosmetic and IF you actually use the package manager (which you
probably should not in the first place) you can just inject the
``PackageManager`` directly instead of the interface.

!!! TASK: Deprecate PackageManagerInterface

---

Neos.Flow/composer.json
composer.json

Since DBAL 2.8 has no b/c breaks, it should be safe to update the version.
See https://github.com/doctrine/dbal/releases/tag/v2.8.0
In the longer term, we should also phase out the doctrine/common dependency.
See https://www.doctrine-project.org/2018/07/12/common-2-9-and-dbal-2-8-and-orm-2-6-2.html
AFAIS we only depend on `Doctrine\Common\Util\Debug` which we are suggested to replace with `symfony/var-dumper`.

TASK: Update Doctrine DBAL dependency to 2.8

---

Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/FileMonitoring.rst
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/LoggingAndDebugging.rst
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Testing.rst
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/index.rst
Neos.Flow/Documentation/TheDefinitiveGuide/PartIV/index.rst
Neos.Flow/Documentation/TheDefinitiveGuide/index.rst
Neos.Flow/Documentation/index.rst

This removes empty parts of the documentation, they are to be written
following their respective tickets:
- File Monitoring, https://github.com/neos/documentation/issues/20
- Logging and Debugging, https://github.com/neos/documentation/issues/18
- Testing, https://github.com/neos/documentation/issues/17
- Deployment and Administration, https://github.com/neos/documentation/issues/15
The part numbering was kept as is, to not break links. The "Deployment
and Administration" part can be put back as "Part IV" when actually
being written.
Resolves https://github.com/neos/documentation/issues/1

TASK: Remove empty documentation parts

---

Neos.Flow/composer.json

The dependabot changes done to the dev collections are not good. Why? Because dependabot only changes the top-level `composer.json` bit leaves the manifests in Neos.Flow untouched.
This makes sure the dependencies in `neos/flow` match the collection dependencies again.
Fixes neos/neos-development-collection#2310

BUGFIX: Make  dev collection and neos/flow dependencies match

---

Neos.Flow/Classes/ObjectManagement/Proxy/Compiler.php
Neos.Flow/Classes/Persistence/Generic/DataMapper.php

Starting in PHP 7.3, PHP will throw a warning when using `continue`
within a `switch` to confirm intent. In PHP, within `switch`, `break`
and `continue` do the same thing.

TASK: PHP 7.3 - Use break instead of continue within a switch case

---

Neos.Flow/Tests/Unit/Property/PropertyMapperTest.php

The changed test does contain an `expects` but did advertise it
`@doesNotPerformAssertions`, leading PhpUnit to consider the
test as risky.

TASK: Fix risky unit test

---

Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php

This fixes an error caused by a wrong format string used to
generate an exception message when a private property is
annotated for configuration injection.

BUGFIX: Fix wrong exception message

---

Neos.Flow/Classes/Package/PackageManager.php

In older setups that did not have a `repositories` section in the composer-maifest `package:create` tried to foreach over a null-value which lead to an php-error. This change checks that the `repositories` is actually an array before iterating.

BUGFIX: Verify the existence of the `repositories` section in the composer manifest before searching for local packages path

---

Neos.Flow/Classes/Http/Request.php
Neos.Flow/Tests/Unit/Http/RequestTest.php

Adds support for file uploads with "/"s in their names.
Adds a `Request::calculateFieldPathsAsArray` method
returning the paths as arrays instead of "/"-separated strings
(later "/"-split again).
Keeps the `calculateFieldPaths` method returning the paths as
strings for backwards-compatibility.
Fixes #1467

BUGFIX: Support "/" in file upload fields

---

Neos.Flow/Classes/Error/Debugger.php
Neos.Flow/Configuration/Settings.Error.yaml
Neos.Flow/Resources/Private/Schema/Settings/Neos.Flow.error.schema.yaml

With the default recursion Limit of 50 php often runs into memory-limits when debugging larger data structures. This change allows to define the recursionLimit via Settings. In addition the default recursionLimit is set to 5.

FEATURE: Make recursion limit for the debugger configurable via Settings

---

Neos.Flow/Classes/Security/Authentication/Provider/PersistedUsernamePasswordProvider.php

This replaces the dummy hash used to prevent timing based attacks by
a valid hash for a random password that was never actually stored
somewhere.
This avoids problems with PHP's encryption methods. With the
previous hash, the hashing was sometimes not applied properly
and the method returns early so that the time-based information
disclosure vulnerability still exists.

TASK: Use proper dummy hash in PersistedUsernamePasswordProvider

---

Neos.Flow/Classes/Security/Authorization/Privilege/Entity/Doctrine/PropertyConditionGenerator.php
Neos.Flow/Configuration/Testing/Policy.yaml
Neos.Flow/Tests/Functional/Security/Authorization/Privilege/Entity/Doctrine/ContentSecurityTest.php
Neos.Flow/Tests/Functional/Security/Authorization/Privilege/Entity/Doctrine/EntityPrivilegeExpressionEvaluatorTest.php
Neos.Flow/Tests/Functional/Security/Fixtures/TestEntityD.php

This is very limited on purpose but allows to write policies like this:
`'isType("Whatever\Domain\Model\Party") && (!property("accounts").contains("context.securityContext.account"))'`

TASK: Allow contains expression on entity properties

---

Neos.Cache/Classes/Backend/TaggableMultiBackend.php

The `is_a` only checks for parents but not for implemented interfaces. `is_sublcass_of` should be used instead to check if the `$backendClassName` implements the interface

BUGIFX: Correctly check for TaggableBackendInterface

---

Neos.Eel/Classes/Helper/StringHelper.php

This method pretty much just redirects its arguments to the PHP-native
`vsprintf` and allows to format strings without `'' + ''` interpolation.

FEATURE: Add `format` method to String EEL Helper

---

Neos.Flow/Scripts/Migrations/AbstractMigration.php

This avoids errors like `fatal: bad source, source=Packages/Sites/Acme.AcmeCom/Resources/Private/Fusion/Root.ts2, destination=Packages/Sites/Acme.AcmeCom/Resources/Private/Fusion/Root.fusion` during `core:migrate`.

TASK: Avoid code migration error if source file does not exist

---

Neos.Flow/Classes/ResourceManagement/Streams/ResourceStreamWrapper.php
Neos.Flow/Tests/Unit/ResourceManagement/Streams/ResourceStreamWrapperTest.php

This avoids the costly ``\Neos\Utility\Unicode\Functions::parse_url``
which does a preg_replace_callback. As we know that we don't expect
just any URL in the resource stream wrapper we might as well use
cheaper string functions to extract the necessary information.
Given that evaluateResourcePath is called a lot especially in a
Neos CMS context this can actually have a performance impact.

TASK: Optimize parsing of resource uris

---

Neos.Eel/Classes/Helper/SecurityHelper.php
Neos.Eel/Tests/Unit/Helper/SecurityHelperTest.php

- `csrfToken` returns CSRF token which is required for "unsafe" requests (e.g. POST, PUT, DELETE, ...)
- `isAuthenticated` returns true, if any account is currently authenticated
- `hasAccess` returns true, if access to the given privilege-target is granted
The new methods add features to eel that previously were available as viewHelpers so they can be used in Fusion directly.

FEATURE: Add methods `csrfToken`, `isAuthenticated` and `hasAccess` to `Security` EelHelper

---

Neos.Flow/Classes/Command/HelpCommandController.php

Fixes the exit code of
./flow non:existing:command
to be 1 instead of 0.
Fixes: #1504

BUGFIX: Fix exit code for unresolved CLI commands

---

Neos.Flow/Classes/Mvc/Controller/AbstractController.php

Now meta http-equiv is only rendered if a delay is requested.

TASK: Avoid rendering of meta http-equiv if location headers are sent

---

Neos.Flow/Configuration/Testing/Settings.yaml

The TestingProvider should be available for all controllers/routes not only for Flow testing controllers otherwise the generic possibility to authenticateRoles in the FunctionalTestCase makes no sense for any other package. In the respective case a Neos test tried to authenticate roles but these would never have an effect due to the patterns.

BUGFIX: Allow testing provider everywhere

---

Neos.Flow/Classes/I18n/Cldr/Reader/PluralsReader.php

Would be better to check the array keys before using them.
INFO: For some langauges like "zh" (china), the property "$this->rulesets" is
not filled properly. So accessing for example "$this->rulesets['zh']" will cause
a PHP Notice: "Undefined index".
**What I did**
In my fluidtemplate, i want to translate a language ID from "zh/Main.xlf" with this code:
```
{f:translate(
id: 'lang.id.with.plurals.definition',
package: 'Some.Package',
source: 'Main.xlf',
locale: 'zh',
quantity: 2
)}
```
The definition of this language ID in my "zh/Main.xlf" is this:
```
<group id="lang.id.with.plurals.definition" restype="x-gettext-plurals">
<trans-unit id="lang.id.with.plurals.definition[0]">
<source>Acme default Foo</source>
<target>Acme ZH Foo</target>
</trans-unit>
<trans-unit …
```

BUGFIX: Accessing non existing array keys can cause a PHP Notice.

---

Neos.Flow/Classes/Reflection/ReflectionService.php
Neos.Flow/Tests/Functional/Reflection/Fixtures/DummyClassWithTypeHints.php
Neos.Flow/Tests/Functional/Reflection/ReflectionServiceTest.php

Currently the Reflection Service does not work well with the `@param Type[]` array syntax. Also `array` type hints without a `@param` annotation result in a `mixed` type. 
Through this PR the Reflection Service resolves `Type[]` to `array<Type>`. And `array` stays `array` even without annotation.

TASK: Respect type hinting in reflection / support "@param Type[]" array syntax

---

Neos.Flow/Classes/Error/AbstractExceptionHandler.php
Neos.Flow/Classes/Mvc/Controller/AbstractController.php
Neos.FluidAdaptor/Classes/View/StandaloneView.php

This adjusts two places to use the ``ActionResponse`` and ensures
backwards compatibility for userland code using the deprecated
``Response`` by not using the new methods just yet.

TASK: Adjust to ActionResponse and ensure backward compatibility

---

Neos.Flow/Classes/Package/PackageManager.php

When private packagist is used the following setting isn added to the repositories section of the composer.json:
```
repositories: [
{
"packagist.org": false
}
]
```
This caused an error because the package:create command tried to access the undefined `type` property of each defined repository.
This change simply checks for the existence of the type key before acessing it.
#fixes https://github.com/neos/neos-development-collection/issues/2448

BUGFIX: Fix package:create and derived commands when private packagist is used

---

Neos.Flow/Classes/I18n/Service.php

Get rid of wording "blacklist"/"whitelist" because there's better terms.
Should have been named like this from the start. I'm to blame.

TASK: Better naming for include and exclude paths/patterns

---

Neos.Cache/Classes/Frontend/AbstractFrontend.php

The typehint of the `flushByTag` method expected an `int` return type, but the method inside the `AbstractFrontend` returned void when a non taggable backend was flushed. This was the case for a `SimpleFileBackend` for example and led to an error.

BUGFIX: Avoid type error when a non taggable cache backend gets flushed by tag

---

Neos.Flow/Classes/Security/Aspect/LoggingAspect.php
Neos.Flow/Classes/Session/Aspect/LoggingAspect.php

As the `'FLOW_LOG_ENVIRONMENT' => []` level was missing in the log data, the log environment data was not set correctly and written to the log by the file writer.

BUGFIX: Fix log environment in logging aspects

---

TYPO3.Flow/Classes/TYPO3/Flow/Security/Cryptography/RsaWalletServicePhp.php
TYPO3.Flow/Configuration/Settings.yaml
TYPO3.Flow/Tests/Unit/Security/Cryptography/RsaWalletServicePhpTest.php

This avoids OpenSSL Padding Oracle Information Disclosure by
allowing to specify the padding algorithm used in the RSA wallet
service.
Most probably you are not even affected, since only OpenSSL 1.0.1t
and 1.0.2h are vulnerable, but better safe than sorry.
The padding algorithm default is changed to OPENSSL_PKCS1_OAEP_PADDING,
but a fallback decryption is in place for all data that was encrypted with the
previously unsafe padding algorithm.
Therefore you should migrate all your existing encrypted data, by running it through
`decryptWithPrivateKey` and then again through `encryptWithPublicKey` ONCE.
Fixes #1566

[SECURITY] Avoid OpenSSL padding oracle attacks

---

Neos.Flow/Classes/ResourceManagement/PersistentResource.php

The name IDX_35DC14F03332102A is different from what Doctrine does
auto-generate, but needs to be used due to BC reasons with existing
migrations.
See https://github.com/neos/neos-development-collection/issues/2475

TASK: Fix name of index on PersistentResource.sha1

---

.travis.yml

Raise PHP versions from 7.1 to 7.2 and 7.2 to 7.3 in the travis test matrix.

TASK: Raise PHP version by one minor version in travis.yaml

---

Neos.FluidAdaptor/Classes/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php

Add error checking when splitting on shorthand syntax.
See https://github.com/neos/neos-development-collection/pull/2484
Related to https://github.com/neos/neos-development-collection/issues/2479

BUGFIX: Avoid PHP exception in NamespaceDetectionTemplateProcessor

---

Neos.Flow/Classes/I18n/Xliff/Model/FileAdapter.php
Neos.Flow/Classes/I18n/Xliff/V12/XliffParser.php
Neos.Flow/Tests/Unit/I18n/Fixtures/MockParsedXliffData.php

The target element in XLIFF is optional, and even though we recommend
in the documentation to set it, most people omit the target for
"source" XLIFF files (i.e. having english content and target-language
being unset).
For these cases the XliffParser now reads the source element content
into the target element. This makes the fallback rules work for
individual translations and not only full XLIFF files.
In other words: when a new string is added to a source catalog, it
will be used as is even when no translation is available – instead of
simply the id being output.

BUGFIX: Use source as target if target-language is empty in XLIFF

---

Neos.Eel/Classes/FlowQuery/FlowQuery.php
Neos.Eel/Classes/Utility.php

Function helpers are static functions that are available in Eel without a containing helper. This
change removes the default q variable and instead adds a static method `q` to the flowQuery
class that is used as helper function with the following configuration:
```
Neos:
Fusion:
defaultContext:
q: 'Neos\Eel\FlowQuery\FlowQuery::q'
ContentRepository:
labelGenerator:
eel:
defaultContext:
q: Neos\Eel\FlowQuery\FlowQuery::q
```
Note: Nested pathes as identifiers for function-helpers are not allowed and will raise an exception.
This is breaking as it makes it necessary to add the configuration above to Neos.Fusion and Neos.ContentRepository. Also custom code that uses FlowQuery and relies on q beeing always present will have to be adjusted.
Upgrade Instructions:
Only if you are using the …

!!! FEATURE: Add function helpers to Eel and remove magic `q`

---

Neos.Flow/Configuration/Settings.Reflection.yaml

I removed all tags from `Settings.Reflection.yaml` that are already in the `$globalIgnoredNames` in `Doctrine\Common\Annotations\AnnotationReader`
There are even more of the ignoredTags in the current master of doctrine/annotations (see link in the issue), but it seems they are not yet in the 1.6.1 release of doctrine/annotations
Resolves #1532

TASK: Clean up ignoredTags configuration with defaults from doctrine AnnotationReader

---

Neos.Flow/Tests/Functional/I18n/Cldr/CldrRepositoryTest.php
Neos.Flow/Tests/Functional/Persistence/PersistenceTest.php
Neos.Flow/Tests/Unit/Http/BrowserTest.php
Neos.Flow/Tests/Unit/I18n/Cldr/CldrRepositoryTest.php
Neos.Flow/Tests/Unit/Persistence/Generic/DataMapperTest.php
Neos.Flow/Tests/Unit/Persistence/Generic/PersistenceManagerTest.php
Neos.Flow/Tests/Unit/ResourceManagement/Streams/ResourceStreamWrapperTest.php
Neos.Utility.ObjectHandling/Tests/Unit/ObjectAccessTest.php

Replace deprecated PhpUnit functions with supported alternatives.
Fixes https://github.com/neos/neos-development-collection/issues/2498

BUGFIX: Remove deprecated PhpUnit functions from tests

---

composer.json

It's already a require, so the duplication just causes problems, when the versions don't match any more (as they do in current master).

BUGFIX: Remove Doctrine from require-dev

---

Neos.Flow/Classes/Log/ThrowableStorage/FileStorage.php
Neos.Flow/Classes/Log/ThrowableStorageInterface.php

The method existed anyway in the "default implementation", but was
destined to become part of the interface.

!!! TASK: Add createWithOptions() to ThrowableStorageInterface

---

Neos.Flow/Classes/Security/Authentication/AuthenticationManagerInterface.php
Neos.Flow/Classes/Security/Authentication/AuthenticationProviderManager.php
Neos.Flow/Tests/Behavior/Features/Bootstrap/SecurityOperationsTrait.php

This removes `getTokens()`, `getProviders()` and `setSecurityContext()`
from `AuthenticationManagerInterface` and `AuthenticationProviderManager`.
Also return type declarations are set on the interface methods.
To adjust your code using any implementations of the interface, replace
- `$this->authenticationManager->getTokens()` with `$this->tokenAndProviderFactory->getTokens()`
- `$this->authenticationManager->getProviders()` with `$this->tokenAndProviderFactory->getProviders()`
(Of course you might need to add injections so the factory is available in
your code.)
If you implemented the interface yourself, remove the methods and use
injection instead of `setSecurityContext()`:
/**
* The security context of the current request
*
* @Flow\Inject
* @var Neos\Flow\Security\Context
*/
protected …

!!! TASK: Remove deprecated methods from AuthenticationManagerInterface

---

Neos.Flow/Classes/I18n/Translator.php
Neos.Flow/Tests/Unit/I18n/TranslatorTest.php

This change makes getTranslationById and getTranslationByOriginalLabel use the configured
locale chain.
This is an updated version of #327 and #328. Please see the discussions there. May be retargeted on master.

TASK: Translator uses locale chain

---

Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Http.rst

Adds a small note that mentions having to configure the trusted proxies in ddev and similar environments. Also explains that Flow therefore trusts all proxies by default in Development context.
Depends on #1586

TASK: Add section for configuration of trusted proxies in container

---

Neos.Flow/Classes/Command/RoutingCommandController.php

If no controller could be found for the given arguments RoutingCommandController:getControllerObjectName() returns null. The return type hint should reflect that to avoid a TypeError.

BUGFIX: Return type hint should reflect nullable

---

Neos.Eel/Classes/Utility.php

The function was added to provide a function for validity checks without any need to duplicate the code which was previously used in the first if-condition of the function evaluateEelExpression.
As @kitsunet mentioned in https://github.com/neos/eel/pull/2 the variable `matches` is not necessary, but I've used it to avoid calling `preg_match(Package::EelExpressionRecognizer, $expression, $matches)` inside the existing function `evaluateEelExpression` and `preg_match(Package::EelExpressionRecognizer, $expression)` inside the new function `isEelExpression`, because to me this seems like duplicated code.
I'm happy with both solutions, so feel free to change it if you decide to remove the variable.

FEATURE: Utility Function to detect Eel expressions

---

.travis.yml

Backport of bcab2bb4fbea62f3ba7bfddc5bd4f22ab4d96675 to fix builds on 4.3 that use wrong DB in mysql setups and fail
https://travis-ci.org/neos/flow-development-collection/builds/536249389

TASK: Synchronise .travis.yml with Neos

---

Neos.Flow/Classes/Command/RoutingCommandController.php

Sorry, found another one...
if subpackage is empty RoutingCommandController:getControllerObjectName() should be called with an empty string for the subPackageKey argument. Otherwise an TypeError is thrown because the argument is not nullable.

BUGFIX: Fix TypeError if subpackage is empty

---

Neos.Flow/Classes/Command/RoutingCommandController.php

IDE complained that a InvalidControllerException is never thrown in the corresponding try-catch-block and i think thats right. Instead there is a InvalidRoutePartValueException thrown in Route:resolves() that should be caught.

BUGFIX: Fix InvalidControllerException is never thrown

---

Neos.Flow/Classes/Core/Booting/Scripts.php

If Flow builds a PHP command for a subrequest, it uses the system default if nothing else is configured. With this change, we avoid Flow executing that request if it isn't explicitly configured to use that same PHP version internally too. This should avoid some errors especially in shared hosting scenarios for less experienced users.

BUGFIX: Flow CLI command warns of mismatching php version

---

Neos.Flow/Classes/Error/Debugger.php

If `$file` points to eval'd code, the `@file(…)` code does not return
an array, leading to `count()` being called on an incompatible value.

BUGFIX: Avoid error in Debugger::findProxyAndShortFilePath()

---

Neos.Utility.Arrays/Classes/Arrays.php
Neos.Utility.Arrays/Tests/Unit/ArraysTest.php

This allows to specify a callback that determines whether the value of the first array is unset before merging.
**What I did**
An additional callback parameter is added to the ```Neos\Utility\Arrays:arrayMergeRecursiveOverruleWithCallback``` method. This allows to conditionally  unset the value of the first array before merging the second array value.
Needed for neos/neos-development-collection#2238
See the created test case.
**Checklist**

FEATURE: Allow overwriting instead of merging in arrayMergeRecursiveWithCallback

---

.travis.yml

This prevents builds from running doubly on branches created on this repository for PRs, e.g. through the StyleCI bot or by github inline PRs.
See https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches

TASK: Safelist branches for travis builds

---

Neos.FluidAdaptor/Classes/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php
composer.json

This allows to install any version of TYPO3 Fluid >= 2.1.3, < 2.5.0 instead of the previously limiting to ~2.1.3
Since Flow 5.0+ requires TYPO3 Fluid 2.5.x, this is consistent.

TASK: Loosen typo3 fluid dependency

---

Neos.Flow/Classes/ObjectManagement/Proxy/ProxyClass.php
Neos.Flow/Tests/Unit/Persistence/RepositoryTest.php
Neos.FluidAdaptor/Classes/ViewHelpers/Security/IfHasRoleViewHelper.php
Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/DateViewHelperTest.php
Neos.Utility.ObjectHandling/Classes/TypeHandling.php

This pattern was overspecified for common types, but at the same time not closed. Hence this was buggy for any type that started with one of the specified types, like a custom `DateTimeRange` type, which would be matched as `DateTime` only.
The new pattern will now just match any identifier made up of characters, digits, backslashes and underscores up to a whitespace or lineend, which also matches all the previously hard-coded types.
This is not breaking in the normal sense, but the change in a very core regex pattern can cause different behaviour in some edge-cases, hence why this bugfix is not applied to lowest maintained branch.
Followup for #1442

!!! BUGFIX: Simplify and strengthen the type matching pattern

---

Neos.Flow/Classes/Security/Context.php
Neos.Flow/Tests/Unit/Security/ContextTest.php

Without this fix, all security tokens – including those which are
implementations of SessionlessTokenInterface – are serialized and
added to the current session. This is a problem for sessionless
tokens, which need to be updated on every request on not just once
per session.
Backport of #1662
Fixes: #1666

BUGFIX: Omit sessionless tokens from session

---

Neos.Flow/Classes/Security/Cryptography/SaltedMd5HashingStrategy.php
Neos.Utility.Arrays/Tests/Unit/ArraysTest.php

md5 is the most insecure hashing algo in existence and we shouldn't support that out of the box, especially not within the `Security` context. If someone has dire need for it in Flow 7.0+, he could always just copy the old strategy and plug it in.
See also https://tools.ietf.org/html/rfc6151
In order to migrate your existing Md5 hashes, you need to configure a different secure hashing strategy and run all your hashed passwords once through the `hashPassword()` upon next user entry.
```php
list($strategyIdentifier, ) = explode('=>', $account->getCredentialsSource(), 2);
if ($strategyIdentifier === 'saltedmd5') {
$account->setCredentialsSource($this->hashService->hashPassword($password));
$this->accountRepository->update($account);
}
```

!!! TASK: Deprecate SaltedMd5HashingStrategy

---

Neos.Flow/Classes/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php
Neos.Flow/Tests/Functional/Persistence/Fixtures/ExtendedTypesEntity.php
Neos.Flow/Tests/Functional/Persistence/PersistenceTest.php

Since #1640 a model with a property annotated like
```php
/**
* @var \DateTimeInterface
*/
protected $someDateTime;
```
lead to an exception in annotation parsing, because the property does not contain a `@ORM\Column(type="...")` mapping.
This worked before, because the type parser interpreted `DateTimeInterface` as just `DateTime` due to the error prone regex matching. Since the regex fix above, `DateTimeInterface` will now be parsed as `DateTimeInterface` and the FlowAnnotationDriver does not automatically map that to an ORM type. This change works around that, by automatically mapping `DateTimeInterface` to the ORM type `datetime` to be b/c with previous behaviour.
Note though, that this is generally bad magic, because you might want your property to be something different from …

BUGFIX: Automatically map DateTimeInterface to ORM type

---

Neos.Flow/Classes/Core/Booting/Scripts.php

**What I did**
Add support for using a fallback to verify whether the `PHP_BINARY` for the currently configured PHP binary file matches the one being used currently.
The current logic only resolves the symlink, which may not always work, e.g. what if the `php` binary is being executed through a wrapper like this?
#!/bin/sh
. /path/to/setenv.sh
exec /path/to/php.bin "$@"
(Where `php.bin` is the binary file and `setenv.sh` a script with sets environment variables - Wrappers like these are heavily used in Bitnami installations.)
Before Flow compares which PHP binary is being used (and which it is supposedly configured to use), we run a PHP `exec` to print `PHP_BINARY`.
Then, we store the result and if no errors were thrown, use this as the detected PHP binary path to compare …

BUGFIX: Allow using Flow with PHP wrappers

---

Neos.Flow/Classes/Mvc/Dispatcher.php
Neos.Flow/Tests/Unit/Mvc/DispatcherTest.php

Adjusts the `Dispatcher` so that it only intercepts GET
requests in order to prevent unwanted side effects when
redirecting to an unsafe request.
Fixes: #1694

BUGFIX: Authentication: Only intercept GET requests

---

.travis.yml
Neos.Eel/Classes/FlowQuery/Operations/AbstractOperation.php
Neos.Flow/Classes/Log/Utility/LogEnvironment.php
Neos.Flow/Classes/Persistence/Doctrine/Query.php
Neos.FluidAdaptor/Classes/ViewHelpers/Security/IfAccessViewHelper.php
Neos.Utility.OpcodeCache/Classes/OpcodeCacheHelper.php
composer.json
psalm-baseline.xml
psalm.xml

This will provide us with immediate feedback on newly introduced typing errors in the code base.
To update the psalm-baseline, which contains the current set of errors that are simply ignored in order to gradually introduce static analysis to a larger code base, you can just run
`bin/psalm --config=Packages/Framework/psalm.xml --update-baseline`
on an installed distribution.
Note though, that this will only remove fixed errors, not add new errors to the baseline. So we could automate this step.
In order to add new errors to the baseline, you have to run
`bin/psalm --config=Packages/Framework/psalm.xml --set-baseline=Packages/Framework/psalm.xml`

FEATURE: Add psalm static code analysis to travis matrix

---

Neos.Utility.Schema/Classes/SchemaValidator.php

Previously, if an array was expected but a non numerically indexed array (i.e. a "dictionary") was given, the error message would output `expected: type=array found: type=array`, which is totally confusing.
See https://github.com/neos/flow-development-collection/pull/1637

TASK: Make array indexing difference more visible

---

Neos.Flow/Classes/Session/Session.php
Neos.Flow/Tests/Unit/Session/SessionTest.php

Under some circumstances, the session metadata cache might iterate a non-array value and the following logging attempt failing with an unsupported operand type error for the `+` array concatenation. This change works around this error, by checking the `$sessionInfo` to be of type array and assigning a wrapper array otherwise.

BUGFIX: Avoid unsupported operand types error

---

Neos.Flow/Configuration/Settings.Resource.yaml

The old defaults for these settings worked but caused trouble once projects got bigger over time:
- `subdivideHashPathSegment: false` caused having too many symlinks in a single folder for many filesystems 
- `relativeSymlinks: false` did not allow to put the `Web/_Resources` directory into the shared folder for faster deployments
ATTENTION: This alters the default behavior and the published resources will get a url with nested pathes. That is why this is considered a breaking change.
NOTE: After updating you have to empty the `Web/_Resources/Persistent` folder and run `./flow resource:publish`. This us usually all done automatically from the deployment tool you are using.
If you do not want this behavior you can disable the subdivision via configuration for your project with the …

!!! TASK: Enable `subdivideHashPathSegment` and `relativeSymlinks` by default

---

Neos.FluidAdaptor/Classes/ViewHelpers/DebugViewHelper.php

**What I did**
When digging through the code I found this instance of capturing the output of `\Neos\Flow\var_dump` using `ob_get_contents` when `\Neos\Flow\var_dump` has a `$return` parameter itself.
Using the `$return` parameter of `\Neos\Flow\var_dump`

TASK: Use var_dump return parameter

---

Neos.Flow/Classes/Mvc/ActionResponse.php
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Http.rst

Adds the two convenience methods `ActionResponse::setCookie()`
and `ActionResponse::deleteCookie()` and adjusts the documentation
accordingly.
Resolves: #1722

FEATURE: Add cookie support to ActionResponse

---

Neos.Flow/Classes/Persistence/Doctrine/Query.php
Neos.Flow/Tests/Functional/Persistence/Doctrine/QueryTest.php

Instead of assuming that every property path with a dot is a path
to an other entity check if the property path is a mapped field which
is also true for embedded object properties.
Resolves #989
**What I did**
We'll i suppose i fixed it :sweat_smile: 
I searched the existing class schema for hints about embedded properties and found it in the entityManager. When the path exists in the fieldMappings it is a field embedded in the object's table. Since we're using doctrine in this kind of query anyway i think we're safe to go whit this solution.
The description of the original bug should be suffice.
**Checklist**

BUGFIX: Do not join select property paths to embedded objects

---

Neos.Flow/Classes/Core/Booting/Scripts.php
Neos.Flow/Tests/Unit/Core/Booting/ScriptsTest.php

Also, the static class does not need to be mocked with PHPUnit, as PHPUnit can not stub static methods anyway.

TASK: Fix ScriptTest invoking dummy commands

---

Neos.Flow/Classes/Http/Component/TrustedProxiesComponent.php

This makes the setting `Neos.Flow.http.trustedProxies.proxies` behave equal for a setting of
`"*"` or `["*"]` or `- "*"`.

BUGFIX: Allow a single '*' entry in trustedProxies

---

Neos.Flow/Classes/Http/Component/SecurityEntryPointComponent.php
Neos.Flow/Tests/Unit/Http/Component/SecurityEntryPointComponentTest.php
Neos.Flow/Tests/Unit/Mvc/DispatcherTest.php

Previously the `Dispatcher` invoked the `startAuthentication()` method
of all authenticated tokens.
That behavior was changed by accident with #1552 and now only the first
Entry Point was triggered.

BUGFIX: Trigger Entry Points of all authenticated tokens

---

Neos.Flow/Tests/Unit/Core/Booting/ScriptsTest.php

This prevents a Warning notice in Unit Tests.
Related to #1731

BUGFIX: Make ScriptsMock::buildSubprocessCommand signature match parent

---

Neos.Error.Messages/Classes/Message.php
Neos.Flow.Log/Tests/Unit/Psr/LoggerTest.php
Neos.Flow/Classes/ResourceManagement/Publishing/MessageCollector.php

This is breaking, because the Error messages no longer accept `null` for the `$code` and `$title` constructor arguments.
See https://github.com/neos/flow-development-collection/pull/1046 for the PR that could not yet fix this issue.

!!! FEATURE: Add strict typehints for error message title and code

---

Neos.Flow/Classes/Http/Component/TrustedProxiesComponent.php

This fixes the case when a configured environment variable (like the default `FLOW_HTTP_TRUSTEDPROXIES`) is not set, in which case the value will be `false`.

BUGFIX: Handle configuration value "false" for trusted proxies

---

Neos.Flow/Classes/Mvc/ActionRequest.php

See https://github.com/neos/neos-development-collection/issues/2668

BUGFIX: Allow FlowUploadedFile coming from HTTP requests

---

Neos.Flow/Resources/Private/Installer/Distribution/Defaults/Web/.htaccess

This is necessary in order to allow e.g. certbot to do it's job.

BUGFIX: Don't redirect `.well-known`

---

Neos.Flow/Classes/Http/RequestHandler.php

BUGFIX: Safeguard ob_end_flush() against empty buffer

---

Neos.Flow/Classes/Http/Component/TrustedProxiesComponent.php

Fixes a regression introduced with #1683

BUGFIX: Allow string for trusted proxies again (env variable use)

---

Neos.Flow/Configuration/Settings.Http.yaml

This will only accept the `X-Forwarded-For` header to override the client IP address by default to be in line with the other headers.
If you use the clientIp from the Http Request, are behind a reverse proxy and did not explicitly configure which HTTP header you expect to contain the original users IP address, then this might break for you if the first reverse proxy in your chain did not set the `X-Forwarded-For` header.
In that case, make sure which header contains the clients IP address and specify that in the `Neos.Flow.http.trustedProxies.headers.clientIp` Setting.

!!! TASK: Be more strict with the default accepted clientIP headers

---

Neos.Cache/Classes/Backend/PdoBackend.php

This fixes the `PdoBackend::getStatus()` and `PdoBackend::setup()` implementation
by getting rid of the Doctrine dependency.
Background:
When configuring the `PdoBackend` to use the same database that already
contains tables with special Doctrine type mappings (for example `flow_json_array`)
comparing the schema led to an exception.
Fixes: #1513

BUGFIX: Fix PdoBackend status & setup

---

Neos.FluidAdaptor/composer.json

Adjusts the dependency declared in `neos/fluid-adaptor` to complement https://github.com/neos/flow-development-collection/pull/1638 and thus fix https://github.com/neos/flow-development-collection/pull/1756

TASK: Loosen typo3fluid/fluid dependency

---

Neos.Flow/Configuration/Settings.yaml

This reverts commit e5bb869d3d1262080bbe687095e7b4a58789d971.
This is necessary, because the inclusion of Fluid in reflection for 4.3 introduced a regression, due to a wrong annotation in Fluid versions < 2.3.
See https://github.com/TYPO3/Fluid/pull/260
Fixes #1756
NOTE: This revert should not be included in upmerges, since the issue does not exist in Flow 5.0+ as it requires Fluid 2.5 minimum

Revert "TASK: Include TYPO3Fluid for reflection"

---

Neos.Flow/Documentation/TheDefinitiveGuide/PartII/Installation.rst

Adds missing documentation that it is required to rename ``Settings.yaml.example`` in order to
have working routing and see the "Welcome" page.
See https://github.com/neos/flow-development-collection/issues/868#issuecomment-279682930
Thanks M.B. from our forum for bringing it up again.

BUGFIX: Adjust installation documentation to account for missing routes config

---

Neos.Flow/Resources/Private/Installer/Distribution/Essentials/Configuration/Development/Settings.yaml.example

In order to make https://github.com/neos/flow-development-collection/pull/1586 more approachable without actually setting a default value in Development.

TASK: Add example development config for allowing all proxies

---

Neos.Flow/Classes/Security/Authorization/RequestFilter.php

This checks the return result of the security interceptor in the authentication request filter. If it is false, this will lead to the filter also rejecting the request.
Before, the request filter always returned true, no matter the return value of the interceptor.
Resolves #1515

FEATURE: Interceptor return value may influence request filter

---

Neos.Flow/Classes/Command/ResourceCommandController.php

This fix makes sure `resource:clean` will remove broken resources from the right collection.
The problem is that you save the SHA1 for a broken resource. Now think about the following case: You have two resources with the same SHA1, but from two different collections (`persistent`/`temporary`). The resource inside the `temporary`-Collection was removed and now you run the command.
It will detect the missing resource from the `temporary`-Collection and add the SHA1 to `$brokenResources`. Now when iteration over `$brokenResources` to get the `PersistentResource` you are using `$this->resourceRepository->findOneBySha1($resourceSha1)`, which ignores the collection. So you can't be sure to get the `PersistentResource` from the `temporary`-Collection that you actually want, it's possible that …

BUGFIX: resource:clean will remove resource from right collection

---

Neos.Cache/Classes/Backend/PdoBackend.php

When configuring the `PdoBackend` to use an SQLite database
it will be set up automatically upon connection.
Invoking the `cache:setup` command afterwards leads to an
error:
General error: 1 table "cache" already exists
With this fix, the creation of cache tables is skipped for
SQLite databases during setup.
Fixes: #1763

BUGFIX: Avoid error when setting up SQLite cache backends

---

Neos.Flow/Classes/Http/Helper/UploadedFilesHelper.php
Neos.Flow/Classes/Mvc/Routing/Dto/ResolveContext.php
Neos.Flow/Classes/Security/Authentication/AuthenticationProviderManager.php
Neos.Flow/Classes/Security/Cryptography/SaltedMd5HashingStrategy.php
Neos.Flow/Classes/Session/Session.php

- Method `AuthenticationProviderManager::setSecurityContext()` was removed. Just get it injected.
- Method `ResolveContext::getRequestUri()` was removed. Use `getBaseUri()` instead.
- Method `UploadedFilesHelper::calculateFieldPaths()` was removed which was unused.

!!! TASK: Remove deprecated methods

---

Neos.Flow/Configuration/Settings.yaml
Neos.Flow/Resources/Private/Schema/Settings/Neos.Flow.utility.schema.yaml

Remove the configuration in flow and the according settings schema, 
as the Lock package was removed already in https://github.com/neos/flow-development-collection/pull/1771

TASK: Remove lockStrategyClassName from settings

---

Neos.Flow/Classes/Validation/Validator/AbstractValidator.php
Neos.Flow/Classes/Validation/Validator/CollectionValidator.php
Neos.Flow/Classes/Validation/Validator/GenericObjectValidator.php

Don't access `$this->result` inside Validators and instead use pushResult/popResult/getResult.

!!! TASK: Set $result private, to remove it from the interface

---

Neos.Flow/Tests/Functional/Http/RequestHandlerTest.php
Neos.Flow/Tests/FunctionalTestCase.php
Neos.Flow/Tests/Unit/Http/Component/TrustedProxiesComponentTest.php

This fixes two symptoms:
- the time reported for functional tests (used to be years…)
- an error in the RequestHandlerTest caused by the PhpUnit Timer
complaining about not being able to determine the time

BUGFIX: Avoid changing REQUEST_TIME in functional tests

---

Neos.Flow/Classes/Mvc/View/ViewInterface.php

The `render()` in `ViewInterface` method used to return a string,
but now that is no longer true. This makes the docblock list the
return types that our `ActionController` handles, to lessen the
potential for confusion.

TASK: Fix documented return type for ViewInterface.render()

---

Neos.Flow/Classes/Validation/Validator/CollectionValidator.php
Neos.Flow/Tests/Unit/Validation/Validator/CollectionValidatorTest.php

Use more generic `AbstractLazyCollection` instead of `PersistentCollection` in `isValid()` of `CollectionValidator` to prevent lazy collection of classes extending `AbstractLazyCollection` to get loaded.
In our case we are extending the `AbstractLazyCollection` to add some additional functionality when handling lazy collections. Due to the final Implementation of `PersistentCollection` we are not able to extend this class.
During the `isValid()` check, all data in the collection is loaded from the database and we run into an out of memory error, because our collection is an instance of `AbstractLazyCollection` and not `PersistentCollection`.
I added an additional unit test `collectionValidatorIsValidEarlyReturnsOnUnitializedDoctrineAbstractLazyCollections` to the PR.
See #1796 (now …

BUGFIX: Check for AbstractLazyCollection in CollectionValidator

---

Neos.Flow/Classes/Mvc/Routing/Dto/ResolveContext.php
Neos.Flow/Classes/Mvc/Routing/Dto/UriConstraints.php
Neos.Flow/Classes/Mvc/Routing/UriBuilder.php
Neos.Flow/Tests/Functional/Mvc/Fixtures/Controller/UriBuilderController.php
Neos.Flow/Tests/Functional/Mvc/Fixtures/RoutePartHandler/UriBuilderSetDomainAndPathPrefixRoutePartHandler.php
Neos.Flow/Tests/Functional/Mvc/Fixtures/RoutePartHandler/UriBuilderSetDomainRoutePartHandler.php
Neos.Flow/Tests/Functional/Mvc/RoutingTest.php
Neos.Flow/Tests/Functional/Mvc/UriBuilderTest.php
Neos.Flow/Tests/Unit/Mvc/Routing/Dto/UriConstraintsTest.php
Neos.Flow/Tests/Unit/Mvc/Routing/RouterTest.php
Neos.Flow/Tests/Unit/Mvc/Routing/UriBuilderTest.php

(this is hard to explain, checked into this with @bwaidelich).
In case all of the following conditions are met::
1) RoutePartHandler with custom hostname
- you have a custom RoutePartHandler, which...
- returns a `ResolveResult`, which ...
- switches to a different hostname (using `->withHost(...)`
2) and you create a link through through this route,
then: the URL contains two slashes after the hostname (i.e. `http://my-host//test`).
(see test case)
With Flow 6.0, a very subtle change to the URL handling happened:
- For Flow < 6.0, we had our own Uri implementation, where the withPath() method looked like this: https://github.com/neos/flow-development-collection/blob/5.3/Neos.Flow/Classes/Http/Uri.php#L577-L600.
- For Flow = 6.0, we switched to `GuzzleHttp\Psr7\Uri`, whose method looks …

BUGFIX: fix double "//" encoding in some URLs

---

Neos.Flow/Classes/Session/Http/SessionResponseComponent.php

This would e.g. overwrite cookies set with the FlashMessage CookieStorage.
Related to #1807
Replacement for #1808 targeted onto 5.1

BUGFIX: Don't overwrite previous Set-Cookie headers in the session component

---

Neos.Flow/Configuration/Settings.Http.yaml
Neos.Flow/Configuration/Settings.Mvc.yaml

This unfortunately got lost when rebasing the feature and was unnoticed till now.
Needs to be 'after setSessionCookie' because that component always overrides the 'Set-Cookie' header right now (see #1810). Apparently, flash message `CookieStorage` doesn't play well with this, hence we also need to change the default storage to `SessionStorage` at least until that is resolved.
Resolves #1807

BUGFIX: Add the FlashMessageComponent to http chain

---

Neos.Flow/Classes/Mvc/ActionRequest.php
Neos.Flow/Classes/Mvc/Controller/AbstractController.php
Neos.Flow/Classes/Mvc/Routing/UriBuilder.php
Neos.Flow/Tests/Unit/Mvc/Routing/UriBuilderTest.php

The ActionRequest needs to set the sub-package key to null when an
empty string is input. This used to be the case earlier and the
handling is effectively just reverted to that behaviour by this.
Fixes #1819

BUGFIX: Fix setting sub-package key in ActionRequest

---

Neos.Flow/Classes/Http/Helper/UploadedFilesHelper.php

Guzzle throws an exception when trying to access the stream of an errored file upload.

BUGFIX: Avoid exception when upcasting errorenous file upload

---

Neos.Flow/Classes/ObjectManagement/Proxy/ProxyClass.php
Neos.Flow/Classes/Validation/Validator/GenericObjectValidator.php
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Validation.rst
Neos.Flow/Tests/Unit/Persistence/RepositoryTest.php
Neos.FluidAdaptor/Classes/ViewHelpers/Security/IfHasRoleViewHelper.php
Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/DateViewHelperTest.php

The new option `skipUnInitializedProxies` allows to skip validation
of uninitialized proxy instances, to avoid recursions down into
unchanged hierarchies.

FEATURE: Allow to skip validation of uninitialized proxies

---

Neos.Flow/Classes/Mvc/Controller/ActionController.php
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/ModelViewController.rst

This allows to return PSR7 streams, PHP resources or anything else that guzzle stream_for can deal with from the action.
https://github.com/guzzle/psr7/blob/master/README.md#function-stream_for
With that it is possible to just do this in an action:
```php
return fopen('/path/to/file', 'r');
```
Resolves #1800

BUGFIX: Allow to return PSR7 streams and PHP resources/file handles from action

---

Neos.Flow/Classes/Http/Helper/ResponseInformationHelper.php
Neos.Flow/Classes/Http/RequestHandler.php

PSR-7 `getHeaderLine()` defaults to concatenating header values with a comma. This doesn't work for the `Set-Cookie` header, so it must be treated uniquely.
Now having multiple headers of the same name, `header()` must be used without replacement of duplicate headers (which is default).
See:
https://www.php-fig.org/psr/psr-7/#headers-with-multiple-values
https://tools.ietf.org/html/rfc7230#section-3.2.2
https://github.com/guzzle/psr7/issues/298
/cc @kitsunet @albe

BUGFIX: Set-Cookie headers mustn't be imploded

---

Neos.Flow/Classes/Package/PackageManager.php
Neos.Flow/composer.json
composer.json

This bugfix ensures, that the `composer require` command always gets executed in the Flow root path (by calling composer require with the --working-direcory flag set to `FLOW_PATH_ROOT `.)
It also introduces the `composer/composer` package to the codebase to replace the `exec` command.
Fixes #1832
Fixes #1778

BUGFIX: Always run composer from Flow root path

---

Neos.Flow/Classes/ResourceManagement/Collection.php

The method docblock stated that it returns a `Generator`, while in reality for a `PackageStorage` with patterns, it would fall back to an `AppendIterator`.
This change instead makes use of `yield` to return the `StorageObjects` in a memory-efficient manner.

TASK: Use yield instead of AppendIterator in getObjects

---

Neos.Flow/Classes/ResourceManagement/Collection.php

This fixes a regression introduced in #1842:
In this change, a "yield" and a "return" call were introduced in the
same method; so that the early return was not properly executed
because PHP somehow thought this is a fully-suspendable function,
although only one part of the "if"-statement was suspendable.
Related: #1842

BUGFIX: fix resource publishing

---

Neos.Flow/Classes/Cli/ConsoleOutput.php

The symfony/console package got new limitations for rendering
the progress bar in quick succession with minor version 4.4.
We need to disable these limitations by default for now as they
break our own tests.
We should think about following the defaults in the future and
adjust our tests accordingly.

BUGFIX: Check existence and disable new rendering limitations

---

Neos.Flow/Classes/Validation/Validator/StringLengthValidator.php
Neos.Flow/Tests/Unit/Validation/Validator/StringLengthValidatorTest.php

Adds an option `ignoreHtml` to the `StringLengthValidator`
Usage:
$validator = new StringLengthValidator(['maximum' => 14, 'ignoreHtml' => true]);
$validator->validate('Some <b>bold</b> text')->hasErrors(); // false
Resolves: neos/neos-ui#2579

FEATURE: Allow StringLengthValidator to ignore HTML tags

---

Neos.Flow/composer.json
composer.json

This has been at ^1.2 for ages, basically since Flow exists. Now, that
version is really, really old (from 2006) and the package has long been
moved from PECL into the PHP source (see https://pecl.php.net/package/json)
With PHP 7.4.0RC6 (at least), the version reported for ext-json is the
same as the PHP version, this blocks installation via composer.
Those two facts seems to warrant a simple * for that extension dependency,
like for the other PHP extensions we depend on.

TASK: Remove version number from ext-json dependency

---

Neos.Flow/Classes/Mvc/ActionResponse.php
Neos.Flow/Classes/Mvc/Controller/ActionController.php
Neos.FluidAdaptor/Classes/Core/Widget/AbstractWidgetViewHelper.php

To fix a bug in Neos this ensures that the ActionReponse properties
are applied to a HTTP response rendered
by a View (a new feature in 6.0).
Technically this should not be necessary as any HTTP response rendered
by a View should be understood as being "complete", sadly that is not
always the case with plugins and widgets so we need to take this detour
for now to apply the properties. In the future this should happen in
the respective Views directly and no longer be the responsiblity of
the MVC or HTTP layer.

BUGFIX: Ensure ActionReponse properties end up in any HttpResponse

---

Neos.Flow/Classes/Configuration/ConfigurationManager.php
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Configuration.rst

This change sets `$allowSplitSource` to `true` for all configuration types.
In addition it changes the default value for that flag to true in the method
`registerConfigurationType()`.
Resolves #603

FEATURE: Allow split sources for all configurations

---

.travis.yml
Neos.Eel/Tests/Unit/Helper/StringHelperTest.php
Neos.Flow/Classes/Aop/Pointcut/PointcutExpressionParser.php
Neos.Flow/Classes/Http/Helper/UploadedFilesHelper.php
Neos.Flow/Classes/Session/Session.php
Neos.Flow/Tests/Unit/Mvc/Routing/RouteTest.php
Neos.Flow/Tests/Unit/Persistence/Generic/SessionTest.php

TASK: PHP 7.4 compatibility

---

Neos.Flow/Classes/Cache/CacheFactory.php

The `FlowSpecificBackendInterface` as well as `Neos\Flow\Cache\Backend`
are gone with Flow 5.0, so this code is never executed.
The `implements CacheFactoryInterface` is redundant, thus removed.

TASK: Remove code dealing with removed class/interface

---

Neos.Cache/Resources/Private/mysql.DDL.sql
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Caching.rst
Neos.Utility.Pdo/Classes/PdoHelper.php

Note: No migrations exist for the PDO cache backend!
To make sure the cache and tags tables are up-to-date, you need to
remove them manually and the run the cache:setup CLI command to have
them recreated with the most recent definition.
Unless you have persistent caches, that should be no problem, but
give that a thought first.
The reasoning behind this change is explained in the documentation
of MySQL and MariaDB.
For MySQL https://dev.mysql.com/doc/refman/8.0/en/innodb-index-types.html
explains:
> If the table has no PRIMARY KEY or suitable UNIQUE index, InnoDB
> internally generates a hidden clustered index named GEN_CLUST_INDEX
> on a synthetic column containing row ID values. The rows are ordered
> by the ID that InnoDB assigns to the rows in such a table. The row
> ID is a 6-byte …

TASK: Add a primary key to "tags" table for MySQL/MariaDB

---

Neos.Cache/Classes/Backend/PdoBackend.php

This makes sure all DB statements during a `set()` operation are in
one transaction, to avoid race conditions.
Fixes #1874

BUGFIX: Include entry removal into DB transaction during set

---

Neos.Flow/Classes/Mvc/DispatchComponent.php

This might seem like a micro optimisation but in fact we create the whole HTTP chain (components) before starting to run the chain, so if something cancels the chain the components after it would still be build. The components itself are a minor problem but I will provide a change for master to lazily create those as well, but the dependency chain of the dispatcher is so big that this change can actually make a difference when combined with something like the FullPageCache package.

BUGFIX: Inject Dispatcher lazily

---

Neos.Flow/Classes/ObjectManagement/CompileTimeObjectManager.php
Neos.Flow/Classes/ObjectManagement/ObjectManager.php

This uses variadic arguments instead of `func_get_args`
in the object manager.

TASK: Switch to variadic function in object manager

---

Neos.Flow/Classes/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php
psalm-baseline.xml

The TableGenerator was never supported anyways, and the Doctrine
fixes are rather cosmetic. But less deprecation = better code.

TASK: Fix some psalm complaints

---

Neos.Flow/Classes/Http/Request.php

When `setBaseUri()` is used with an URI that has query parameters
or a fragment, this leads to broken link generation. Usually a non-issue,
since `detectBaseUri()` is used most often, and that removes those
already.

BUGFIX: Remove fragment/query in setBaseUri()

---

Neos.Flow/Classes/ResourceManagement/Storage/WritableFileSystemStorage.php

While working with `ResourceManager` I noticed that importing non-existent resources would fail later in the process than expected: They would only fail when trying to copy the temporary file to it's persistent location instead of failing when fetching the original file.
**What I did**
This PR fixes the incorrect error handling of fetching files when importing resources.
The code assumed that `copy` would throw an exception if it failed - however, it returns `false` in that case.
Try to import a non-existent resource (e.g. http://example.com/this-file-does-not-exist). It should now correctly throw the `Could not copy the file from "..." to temporary file "..."` exception  from `WritableFileSystemStorage::importResource` instead of the much later `The …

BUGFIX: Fix error handling for importing resources

---

Neos.Flow/Classes/I18n/Cldr/Reader/DatesReader.php

It might happen that there is a discrepancy between parsedFormatsIndices and parsedFormats cache. We need to make sure we are accessing the consistent information instead of relying that both are there, to avoid a PHP exception.
Resolves #564 
The problem described in #564 is not easy to reproduce, as it only happens "once in a while" in production. See issue comments for further information.
**Checklist**

BUGFIX: Make sure to use only a consistent DatesReaderCache

---

.travis.yml

Fixes build config validation complaints:
- W notifications.slack: unknown key on_start (never)
- I root: missing os, using the default linux
- I root: key matrix is an alias for jobs, using jobs

TASK: Fix validation warnings/errors on .travis.yml

---

Neos.Flow/Classes/Reflection/ParameterReflection.php
Neos.Flow/Classes/Reflection/ReflectionService.php
Neos.Flow/Tests/Unit/Reflection/Fixture/AliasedClass.php
Neos.Flow/Tests/Unit/Reflection/Fixture/ClassWithAlias.php
Neos.Flow/Tests/Unit/Reflection/Fixture/ClassWithAliasDependency.php
Neos.Flow/Tests/Unit/Reflection/ReflectionServiceTest.php

The namespace change introduced with doctrine/persistence 1.3.x makes use of `class_alias` to create a b/c layer over the old class names (see https://github.com/greg0ire/type_deprecation_experiment). However, this broke for a couple of our depending packages that still used the old `Doctrine\Common\Persistence\ObjectMananger` class as a method typehint.
The reason is, that PHP Reflection returns different values for aliased method parameter types when using `ReflectionParameter::getClass()->getName()` vs. `ReflectionParameter::getType()->getName()`.
The former returns the name of the actual class, instead of the alias, while the latter returns the actual name that was used in the typehint, regardless if it is an alias only.
In turn, this led our dependency injection to try to inject …

BUGFIX: Correctly reflect type of aliased classes in method typehints

---

Neos.Flow/Classes/Reflection/DocCommentParser.php
Neos.Flow/Tests/Unit/Reflection/DocCommentParserTest.php

Fixes #1900
**What I did**
Single line docblocks would break AOP compilation because the end-comment string `*/` would be interpreted as part of the comment.
The end-comment string `*/` is now removed from all lines before parsing them. This means that the previous check for the end of the comment `if ($line === '*/`)` no longer works but as far as I could determine this explicit check is not actually needed.
There are tests
**Checklist**

BUGFIX: Parse single-line docblock comments correctly

---

Neos.Cache/Classes/Backend/PdoBackend.php

**What I did**
Call `connect` in `rewind` method to make sure that a connection exists.

BUGFIX: Prevent connection error when calling getIterator for PdoBackend

---

Neos.Flow/Classes/Persistence/Doctrine/Logging/SqlLogger.php

The SqlLogger did not log anything since Flow 6.0 due to a instanceof check, when it was a dependency proxy. This change resolves the dependency.
Resolves #1854

BUGFIX: Resolve SqlLogger when it is a dependency proxy

---

Neos.Flow/Classes/Reflection/ReflectionService.php

Currently the method `saveProductionData()` from the `ReflectionService`
writes to both caches `reflectionDataRuntimeCache` and
`classSchemataRuntimeCache` but flushes only the former first.
Additionally the `hasFrozenCacheInProduction()` method only checks
the first cache.
This allows a race condition where the `classSchemataRuntimeCache` is
built and frozen but `reflectionDataRuntimeCache` isn't.
This change ensures the `classSchemataRuntimeCache` is also flushed.
Error message:
```
Exception #1323344192 in line 68 of /var/www/Packages/Libraries/neos/cache/Classes/Frontend/VariableFrontend.php: Cannot add or modify cache entry because the backend of cache "Flow_Reflection_RuntimeClassSchemata" is frozen.
```

BUGFIX: Flush classSchemataRuntimeCache before saving production data

---

Neos.Flow/Classes/Http/Helper/UploadedFilesHelper.php

When uploading multiple files (i.e. in an array), the existing files (persisted resource) would be dropped.
By modifying the `$currentPath` value, Flow built a wrong path:
The first file would be fine - f.e. path "files.0", but the second one will fail due to the path being "files.0.1" instead of "files.1".
fixes #1857

BUGFIX: Uploaded file upcasting with multiple files

---

Neos.Flow/Classes/Http/Client/Browser.php
Neos.Flow/Classes/Http/Helper/UploadedFilesHelper.php

Reverts neos/flow-development-collection#1917
This should have landed in 6.0, see #1922

Revert "BUGFIX: Browser correctly builds uploaded files from form"

---

Neos.Flow/Classes/Core/Booting/Scripts.php
Neos.Flow/Classes/Log/ThrowableStorage/FileStorage.php

Fixed the checking for valid request and response objects.
Remove superflous configuration of throwablestorage in `Scripts::initializeExceptionStorage`

BUGFIX: Fix output of request and response in throwable storage

---

Neos.Cache/Classes/Backend/FileBackend.php

When `substr($metaData, 0, -self::EXPIRYTIME_LENGTH)`on
`$metadata` in the cache `FileBackend.findIdentifiersByTag()`
method fails, `false` is passed to `explode()` causing:
`Exception in line 253 of /…/FileBackend.php: explode() expects
parameter 2 to be string, boolean given`
This fixes that by casting the result to a string.

BUGFIX: Avoid exception in findIdentifiersByTag()

---

Neos.Flow/Classes/Security/Authorization/Privilege/Entity/Doctrine/PropertyConditionGenerator.php

**What I did**
Fixed the behavior of the `\Neos\Flow\Security\Authorization\Privilege\Entity\Doctrine\EntityPrivilege` if you execute an `in` operation on an empty array.
```yaml
matcher: 'isType("Neos\Neos\Domain\Model\Site") && !property("nodeName").in("context.userInformationContext.siteNodeNames")'
```
If `getSiteNodeNames()` evaluates to `[]` which is possible and valid, the PropertyGenerator tries to to `getParameter()` on this value which can only be applied to scalar values.
This is caused by only checking on an exact `null`, but an empty array should also be ignored.
Rebased follow-up to #1681

BUGFIX: EntityPrivilege fails on empty IN condition

---

Neos.Flow/Classes/Core/Bootstrap.php
Neos.Flow/Classes/Core/ProxyClassLoader.php
Neos.Flow/Classes/Utility/Environment.php

Previously there were three different implementations of the composition of a temporary directory path name. The one in ProxyClassLoader didn't use SubContexts correctly.
This change unifies all implementations to a central static method `composeTemporaryDirectoryName()`.
Previous error message:
```
include(): Failed opening '/var/www/myproject/Data//Temporary/Development/Local/AvailableProxyClasses.php' for inclusion (include_path='.:/usr/share/php')
```

BUGFIX: Fix usage of SubContexts in ProxyClassLoader

---

Neos.Cache/Classes/Backend/PdoBackend.php
Neos.Flow/Classes/Utility/Now.php
Neos.Flow/Configuration/Settings.Reflection.yaml

TASK: Fix psalm errors

---

Neos.Flow/Classes/Mvc/Controller/ActionController.php
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Templating.rst

In order for a package to interact with the rendering views available variables
a signal is being emitted upon resolving of the view.
The variables will be available in the view in the MVC context only
Resolves #1902
**What I did**
I added a Signal/Slot once the view has been resolved
Test functionality with the following package
https://github.com/sorenmalling/SorenMalling.EmitViewResolved

FEATURE: Emit a signal when view is resolved

---

Neos.Flow/Classes/Security/Authentication/AuthenticationTokenResolver.php
Neos.Flow/Classes/Security/Authentication/TokenAndProviderFactory.php
Neos.Flow/Classes/Security/Exception/NoAuthenticationTokenFoundException.php
Neos.Flow/Tests/Unit/Security/Authentication/AuthenticationTokenResolverTest.php
Neos.Flow/Tests/Unit/Security/Authentication/TokenAndProviderFactoryTest.php

The documentation has long been showing that you can define
a security token by it's simple name, if in the Neos.Flow
package.
This has not been really true, since there was no resolving
from the simple string, similar to how providers has been
resolved.
This change brings the same resolving functionality as the
provider
Resolves #947
Added a new Resolver class, with exact same functionality as the AuthenticationProviderResolver class
Use the documentation example of a token and provider example
https://flowframework.readthedocs.io/en/6.0/TheDefinitiveGuide/PartIII/Security.html#reuse-of-tokens-and-providers

FEATURE: Resolve authentication token by simple name

---

Neos.Flow/Classes/Mvc/ActionRequest.php
Neos.Flow/Classes/Mvc/DispatchComponent.php
Neos.Flow/Classes/Property/TypeConverter/MediaTypeConverter.php

When sending e.g. a JSON request with an array as body (["foo","bar"]), Flow would throw an exception "Invalid argument name (must be a non-empty string)." when visiting the array key "0" due to the `empty()` check.
This change fixes that by backporting a fix that is already in place in Flow 6.0+ which only checks for empty string.
Such an array can not be mapped to a controller argument, but you can still technically access the argument from the controller via `$this->arguments->getArgument("0")` or the whole body via
`$this->request->getHttpRequest()->getParsedBody()`.
Replaces #1913

BUGFIX: Allow numeric array body in request

---

Neos.Flow/Classes/Security/Authentication/AuthenticationTokenResolver.php

Some small follow-up fixes to https://github.com/neos/flow-development-collection/pull/1936

TASK: Fix variable naming in AuthenticationTokenResolver

---

Neos.Flow/Classes/Package/PackageManager.php

Fixes https://github.com/neos/flow-development-collection/pull/1549 again for 6.0+ after https://github.com/neos/flow-development-collection/commit/1eb95525a63420e1a35f103c943d36de5a515b75 accidentially reverted it.
Thanks @radmiraal

BUGFIX: Fix upmerge error

---

Neos.Flow/Classes/Persistence/Doctrine/ObjectValidationAndDeDuplicationListener.php

This fix is needed since commit 2f860a586753551b64785c91a87798ad124bb171 of version 5.3.13
Doctrine entities from third party packages that are not included by the Flow setting Neos.Flow.object.includeClasses are not known to the reflection service anymore when running in Production context. This resulted in an exception when calling the deduplicateValueObjectInsertions() function when having such entities scheuduled for insertion. The added not null check fixes this exception but also skips the duplication validation for those entities.
The related reflection and caching issue which brought up this problem is addressed in https://github.com/neos/flow-development-collection/issues/1950

BUGFIX: Persist doctrine entities unknown to the reflection service

---

Neos.Flow/Classes/Command/CacheCommandController.php

In order to run garbage collection the following command
has been introduced
`./flow cache:collectgarbage`
which will iterator over all configured caches and
run the corresponding `collectGarbage` method.
You can also run garbage collection on a single cache
by definined the cache identifier
`./flow cache:collectgarbage --cache-identifier Flow_Monitor`
Resolves #863

FEATURE: Run garbage collection of configured caches

---

Neos.Flow/Classes/ObjectManagement/CompileTimeObjectManager.php
Neos.Flow/Classes/ObjectManagement/Configuration/Configuration.php
Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php
Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php
Neos.Flow/Classes/ObjectManagement/ObjectManager.php
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/ObjectManagement.rst
Neos.Flow/Tests/Unit/ObjectManagement/Configuration/ConfigurationTest.php
Neos.Flow/Tests/Unit/ObjectManagement/Fixture/StaticFactory.php
Neos.Flow/Tests/Unit/ObjectManagement/ObjectManagerTest.php
Neos.Utility.ObjectHandling/Classes/ObjectAccess.php

This change allows to configure static factory methods in `Objects.yaml` by only specifying a `factoryMethodName` and leaving out `factoryObjectName`.
Example:
```
Acme\My\Class:
factoryMethodName: Acme\My\Class::fromStatic
arguments:
1:
setting: Acme.My.Class.ConfigurableValue
```
Before this would have required to create a non-static factory method inside a dedicated factory class (to avoid cyclic instanciation).

FEATURE: Allow configuring static factory methods in Objects.yaml

---

Neos.Flow/Classes/Http/Helper/ResponseInformationHelper.php
Neos.Flow/Tests/Unit/Http/Helper/ResponseInformationHelperTest.php

For responses that match the following conditions an 304 status is returned:
- The request method is GET or HEAD.
- The response status is 200 status.
- The response has has ETag header that matches one of the If-None-Match headers of the request.
!!! The generation of the Etag header is not part of this change and is the job of the application.
Other changes: 
- 304 responses now have an empty body
- Only GET and HEAD Requests will receive 304 status based on ETag and Last-Modified headers
**Checklist**

FEATURE: Improve 304 response handling

---

Neos.Flow/Classes/Error/Debugger.php

This change lets the debug-array-renderer use the pseudo type iterable (Array or Traversable) instead of array. That way all foreachachble objects are rendered as an array. 
This replaces the previous exceptions for ArrayObjects and DoctrineCollections and will also enable to properly debug other Traversable objects aswell.

FEATURE: Array Debugger tolerates iterables

---

Neos.Flow/Classes/ObjectManagement/CompileTimeObjectManager.php
Neos.Flow/Classes/ObjectManagement/Configuration/Configuration.php
Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php
Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php

Until now a class configured to be constructed by a factory with arguments would end up giving those arguments to both the factory and the class constructor. This can lead to errors when the class constructor expects different arguments.
This change fixes that by separating the arguments for the factory from the class constructor arguments. The `arguments` setting in `Objects.yaml` will refer to the factory method arguments when `factoryObjectName` is given, otherwise to the class constructor arguments.
Fixes #1933

BUGFIX: Objects configured with factory don't receive factory arguments

---

.travis.yml
Neos.Flow/composer.json
composer.json

This should make the psalm runs more consistent by pinning the psalm version to a minor. If we want to update to a newer version to cover new checks, we now need to manually update the dependency version and fix new errors by changing our codebase or the psalm-baseline.

TASK: Don't install latest psalm in travis runs every time

---

Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php

The original code only attempted to fix newly introduced factory arguments, but since #1967 those factory arguments are separated from object arguments. Hence this "fix" didn't work any more.

BUGFIX: Adapt virtual objects change to factory arguments bugfix

---

Neos.Flow/Classes/I18n/Cldr/Reader/NumbersReader.php

It might happen that there is a discrepancy between parsedFormatsIndices and parsedFormats cache. We need to make sure we are accessing the consistent information instead of relying that both are there, to avoid a PHP exception.
Same fix was already applied to DatesReader, see https://github.com/neos/flow-development-collection/pull/1899.
Resolves #564
**Checklist**

BUGFIX: Make sure to use only a consistent NumbersReaderCache

---

.github/main.workflow
.github/workflows/issue_comment.yml

Idea is that a `/rebase` comment rebases the current PR on top of the destination branch, so that we are sure that latest state is included. Current implementation tries the rebase on every comment (see results in https://github.com/neos/flow-development-collection/actions).
In 6.1/6.2 the action was already converted to "v2" style (see https://github.com/neos/flow-development-collection/pull/1765).
So in 5.3 first cherry-picked the conversion from 
After that changed the workflow definition so it looks exactly like the documented:
https://github.com/cirrus-actions/rebase

TASK: Trigger GitHub rebase action only on /rebase

---

Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php
Neos.Flow/Tests/Functional/Persistence/Fixtures/ObjectHoldingAnEntity.php
Neos.Flow/Tests/Functional/Persistence/PersistenceTest.php

BUGFIX: Allow objects to be serialized twice without loosing their relations to persisted properties

---

Neos.Flow/Classes/Command/DoctrineCommandController.php
Neos.Flow/Classes/Persistence/Doctrine/Mapping/ClassMetadata.php
Neos.Flow/Classes/Persistence/Doctrine/Repository.php
Neos.Flow/Classes/Security/Authorization/Privilege/Entity/Doctrine/ConjunctionGenerator.php
Neos.Flow/Classes/Security/Authorization/Privilege/Entity/Doctrine/DisjunctionGenerator.php
Neos.Flow/Classes/Security/Authorization/Privilege/Entity/Doctrine/EntityPrivilege.php
Neos.Flow/Classes/Security/Authorization/Privilege/Entity/Doctrine/FalseConditionGenerator.php
Neos.Flow/Classes/Security/Authorization/Privilege/Entity/Doctrine/NotExpressionGenerator.php
Neos.Flow/Classes/Security/Authorization/Privilege/Entity/Doctrine/PropertyConditionGenerator.php
Neos.Flow/Classes/Security/Authorization/Privilege/Entity/Doctrine/SqlGeneratorInterface.php
Neos.Flow/Classes/Security/Authorization/Privilege/Entity/Doctrine/TrueConditionGenerator.php
Neos.Flow/Classes/Security/Authorization/Privilege/Entity/EntityPrivilegeInterface.php
Neos.Flow/Tests/Unit/Reflection/Fixture/Model/EntityWithDoctrineProxy.php
Neos.Utility.ObjectHandling/Tests/Unit/Fixture/Model/EntityWithDoctrineProxy.php

This fixes psalm errors due to the namespace renaming of various doctrine classes in doctrine/orm 2.7.3 release. The old class name was an alias since 2.7, so this should not break anything. 🤞

TASK: Rename Doctrine\Common\Persistence -> Doctrine\Persistence

---

Neos.Flow/Classes/Security/Authentication/Provider/PersistedUsernamePasswordProvider.php
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Security.rst
Neos.Flow/Tests/Unit/Security/Authentication/Provider/PersistedUsernamePasswordProviderTest.php

Adds an option `lookupProviderName` to the `PersistedUsernamePasswordProvider` that allows the provider to be reused for multiple authentication types.
Example:
```yaml
Neos:
Flow:
security:
authentication:
providers:
'Acme.SomePackage:Default':
provider: PersistedUsernamePasswordProvider
token: UsernamePassword
'Acme.SomePackage:Default.HttpBasic':
provider: PersistedUsernamePasswordProvider
providerOptions:
lookupProviderName: 'Acme.SomePackage:Default'
token: UsernamePasswordHttpBasic
entryPoint: HttpBasic
```
Resolves: #1996

FEATURE: Configurable PersistedUsernamePasswordProvider lookup name

---

Neos.FluidAdaptor/Classes/Core/Widget/AjaxWidgetComponent.php
Neos.FluidAdaptor/Resources/Private/Templates/Tests/Functional/Core/Fixtures/ViewHelpers/SomeAjax/Index.html
Neos.FluidAdaptor/Tests/Functional/Core/Fixtures/ViewHelpers/Controller/SomeAjaxController.php
Neos.FluidAdaptor/Tests/Functional/Core/Fixtures/ViewHelpers/Controller/View/CustomView.php
Neos.FluidAdaptor/Tests/Functional/Core/WidgetTest.php

If a WidgetController has a view returning a PSR-7 response, it
was not replaced in Ajax context. Now the behavior of the
ReplaceComponent is merged into the AjaxWidgetComponent, so the
expected ActionController behavior can be guaranteed
Solves: #2027

BUGFIX: Allow Views to replace the response in AjaxWidgetContext

---

Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php
Neos.Flow/Tests/Unit/ObjectManagement/Configuration/ConfigurationBuilderTest.php

This bug was uncovered with the previous fix to not map arguments to the object when a factory is configured (see #1967).
That way (singleton) objects which expected a (non-optional/nullable) constructor argument that could not be autowired (e.g. because it was a scalar) would lead to the exception "Could not autowire required constructor argument ... for singleton class ...".
This change fixes that, by completely skipping autowiring for objects configured with a factory. The factory has full responsibility to create and wire the constructor arguments correctly.

BUGFIX: Avoid trying to autowire constructor arguments for factory created objects

---

Neos.Flow/Configuration/Settings.Log.yaml

Updating https://github.com/neos/flow-development-collection/pull/1998 to correct version.

BUGFIX: Correct default log file size

---

Neos.Cache/Classes/Backend/PdoBackend.php

Running the setup for a PdoBackend multiple times should
not lead to an error, similar to other Backends.
Resolves: #2039
**What I did**
Allow PdoBackend::setup() to be called multiple times.
Check if cache tables exist in PdoBackend::setup() before creating them.
See #2039

BUGFIX: Check if PdoBackend cache tables exist in setup

---

Neos.Flow/Classes/Core/Booting/Scripts.php

The check if the current executing php binary path as set in `PHP_BINARY` matches the given setting in `phpBinaryPathAndFilename` was case-sensitive. This check is only done when the setting is specified and should guarantee that the path specified refers to the same binary as the one executing the current script. On Windows, the filesystem is case-insensitive by default though (Windows 10 has options to make it case-sensitive) and the chance that someone accidentially gets the casing of the path wrong on windows is (arguably) much more likely than someone having different versions of php installed on a case-sensitive filesystem in pathes `/foo/PHP/php` and `/foo/php/php` respectively.
~Even if that would be the case, if the two versions do not match the check at …

BUGFIX: Make php binary setting check use realpath

---

Neos.Eel/Classes/Helper/ArrayHelper.php
Neos.Eel/Classes/Helper/MathHelper.php
Neos.Eel/Tests/Unit/Helper/ArrayHelperTest.php
Neos.Eel/Tests/Unit/Helper/JsonHelperTest.php
Neos.Flow/Classes/Aop/AdvicesTrait.php
Neos.Flow/Classes/Cli/CommandController.php
Neos.Flow/Classes/Mvc/Controller/ActionController.php
Neos.Flow/Classes/ObjectManagement/DependencyInjection/DependencyProxy.php
Neos.Flow/Classes/ObjectManagement/ObjectManager.php
Neos.Flow/Classes/ObjectManagement/Proxy/ProxyConstructor.php
Neos.Flow/Classes/Persistence/Doctrine/Query.php
Neos.Flow/Classes/Session/Aspect/LazyLoadingAspect.php
Neos.Flow/Classes/SignalSlot/Dispatcher.php
Neos.Flow/Tests/Behavior/Features/Bootstrap/SecurityOperationsTrait.php
Neos.FluidAdaptor/Classes/Core/ViewHelper/AbstractViewHelper.php
Neos.Utility.ObjectHandling/Classes/ObjectAccess.php

This is supported since PHP 5.6 and is actually faster than call_user_func_array at least since PHP 7.
Just be sure to not use it in places where the method is static or a Closure.
This also deprecates `ObjectAccess::instantiateClass()` (retrospectively). It will be removed with Flow 7.

TASK: Use argument unpacking instead of call_user_func_array

---

Neos.Flow/Classes/Http/Client/InternalRequestEngine.php
Neos.Flow/Configuration/Settings.Http.yaml
Neos.Flow/Tests/Functional/Mvc/ActionControllerTest.php
Neos.Flow/Tests/Functional/Mvc/Fixtures/Controller/StandardController.php

The FlashMessages component by default uses the SessionStorage, which depends on sending the session cookie through the SessionResponse component. However, the FlashMessages component was configured to be run **after** the session component. That way, unless a session was (still) open, the `Set-Cookie` was not sent and hence the flash message got lost.
This was primarily visible after logging out and redirecting the user with a flash message.
Thanks @astehlik for finding the root cause!
Resolves #1807

 BUGFIX: Set session cookie after flash message storage

---

Neos.Flow/Classes/Http/Client/Browser.php
Neos.Flow/Tests/Functional/Http/Client/BrowserTest.php
Neos.Flow/Tests/Functional/Http/Fixtures/Controller/RequestController.php

Since 6.0 the Browser `$arguments` were accidentially moved to the request query parameters, while they should reflect the post body arguments.
The docblock even states that:
`@param array $arguments Arguments to send in the request body`
Note that this slightly changes behaviour if you adapted your usage of Browser since 6.0. If you want to send query parameters, you should instead provide an `Uri` instance with the parameters, as was already the case prior to 6.0.

BUGFIX: Browser arguments are the request parsed body

---

Neos.Eel/composer.json
Neos.Flow/Classes/Composer/InstallerScripts.php
Neos.Flow/Tests/FunctionalTestCase.php
Neos.Flow/composer.json
Neos.Kickstarter/composer.json
Neos.Utility.Schema/Readme.rst
composer.json

There never was and never will be a typo3/flow version of 6.3+

TASK: Remove typo3 namespace replacements

---

Neos.Flow/Configuration/Settings.Log.yaml

The configuration of the throwable exceptions should not be part of the `psr3` level. And the default config did not work since 6.0. The method `initializeExceptionStorage` still expects the configuration to be at the path `Neos.Flow.log.throwables`.
Fixes: #2082

BUGFIX: Correct indention for throwables config

---

Neos.Flow/Classes/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Persistence.rst
Neos.Flow/Tests/Functional/Persistence/Doctrine/AggregateTest.php
Neos.Flow/Tests/Functional/Persistence/Fixtures/Post.php
Neos.Flow/Tests/Functional/Persistence/Fixtures/Tag.php
psalm-baseline.xml

Inside a single aggregate `OneToMany` relations are normally best modelled unidirectionally. Bidirectional relations always are harder to manage correctly and can easily lead to unintentional traversal of entity hierarchies with all the drawbacks.
Since Doctrines `OneToMany` annotation is always bidrectional and also dictates the owning side of the relation (at the unexpected side from a modelling PoV), it is not straightforward to modell this correctly.
In Flow specifically, we try to follow DDD best practices in modelling and this means, that the aggregate root is the entry point and the entity that is sent to a repository to persist it and all its subentities. This can not be achieved with the standard doctrine `OneToMany` annotation when the one side is supposed to be closer to the …

!!!FEATURE: Allow unidirectional OneToMany relations

---

Neos.Flow/Classes/ResourceManagement/PersistentResource.php
Neos.Flow/Classes/ResourceManagement/ResourceMetaDataInterface.php
Neos.Flow/Classes/ResourceManagement/Storage/FileSystemStorage.php
Neos.Flow/Classes/ResourceManagement/Storage/PackageStorage.php
Neos.Flow/Classes/ResourceManagement/Storage/StorageObject.php
Neos.Flow/Classes/ResourceManagement/Storage/WritableFileSystemStorage.php
Neos.Flow/Migrations/Mysql/Version20200908155620.php
Neos.Flow/Migrations/Postgresql/Version20200908155621.php

Removes the `md5` property from persistent resources that is obsolete since
we introduced a `sha1` field.
Note:
This change is marked breaking because it removes the two API methods
`PersistentResource::getMd5()` and `PersistentResource::setMd5()`.
In practice this should never be an issue really.
Instead of `PersistentResource::getMd5()` one could use `PersistentResource::getSha1()`
in order to retrieve a unique hash for a file.
In case a MD5 hash is required, the following one can do `md5(stream_get_contents($resource->getStream()))`
Fixes: #2112

!!! BUGFIX: Remove unused MD5 in ResourceMetaDataInterface

---

Neos.Flow/Classes/ResourceManagement/PersistentResource.php
Neos.Flow/Classes/ResourceManagement/ResourceMetaDataInterface.php
Neos.Flow/Classes/ResourceManagement/Storage/StorageObject.php

Marks `ResourceMetaDataInterface::getMd5()` and `ResourceMetaDataInterface::setMd5()` deprecated.
This affects the implementing classes `PersistentResource` and `StorageObject`.
Related: #2112
Related: #2113

BUGFIX: Deprecate unused MD5 in ResourceMetaDataInterface

---

Neos.Flow/Classes/ResourceManagement/ResourceManager.php
Neos.Flow/Configuration/Settings.Resource.yaml
Neos.Flow/Migrations/Code/Version20200813181400.php
Neos.Flow/Resources/Private/Schema/Settings/Neos.Flow.resource.schema.yaml

As part of our move to getting rid of bad wording in our code base, this changes the setting `Neos.Flow.resource.uploadExtensionsBlacklist` to the much more descriptive `Neos.Flow.resource.extensionsBlockedFromUpload`.
This is breaking as it changes the path to a setting, but is covered by a code migration.
Related to #2024

!!!TASK: Rename 'uploadExtensionBlacklist' setting to 'extensionsBlockedFromUpload'

---

Neos.Flow/Classes/Http/Helper/ResponseInformationHelper.php

As defined in RFC 7232 section 4.2 the http status 412 indicates that a precondition for a request failed
and that the requested operation could not be executed which only makes sense for non safe requests.
The bug in here is that this is checked after the fact so Flow would still perform the operation but the standard compliance component would add a precondition failed header and thus not prevent the in flight collision but make the problem harder to understand.
This change removes the code for the 412 status from the standard compliance helper. If any application would want to use the status it should evaluate the precondition headers and throw an exception with 412 status if needed.
Fixes: #2062

!!! BUGFIX: Do not create 412 Status 'Precondition Failed' in standard compliance helper

---

Neos.Flow/Classes/Session/Http/SessionRequestComponent.php
Neos.Flow/Tests/Unit/Http/Component/SessionRequestComponentTest.php

According to RFC 6265 https://tools.ietf.org/html/rfc6265#section-4.1.1 a cookie
value may be enclosed in double quotes.
This change takes this into account by removing the first and last double quote of a
value (enclosing double quotes) when starting/resuming a session.
Fixes: #2133

BUGFIX: Trim enclosing double quotes from session cookie

---

Neos.Flow/Classes/Mvc/Controller/AbstractController.php
Neos.Flow/Tests/Functional/Mvc/AbstractControllerTest.php
Neos.Flow/Tests/Functional/Mvc/Fixtures/Controller/AbstractControllerTestAController.php

This sets the negotiated media type from the Controller in the `ActionResponse`.

BUGFIX: ActionResponse contains negotiated media type as content-type

---

Neos.Flow/Classes/Property/TypeConverter/CollectionConverter.php
Neos.Flow/Tests/Functional/Property/Fixtures/TestClassWithMissingCollectionElementType.php
Neos.Flow/Tests/Functional/Property/PropertyMapperTest.php
Neos.Flow/Tests/Unit/Property/TypeConverter/CollectionConverterTest.php

BUGFIX: Throw helpful exception when collection property has missing element type

---

Neos.Flow/Classes/Aop/JoinPoint.php

BUGFIX: Correctly recognize NULL method arguments in JoinPoint

---

Neos.Flow/Classes/Configuration/RouteConfigurationProcessor.php
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Routing.rst
Neos.Flow/Tests/Unit/Configuration/ConfigurationManagerTest.php

Allows variables to be used in route part handler options like:
```yaml
-
name: 'Some route'
uriPattern: 'some/{part}'
defaults:
routeParts:
'part':
handler:   'Some\RoutePart\Handler'
options:
someOption: '<someVariable>'
```
Related: https://github.com/neos/neos-development-collection/issues/3020
Resolves: #2142

FEATURE: Consider route variables in handler options

---

Neos.Flow/Classes/Configuration/RouteConfigurationProcessor.php
Neos.Flow/Tests/Unit/Configuration/ConfigurationManagerTest.php

Adjusts the `RouteConfigurationProcessor` so that it doesn't implicitly
convert route configuration options to strings when merging routes.
Background:
This fixes a regression introduced with #2145 that lead to the Neos
route
```yaml
-
name: 'Homepage'
uriPattern: '{node}'
routeParts:
'node':
options:
onlyMatchSiteNodes: true
```
to be converted such that the `onlyMatchSiteNodes` option was casted
to a string of `"1"` leading to the homepage route resolving all node links.
Resolves: #2142

BUGFIX: Don't convert route options to strings when merging subroutes

---

Neos.Flow/Classes/Http/BaseUriProvider.php
Neos.Flow/Classes/Mvc/Routing/UriBuilder.php
Neos.Flow/Tests/Unit/Http/BaseUriProviderTest.php

This adds a parameter `$fallbackRequest` to `BaseUriProvider::getConfiguredBaseUriOrFallbackToCurrentRequest()`
that allows it to work in contextx where the active HTTP request
can't get hold of (i.g. in CLI mode).
This also adjusts `UriBuilder::build()` to make use of that new parameter
such that the following code works again from CLI:
```php
$httpRequest = ServerRequest::fromGlobals();
$actionRequest = ActionRequest::fromHttpRequest($httpRequest);
$uriBuilder = new UriBuilder();
$uriBuilder->setRequest($actionRequest);
$uriBuilder->uriFor(...);
```
Previously this would throw an HTTP exception
```
No base URI could be provided. This probably means a call was made outside of an HTTP
request and a base URI was neither configured nor set during runtime.
```
when executed in CLI context. …

BUGFIX: Allow URI-building from CLI context

---

Neos.FluidAdaptor/Classes/ViewHelpers/Format/BytesViewHelper.php
Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/BytesViewHelperTest.php

The `BytesViewHelper` can be localized like the `NumberViewHelper`.
solves #601

FEATURE: Add localization for BytesViewHelper

---

Neos.Flow/Classes/Mvc/Controller/AbstractController.php
Neos.Flow/Tests/Functional/Mvc/AbstractControllerTest.php
Neos.Flow/Tests/Functional/Mvc/Fixtures/Controller/AbstractControllerTestAController.php

This introduced a serious regression with the way responses are merged. With this a ContentType will ALWAYS be set in the ActionResponse which means the if conditions while merging inside the ActionResponse will always be true so no overwriting of the content type can happen from repsonses generated in a view for example. Eg. Fusion responses that override the content type will not be able to do that.
Reverts: #2005

Revert "BUGFIX: ActionResponse contains negotiated media type as content-type"

---

Neos.Flow/Classes/Persistence/Doctrine/ConnectionFactory.php
Neos.Flow/Configuration/Objects.yaml

Questions:
-  ~Should it have a options argument, so you can override configuration?~ (nope - see comment below)
Resolves: #2170

FEATURE: Introduce connection factory

---

.travis.yml
Neos.Flow/Classes/Security/Authorization/Privilege/AbstractPrivilege.php
Neos.Flow/Classes/Security/Authorization/Privilege/PrivilegeTarget.php
Neos.Flow/Classes/Security/Policy/PolicyService.php
Neos.Flow/Classes/Security/Policy/Role.php
Neos.Flow/Tests/Unit/Security/Policy/RoleTest.php

This adds the optional configuration values label and description
to role definitions and label to privilege targets. The meta data can
be used to document roles and privilegeTarget and to guide
administrators to assign the correct roles to users.
Example:
```
'Neos.Neos:UserManager':
label: Neos User Manager
description: A user with this role is able to create, edit and delete users which has the same or a subset of his own roles.
privileges:
...
```
Resolves: #2162

FEATURE: Add meta data to roles and privilegeTargets

---

Neos.Flow/Classes/ResourceManagement/EelHelper/StaticResourceHelper.php

Add a helper to read the uri and content of static (package) resources as this
previously often tedious. The primary usecase is creating resource urls in afx.
StaticResource.uri (packageKey, pathAndFilename, localize)
- (string) packageKey
- (string) pathAndFilename
- (boolean, optional) localize = false
StaticResource.content (packageKey, pathAndFilename, localize)
- (string) packageKey
- (string) pathAndFilename
- (boolean, optional) localize = false
example use in afx:
```
<link rel="stylesheet" href={StaticResource.uri('Neos.Demo', 'Public/Styles/Main.css')} media="all" />
<style>{StaticResource.content('Neos.Demo', 'Public/Styles/Main.css')}</style>
```
Resolves: #2175

FEATURE: Add StaticResource EEL Helper

---

Neos.Flow/Classes/Composer/InstallerScripts.php

Instead of querying the removed method ::getJobType we now check
the class of the job instance like we do in the first lines
of the method.
Resolves: #2187

BUGFIX: Make InstallerScripts compatible to composer version 2.0+

---

Neos.Flow/Classes/Session/Aspect/SessionObjectMethodsPointcutFilter.php

The matches() method did not skip private methods, so Flow tried to build interceptors for them. That breaks as of the bugfix in https://github.com/neos/flow-development-collection/pull/2131, leading to https://github.com/neos/flow-development-collection/issues/2190
Additionally a potential bug in the regular expression used to skip certain methods is fixed. Without the grouping the first alternative was anchored to the start, the last to the end, but others could be anywhere in the string.

BUGFIX: Skip private methods in SessionObjectMethodsPointcutFilter

---

Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/SignalsAndSlots.rst

- recommend use of `::class` constant
- explicitly point out signal name vs method name difference
- add example for slot being a closure
Resolves #2061

TASK: Clarify signal/slot documentation

---

Neos.Cache/Classes/Backend/MemcachedBackend.php

`Memcache->get()` can return `false` if the key is not set, 
so the type must be checked before checking if the value was chunked.
Configure some caches to use Memcached as backend.
Flush the cache.
Go to the Neos login page: an exception is shown.
Apply the fix.
Flush the cache.
Go to the Neos login page: the login form is displayed.
Fixes: #2194

BUGFIX: Ensure memcache value is a string before searching for chunk

---

Neos.Flow/Classes/Http/Client/InternalRequestEngine.php

Since the introduction of the PSR-15 middlewares in #1928, the internal request engine should have invoked those but didn't until now.
Related to #2019

BUGFIX: InternalRequestEngine uses middlewares

---

Neos.Flow/Tests/Unit/Mvc/Routing/RouteTest.php

* stricter asserts (replace `assertEquals` by `assertSame`)
* replace calls to deprecated `getPathConstraint()`
* use `resolveRouteValues()` helper method

BUGFIX: Tweak RouteTest

---

Neos.Flow/Classes/Command/RoutingCommandController.php

Overhauled `./flow routing:*` commands with a better UX and
some new features:
* The output of the `routing:show` and `routing:list` commands
has been cleaned up and information like supported HTTP methods
were added
* The `routing:getPath` command was deprecated in favor of a new
`routing:resolve` command that now supports all of the latest
routing features and has a more informative output
* The `routing:routePath` command was deprecated in favor of a new
`routing:match` command accordingly.
Related: #1126

FEATURE: Improved Routing CLI commands

---

Neos.Flow/Classes/Persistence/QueryInterface.php

This helps psalm (and IDEs) understand the method takes multiple arguments and not just one.

TASK: Adjust docblock to hint at variadic arguments

---

.travis.yml

This removes the PHP 7.2. builds from travis and raises the PHP version for static analysis to PHP 7.3

TASK: Remove PHP 7.2 from build matrix

---

Neos.Flow/Classes/Mvc/ActionResponse.php

This fixes the missing namespace imports for correct `SetHeaderComponent` and `ReplaceHttpResponseComponent` b/c class names.

BUGFIX: Add missing imports for removed SetHeaderComponent and ReplaceHttpResponseComponent

---

Neos.Flow/Classes/ResourceManagement/ResourceManager.php
Neos.Flow/Classes/ResourceManagement/ResourceRepository.php

This introduces a new function in the resourceRepository that allows to count the number of times a file is referenced in a PersistentResource. This function is used in deleteResource of the ResourceManager to improve speed when a file is used in a lot of Persistent Resources.
Same change as with #2229 but should now be merged into Flow 5.3.
Fixes #2228

TASK: Use count instead of find in repository deleting resource

---

Neos.Flow/Classes/Core/Bootstrap.php

This has been forgotten when branching off 6.3.

TASK: Fix FLOW_VERSION_BRANCH variable

---

Neos.FluidAdaptor/Classes/Core/Parser/SyntaxTree/ResourceUriNode.php
Neos.FluidAdaptor/Classes/Core/ViewHelper/AbstractViewHelper.php
Neos.FluidAdaptor/composer.json
composer.json

With this you need to update to TYPO3 Fluid 2.5.11+ or 2.6.10+
See https://github.com/TYPO3/Fluid/commit/f20db4e74cf9803c6cffca2ed2f03e1b0b89d0dc#r44244534

!!! BUGFIX: Adjust to TYPO3Fluid 2.5.11 and 2.6.10 signature changes

---

Neos.FluidAdaptor/Classes/Core/Widget/AjaxWidgetMiddleware.php
Neos.FluidAdaptor/Configuration/Settings.yaml

Otherwise, the security context is not initialized and security would not work but throw an exception (e.g. Neos.Setup)

BUGFIX: AjaxWidgetsMiddleware initializes SecurityContext

---

Neos.FluidAdaptor/Classes/Core/ViewHelper/AbstractViewHelper.php
Neos.FluidAdaptor/Tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php

This removes the `Neos\FluidAdaptor\Core\Exception`s when the ArgumentDefinition is invalid in favor of the native TYPO3 Fluid exceptions. With this we remove the boilerplate we have to keep in sync with upstream.
See https://github.com/TYPO3/Fluid/issues/529 and https://github.com/neos/flow-development-collection/pull/2257#issuecomment-728825319

!!! TASK: Remove custom FluidAdaptor Exceptions on invalid ArgumentDefinition

---

Neos.Flow/Configuration/Settings.Http.yaml

Adjusts the order of the Middleware components so that
the `SessionMiddleware` is executed before the `RoutingMiddleware`.
Otherwise session based authentication won't work until the
routing middleware was executed.
This also removes most of the explicit `position` configurations
in order to avoid too much interdependency.
If a 3rd party middleware needs to be executed before/after another
one, it can still use `position: before/after <name>`  of course.
Depending on the order of _multiple_ other components is considered
bad practice. But if that's really required one could still add a
`position` setting to the existing middleware configuration.
Related: #2019

BUGFIX: Fix default order of middleware components

---

Neos.FluidAdaptor/Classes/Core/Parser/SyntaxTree/ResourceUriNode.php
Neos.FluidAdaptor/Classes/Core/ViewHelper/AbstractViewHelper.php
Neos.FluidAdaptor/Tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php
Neos.FluidAdaptor/composer.json
composer.json

This is breaking in case you created your own ViewHelper that overrides the `registerArgument()` or `overrideArgument()` method. In that case you need to add a new boolean optional argument `$escape = null` and forward that to the parent method.
This is a backport of #2257
Fixes #2260

!!! BUGFIX: Make FluidAdaptor compatible with TYPO3Fluid 2.5.11+ and 2.6.10+

---

Neos.Flow/Classes/ResourceManagement/Storage/FileSystemStorage.php

Somehow this went unnoticed and the `getObjects()` method returned a generator generator. Also the element type docblock was wrong.

BUGFIX: FileSystemStorage::getObjects correctly returns a generator of StorageObject

---

Neos.Utility.ObjectHandling/Classes/TypeHandling.php
Neos.Utility.ObjectHandling/Tests/Unit/TypeHandlingTest.php

This adds \Traversable to the array of valid collectionTypes in the TypeHandling class.
Fixes: #2201

FEATURE: Accept \Traversable as a collection type in validation

---

.travis.yml

Adjusts the Travis CI configuration allowing static analysis (psalm) to fail
since they are very fragile at the moment.

Allow psalm checks to fail

---

Neos.Flow/Scripts/migrate.php

This reduces the maximum line length of output to 80 chars when running core migrations.
See https://stackoverflow.com/questions/4651012/why-is-the-default-terminal-width-80-characters for more information

BUGFIX: Reduce maximum line length to 80 chars

---

Neos.Flow/Classes/Mvc/Routing/Dto/UriConstraints.php
Neos.Flow/Tests/Unit/Mvc/Routing/Dto/UriConstraintsTest.php

This fixes the behavior of `UriConstraints` when using `withPort()` with
a (custom) port that is equal to the port of the applied URL:
```
UriConstraints::create()->withPort(8080)->applyTo(new Uri('http://localhost:8080'), true);
```
Now creates `http://localhost:8080` while it was `http://localhost` before.
Fixes: #2263

BUGFIX: Fix UriConstraints::withPort() when port is equal to current port

---

Neos.Flow/Classes/Http/Cookie.php
Neos.Flow/Configuration/Settings.Session.yaml
Neos.Flow/Tests/Unit/Http/CookieTest.php
Neos.Flow/Tests/Unit/Http/Middleware/SessionMiddlewareTest.php
Neos.Flow/Tests/Unit/Session/SessionTest.php

The neos-ui complaining with warning in the modern browsers because our session cookie has no defined same site attribute and so the browser expect to have a same site with the lax value or none but with the secure attribute.
As the browsers use LAX as default we now also define that.
For mor information read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
Resolves: #2031
**What I did**
Define `SameSite=Lax` when no sameSite is defined.
Just load the neos backend and check the dev console for warning. There should be no warning regarding session cookies.
**Checklist**

!!! BUGFIX: Define default SAMESITE attribute to LAX

---

Neos.Flow/Classes/Security/Authentication/TokenInterface.php

The result of this call is not used (see https://github.com/neos/flow-development-collection/blob/af7b3374688878b822528b4a761741f1102de1cf/Neos.Flow/Classes/Security/Context.php#L787)

TASK: Fix return type annotation for TokenInterface::updateCredentials()

---

Neos.Flow/Classes/Command/MiddlewareCommandController.php

Adds a CLI command `middleware:list` that can be used to list
all configured middleware components in the order they will be
executed.
Related: #2258

FEATURE: Middleware CLI command

---

Neos.Flow/Documentation/TheDefinitiveGuide/PartII/Configuration.rst

`./flow doctrine:create && ./flow doctrine:migrationversion --add --version all` directly initializes the database schema and marks all migrations as done. This can be a helpful alternative initial setup in some cases.

TASK: Document alternative initial database setup method

---

Neos.Flow/Migrations/Code/Version20201205172733.php

Provides a minimal core migration that will show a warning
when the migrated package contains PHP code that refers to
the no longer existing `ComponentInterface`.
Usage:
./flow flow:core:migrate <Package-Key> --version 20201205172733
Example output:
```
Warnings
--------------------------------------------------------------------------------
* Following files refer to the ComponentInterface that has been removed
with Flow 7.0:
* Classes/Http/SomeComponent.php
* Classes/Http/SomeOtherComponent.php
The component chain was replaced with a middleware chain in Flow 7. Please make
sure you have read the upgrade instructions and converted your components to
middlewares.
--------------------------------------------------------------------------------
```
Related: #2258

TASK: Add core migration that warns about component chain usage

---

Neos.Flow/Documentation/TheDefinitiveGuide/PartV/CodingGuideLines/PHP.rst

Clicking the preview image on https://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartV/CodingGuideLines/PHP.html#cgl-on-one-page leads to a 404 currently

TASK: Fix link target of CGL on one page PDF

---

Neos.Flow/Classes/Mvc/Routing/IdentityRoutePart.php
Neos.Flow/Classes/Mvc/Routing/ObjectPathMapping.php
Neos.Flow/Classes/Persistence/Doctrine/PersistenceManager.php
Neos.Flow/Classes/Persistence/Doctrine/Repository.php
Neos.Flow/Classes/Persistence/PersistenceManagerInterface.php
Neos.Flow/Classes/Persistence/Repository.php
Neos.Flow/Classes/Property/TypeConverter/PersistentObjectConverter.php
Neos.Flow/Classes/Reflection/ClassReflection.php
psalm-baseline.xml

This makes use of psalm specific docblock attributes for class-string types.
That tells Psalm to make sure that the value is always given a ::class constant
https://psalm.dev/docs/annotating_code/type_syntax/scalar_types/#class-string

TASK: Some psalm corrections

---

Neos.Flow/Classes/Command/DoctrineCommandController.php

Tweaks the output of the `doctrine:migrationgenerate` command so that it renders the path of the new migration relative to the root directory.
Before:
The migration was moved to: Application/<Package.Key>/Migrations/<DB-Type>/Version<Version>.php
Now:
The migration was moved to: Packages/Application/<Package.Key>/Migrations/<DB-Type>/Version<Version>.php
Fixes #2296

BUGFIX: Correct printed path for created doctrine migrations

---

Neos.Flow/Scripts/flow.php

This adds a helpful message to the CLI output like this, if the Composer autoload file is mssing:
```
> ./flow
Composers autoload.php file was not found. The file is expected to be located in the path:
/Users/soren/Projects/flow-development-distribution/Packages/Framework/Neos.Flow/Scripts/../../../Libraries/autoload.php
This could be due to a missing 'config' => 'vendor-dir' section of your root 'composer.json' file.
The section key and value should look like the following
"vendor-dir": "Packages/Libraries"
Update your 'composer.json' file and run the 'composer update' command.
```
Resolves #2282

TASK: Print a helpful message, if autoload.php can not be found in CLI

---

Neos.Flow/Migrations/Code/Version20201207104500.php

This adds some basic code migrations for the move away from HTTP Components.
Related: #2019, #2258

TASK: Add migration for ComponentContext deprecation

---

Neos.Kickstarter/composer.json

This should have been done automagically, see https://github.com/neos/flow-development-distribution/pull/56

TASK: Set dependency on neos/fluid-adaptor in neos/kickstarter

---

Neos.FluidAdaptor/composer.json
Neos.Kickstarter/composer.json
composer.json

typo3fluid was accidentially included in the collection require, vimeo/psalm was duplicated and doctrine dependencies were duplicated in require-dev.

TASK: Fix composer dependencies

---

composer.json

See https://github.com/symfony/polyfill#design
This prevents installing the symfony polyfills for php <= 7.1 and mbstring, since those are requirements of this Flow version.

TASK: Replace symfony polyfills due to min PHP version

---

Neos.Flow/Classes/Aop/AspectContainer.php
Neos.Flow/Classes/Aop/Builder/ProxyClassBuilder.php

This will now throw an exception that suggests to flush caches or check the existence and namespacing of the aspect class.
Until now such a case would lead to an unhelpful exception of:
```
Warning: Invalid argument supplied for foreach() in /…/Packages/Framework/Neos.Flow/Classes/Aop/Builder/ProxyClassBuilder.php line 319
```
because the following `get_class_methods()` call would return `null` which is not checked for.

TASK: Improve exception when a class can not be loaded during AOP building

---

Neos.Flow/Classes/ObjectManagement/Proxy/Compiler.php

`get_class_vars()` will also return static properties. Hence we also try to access static properties for rendering the annotation and access them non-statically. This will lead to errors.
See https://github.com/zircote/swagger-php/issues/359#issuecomment-303058035 / https://github.com/zircote/swagger-php/issues/359#issuecomment-303227013
This solves that by using `get_object_vars()`, which will only return non-static properties with their current values.

BUGFIX: Don't access static properties in annotation classes

---

Neos.Kickstarter/Classes/Service/GeneratorService.php

**What I did**
Previously, when trying to create translation files with targetLanguageKeys defined (`flow kickstart:translation --target-language-keys="de"` for example), an error was thrown. 
The error said, that translationUnits is not defined in Neos\Kickstarter\Service\GeneratorService. This is, because Neos\Flow\I18n\Xliff\V12\XliffParser::getParsedData will return an array (for each <file>-Entry in the Xliff-File, typically only one entry). So we need to use the first item of that data to get the translationUnits from it. 
I only made a little change and added `[0]` to `$parsedXliffArray` in `Neos\Kickstarter\Service\GeneratorService::generateTranslation()`.
1. Try to kickstart a translation with `--target-language-keys` defined. An error will …

BUGFIX: Fix creation of translations with targetLanguageKeys defined

---

Neos.Flow/Classes/ResourceManagement/ResourceTypeConverter.php

The code did not handle a missing `$configuration` when converting an hash and data array containing an identifier.
See https://github.com/neos/flow-development-collection/pull/1931/files#r503144893

BUGFIX: Correctly handle missing configuration with identity creation

---

Neos.Flow/Classes/Command/SecurityCommandController.php
Neos.Flow/Classes/Security/Policy/PolicyService.php
Neos.Flow/Configuration/Policy.yaml
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Security.rst
Neos.Flow/Resources/Private/Schema/Policy.schema.yaml

This builds upon the work started with #2166 and
* Fixes the Policy schema
* Adds label & description to the "magic" base roles
* Adds CLI commands in order to make use of the metadata
within Flow
Usage:
./flow security:listRoles --include-abstract
./flow security:describeRole Neos.Flow:Everybody
Related: #2162

BUGFIX: Finalize introduction of role and privilege metadata

---

Neos.Flow/Configuration/Caches.yaml

Otherwise changing the default configs defaultLifetime will also make this cache be emptied unexpectedly and unnecessarily.

BUGFIX: Set Flow_Security_Cryptography_HashService defaultLifetime explicitly

---

Neos.Flow/Migrations/Code/Version20201205172733.php

Currently only the first part of the line is displayed

BUGFIX: Reduce the migration message to one line

---

Neos.Flow/Classes/SignalSlot/Dispatcher.php

This fixes a regression introduced with #2216
Fixes neos/content-repository-search#42

BUGFIX: Avoid passing signal information depending on other signals to same slot

---

Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Persistence.rst

Since doctrine/dbal 2.11 PrimaryReadReplicaConnection should be used.
This change updates the documentation to reflect this change.
See https://github.com/doctrine/dbal/issues/4052 for details.

TASK: Update documentation to remove deprecated Doctrine connection

---

Neos.Eel/Classes/Helper/MathHelper.php

The internally used `ceil` and `floor` methods of the `trunc` helper return a float which doesn’t
match the signature anymore and leads to unexpected comparison issues when using this helper in Fusion.
**What I did**
Cast the return values to int.
See above
Call `trunc` with a positive int as parameter and check the type of the returned value. Instead of an int you would get a float.
**Checklist**

BUGFIX: Return correct type for EEL trunc math helper

---

Neos.Flow/Classes/Persistence/Doctrine/Service.php

This basically adds a `EntityManager::flush()` call after `MetadataStorage::ensureInitialized()`
invocations in order to apply any metadata migrations immediately.
Without this a `./flow doctrine:migrate` call might leave the metadata storage in a half-migrated
state if it leads to an exception.
Related: #2244
Related: #2357

BUGFIX: Persist doctrine MetadataStorage changes immediately

---

Neos.Cache/Classes/Backend/MemcachedBackend.php

This fixes the extraction of the port from the `servers` option(s) if they are not bound to the `tcp://` protocol and checks for missing `servers` option in constructor.

BUGFIX: Correctly extract port from memcached servers setting

---

.github/workflows/build.yml

For PRs the `GITHUB_REF` points to `refs/pull/$PRNUMBER/merge`, which does not contain the base branch at all.

TASK: Correctly extract target branch for pull requests

---

.github/workflows/build.yml
Neos.Eel/Classes/Helper/ArrayHelper.php
Neos.Eel/Tests/Unit/Helper/ArrayHelperTest.php

Backport of #2392 in order to fix neos/neos-development-collection#3287 in a bugfix release of Neos.Ui

FEATURE: Expose array_values() in Array eelHelper

---

Neos.Eel/Classes/Helper/ArrayHelper.php
Neos.Eel/Tests/Unit/Helper/ArrayHelperTest.php

According to the documentation and method signature the callback argument in the Array.filter Eel method is optional.
Also the underlying php function array_filter supports beeing called without a callback. In which case it filters empty values which is really handy in places. However due to the passed flag ARRAY_FILTER_USE_BOTH this leads to an error.
The code adjusts the call to array_filter to only pass callback and ARRAY_FILTER_USE_BOTH if the filter is not null and adds a testcase for an empty filter.
Resolves: #2401 2401

BUGFIX: `Array.filter` fails with empty callback

---

Neos.Flow/Classes/Cache/CacheFactory.php

Persistent caches, even non-file backends, should be pretty persistent. This is the way.
Related to #2345

TASK: Persistent caches will have a defaultLifetime of 0

---

Neos.Flow/Migrations/Code/Version20201109224100.php

**What I did**
I added the Flow migration namespace to the regex in code migration Version20201109224100. This prevents getDescription methods that are not part of a doctrine migration class to be changed (see #2363).
I added the namespace to the regex (which makes the regex a bit ugly). I am not sure if it was perhaps better to collect all relevant files (e.g. based on directory structure) instead and apply all searchAndReplace operations only to those files.
Create a regular class and a doctrine migration and add a getDescription method without return type signature to both classes. When you execute the code migration, only the method signature of the doctrine migration class should be changed.

BUGFIX: Prevent wrong code replacements in migration

---

Neos.Flow/Classes/Session/Session.php

Currently it is possible to change the cookie value of `Neos_Flow_Session` (`TYPO3_Flow_Session`) to an invalid cache identifier. This leads to an `InvalidArgumentException` and an error code 500. 
This pull requests checks the validity of the session identifier before attempting to access the `metaDataCache`.
Retargeted follow-up to #1132
Thanks @Torsten85 and sorry for being late with accepting this

BUGFIX: Check for valid session identifier before accessing the cache

---

Neos.Flow/Tests/Functional/Security/Authentication/Provider/PersistedUsernamePasswordProviderTest.php

This prevents the tests from failing occasionally because the test starts directly before the current second switches.

BUGFIX: Authentication tests don't depend on test running within a second

---

Neos.Flow/Classes/Http/AbstractMessage.php
Neos.Flow/Tests/Unit/Http/AbstractMessageTest.php

Previously the PSR-7 forward compatibility method `withAddedHeader()` would overwrite existing headers and was hence the same as `withHeader()`. This change fixes that by correctly setting the `$overwrite` argument in the delegate method.
See https://github.com/neos/flow-development-collection/pull/2361#discussion_r588867079

BUGFIX: WithAddedHeader does not overwrite existing header

---

Neos.FluidAdaptor/Classes/Core/ViewHelper/ViewHelperResolver.php
Neos.FluidAdaptor/Configuration/Settings.yaml

**What I did**
Added the ability to add Fluid namespaces via configuration.
By adding a new configuration option:
```
Neos:
FluidAdaptor: 
defaultNamespaces
```
This configuration is used, to add namespaces inside the ViewHelperResolver.
Add a default namespace in Settings.yaml and try to use its view helpers in any template, without including the namespace there.
**Checklist**
Resolves: #2375

FEATURE: Introduce ability to add Fluid namespaces via configuration

---

Neos.Flow/Classes/ObjectManagement/Proxy/ProxyClass.php

Add the @codeCoverageIgnore annotation to proxy class to ignore it in the coverage report.
- [ x ] Code follows the PSR-2 coding style
- [ x ] Tests have been created, run and adjusted as needed
- [ x ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

BUGFIX: Ignore ProxyClass in code coverage of phpunit

---

Neos.Flow/Tests/Unit/I18n/LocaleTypeConverterTest.php

This fixes running tests with code coverage.

BUGFIX: Outdated class name in @covers annotation

---

.github/workflows/build.yml

See https://github.com/neos/neos-development-collection/pull/3311#issuecomment-803560353
Note that the Flow migrations somehow weren't affected for some reason, but still this is the correct way to go about a `doctrine:create` (and mabye that command should itself mark all migrations applied).

TASK: Mark all migrations as applied after behat setup

---

Neos.Http.Factories/composer.json
composer.json

This is a workaround for https://github.com/guzzle/psr7/pull/401 - 🤞 it will be fixed with 1.8.1

TASK: Exclude breaking 1.8.0 guzzle/psr7 version

---

.github/workflows/build.yml
Neos.Cache/Classes/Backend/FileBackend.php
Neos.Cache/Tests/Unit/Backend/FileBackendTest.php
Neos.Cache/Tests/Unit/Backend/SimpleFileBackendTest.php
Neos.Eel/Classes/Helper/MathHelper.php
Neos.Flow/Classes/Core/LockManager.php
Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php
Neos.Flow/Classes/Package/PackageManager.php
Neos.Flow/Classes/Property/TypeConverter/MediaTypeConverter.php
Neos.Flow/Classes/Reflection/MethodReflection.php
Neos.Flow/Classes/Reflection/ParameterReflection.php
Neos.Flow/Classes/Reflection/ReflectionService.php
Neos.Flow/Classes/SignalSlot/Dispatcher.php
Neos.Flow/Classes/Utility/PhpAnalyzer.php
Neos.Flow/Tests/Functional/Mvc/ActionControllerTest.php
Neos.Flow/Tests/Unit/SignalSlot/DispatcherTest.php
Neos.Utility.Files/Classes/Files.php
composer.json
psalm-baseline.xml

This makes our code base work on PHP 8. It does not yet add support for PHP 8 features. See #2404 for this.
Related to #2233

TASK: Add basic support for PHP8

---

Neos.Flow/Classes/Persistence/Doctrine/PersistenceManager.php
Neos.Flow/Configuration/Settings.Persistence.yaml
Neos.Flow/Tests/Unit/Persistence/Doctrine/PersistenceManagerTest.php

Also, this avoids calling calculateChangeset() twice for requests that only want allowed objects to be persisted.
Resolves #1893

TASK: Avoid opening database connection if nothing to persist

---

Neos.Flow/Classes/Mvc/ActionResponse.php
Neos.Flow/Tests/Functional/Mvc/ActionControllerTest.php
Neos.Flow/Tests/Functional/Mvc/Fixtures/Controller/ActionControllerTestAController.php

Redirecting from controllers using redirectToUri allows the developer to
set the status code to be used. However the actual status code returned
to the client was always 303.
Changing the order so that statusCode is being handled after redirectUri fixes the issue.
**Checklist**

BUGFIX: Allow non-standard status codes in redirects

---

Neos.Flow/Classes/ObjectManagement/ObjectManager.php

The Doctrine object manager used to be Doctrine\Common but got moved
to Doctrine\Persistence. Both are intrefaces.
Doctrine provides a compatibility layer implemented as class_alias().
There are situations where legacy code calls for Doctrine\Common, the
PHP feature of class_alias mapps to Doctrine\Persistence and Flow does
not know about it.

BUGFIX: Allow Doctrine object manager to appear as different class names

---

Neos.FluidAdaptor/Classes/Core/ViewHelper/AbstractConditionViewHelper.php
Neos.FluidAdaptor/Classes/ViewHelpers/Security/IfAccessViewHelper.php
Neos.FluidAdaptor/Classes/ViewHelpers/Security/IfAuthenticatedViewHelper.php
Neos.FluidAdaptor/Classes/ViewHelpers/Security/IfHasRoleViewHelper.php
Neos.FluidAdaptor/Classes/ViewHelpers/Validation/IfHasErrorsViewHelper.php

The method signature change is not breaking and prevents a deprecation warning when running on PHP 8. The `null` default was never used, because the method is never called without arguments anyway.
Resolves #2435

TASK: Fix "Required parameter follows optional parameter" deprecation in PHP8

---

Neos.Flow/Tests/Unit/Http/Helper/RequestInformationHelperTest.php

Fixes the `RequestInformationHelperTest` that fails since 441b61b4b5b7a9b9340f77ea992c323a40d2f13c

TASK: Fix unit tests

---

Neos.Flow/Classes/Persistence/Doctrine/PersistenceManager.php

With the changes in #2423 the PersistenceManager was registered as a Doctrine EventListener.
Hence, when building the EntityManager, the PersistenceManager got instanciated with a completely new non-lazy EntityManager. This caused errors when trying to persist entities, as they were not known to that instance of the EntityManager.
This change makes the EntityManager instanciation lazy again and handles the type mismatch of the lazy DependencyProxy in the SchemaTool.
This is an alternative fix to #2448

BUGFIX: Use lazy EntityManager injection to prevent recursive instanciation

---

Neos.Flow/Classes/Cli/ConsoleOutput.php

The [Symfony Console Table components](https://symfony.com/doc/current/components/console/helpers/table.html) supports settings a header title for a table.
So should we :-)

TASK: Support header title for table output in console

---

Neos.Flow/Classes/Utility/Environment.php
Neos.Flow/Resources/Private/Installer/Distribution/Defaults/Web/.htaccess
Neos.Flow/Scripts/PhpDevelopmentServerRouter.php
Neos.Flow/Tests/FunctionalTestCase.php

This flips the default behavior for the `FLOW_REWRITEURLS` environment
variable: If it is _not_ specified (or contains a value other than `0`)
URL rewriting will be enabled.
Previously URL rewriting was enabled with a corresponding `SetEnv` configuration
for Apache.
For other servers and CLI a corresponding configuration (or a
`putenv('FLOW_REWRITEURLS=1')` call at runtime) was required in order to
activate URL rewriting.
This could be a breaking change in case you relied on the previous behavior.
For example: Using the `UriBuilder` in CLI previously created URLs in the format `/index.php/some/path`. Now it will lead to `/some/path` by default.
To re-establish the former behavior, the `FLOW_REWRITEURLS` can be set to 0 explicitly, for example via `putenv('FLOW_REWRITEURLS=1');`.

!!! FEATURE: Enable URL Rewriting by default

---

Neos.Flow/Classes/Cli/ConsoleOutput.php

**What I did**
The access modifier for `getProgressBar()` in `ConsoleOutput.php` is now public.
I'm using reflection to access the progressbar in a project to use symfonie's time estimation for a long running command. I think there shouldn't be much harm in just making `getProgressBar()` public.
Maybe this could go into the 7.1 release?
[Symfony Progressbar Docs](https://symfony.com/doc/current/components/console/helpers/progressbar.html)
**Checklist**

FEATURE: Cli ProgressBar is public accessible

---

Neos.Flow/Tests/Functional/SignalSlot/Fixtures/SubClass.php
Neos.Flow/Tests/Functional/SignalSlot/SignalSlotTest.php
Neos.Flow/Tests/Unit/SignalSlot/DispatcherTest.php

These tests verify that our current signal/slot dispatching works with byReference arguments.
Related to #2412

TASK: Add test that covers signal arguments by reference passing

---

Neos.Flow/Classes/Cache/AnnotationsCacheFlusher.php
Neos.Flow/Classes/Package.php

Adds a method `registerAnnotation()` that allows further annotations
to lead to the corresponding caches to be flushed.
This also tweaks `flushConfigurationCachesByCompiledClass()` and makes
the class a singleton.

Suggestion: Make AnnotationCacheFlusher usable for 3rd parties

---

Neos.Flow/composer.json
Neos.Utility.Unicode/composer.json
composer.json

The replacements added according to the symfony/polyfill README (and
tweaked recently to actually appear in the split manifest) lead to an
installation issue (composer/composer#9834)
Thus this removes the PHP 5 polyfills (those not being replaced should
not be an issue) to fix that. Also, since we require PHP 7.1, the 7.2
polyfill must not be replaced.

TASK: Tweak polyfill replacements

---

Neos.Flow/Classes/Mvc/ActionResponse.php

The current PHP typehint of `: string` will cause this method to throw an error when `setContentType()` was not called before with a valid string. In Flow 7 we lifted the typehint to `?string`, but IMO that does only complicate the API unnecessarily, because `''` is not a valid content type any way and hence indistinguishable from "did not set content type" for any useful means and purposes.
Hence I suggest using null coalescing instead (and changing the 7+ typehint back to `string`, though that would be breaking).
See also discussion in https://github.com/neos/flow-development-collection/pull/2180#discussion_r550197400

BUGFIX: Null coalesce content type in ActionResponse getter

---

Neos.Flow/Classes/Package.php
Neos.Flow/Classes/Persistence/Doctrine/Query.php
Neos.Flow/Tests/Unit/Mvc/View/JsonViewTest.php

This removes some left-over namespace imports and the signal/slot connection for `allObjectsPersisted` on the generic persistence.

TASK: Remove generic persistence left-overs

---

Neos.Flow/Classes/Mvc/ActionResponse.php

This removes the nullability of the `getContentType()` getter on the `ActionResponse`, which was only added to technically fit the possibility that the value is `null` without thinking about the API.
A content type of empty string is already enough to denote a "not set/unspecified" case and an additional `null` only makes the API more complex than needed.
This change is not technically breaking, even though it changes a return type, since the new return type is more strict. It could be breaking if you check for a `null` return value only without handling an empty string case. You should use the `hasContentType()` method before calling the getter.
Follow-up to #2458 which is a follow-up to #2180

TASK: Make ActionResponse::getContentType non-nullable

---

Neos.FluidAdaptor/Classes/Core/ViewHelper/TemplateVariableContainer.php
Neos.FluidAdaptor/Tests/Functional/View/StandaloneViewTest.php

With this patch it's possible to use the fluid variable nesting feature as well as a specific accessor per element on the path.
**How to use it**
Create a fluid template with nested variables that access an array value:
```html
{config.{type}.value.{flavor}}
```
Assign an array and the two keys:
```php
$this->view->assign('type', 'thing');
$this->view->assign('flavor', 'yellow');
$this->view->assign('config', ['thing' => ['value' => ['yellow' => 'Okayish']]]);
```

BUGFIX: Support nested fluid variables by using the original fluid method

---

Neos.Flow/Classes/Mvc/View/JsonView.php
Neos.Flow/Tests/Unit/Mvc/View/JsonViewTest.php

This allows to override the badly chosen default format of DateTimeInterface::ISO8601 which is not really compatible to ISO8601 in the JsonView options `datetimeFormat` - see https://www.php.net/manual/en/class.datetimeinterface.php#datetime.constants.iso8601

TASK: Make JsonView datetime format configurable

---

Neos.Flow/Classes/Persistence/Doctrine/CacheAdapter.php

Follow up to #2480 when the issue was found to live inside our CacheAdapter and missing return value

BUGFIX: Return boolean in doctrine CacheAdapter::save

---

Neos.Flow/Classes/Core/Booting/Scripts.php

This makes our own tests only use the old class loader if the `FLOW_ONLY_COMPOSER_LOADER` env var is set to `false`.
Related to #2417

TASK: Disable old class loader in testing context by default

---

Neos.Flow/Classes/Persistence/Doctrine/Service.php

Move DoctrineMigrations folder to the Temporary folder. See related ticket #2425 for explanation on the topic
Resolves: #2425

TASK: Move DoctrineMigrations folder to Temporary Data folder

---

Neos.Flow/composer.json
composer.json

As of doctrine/orm 2.9.3 it is again compatible with Flow (see #2495), so we can allow installing it (again).

TASK: Allow installing Doctrine 2.9

---

Neos.Http.Factories/composer.json
composer.json

It is incompatible with versions < 1.7 due to the replaced `stream_for` method. The ~2.0 dependency was added before the actual 2.0 release and this breaking change was added later, making it incompatible. If 2.0+ is needed, you need to upgrade to Flow 7.1

TASK: Disallow installing guzzlehttp/psr7 2.0

---

Neos.Flow/Classes/Reflection/ReflectionService.php

Since PHP 7.1 iterable, object and mixed are new allowed PHP types, which are not allowed to be "qualified".
But having a method returning one of those (and having a corresponding type-hint) did lead to a proxy method, annotated with \type, which will lead to a PHP Fatal error: Type declaration 'type' must be unqualified in ...
This resolves #2498
List of types taken from here:
https://www.php.net/manual/de/language.types.declarations.php
(and yes, this commit includes one type, which is part of PHP8.0 which is not (yet?) supported by Flow 6.3, but I guess it will not harm anyone and definitely makes live easier in upwards versions.

Added all new types introduced since PHP7.1 to not being qualified

---

Neos.Cache/Classes/Backend/TaggableMultiBackend.php

If the flushByTag or findIdentifiersByTag methods of the TaggableMultiBackend are used before backend initialization by other methods, the backends have to be prepared. Otherwise, `$this->backends` is an empty array and no cache entries are flushed.
**What I did**
I added the `$this->prepareBackends()` calls in the two methods.
- Configure the TaggableMultiBackend for the Neos_Fusion_Content cache
- Change a node property in the Neos backend
- Reload the page
Before this change, the change of the node property was saved to the db, but the cache was not flushed. Thus, the incorrect property value was shown in the Neos backend after a page reload.

BUGFIX: Ensure cache backends are prepared before usage

---

Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Security.rst

The ``rejectAll`` option needs to be set as boolean. 
See:  https://github.com/neos/flow-development-collection/blob/6.3/Neos.Flow/Classes/Security/Authorization/FilterFirewall.php#L53

TASK: Fix documentation for firewall option "rejectAll"

---

Neos.Flow/Classes/Package/PackageManager.php

**What I did**
The `PackageManager::getPackage($packageKey)` method should throw an exception or return the found package. There is a case, such that `getPackage` returns `null`. In recent php versions, this causes a php error because the return value of the api `public function getPackage($packageKey): PackageInterface` is not met:
```
Exception in line 514 of /var/www/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Flow_ResourceManagement_Streams_ResourceStreamWrapper.php: Return value of Neos\Flow\Package\PackageManager::getPackage() must implement interface Neos\Flow\Package\PackageInterface, null returned - See also: 202106101712258f223a.txt
```
In older flow versions (4.0 and up), this might also be a problem, because the method actually can return null instead of …

BUGFIX: retrieve package by case insensitive packageKey

---

Neos.Flow/Classes/Security/Authentication/Token/BearerToken.php

This allows to use the BearerToken in combination with other
authentication header bases authentications like UsernamePasswordHttpBasic
closes #2490

BUGFIX: Allow for multiple authentication header

---

Neos.Flow/Classes/Command/ResourceCommandController.php

`$targetCollection->getObjects()` method returns a generator, which will always return `false` in an `empty()` check.
This makes it impossible to use `resource:copy` as this always fails with a `The target collection "tmpNewCollection" is not empty.` error.
The problem is mentioned here: https://github.com/neos/flow-development-collection/issues/2510
**What I did**
Change `!empty()` against a `->valid()` check
Use `resource:copy` to copy assets to an empty Storage.
**Checklist**
- ~~[ ] Tests have been created, run and adjusted as needed~~ (not needed)
This replaced PR https://github.com/neos/flow-development-collection/pull/2512

BUGFIX: Change empty check on target collection to `valid()` in resource:copy

---

Neos.Flow/Classes/I18n/EelHelper/TranslationHelper.php

**What I did**
`translateByExplicitlyPassedOrderedArguments()` and `I18n.translate()` now accept `$source` argument to contain dots instead of only a path to the translation file.
When we use translations we use for example the shorthand
```php
{I18n.translate('Muensmedia.DistributionPackage:NodeTypes.Content.Todo.Container:ui.label')}
```
when we want to pass arguments we had to use
```php
${I18n.translate('progress', null, {solved: this.checkedElementsCount, total: this.checkboxCount}, 'NodeTypes/Content/Todo/Container', 'Muensmedia.DistributionPackage')}
```
As you can see, you have to pass the **path** to the translation file instead of the well known dot-notation.
This commit enables you to use also the well known dot-notation for the source argument:
```php …
```

FEATURE:  I18n.translate() now accept $source to contain dots instead of only a path to the translation file

---

Neos.Flow/Classes/I18n/EelHelper/TranslationHelper.php

This fixes a bug that was introduced with PR #2476
Before it was possible to set the filename to `null`:
```
I18n.translate('foo', null, [], null, 'Foo.Bar')
```
but without this fix, you have to set the source to `Main`
```
I18n.translate('foo', null, [], 'Main', 'Foo.Bar')
```

BUGFIX: Allow null for source in translation helper

---

Neos.Flow/Classes/Security/Context.php
Neos.Flow/Tests/Unit/Security/ContextTest.php

When code is wrapped in a `Security\Context::withoutAuthorizationChecks()` call
and exceptions are caught, authorization checks are no longer disabled in the outer
closure leading to exceptions like
```
The security Context cannot be initialized yet
```
This change fixes this by resetting the `authorizationChecksDisabled` to the
previous value in a `finally` block.
Fixes: #2521

BUGFIX: Keep authorization checks disabled if an exception is swallowed

---

Neos.Flow/Classes/Composer/InstallerScripts.php

Previously the scripts were run for every package at the end of the install process.
The scripts only need to be run once.

TASK: Run post-update scripts only once 

---

Neos.Cache/composer.json
Neos.Error.Messages/composer.json
Neos.Flow.Log/composer.json
Neos.Flow/composer.json
Neos.Utility.Arrays/composer.json
Neos.Utility.Files/composer.json
Neos.Utility.MediaTypes/composer.json
Neos.Utility.ObjectHandling/composer.json
Neos.Utility.Schema/composer.json
Neos.Utility.Unicode/composer.json
composer.json

Version 9.1 introduces the method `assertFileDoesNotExist()`
which is used since Flow 7.0 (#2310)

TASK: Raise minimal phpunit to 9.1 

---

Neos.Http.Factories/composer.json
composer.json

Version 1.7 introduces the GuzzleHttp\Psr7\Utils class
which is used since Flow 7.1
See #2525 and #2501

TASK: Raise minimal guzzlehttp/psr7 to 1.7

---

Neos.Kickstarter/composer.json

Only the created package has a dependency on Fusion, iff it uses generated Fusion templates
This needs to be followed up with a change that will add those dependencies to the created packages composer manifest via some way.

TASK: Remove fusion dependencies

---

Neos.Flow/Classes/Reflection/ReflectionService.php

In some cases this error comes up:
Trying to get property 'lazy' of non-object in ConfigurationBuilder
The reason for the error is the fact that the `current()` call does not return the existing annotation instance. The array pointer seems to point somewhere else. Using `reset()` instead of current solves the issue.
Using `reset()` does not really alter the (promised) behaviour of the method, so it is used instead.
Fixes #2532

BUGFIX: Return first existing annotation, not "current" one

---

Neos.Flow/Classes/Cli/Dispatcher.php
Neos.Flow/Classes/Package.php

Together with Flow 6.x the Cli commands have been seperated from the Http ActionControllers.
Before these slots have been guaranteed to be executed during runtime only. This patch restores
that behavior. There will be another commit against master, which introduces new 4 new signals,
so in future you can even use compile time slots.
Fixes #2528

BUGFIX: Do not run before and afterControllerInvocation signals in compile time

---

Neos.Flow/composer.json
composer.json

This is required to pass emailAddressValidatorUsingStrictHasErrorsForAnEmailAddressWithWarnings with data set #0
See https://github.com/egulias/EmailValidator/pull/233

TASK: Raise minimum egulias/email-validator version to 2.1.17

---

Neos.Flow/composer.json
composer.json

This also fixes onto ^1.12 to include the `@NamedConstructorAnnotation` we use since adding PHP8 attributes support

TASK: Add explicit doctrine annotations dependency

---

Neos.Flow/Classes/Cli/RequestBuilder.php
Neos.Flow/Tests/Unit/Cli/RequestBuilderTest.php

**What I did**
With this PR, a CLI command can make use of array's as an argument type.
If an argument is given multiple times and the type is an array, the argument values are pushed at the end of the array.
As an example, this can be handy, if you need to process multiple language dimensions, nodes or urls, like
```
./flow my.pckg:index --dimension en --dimension de
```
Maybe this can also be considered for the 7.2 release?
The CLI `RequestBuilder` now distinguishes between array and non-array arguments. If an argument is of type `array` the argumentValue is appended to the array.
Create a command controller command with an array signature like
```
public function indexCommand(array $dimension){
```
and then use the argument `--dimension` multiple …

FEATURE: CLI parse array type controller arguments

---

Neos.Flow/composer.json
composer.json

This makes sure the required `composer/composer` dependency is not
affected by CVE-2021-29472
https://github.com/composer/composer/security/advisories/GHSA-h5h8-pc6h-jvvx

TASK: Require fixed composer/composer packages

---

Neos.Flow/Tests/Unit/Fixtures/SessionlessTestToken.php
Neos.Flow/Tests/Unit/Http/Component/SecurityEntryPointComponentTest.php
Neos.Flow/Tests/Unit/Http/Helper/RequestInformationHelperTest.php
Neos.Flow/Tests/Unit/Persistence/Doctrine/PersistenceManagerTest.php
Neos.Flow/Tests/Unit/Property/TypeConverter/CollectionConverterTest.php
Neos.Flow/Tests/Unit/Security/ContextTest.php
Neos.Flow/Tests/Unit/Security/SessionDataContainerTest.php

The new `SessionlessTestToken` class is needed to replace the mocking of two interfaces (`TokenInterface` and `SessionlessTokeInterface`) in one call.

TASK: Fix PhpUnit deprecation warnings

---

Neos.FluidAdaptor/Classes/Core/Rendering/RenderingContext.php
Neos.FluidAdaptor/composer.json
composer.json

With `typo3fluid/fluid` 2.7.0 the `$view` constructor argument to
`RenderingContext` is gone, but we support lower versions, thus things
break.
This brings back the argument in our code and pins Fluid to < 2.7.0
for Flow below 7.2.0.
See https://github.com/neos/flow-development-collection/issues/2541
See https://github.com/TYPO3/Fluid/pull/548

BUGFIX: Bring back RenderingContext view argument, pin Fluid version

---

Neos.Flow/Classes/Persistence/Generic/PersistenceManager.php

With https://github.com/neos/flow-development-collection/pull/2448
the method `throwExceptionIfObjectIsNotAllowed()` was removed, but
the `Generic\PersistenceManager` was not adjusted. This fixes that in
the simplest possible way…

BUGFIX: Add missing method to Generic\PersistenceManager

---

Neos.Flow/composer.json
composer.json
psalm-baseline.xml
psalm.xml

This updates psalm to 4.9 and also updates the baseline.
The new `ParamNameMismatch` error is lowered to `info` level.
Related to https://github.com/neos/flow-development-distribution/issues/74
Resolves #2515

TASK: Update psalm to 4.9

---

Neos.Flow/Classes/Core/Booting/Scripts.php
Neos.Flow/Classes/Http/Helper/RequestInformationHelper.php
Neos.Flow/Classes/Log/ThrowableStorage/FileStorage.php

According to https://github.com/neos/flow-development-collection/issues/2548
this is my suggestion for better request information in the exception
dump files.
The goal is better readability of the request information for humans
and the chance to parse them with scripts:
- Add the name of the request headers
- Separate each header (name: value) into an own line
- Add the request target (requested url)

TASK: improve request information in exception logfiles

---

Neos.Flow/Classes/ObjectManagement/Proxy/ProxyConstructor.php
Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/ClassImplementingInterfaceWithConstructor.php
Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/InterfaceWithConstructor.php
Neos.Flow/Tests/Functional/ObjectManagement/ProxyCompilerTest.php

Adjusts the proxy building for classes such that it throws a more
helpful exception when trying to generate proxies for classes
implementing an interface with constructor and parameters.
Fixes: #2554

BUGFIX: Prevent proxies for classes with unsupported interfaces

---

Neos.Flow/Classes/Aop/Builder/ProxyClassBuilder.php
Neos.Flow/Classes/ObjectManagement/Proxy/Compiler.php
Neos.Flow/Classes/ObjectManagement/Proxy/ProxyClass.php
Neos.Flow/Classes/Persistence/Aspect/PersistenceMagicAspect.php
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/AspectOrientedProgramming.rst
Neos.Flow/Tests/Unit/ObjectManagement/Proxy/ProxyClassTest.php

With PR #2533 docblocks are copied from the original class to the proxy class. This breaks when using annotations without the "standard" imports `Flow` and `ORM`. One example is the ImportedAsset domain model.
This fixes that by some changes to the proxy building.
Note, if you use property introduction via AOP, those properties must from now on use fully-qualified classnames for annoatations on them!
Fixes #2564

!!! BUGFIX: Avoid broken proxy docblocks

---

Neos.Flow/Classes/Security/Authentication/Provider/TestingProvider.php
Neos.Flow/Tests/FunctionalTestCase.php

As of https://github.com/neos/flow-development-collection/pull/1213
the authentication providers are created using a factory method, this
breaks the assumption the `TestingProvider` is a singleton.
The result is that e.g. ´authenticateRoles([])` no longer works as
expected in functional tests.
This fixes the issue by fetching the provider from the factory instead
of the object manager.
Fixes #2386

BUGFIX: Correctly set up TestingProvider for "testable security"

---

Neos.Flow/Classes/Package.php

With PR #2448 the `shouldCheck()` was added, having a return type
declaration of `bool`. The value returned is set only by the argument
given to `persistAll()`, so having Behat tests fail when the value was
a string seemed strange.
The actual value was even stranger:
Neos\\Flow\\Cli\\SlaveRequestHandler::dispatchedCommandLineSlaveRequest
Reason: The `Package` class in `Neos.Flow` connects a signal to the
`persistAll()` method, and the "signal information" is passed as an
argument…
This change fixes that.

BUGFIX: Do not pass signal information to persistAll

---

Neos.Flow/Classes/Persistence/Doctrine/ObjectValidationAndDeDuplicationListener.php

Doctrine 2.10 switched spl_object_hash for spl_object_id which breaks the deduplication listener. Thanks @dlubitz.
We should use `scheduleForDelete` instead of manually unsetting the to be inserted entity via the object hash.
See https://github.com/doctrine/orm/commit/84ad007de39bc0947be838c8efcf1455513cbdca

BUGFIX: Don't rely on doctrine using spl_object_hash

---

Neos.Utility.Files/Classes/Files.php

When a resource is deleted the method `removeEmptyDirectoriesOnPath` is used, which cause an E_WARNING with PHP 8.0. Even if the shutup operator is used. This bugfix catch the E_WARNING to break the foreach at the right time.

BUGFIX: Catch Warning for rmdir in PHP 8.0

---

Neos.Flow/Classes/Command/SignalCommandController.php

The CLI command lists all signals with their slots. As parameter it accepts the class name and method name of the signal to filter the output.
Help output:
```
Lists all connected signals with their slots.
COMMAND:
neos.flow:signal:listconnected
USAGE:
./flow signal:listconnected [<options>]
OPTIONS:
--class-name
--method-name
```
Example output:
```
$ ./flow signal:listconnected 
Connected signals with their slots.
Neos\Flow\Mvc\Dispatcher
afterControllerInvocation
[0] Closure
Neos\Flow\Cli\SlaveRequestHandler
dispatchedCommandLineSlaveRequest
[0] Neos\Flow\Persistence\PersistenceManagerInterface::persistAll
Neos\Flow\Core\Booting\Sequence
afterInvokeStep
[0] Closure
[1] Closure
[2] Closure
[3] Closure
Neos\Flow\Monitor\FileMonitor
filesHaveChanged
[0] Closure
[1] …
```

FEATURE: CLI command to list all connected signals with their slots

---

Neos.Flow/Classes/Composer/InstallerScripts.php

This reverts commit d79947442d7de8c59f0d6460e0affef30406148b.
Resolves: #2621
Original by @marcrobertscamao:
This fix resolves the issue of postPackageUpdateAndInstall not installing resources from all installed packages
What I did
Remove the single run code for the postPackageUpdateAndInstall function only
How to verify it
Clone git@github.com:marcrobertscamao/resource-test.git
Run composer install
See resource1.txt in the root and resource2.txt in the root

Revert "TASK: Run post-update scripts only once"

---

Neos.Flow/Classes/Aop/Advice/AroundAdvice.php
Neos.Flow/Tests/Unit/Aop/Advice/AroundAdviceTest.php

The [documentation](https://neos.readthedocs.io/en/stable/References/Signals/Flow.html#aroundadvice-neos-flow-aop-advice-aroundadvice) mentions, that the `AroundAdvice` emit's the `adviceInvoked` signal. This is not the case, because `AroundAdvice` overrides the `invoke(JoinPointInterface $joinPoint)` method from `AbstractAdvice`.
**What I did**
This bugfix, just add's the missing signal, thus every advice should be easier to log using a slot for `adviceInvoked`.

BUGFIX: AroundAdvice emits adviceInvoked signal

---

Neos.Cache/Classes/Backend/AbstractBackend.php
Neos.Cache/Classes/Backend/ApcuBackend.php
Neos.Cache/Classes/Backend/MemcachedBackend.php
Neos.Cache/Classes/Backend/RedisBackend.php
Neos.Cache/Tests/Unit/Backend/RedisBackendTest.php

Also refactors MemCached and ApcuBackend to use the `getPrefixedIdentifier()` method.
Resolves: #2618

!!! BUGFIX: Prefix RedisBackend keys with application context

---

Neos.Flow/Tests/FunctionalTestCase.php

When extending the `FunctionalTestCase` without either `$testableSecurityEnabled` or `$testablePersistenceEnabled` set to `true`, the `privilegeManager` will get `overrideDecision` set to `true`.
All test classes executed later will now also have `overrideDecision` set to `true` instead of the expected `null`.
This fix ensures that `privilegeManager->reset()` is called no matter what.

BUGFIX: FunctionalTestCase doesn't reset PrivilegeManager on setup

---

Neos.Flow/Classes/Annotations/IgnoreValidation.php
Neos.Flow/Tests/Functional/Mvc/Fixtures/Controller/NestedObject.php
Neos.Flow/Tests/Functional/Mvc/Fixtures/Controller/TestObjectArgument.php

It should be possible to annotate a property with just `@Flow\IgnoreValidation` without any arguments.
This was a regression from #2468.
Related to https://github.com/neos/neos-development-collection/issues/3515 and https://github.com/neos/neos-development-collection/pull/3411

BUGFIX: IgnoreValidation can be used without arguments on a property

---

Neos.FluidAdaptor/Classes/View/TemplatePaths.php

The $pathAndFilename argument has been declared nullable in upstream 2.7.1+ and psalm was notifying about this.
See https://github.com/TYPO3/Fluid/commit/2d28324f02b384bb4e1983cbd72813d31e8493c7

TASK: Adjust docblock typehint to TYPO3Fluid change

---

Neos.Cache/Classes/Backend/PdoBackend.php

This prevents errors for cache setup with PDOBackends for caches that are flushed early on eg. due to file monitors.
Fixes: #2634

BUGFIX: PDOBackend ignores missing tables in flush

---

Neos.Flow/Classes/Mvc/Routing/Dto/UriConstraints.php
Neos.Flow/Tests/Unit/Mvc/Routing/Dto/UriConstraintsTest.php

This fixes the following:
- given an HTTPS connection to a proxy that passes the request handling to a server via HTTP
- given a shortcut node pointing to `http://www.acme.com`
- will result in `http://www.acme.com:443` leading to errors
This fixes it by using the (at this point already set!) scheme of the `$uri` to fill in the standard
port.

BUGFIX: Wrong port assigned in applyTo()

---

Neos.Flow/Scripts/flow.php

Without this fix, every interaction with Flow/Neos on PHP 8.1 will lead to a Deprecation warning:
```
PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /Packages/Framework/Neos.Flow/Scripts/flow.php on line 68
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /Packages/Framework/Neos.Flow/Scripts/flow.php on line 68
```

BUGFIX: Fix PHP 8.1 compatibility of flow.php script

---

Neos.Flow/Classes/Error/Debugger.php
Neos.Flow/Tests/Unit/Error/DebuggerTest.php

BUGFIX: Don't access uninitialized property in Debugger

---

Neos.Flow/Classes/Mvc/Routing/DynamicRoutePart.php
Neos.Flow/Tests/Unit/Mvc/Routing/DynamicRoutePartTest.php
Neos.Flow/Tests/Unit/Mvc/Routing/Fixtures/UriArgumentObjectWithToString.php

When resolving values for a route via DynamicRoutePart, object are only being looked up in the persistence manager.
With this change, we honour if a identifier is found, and if not, we look at the object to see, if it has a __toString method available, to give us a value.
This is backward compatible, since we respect the identifier, if given at first
Reolves #2658

BUGFIX: Use __toString for resolving value in DynamicRoutePart

---

Neos.Utility.Files/Classes/Files.php

Makes sure the check does not use potentially outdated information.
Fixes #2670

BUGFIX: Clear stat cache when checking for directory

---

.github/workflows/build.yml
Neos.Cache/composer.json
Neos.Eel/composer.json
Neos.Error.Messages/composer.json
Neos.Flow.Log/composer.json
Neos.Flow/Classes/Core/Bootstrap.php
Neos.Flow/composer.json
Neos.FluidAdaptor/composer.json
Neos.Http.Factories/composer.json
Neos.Kickstarter/composer.json
Neos.Utility.Arrays/composer.json
Neos.Utility.Files/composer.json
Neos.Utility.MediaTypes/composer.json
Neos.Utility.ObjectHandling/composer.json
Neos.Utility.OpcodeCache/composer.json
Neos.Utility.Pdo/composer.json
Neos.Utility.Schema/composer.json
Neos.Utility.Unicode/composer.json
composer.json

Neos 8 will depend on php 8. This change adjusts composer dependencies, the MINIMUM_PHP_VERSION in the flow bootstrap and adjusts the github actions to only run for supported php-versions.
Resolves: #2708

!!! TASK: Raise minimal supported PHP version to 8.0.0

---

Neos.Flow/Classes/Error/AbstractExceptionHandler.php
Neos.Flow/Classes/Error/DebugExceptionHandler.php
Neos.Flow/Classes/Error/ProductionExceptionHandler.php

resolves: #1108
previously, a custom error view is for rendering groups only used if `templatePathAndFilename` is set. See #1108
**A custom view will now be used if ...**
-  ... there is a matching rendering group (no further checks. It *could* be also a rendering group with empty options (no viewClassName or viewOptions) ... what would then trow an error probably - depending on the view)
- ... `defaultRenderingOptions.templatePathAndFilename` passes isset() (to not change previous working behaviour - should get depreceated sometime)

BUGFIX: Use custom error view for rendering group independent of the configuration 'templatePathAndFilename'

---

Neos.Flow/Classes/Log/ThrowableStorage/FileStorage.php
Neos.Flow/Classes/Log/ThrowableStorageInterface.php

This clarifies the use of `logThrowable()` from `ThrowableStorage` and
`ThrowableStorageInterface`.

TASK: Improve ThrowableStorage docblocks

---

Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/ErrorAndExceptionHandling.rst

related #1108
related #2638 
Concerning:
`Neos.Flow.error.exceptionHandler.renderingGroups.{exampleGroup}.options`
include the overseen options:
`viewClassName`, and `viewOptions`
mark the legacy options as @deprecated and show alternative

BUGFIX: Documentation fix follow up to #1108 and #2638

---

Neos.Flow/Classes/Mvc/Controller/ActionController.php
Neos.Flow/Classes/Mvc/Controller/MvcPropertyMappingConfigurationService.php
Neos.FluidAdaptor/Tests/Functional/Form/FormObjectsTest.php

When HMAC validation fails during request processing, the controller
will return a response with a status code of 400, as that is caused
by a bad request. The exception is logged with a notice to the log,
to aid in debugging errors
Previously the uncaught exception would cause a status 500 response
and log a critical error.
Fixes #2681

TASK: Return 400 response when HMAC validation fails

---

.styleci.yml
Neos.Flow/Classes/ObjectManagement/CompileTimeObjectManager.php
Neos.Flow/Classes/ObjectManagement/Proxy/Compiler.php
Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/PHP8/BackedEnumWithMethod.php
Neos.Flow/Tests/Functional/ObjectManagement/Fixtures/PHP81/BackedEnumWithMethod.php
Neos.Flow/Tests/Functional/ObjectManagement/ProxyCompilerTest.php

This change introduces a check in the proxy class compiler which makes sure that PHP 8.1 enums are not considered as regular classes and are removed from the list of proxyable classes.
How to reproduce:
1. create an enum, for example in `Packages/Acme/Classes/ExampleEnum.php`:
```php
namespace Acme;
enum ExampleEnum
{
case FOO;
case BAR;
}
```
2. let Flow compile classes, the following error will appear:
> PHP Fatal error:  Cannot declare class Acme\ExampleEnum, because the name is already in use in /application/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Acme_ExampleEnum.php on line 23
Addresses #2698

BUGFIX: Don't create proxy classes for PHP enums

---

Neos.Flow/Classes/Error/AbstractExceptionHandler.php

BUGFIX: Custom error view: skip 'viewOptions' that are 'null' #2738

---

Neos.Flow/Classes/Http/Client/Browser.php
Neos.Flow/Classes/Http/Client/CurlEngine.php
Neos.Flow/Classes/Http/Client/Exception.php
Neos.Flow/Classes/Http/Client/InternalRequestEngine.php
Neos.Flow/Classes/Http/Client/RequestEngineInterface.php
Neos.Flow/Configuration/Objects.yaml
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Http.rst
Neos.Flow/composer.json
composer.json

The `Neos\Flow\Http\Client\Browser` now implements the `Psr\Http\Client\ClientInterface` and works with dependency injection by default.
The signature of the method sendRequest is relaxed slightly from ServerRequestInterface to RequestInterface and the curl requestEngine is injected by default. That way any browser is ready for use from the start.
Internally the request engines now also use the RequestInterface instead of ServerRequestInterface.
This should be almost non breaky because changes ServerRequestInterface is still allowed as it extends the RequestInterface. The InternalRequestEngide will upcast the RequestInterfaces to ServerRequestInterface when needed.
!!!The PR removes the @api annotation from the requestEngines to allow us to remove or alter those in the future.
Resolves: …

!!! FEATURE: Implement Psr-18 HTTP\Client

---

Neos.Flow/Classes/Cache/CacheManager.php
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Caching.rst
Neos.Flow/Tests/Unit/Cache/CacheManagerTest.php
Neos.Flow/composer.json

The methods create PSR Frontends for the cache with the given identifier. This allows to configure psr caches via
objects and caches yaml. This is an improvement as the included factories are not that easy to use.
The following settings in Objects.yaml allow to inject PSR Caches into Flow Classes:
```
Vendor\Site\Service:
properties:
simpleCacheProperty:
object:
factoryObjectName: Neos\Flow\Cache\CacheManager
factoryMethodName: getSimpleCache
arguments:
1:
value: Cache_Identifier_1
cachePoolProperty:
object:
factoryObjectName: Neos\Flow\Cache\CacheManager
factoryMethodName: getCacheItemPool
arguments:
1:
value: Cache_Identifier_2
```
!!! While possible it is not advisible to access the same cache with multiple Interfaces as the storage formats may differ. !!!
Resolves: #2690 …

FEATURE: Add methods getSimpleCache PSR-16 and getCacheItemPool PSR-6 to the cacheManager

---

Neos.Cache/Classes/Backend/ApcuBackend.php
Neos.Cache/Classes/Backend/FileBackend.php
Neos.Cache/Classes/Backend/MemcachedBackend.php
Neos.Cache/Classes/Backend/NullBackend.php
Neos.Cache/Classes/Backend/PdoBackend.php
Neos.Cache/Classes/Backend/RedisBackend.php
Neos.Cache/Classes/Backend/TaggableBackendInterface.php
Neos.Cache/Classes/Backend/TaggableMultiBackend.php
Neos.Cache/Classes/Backend/TransientMemoryBackend.php
Neos.Cache/Classes/Frontend/AbstractFrontend.php
Neos.Cache/Classes/Frontend/FrontendInterface.php
Neos.Cache/Tests/Functional/Backend/RedisBackendTest.php
Neos.Cache/Tests/Unit/Backend/AbstractBackendTest.php
Neos.Cache/Tests/Unit/Backend/ApcuBackendTest.php
Neos.Cache/Tests/Unit/Backend/FileBackendTest.php
Neos.Cache/Tests/Unit/Backend/PdoBackendTest.php
Neos.Cache/Tests/Unit/Backend/RedisBackendTest.php
Neos.Cache/Tests/Unit/Backend/TransientMemoryBackendTest.php
Neos.Flow/Classes/Mvc/Routing/RouterCachingService.php
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Caching.rst

**What I did**
This change introduces the `flushByTags` method to taggable cache backends. This allows each backend to be further optimised in the future to find the best way to flush multiple tags from its storage.
Resolves: #2717
The `TaggableBackendInterface` and `FrontendInterface` were extended with the method `flushByTags` and each provided backend in the core got a simple implementation for it to fulfil the interface.

!!! FEATURE: Introduce flushByTags to taggable cache backends

---

Neos.Flow/Classes/Error/AbstractExceptionHandler.php
Neos.Flow/Configuration/Settings.Error.yaml
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/ErrorAndExceptionHandling.rst
Neos.Flow/Migrations/Code/Version20220318174300.php
Neos.Flow/Tests/Unit/Error/AbstractExceptionHandlerTest.php

resolves: #2742
Concerning:
`Neos.Flow.error.exceptionHandler.renderingGroups.{exampleGroup}.options`
remove the legacy way of passing
* templatePathAndFilename
* layoutRootPath
* partialRootPath
* format
to a fluid view.
migrate those options to the equivalent `viewOptions`
migration see: https://github.com/neos/flow-development-collection/pull/2748
(Make sure youre on flow only - or comment out the neos.neos error view settings or also use https://github.com/neos/neos-development-collection/pull/3637)
throw some of these at your favorite places and marvel at the great exceptions:
```php
throw new DatabaseException();
throw new TargetNotFoundException(); // provokes a 404
```

!!!TASK: Remove legacy fluid custom error view options and migrate to `viewOptions`

---

Neos.Flow/Classes/ResourceManagement/Target/FileSystemSymlinkTarget.php

Fixup for:
`TASK: Further clarify use of only "extension" from pathinfo`
https://github.com/neos/flow-development-collection/pull/2729
commit https://github.com/neos/flow-development-collection/commit/e1e9f006f491effe88111f92368810bf6e3d4bb7
noticed because psalm failed: https://github.com/neos/flow-development-collection/runs/5632499130?check_suite_focus=true

BUGFIX: Use of undefined variable `$pathInfo['extension']`

---

Neos.Flow/Classes/Http/Client/InternalRequestEngine.php

According to the HTTP spec, characters like line breaks and some other are not allowed within a request header. Exception messages typically include those. Since guzzlehttp/psr7 1.8.4 it validates headers to this spec and makes our builds fail. This fixes that by base64 encoding the exception message we transfer via the `X-Flow-ExceptionMessage` header. Currently there is no code in the core that uses this header, but if you read this header at some obscure place, you need to `base64_decode()` the value first.
See https://github.com/guzzle/psr7/pull/486/files#diff-fb174524a7bba27ce140bc6ccd1c30811a6abeed9328e783b326189551ba7ed4R253

BUGFIX: Properly encode error message in internal request header

---

Neos.Flow/Classes/Mvc/Controller/ActionController.php
Neos.Flow/Tests/Functional/Mvc/ActionControllerTest.php

When a required argument is missing request processing, the controller
will return a response with a status code of 400, as that is caused
by a bad request. The exception is logged with a notice to the log,
to aid in debugging errors.
Previously the uncaught exception would cause a status 500 response
and log a critical error.
Fixes #2682

TASK: Return 400 response if required argument is missing

---

Neos.Cache/Classes/Backend/PdoBackend.php

**What I did**
Without this patch using custom table names for the PDO cache backend would cause problems
as some queries didn’t respect the given table names but used the defaults during DELETE
operations. This has been adjusted.
Use the configured table names as in all the other queries.
Use the backend with custom table names and try to flush them. Without the change an error would occur if the default tables have never been used and setup.
**Checklist**

BUGFIX: Use configured pdo cache tables during flush and garbage collection

---

Neos.Flow/Classes/ResourceManagement/Target/FileSystemSymlinkTarget.php

If the symlink could not be created but exists, check if it points to
the expected target and ignore the error in that case.
Fixes #2667

BUGFIX: Avoid race condition on symlink publishing

---

Neos.Eel/Classes/Helper/ArrayHelper.php
Neos.Eel/Tests/Unit/Helper/ArrayHelperTest.php

related: https://github.com/neos/neos-development-collection/pull/3658
fixes: https://github.com/neos/neos-development-collection/issues/3657

BUGFIX: Make Array.push accept `null` for array type casting

---

Neos.Flow/Classes/Persistence/Doctrine/DataTypes/JsonArrayType.php
Neos.Flow/Classes/Property/TypeConverter/DenormalizingObjectConverter.php
Neos.Flow/Tests/Unit/Persistence/Doctrine/DataTypes/JsonArrayTypeTest.php
Neos.Flow/Tests/Unit/Property/TypeConverter/DenormalizingObjectConverterTest.php
Neos.Flow/Tests/Unit/Property/TypeConverter/Fixture/ArrayBasedValueObject.php
Neos.Flow/Tests/Unit/Property/TypeConverter/Fixture/BooleanBasedValueObject.php
Neos.Flow/Tests/Unit/Property/TypeConverter/Fixture/FloatBasedValueObject.php
Neos.Flow/Tests/Unit/Property/TypeConverter/Fixture/IntegerBasedValueObject.php
Neos.Flow/Tests/Unit/Property/TypeConverter/Fixture/StringBasedValueObject.php

When converting from simple types the denormalizer now checks wether the target class has a method `from$TYPE` and uses this to create the object.  Supported method names are `fromArray`, `fromString`, `fromBool`, `fromInt` and `fromFloat`.
For example the following controller action would use the methods `BirthDate::fromString` or `BirthDate::fromArray` (depending on submitted data) to instantiate the $birthDate argument.
```
public function indexAction(BirthDate $birthDate) 
```
In addition the JsonArray Type is extended to support this aswell. The serialization as flow entities takes precedence over the serialization as value object flow objects that implement \JsonSerializable are still serialized as Flow Objects in JsonArray properties. While beeing a Flow feature this allows to …

FEATURE: Create ValueObjects from simple types by calling `from$TYPE` for objects and JsonArray properties

---

Neos.Flow/Classes/Mvc/View/JsonView.php
Neos.Flow/Tests/Unit/Mvc/View/JsonViewTest.php

Resolves #2446
Related to  #2445

!!!TASK: Change default JsonView DateTime format to ISO compliant DateTime::ATOM

---

Neos.Flow/Classes/Mvc/Routing/Dto/UriConstraints.php
Neos.Flow/Tests/Unit/Mvc/Routing/Dto/UriConstraintsTest.php

Previously, if `UriConstraints` were applied to an URL with a non-default
port (e.g. "8080") this port constraint was applied to the target URL even
if no explicit port constraint was set.
Fixes: #2714

BUGFIX: Fix UriConstraints port constraints for default ports

---

Neos.Flow/Classes/Property/TypeConverter/DenormalizingObjectConverter.php
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/PropertyMapping.rst
Neos.Flow/Tests/Unit/Property/TypeConverter/DenormalizingObjectConverterTest.php
Neos.Flow/Tests/Unit/Property/TypeConverter/Fixture/BooleanBasedValueObjectWithLongName.php
Neos.Flow/Tests/Unit/Property/TypeConverter/Fixture/IntegerBasedValueObjectWithLongName.php

...in addition to their short version (`fromBool()` and `fromInt()`).
This also adds a short documentation about Value Object property mapping.
Related: #2763

FEATURE: Extend DenormalizingObjectConverter to support fromBoolean and fromInteger

---

Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php
Neos.Flow/Classes/ObjectManagement/Proxy/ObjectSerializationTrait.php
Neos.Flow/Classes/Property/TypeConverter/ArrayFromObjectConverter.php
Neos.Flow/Classes/Reflection/ReflectionService.php
Neos.Flow/Classes/Validation/Validator/GenericObjectValidator.php
Neos.Utility.ObjectHandling/Classes/TypeHandling.php

The `Doctrine\ORM\Proxy\Proxy` is deprecated and extends the
`Doctrine\Persistence\Proxy`.

TASK: Avoid deprecated Doctrine ORM proxy

---

Neos.FluidAdaptor/Classes/ViewHelpers/Form/AbstractFormFieldViewHelper.php
Neos.Utility.ObjectHandling/Classes/ObjectAccess.php

That has been deprecated for ages and was to be dropped with 5.0
already.

TASK: Drop nullability of $propertyPath on getPropertyPath()

---

Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php
Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php
Neos.Flow/Classes/Reflection/ReflectionService.php
Neos.Flow/Tests/Functional/ObjectManagement/LazyDependencyInjectionTest.php

This change introduces basic support for PHP 7.4 class property types
for property injection.
It allows for using types as follows:
```php
/**
* @Flow\Inject
**/
protected LoggerInterface $logger;
```
In order to allow this syntax, Lazy Property Injection is disabled
when a type is declared. To still use Lazy Property Injection, don't
use a PHP type declaration but a `@var` annotation:
```php
/**
* @Flow\Inject
* @var LoggerInterface
**/
protected $logger;
```
If using both (type declaration _and_ `@var`), it is handled non-lazily.
Lazy Property Injection on properties with type declarations may 
be re-implemented as part of a future release.
#2114

FEATURE: Type declaration support for property injection

---

Neos.Cache/Classes/Backend/RedisBackend.php

The `frozen` key is already included in the prefixed argument in combination with the wildcard in the Lua script.
Therefore it can be safely removed. The script anyway didn’t use it.
The matching functional test works correctly.

TASK: Remove unused parameter in Redis flush

---

Neos.Flow/Configuration/Settings.Reflection.yaml

**What I did**
This adds the missing behat annotations to ignored tags, so behat tests using those hooks can be reflected.
This is an example of the error that occurs currently when `@BeforeSuite` or `@AfterSuite` is used in any Behat Step class.
see also https://github.com/sandstorm/Sandstorm.E2ETestTools/pull/6
This can also be avoided when classes containing those annotations are *not reflected*, meaning if they are outside the psr classes directory.
When they are *inside* psr class directories, an error is thrown (see screenshot)

BUGFIX: Add behat @BeforeSuite and @AfterSuite to ignored annotation tags

---

Neos.Flow/Classes/Persistence/AbstractPersistenceManager.php
Neos.Flow/Classes/Persistence/Doctrine/PersistenceManager.php
Neos.Flow/Classes/Persistence/PersistenceManagerInterface.php

This reverts commit 18386878d77b5d93ff976769f967a3713ce2d7e6. 
The return type `object` is not handled properly yet in proxy class building which causes trouble on the neos side. We are reverting this now as hotfix. The proper handling of `object` types can be added as bugfix. The type annotations for the PersistenceManagerInterface will have to wait until next major.
**Checklist**

Revert "TASK: Add type declarations in PersistenceManagerInterface"

---

Neos.Flow/Classes/Core/LockManager.php

This is a followup PR to https://github.com/neos/flow-development-collection/pull/2716 to catch PHP 8 Throwables possibly thrown during `@unlink($this->lockPathAndFilename);`.

BUGFIX: LockManager catches PHP 8 Throwable during unlockSite

---

Neos.Flow/Classes/Core/Bootstrap.php
Neos.Flow/Scripts/flow.php

The trim method did not like beeing called with a null argument when the FLOW_CONTEXT environment was not set.
```
PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/ficzel/PhpStormProjects/neos-development-distribution-8-0/Packages/Framework/Neos.Flow/Scripts/flow.php on line 68
```

BUGFIX: Address deprecation warnings from PHP 8.1

---

Neos.FluidAdaptor/composer.json

BUGFIX: Require psr/log ^2.0 in FluidAdapter

---

Neos.Cache/composer.json
Neos.Flow/composer.json
composer.json

TASK: Relax psr cache constraints

---

Neos.Flow/Classes/Core/LockManager.php
Neos.Flow/Documentation/TheDefinitiveGuide/PartII/Configuration.rst
psalm-baseline.xml

The lock holding page was supposed to be customizable through
an environment variable, but that never worked…
Now it does, using the new variable name `FLOW_LOCK_HOLDING_PAGE`
as well as the (now deprecated) old name `FLOW_LOCKHOLDINGPAGE`.
Fixes #2798

BUGFIX: Use env var for FLOW_LOCK_HOLDING_PAGE

---

Neos.Flow/Classes/Cli/SlaveRequestHandler.php
Neos.Flow/Classes/Command/CoreCommandController.php
Neos.Flow/Tests/Behavior/Features/Bootstrap/SubProcess/SubProcess.php

This removes the interactive shell functionality and deeprecates
the support classes for this. Those are still used by the behat
tests and everything should be moved to a separate package at
which point we will reintroduce the interactive shell in that
new package. At that point renaming will likely happen, therefore
the respective classes are marked deprecated. None of it was public
API before so this is not marked breaking.

TASK: Remove interactive shell and deprecate infrastructure

---

Neos.Flow/Classes/Package.php
Neos.Flow/Classes/Persistence/Doctrine/PersistenceManager.php
Neos.Flow/Classes/Persistence/PersistenceManagerInterface.php
Neos.Flow/Tests/Unit/Persistence/Doctrine/PersistenceManagerTest.php

If you ever used `persistAll(true)` you should replace those invocations with `persistAllowedObjects()`.

!!! TASK: Add `persistAllowedObjects()` deprecate flag argument for `persistAll()` in PersistenceManager

---

Neos.Flow/Classes/Mvc/Routing/Dto/UriConstraints.php

Reverts neos/flow-development-collection#2813

Revert "BUGFIX: Uri must not be constructed with empty string"

---

Neos.Flow/Classes/Mvc/Routing/Dto/UriConstraints.php

Adjusts `UriConstraints::applyTo()` such that it never creates
an `Uri` instance with a path of `/` (which according to `guzzle/psr` was
deprecated since 1.x and invalid with 2.x)
Fixes: #2473

BUGFIX: Prevent UriConstraints to generate invalid URIs

---

Neos.Flow/Classes/Mvc/Routing/RouterCachingService.php
Neos.Flow/Tests/Unit/Mvc/Routing/RouterCachingServiceTest.php

Adjusts `RouterCachingService` such that it includes the specified
`RouteParameters` into the generated `resolveCacheIdentifier`.
Fixes: #2815

BUGFIX: Respect RouteParameters in ResolveCache

---

.github/workflows/build.yml

This runs the various tests in the build matrix against MariaDB 10.6 and PostgreSQL 14. The "lowest dependencies" job is run against MariaDB 10.2 and PostgreSQL 10.
See #2824

TASK: Run tests against current database versions

---

Neos.Flow.Log/composer.json
Neos.Flow/composer.json
Neos.FluidAdaptor/composer.json
composer.json

The change in https://github.com/neos/flow-development-collection/pull/2792 did only allow for psr/log 2.0 while already adding the return type hints that are only part of 3.0. This change allows installing both 2.0 || 3.0 like we do for the other psr interfaces and provides implementations for both versions. Thanks @jonnitto for bringing this up
See also https://github.com/neos/flow-development-collection/pull/2805

TASK: Allow installing psr/log 3.0 and provide implementation for it

---

Neos.Flow/Classes/Validation/ValidatorResolver.php

This change adds logic to the ValidatorResolver to accept properties
which were promoted in a constructor (PHP 8.1 promoted properties)
and thus do not have a @var annoation in a doc comment.
At the same time, @var annotations are not necessary anymore if a
type declaration was provided.
Resolves #2835

TASK: Support promoted properties in validator

---

Neos.Flow/Classes/ObjectManagement/Proxy/ObjectSerializationTrait.php

This change introduces support for PHP 7.4 style class property
type declarations for objects to be serialized by Flow. Previously,
a `@var` annotation had to be specified for each class property, in
order to communicate the type to Flow's serialization mechanism.
Resolves #2843

FEATURE: Support object serialization without var annotation

---

Neos.Cache/Tests/Functional/Backend/PdoBackendTest.php

If the database setup fails, catching a `Throwable` is needed to skip
correctly.
**Review instructions**
The tests should pass, as opposed to https://github.com/neos/flow-development-collection/actions/runs/2346671349
See https://github.com/neos/flow-development-collection/pull/2838 for the "source" of this.

TASK: Fix setup error handling in PdoBackendTest

---

Neos.Flow/Classes/I18n/Cldr/Reader/DatesReader.php
Neos.Flow/Tests/Functional/I18n/Cldr/Reader/DatesReaderTest.php

Closes: #2849
The cache key for a dateTime format is now the expanded format pattern instead of `{0} {1}`.

BUGFIX: Use expanded pattern as cache key for dateTime format

---

Neos.Flow/Classes/Http/Client/InternalRequestEngine.php

The `HttpRequestEngine` holds a reference to the "current" http request in each step of the middleware chain.
The internal request engine does not, making it hard to write tests, that predict system behavior.
With this patch you can fetch the current request (and not only the outer most) even in `InternalRequestEngine`
See `\Neos\Flow\Http\RequestHandler::handleRequest()`
**Checklist**

BUGFIX: InternalRequestEngine should behave like HttpRequestEngine

---

Neos.Flow/Classes/ObjectManagement/Proxy/ProxyMethod.php

The check `is_numeric` evaluates to true for strings like `"1"` therefore the generated code would be missing the quotes
necessary to keep the default argument a string. This causes type errors in the proxy class when the arguments type is `string`.
Therefore the check whether an argument value is a string should be done first.
This change could be breaking if no type is used and a method somehow relies on the proxy class turning the argument default into a number.
Resolves: #2864

BUGFIX: Don't convert numeric strings to numbers in proxy method argument defaults

---

Neos.Flow/Classes/Cli/ConsoleOutput.php

The other question methods take arrays or strings as arguments which is easy and convenient however the underlying symfony console offers more flexibility.
This pr adds the method `askQestion` that accepts a smfony console question object and thus allows the full flexibility at the price of complexity.
In addition the method `getQuestionHelper` is made public to make this as accessible as the `getProgressBar` method.
**Review instructions**
I chose not to allow Question objects in the `ask` method because this method has a default argument that only makes sense when the question is passed as array or string.
**Checklist**

FEATURE: Add method `askQuestion` to console output that accepts a `Question` object

---

Neos.Flow/.phpstorm.meta.php

The old .phpstorm.meta.php syntax is deprecated, see
https://www.jetbrains.com/help/phpstorm/ide-advanced-metadata.html#legacy-metadata-format-deprecated
**Review instructions**
Code completion in PhpStorm should still "know" about these:
```php
// $environment is Environment|obect
$environment = $bootstrap->getEarlyInstance(Environment::class);
// $environment is Environment|obect
$environment = $objectManager->get(Environment::class);
```
**Checklist**

TASK: Update .phpstorm.meta.php syntax

---

Neos.Http.Factories/composer.json

This makes sure `guzzlehttp/psr7` is will not be used in version with a known
security issue.
**Checklist**

TASK: Raise guzzlehttp/psr7 to ^1.8.4 (security fix)

---

Neos.Flow/Classes/Http/Middleware/MethodOverrideMiddleware.php
Neos.Flow/Configuration/Settings.Http.yaml
Neos.Flow/Tests/Functional/Http/Client/BrowserTest.php
Neos.Flow/Tests/Functional/Http/Fixtures/Controller/RequestController.php
Neos.Flow/Tests/Unit/Http/Middleware/MethodOverrideMiddlewareTest.php

The documented feature to override the request method with the POST argument `__method` or one of the HTTP headers X-Http-Method-Override or X-Http-Method was accidentally removed in the transition towards PSR-7. This adds it back in by adding a middleware that does the same logic that was removed with the previous Http\Request class.
Resolves #2856

BUGFIX: Reimplement request method override via middleware

---

Neos.Cache/Classes/Backend/MultiBackend.php
Neos.Cache/Classes/Backend/TaggableMultiBackend.php
Neos.Cache/Readme.md
Neos.Cache/Tests/Unit/Backend/MultiBackendTest.php
Neos.Cache/composer.json
Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Caching.rst
psalm-baseline.xml

This introduces a new feature for the MultiBackend and the TaggableMultiBackend which automatically removes unhealthy sub backends from the list of backends for the remainder of a request.
If a sub backend throws any error, the error will be caught, logged and the backend removed from the list of sub backends. If the sub backend causing trouble is the last one configured for the MultiBackend, it will not be removed.
The feature can be disabled by setting the option `removeUnhealthyBackends` to `false`.
Resolves #2890

FEATURE: Skip unhealthy cache backends in MultiBackend

---

Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/CommandLine.rst

Update the cli command example in the documentation to follow best practices.
In commands, when showing a progress bar, using ->progressFinish() does not output a newline. This is intended, as it allows adding further text in the same line. However, the full command output - unless empty - should end with a newline.
See https://github.com/neos/neos-development-collection/issues/3894
**Checklist**

TASK: Improve command documentation

---

Neos.Eel/Classes/CompilingEelParser.php
Neos.Eel/Classes/CompilingEvaluator.php

Fixes #2906
**Review instructions**
Code in Data/Temporary/…/Cache/Data/Eel_Expression_Code/expression_* should have static fucntions…
**Checklist**

FEATURE: Produce static functions in CompilingEvaluator
