neos/flow-development-collection

- TYPO3.Flow/Classes/TYPO3/Flow/Composer/InstallerScripts.php
The InstallerScripts taking care of copying distribution resources
after composer operations would assume package paths that are
incompatible with the joined repositories. This will result in
missing Neos Routes on installing from the collection repository.
This is a first step after which the joined composer.json can be
used fully.
This deprecates the ["extras"]["typo3/flow"]["manage-resources"]
configuration for copying distribution resources. The deprecation
is in effect from 3.1 onwards and this option will be removed
three versions later. The new
["extras"]["neos"]["installer-resource-folders"] configuration
which is an array of directories containing installer resources
superseeds it with this changes and takes precedence. A typical
replacement would be: …
> [TASK] Allow InstallerScripts to work with collection repository

- .travis.yml
> [TASK] Add .travis.yml

- Readme.rst
> [TASK] Add Readme with Travis CI badge

- .travis.yml
> [TASK] Use specific build matrix for less tests

- .travis.yml
> [TASK] Run only tests for Flow dev collection packages on Travis CI

- Readme.rst
> [TASK] Add Code Climate to Readme

- .codeclimate.yml
> [TASK] Exclude auto-generated and 3rd party code from Code Climate

- TYPO3.Flow/Classes/TYPO3/Flow/Object/DependencyInjection/ProxyClassBuilder.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Streams/StreamWrapperAdapter.php
Comply with https://wiki.php.net/rfc/uniform_variable_syntax
Resolves: NEOS-1608
> [TASK] Use uniform variable syntax of PHP7

- Readme.rst
- apigen.yml
This adds an apigen.yml file for use when generating API docs.
> [TASK] Add apigen.yml

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/EntityManagerFactory.php
A purely non-functional cleanup change.
> [TASK] Add use statements to EntityManagerFactory

- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ReflectionService.php
This is a mild refactoring of the ``ReflectionService`` which
doesn't change any functionality but reduces method complexity
and size by splitting and reordering of code.
> [TASK] Improve readability of ReflectionService

- .travis.yml
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Client/InternalRequestEngine.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/Configuration/Configuration.php
- TYPO3.Flow/Tests/Functional/Mvc/ActionControllerTest.php
- TYPO3.Flow/Tests/Unit/Object/Configuration/ConfigurationTest.php
- TYPO3.Flow/Tests/Unit/Package/PackageFactoryTest.php
- TYPO3.Flow/Tests/Unit/Package/PackageTest.php
This fixes a few remaining (test) incompatibilities with PHP 7.
> [TASK] Finalize PHP 7 support

- .travis.yml
Adds some php configuration settings to the travis configuration
to reduce the possibility of heap corruption errors.
> [TASK] Add best practice config to travis.yml

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Routing.rst
Adjust Routing chapter to the placeholder support
in routing defaults introduced with FLOW-76
Related: FLOW-76
> [TASK] Tweak routing documentation

- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/RedisBackend.php
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Caching.rst
> [TASK] Add missing compression support in RedisBackend

- TYPO3.Kickstart/Resources/Private/Generator/Controller/ActionControllerTemplate.php.tmpl
- TYPO3.Kickstart/Resources/Private/Generator/Controller/CommandControllerTemplate.php.tmpl
- TYPO3.Kickstart/Resources/Private/Generator/Controller/CrudControllerTemplate.php.tmpl
- TYPO3.Kickstart/Resources/Private/Generator/Documentation/index.rst
- TYPO3.Kickstart/Resources/Private/Generator/Model/EntityTemplate.php.tmpl
- TYPO3.Kickstart/Resources/Private/Generator/Repository/RepositoryTemplate.php.tmpl
- TYPO3.Kickstart/Resources/Private/Generator/Tests/Unit/Model/EntityTestTemplate.php.tmpl
- TYPO3.Kickstart/Resources/Private/Generator/View/DefaultLayout.html
- TYPO3.Kickstart/Resources/Private/Generator/View/EditTemplate.html
- TYPO3.Kickstart/Resources/Private/Generator/View/IndexTemplate.html
- TYPO3.Kickstart/Resources/Private/Generator/View/NewTemplate.html
- TYPO3.Kickstart/Resources/Private/Generator/View/SampleIndexTemplate.html
- TYPO3.Kickstart/Resources/Private/Generator/View/ShowTemplate.html
This change removes the TYPO3 brand name and updates some invalid links.
> TASK: Generate PSR2 based code and some cleanup

- TYPO3.Flow/Classes/TYPO3/Flow/Utility/Lock/FlockLockStrategy.php
Unlinking the lock file again causes race conditions which the
locking should prevent in the first place. Until we found out a
solid way to do this we need to keep those files even though
this is not optimal due to the high amount of inodes those lock
files use up.
> [BUGFIX] Don't unlink lock file

- TYPO3.Flow/Scripts/Migrations/Manager.php
> BUGFIX: Skip Neos.* packages by default in core:migrate

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/ReleaseNotes/310.rst
NEOS-1713 #comment Release notes for Flow 3.1
> TASK: Add release notes for Flow 3.1

- TYPO3.Flow/Classes/TYPO3/Flow/Package/Package.php
Fix missing refactoring from 30b326a9735c80cd88c0acebcde127c02d6a198b
> BUGFIX: Fix argument must be array but string given

- TYPO3.Flow/Classes/TYPO3/Flow/Command/SecurityCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Security/Cryptography/RsaWalletServiceInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Security/Cryptography/RsaWalletServicePhp.php
Improves naming and documentation in RsaWalletService and the related command controller.
> TASK: RsaWalletService tweaks

- TYPO3.Flow/Classes/TYPO3/Flow/Log/Logger.php
This change add the current PHP process PID, script Inode and
current user information (UID, GID, Username) when Flow log an
exception.
> TASK: Add PHP process debug info in logged exception

- TYPO3.Flow/Classes/TYPO3/Flow/Command/SecurityCommandController.php
A new CLI command to generate a key pair:
./ flow security:generatekeypair
> FEATURE: Command to generate key pair for RsaWalletService

- TYPO3.Flow/Documentation/Quickstart/index.rst
- TYPO3.Flow/Documentation/StyleGuide/About.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartII/Validation.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartII/View.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/ErrorAndExceptionHandling.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Templating.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/ChangeLogs/300-beta4.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/ChangeLogs/300-beta5.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/ChangeLogs/300.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/CodingGuideLines/PHP.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/ReleaseNotes/300.rst
I've tried to fix as much as possible.
But I can't resolve some errors, e.g. in ChangeLog some labels exist twice as there were two pull requests for the same topic leading to the same title.
Beside that, there are two code blocks I can't fix with my knowledge and without breaking the code.
> TASK: Fix rST errors and warnings for 3.0

- TYPO3.Flow/Documentation/Quickstart/index.rst
- TYPO3.Flow/Documentation/StyleGuide/About.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartII/Validation.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartII/View.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/ErrorAndExceptionHandling.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Templating.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/ChangeLogs/310.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/ChangeLogs/index.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/CodingGuideLines/PHP.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/ReleaseNotes/300.rst
I've tried to fix as much as possible.
But I can't resolve some errors, e.g. in ChangeLog some labels exist twice as there were two pull requests for the same topic leading to the same title.
Beside that, there are two code blocks I can't fix with my knowledge and without breaking the code.
> TASK: Fix rST errors and warnings for 3.1

- TYPO3.Flow/Resources/Private/Schema/Settings/TYPO3.Flow.core.schema.yaml
- TYPO3.Flow/Resources/Private/Schema/Settings/TYPO3.Flow.http.schema.yaml
Adds the settings introduced in #299 to the schema files.
Refactores the constants to lower case
> TASK: Adjust schema files to new settings introduced in #299

- Neos.RedirectHandler/Classes/Command/RedirectCommandController.php
Add PHPDoc comments used for command reference in the ``redirect`` command controller.
> TASK: Provide comments used as command reference for ``redirect`` command

- TYPO3.Flow/Classes/TYPO3/Flow/Command/CacheCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Configuration/ConfigurationManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/AbstractPersistenceManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ReflectionService.php
- TYPO3.Flow/Classes/TYPO3/Flow/Security/AccountRepository.php
- TYPO3.Flow/Classes/TYPO3/Flow/Security/Aspect/PolicyEnforcementAspect.php
- TYPO3.Flow/Tests/Behavior/Features/Bootstrap/FeatureContext.php
- TYPO3.Flow/Tests/Functional/Command/BehatHelperCommandController.php
- TYPO3.Flow/Tests/Functional/Persistence/Doctrine/AggregateTest.php
- TYPO3.Flow/Tests/Functional/Security/Authorization/Privilege/Entity/Doctrine/EntityPrivilegeExpressionEvaluatorTest.php
- TYPO3.Flow/Tests/Unit/Cache/Backend/MemcacheBackendTest.php
- TYPO3.Flow/Tests/Unit/I18n/LocaleTypeConverterTest.php
- TYPO3.Flow/Tests/Unit/Resource/Target/FileSystemTargetTest.php
- TYPO3.Flow/Tests/Unit/Security/RequestPattern/IpTest.php
- TYPO3.Fluid/Classes/TYPO3/Fluid/Core/Widget/AbstractWidgetViewHelper.php
- TYPO3.Fluid/Classes/TYPO3/Fluid/ViewHelpers/Security/IfHasRoleViewHelper.php
- TYPO3.Fluid/Migrations/Code/Version20150214130800.php
- TYPO3.Fluid/Tests/Functional/Core/ParserIntegrationTest.php
- TYPO3.Fluid/Tests/Unit/ViewHelpers/Format/BytesViewHelperTest.php
- TYPO3.Fluid/Tests/Unit/ViewHelpers/Security/IfHasRoleViewHelperTest.php
This changes removes imprts that are not
longer needed.
> TASK: Remove unneeded class imports

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/Service.php
This task makes generated database migrations compatible with
the PSR-2 coding style guide.
--
Just a question: Is it okay to use here the same commit message? (see https://github.com/neos/flow-development-collection/commit/d47f7114b7f27989100d3ee1e09050d855221490)
> TASK: Generated database migrations are PSR-2 compatible

- TYPO3.Eel/Tests/Unit/AbstractEvaluatorTest.php
- TYPO3.Eel/Tests/Unit/ProtectedContextTest.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Request.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/RequestHandler.php
- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/Service.php
- TYPO3.Flow/Classes/TYPO3/Flow/Security/Authorization/Privilege/Entity/Doctrine/ConditionGenerator.php
- TYPO3.Flow/Tests/Functional/Http/RequestHandlerTest.php
- TYPO3.Flow/Tests/Functional/Security/Authentication/Provider/PersistedUsernamePasswordProviderTest.php
- TYPO3.Flow/Tests/Unit/Error/DebuggerTest.php
- TYPO3.Flow/Tests/Unit/Mvc/Routing/RouteTest.php
- TYPO3.Flow/Tests/Unit/Object/DependencyInjection/DependencyProxyTest.php
- TYPO3.Flow/Tests/Unit/Security/ContextTest.php
- TYPO3.Flow/Tests/Unit/Security/Policy/PolicyServiceTest.php
- TYPO3.Flow/Tests/Unit/SignalSlot/DispatcherTest.php
- TYPO3.Fluid/Tests/Unit/ViewHelpers/Security/IfHasRoleViewHelperTest.php
This pull request applies code style fixes from an analysis carried out by StyleCI.
For details, see https://styleci.io/analyses/XN4pa4
> TASK: Apply fixes from StyleCI

- TYPO3.Flow/Tests/Functional/Property/TypeConverter/FloatConverterTest.php
- TYPO3.Flow/Tests/Unit/Aop/Pointcut/PointcutSettingFilterTest.php
- TYPO3.Flow/Tests/Unit/Core/ApplicationContextTest.php
- TYPO3.Flow/Tests/Unit/Object/Configuration/ConfigurationTest.php
- TYPO3.Flow/Tests/Unit/Persistence/RepositoryTest.php
- TYPO3.Flow/Tests/Unit/Security/Authentication/AuthenticationProviderResolverTest.php
- TYPO3.Flow/Tests/Unit/Security/Authentication/EntryPoint/WebRedirectTest.php
- TYPO3.Flow/Tests/Unit/Security/Authorization/InterceptorResolverTest.php
- TYPO3.Flow/Tests/Unit/Security/RequestPatternResolverTest.php
- TYPO3.Flow/Tests/Unit/Validation/Validator/ConjunctionValidatorTest.php
- TYPO3.Fluid/Tests/Unit/Core/Widget/AbstractWidgetViewHelperTest.php
- TYPO3.Fluid/Tests/Unit/Core/Widget/AjaxWidgetContextHolderTest.php
This is rather cosmetic, it fixes IDE navigation and error detection.
> TASK: Make expected exception class name fully qualified

- TYPO3.Flow/Classes/TYPO3/Flow/Core/Bootstrap.php
- TYPO3.Flow/Tests/Unit/Core/BootstrapTest.php
This change fixes a missing class import introduced with PR #376 into the 2.3 branch.
> BUGFIX: FlowException is no imported

- TYPO3.Eel/Documentation/README.md
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Eel.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/index.rst
- TYPO3.Flow/Documentation/conf.py
* To explain what Eel is about.
* To ease starting with Eel.
* To provide a central place for Eel where further documentation is
referenced.
> FEATURE: Provide basic documentation about Eel

- TYPO3.Flow/Classes/TYPO3/Flow/Aop/Builder/ProxyClassBuilder.php
Any sub class of a class that has an advice also needs to initialize
the advices array in the constructor or otherwise that will lead to
exceptions later on. The only reason it works currently is the
``\TYPO3\Flow\Object\Proxy\DoctrineProxyFixingTrait``
which (as a side effect) masks this bug. If we want to get rid of this
trait with newer Doctrine versions we need to fix the bug on our side.
> BUGFIX: Sub classes of adviced classes should initialize advices

- TYPO3.Flow/Classes/TYPO3/Flow/Aop/Builder/ProxyClassBuilder.php
The fix done in commit 8ca79cda53f90415458eb825c5bac52105d08d40
did not catch all cases as target classes that do not have an
advice applied (usually the parent class then has the advice),
was not treated with the fix for methods and advices.
This change adds treatment for those classes as well.
> BUGFIX: MethodsAndAdvices fix for non proxied target classes

- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ReflectionService.php
- TYPO3.Flow/Classes/TYPO3/Flow/Utility/Unicode/TextIterator.php
- TYPO3.Flow/Tests/Unit/Aop/Advice/AbstractAdviceTest.php
- TYPO3.Flow/Tests/Unit/Aop/Advice/AroundAdviceTest.php
- TYPO3.Flow/Tests/Unit/Aop/Advice/Fixtures/SomeClass.php
- TYPO3.Flow/Tests/Unit/Mvc/View/Fixtures/NestedTestObject.php
- TYPO3.Flow/Tests/Unit/Mvc/View/JsonViewTest.php
- TYPO3.Flow/Tests/Unit/Security/AccountTest.php
- TYPO3.Flow/Tests/Unit/Security/Fixture/PartyService.php
Mocking a "virtual" class is no longer allowed, so we use fixture classes.
> TASK: Adjust unit tests to use "real mocks"

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php
- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ReflectionService.php
- TYPO3.Flow/Tests/Functional/Persistence/Doctrine/PersistClonedRelatedEntitiesTest.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/TestEmbeddable.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/TestEntity.php
- TYPO3.Flow/Tests/Functional/Persistence/PersistenceTest.php
This adds mappings for the @ORM\Index annotation attributes "flags" and "options" as well as the @ORM\UniqueConstraints annotation attribute "options".
Also, this adds a test for and fixes the Doctrine Embeddables.
> BUGFIX: Add missing Doctrine 2.5 mappings and fix Embeddables

- TYPO3.Flow/Classes/TYPO3/Flow/Property/PropertyMapper.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/PropertyMappingConfiguration.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/PropertyMappingConfigurationBuilder.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverterInterface.php
Preparations for easier namespace migration.
> TASK: Cleanup absolute namespaces in property mapper

- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/AbstractBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/ApcBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/BackendInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/FileBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/MemcachedBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/NullBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/PdoBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/RedisBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/SimpleFileBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/TransientMemoryBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cache/CacheFactory.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cache/CacheManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Frontend/CacheEntryIterator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Frontend/FrontendInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Frontend/PhpFrontend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Frontend/StringFrontend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Frontend/VariableFrontend.php
Remove absolute namespaces and legacy array syntax
> TASK: Refactor Flow / Cache classes code style

- Readme.rst
> TASK: Point to a Flow LICENSE file in Readme.rst

- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Collection.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/CollectionInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Publishing/ResourcePublisher.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Resource.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/ResourceManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/ResourcePointer.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/ResourceRepository.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/ResourceTypeConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Storage/FileSystemStorage.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Storage/PackageStorage.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Storage/StorageInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Storage/WritableFileSystemStorage.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Storage/WritableStorageInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Streams/ResourceStreamWrapper.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Streams/StreamWrapperAdapter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Target/FileSystemSymlinkTarget.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Target/FileSystemTarget.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Target/TargetInterface.php
> TASK: Refactor absolute namespaces in Flow / Resource Classes

- TYPO3.Flow/Classes/TYPO3/Flow/Session/Aspect/LazyLoadingAspect.php
- TYPO3.Flow/Classes/TYPO3/Flow/Session/Aspect/LoggingAspect.php
- TYPO3.Flow/Classes/TYPO3/Flow/Session/Aspect/SessionObjectMethodsPointcutFilter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Session/Exception.php
- TYPO3.Flow/Classes/TYPO3/Flow/Session/Exception/OperationNotSupportedException.php
- TYPO3.Flow/Classes/TYPO3/Flow/Session/Exception/SessionAutostartIsEnabledException.php
- TYPO3.Flow/Classes/TYPO3/Flow/Session/Exception/SessionNotStartedException.php
- TYPO3.Flow/Classes/TYPO3/Flow/Session/Session.php
- TYPO3.Flow/Classes/TYPO3/Flow/Session/SessionInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Session/SessionManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Session/SessionManagerInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Session/TransientSession.php
> TASK: Refactor absolute namespaces in Flow / Session classes

- TYPO3.Eel/Classes/TYPO3/Eel/Helper/StringHelper.php
- TYPO3.Eel/Tests/Unit/Helper/StringHelperTest.php
Adds missing PHPDoc to StringHelper functions and add more examples.
> TASK: Improve StringHelper documentation

- TYPO3.Flow/Classes/TYPO3/Flow/Configuration/ConfigurationManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Configuration/ConfigurationSchemaValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Configuration/Source/YamlSource.php
Also refactor legacy array syntax
> TASK: Refactor absolute namespaces in Flow / Configuration classes

- TYPO3.Flow/Classes/TYPO3/Flow/Log/Backend/AbstractBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Log/Backend/AnsiConsoleBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Log/Backend/ConsoleBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Log/Backend/FileBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Log/Backend/NullBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Log/EarlyLogger.php
- TYPO3.Flow/Classes/TYPO3/Flow/Log/Logger.php
- TYPO3.Flow/Classes/TYPO3/Flow/Log/LoggerFactory.php
- TYPO3.Flow/Classes/TYPO3/Flow/Log/LoggerInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Log/SecurityLoggerInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Log/SystemLoggerInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Log/ThrowableLoggerInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Monitor/ChangeDetectionStrategy/ModificationTimeStrategy.php
- TYPO3.Flow/Classes/TYPO3/Flow/Monitor/FileMonitor.php
> TASK: Refactor absolute namespaces in Flow / Log and Monitor

- TYPO3.Flow/Classes/TYPO3/Flow/Package/Documentation.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/MetaData.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/MetaData/Company.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/MetaData/PackageConstraint.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/MetaData/Person.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/MetaData/SystemConstraint.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/MetaDataInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/Package.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageFactory.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageManagerInterface.php
> TASK: Refactor absolute namespaces in Flow / Package classes

- TYPO3.Flow/Classes/TYPO3/Flow/Property/PropertyMapper.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/PropertyMappingConfiguration.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/PropertyMappingConfigurationBuilder.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/PropertyMappingConfigurationInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/AbstractTypeConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/ArrayConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/ArrayFromObjectConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/BooleanConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/CollectionConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/DateTimeConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/FloatConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/IntegerConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/MediaTypeConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/ObjectConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/PersistentObjectConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/PersistentObjectSerializer.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/SessionConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/StringConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/TypedArrayConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/UriTypeConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverterInterface.php
> TASK: Refactor absolute namespaces in Flow / Property Classes

- TYPO3.Flow/Classes/TYPO3/Flow/Security/Context.php
- TYPO3.Flow/Classes/TYPO3/Flow/Security/RequestPattern/Host.php
- TYPO3.Flow/Tests/Functional/Http/Client/CurlEngineTest.php
- TYPO3.Flow/Tests/Functional/Mvc/ActionControllerTest.php
- TYPO3.Flow/Tests/Functional/Mvc/ActionRequestTest.php
- TYPO3.Flow/Tests/Functional/Object/DependencyInjectionTest.php
- TYPO3.Flow/Tests/Unit/Security/RequestPattern/HostTest.php
- TYPO3.Flow/Tests/Unit/Utility/SchemaValidatorTest.php
- TYPO3.Flow/Tests/Unit/Validation/Validator/CollectionValidatorTest.php
- TYPO3.Flow/Tests/Unit/Validation/Validator/EmailAddressValidatorTest.php
Replaces references to typo3.org with matching references to neos.io.
> TASK: Remove references to typo3.org

- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ClassReflection.php
- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ClassSchema.php
- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/DocCommentParser.php
- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/MethodReflection.php
- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ObjectAccess.php
- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ParameterReflection.php
- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/PropertyReflection.php
- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ReflectionService.php
> TASK: Refactor absolute namespaces in Flow / Reflection classes

- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/AbstractCompositeValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/AbstractValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/BooleanValueValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/CollectionValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/ConjunctionValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/CountValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/DateTimeRangeValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/DateTimeValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/DisjunctionValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/GenericObjectValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/LocaleIdentifierValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/NumberRangeValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/NumberValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/RegularExpressionValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/StringLengthValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/UniqueEntityValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/ValidatorInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/ValidatorResolver.php
> TASK: Refactor absolute namespaces in Flow / Validation classes

- TYPO3.Flow/Tests/Functional/Package/PackageManagerTest.php
- TYPO3.Flow/Tests/Functional/Persistence/Aspect/PersistenceMagicAspectTest.php
- TYPO3.Flow/Tests/Functional/Persistence/Doctrine/AggregateTest.php
- TYPO3.Flow/Tests/Functional/Persistence/Doctrine/IndexedCollectionTest.php
- TYPO3.Flow/Tests/Functional/Persistence/Doctrine/LazyLoadingTest.php
- TYPO3.Flow/Tests/Functional/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriverTest.php
- TYPO3.Flow/Tests/Functional/Persistence/Doctrine/PersistClonedRelatedEntitiesTest.php
- TYPO3.Flow/Tests/Functional/Persistence/Doctrine/QueryTest.php
- TYPO3.Flow/Tests/Functional/Persistence/Doctrine/RepositoryTest.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/CommentRepository.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/CommonObject.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/EventSubscriber.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/Post.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/PostRepository.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/RelatedIndexEntity.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/SubEntity.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/SubSubEntityRepository.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/SuperEntityRepository.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/TestEntity.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/TestEntityAspect.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/TestEntityRepository.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/TestValueObjectWithTransientProperties.php
- TYPO3.Flow/Tests/Functional/Persistence/PersistenceTest.php
- TYPO3.Flow/Tests/Functional/Property/Fixtures/TestClass.php
- TYPO3.Flow/Tests/Functional/Property/PropertyMapperTest.php
- TYPO3.Flow/Tests/Functional/Property/TypeConverter/FloatConverterTest.php
- TYPO3.Flow/Tests/Functional/Property/TypeConverter/ObjectConverterTest.php
- TYPO3.Flow/Tests/Functional/Property/TypeConverter/PersistentObjectConverterTest.php
Folders Persistence and Property
Also refactored legacy array synt
> TASK: Refactor absolute namespaces in Flow / Functional Test Classes

- TYPO3.Flow/Classes/TYPO3/Flow/Command/CoreCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/HelpCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/ResourceCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/RoutingCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/SecurityCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Error/AbstractExceptionHandler.php
- TYPO3.Flow/Classes/TYPO3/Flow/Error/Debugger.php
- TYPO3.Flow/Classes/TYPO3/Flow/Error/ErrorHandler.php
- TYPO3.Flow/Classes/TYPO3/Flow/Error/Message.php
- TYPO3.Flow/Classes/TYPO3/Flow/Error/Result.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/AbstractMessage.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Client/Browser.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Client/CurlEngine.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Client/InternalRequestEngine.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Client/RequestEngineInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Component/ComponentChain.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Component/ComponentChainFactory.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Component/ComponentContext.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Component/StandardsComplianceComponent.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Cookie.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Headers.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/HttpRequestHandlerInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Message.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Request.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/RequestHandler.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Response.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Uri.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/UriTemplate.php
> TASK: Refactor absolute namespaces in Flow / HTTP and Error classes

- TYPO3.Flow/Classes/TYPO3/Flow/Object/CompileTimeObjectManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/Configuration/Configuration.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/Configuration/ConfigurationArgument.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/Configuration/ConfigurationBuilder.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/Configuration/ConfigurationProperty.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/DependencyInjection/DependencyProxy.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/DependencyInjection/ProxyClassBuilder.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/ObjectManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/ObjectManagerInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/ObjectSerializer.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/Proxy/Compiler.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/Proxy/ProxyClass.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/Proxy/ProxyConstructor.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/Proxy/ProxyMethod.php
> TASK: Refactor absolute namespaces in Flow / Object

- TYPO3.Flow/Classes/TYPO3/Flow/Core/ApplicationContext.php
- TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php
- TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Sequence.php
- TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Step.php
- TYPO3.Flow/Classes/TYPO3/Flow/Core/Bootstrap.php
- TYPO3.Flow/Classes/TYPO3/Flow/Core/ClassLoader.php
> TASK: Refactor absolute namespaces in Flow / Core classes

- TYPO3.Eel/Classes/TYPO3/Eel/Helper/ArrayHelper.php
- TYPO3.Eel/Tests/Unit/Helper/ArrayHelperTest.php
With this helper it is possible to flip the keys and values from an array.
`Array.flip(array)`
> FEATURE: ``Array.flip()`` Eel helper

- TYPO3.Flow/Classes/TYPO3/Flow/Security/Authentication/AuthenticationManagerInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Security/Authentication/AuthenticationProviderManager.php
Adds a new getter method to the AuthenticationManagerInterface, that has to return all provided authentication providers.
> FEATURE: Extend AuthenticationManagerInterface with getter for providers

- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/RedisBackend.php
- TYPO3.Flow/Tests/Functional/Cache/Backend/RedisBackendTest.php
When setting or flushing by tag the list of entries is not correctly
updated. This could also occur if an entry is expired.
This change fixes the flush by tag behaviour to correctly remove
entries and adds a check into the iteration of cache entries to check
for existing entries.
> BUGFIX: Redis backend should prevent iteration of duplicate entries

- TYPO3.Eel/composer.json
- TYPO3.Flow/Configuration/Settings.yaml
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/ObjectManagement.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/PackageManagement.rst
- TYPO3.Flow/Tests/Unit/ObjectManagement/CompileTimeObjectManagerTest.php
- TYPO3.Flow/Tests/Unit/Package/PackageManagerTest.php
- TYPO3.Flow/Tests/Unit/Package/PackageTest.php
- TYPO3.Flow/composer.json
- TYPO3.Kickstart/composer.json
Related to neos/neos-development-collection#1241
> TASK: Use neos-* as composer package type consistently

- Neos.Flow/Tests/Unit/Security/Policy/RoleTest.php
See neos/neos-development-collection#1240
> BUGFIX: Adjust RoleTest to renamed vendor

- Neos.Flow/Migrations/Mysql/Version20161125121218.php
- Neos.Flow/Migrations/Postgresql/Version20161125121217.php
See neos/neos-development-collection#1240
> TASK: Add Doctrine migrations to rename role identifiers

- TYPO3.Flow/Resources/Private/Schema/Settings/TYPO3.Flow.security.schema.yaml
> FEATURE: added missing "schema“-definition for the "token"-property of "authentication"-providers

- Neos.Flow/Classes/Core/Booting/Scripts.php
The setting ``TYPO3.Flow.utility.environment.temporaryDirectoryBase``
was deprecated and with this change finally removed.
The temporary path defaults to FLOW_PATH_ROOT . 'Data/Temporary', but
you can always override the temporary path via the environment variable
``FLOW_PATH_TEMPORARY_BASE`` instead.
Note that in either case a sub path will be created based on the
current application context.
> !!! TASK: Remove deprecated support of temporary path setting

- Neos.Flow/Classes/Cache/CacheFactory.php
- Neos.Flow/Classes/Command/CoreCommandController.php
- Neos.Flow/Classes/Command/DoctrineCommandController.php
- Neos.Flow/Classes/Http/Uri.php
- Neos.Flow/Classes/Mvc/Controller/ActionController.php
- Neos.Flow/Classes/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php
- Neos.Flow/Classes/Persistence/Doctrine/Service.php
- Neos.Flow/Classes/Property/TypeConverter/ObjectConverter.php
- Neos.Flow/Classes/ResourceManagement/PersistentResource.php
- Neos.Flow/Classes/Session/Aspect/LoggingAspect.php
- Neos.Flow/Classes/Validation/ValidatorResolver.php
This change fixe a couple of stale reference to classes which
have been moved around recently.
> BUGFIX: Invalid namespaces and class references

- Neos.Cache/Classes/Backend/PdoBackend.php
- Neos.Cache/Classes/Backend/SimpleFileBackend.php
- Neos.Cache/Tests/PhpUnitBootstrap.php
- Neos.Cache/Tests/Unit/Backend/PdoBackendTest.php
- Neos.Cache/Tests/Unit/Backend/SimpleFileBackendTest.php
- Neos.Utility.Unicode/Classes/Exception.php
This change fixes a couple of code style issues which
slipped in through prior pull requests.
> TASK: Fix code style issues

- Neos.Cache/Classes/Backend/PdoBackend.php
This change also cache the context value, to avoid too much call of the
md5 functions.
> BUGFIX: Missing $context variable in PdoBackend

- TYPO3.Fluid/Classes/TYPO3/Fluid/ViewHelpers/Format/CurrencyViewHelper.php
- TYPO3.Fluid/Tests/Unit/ViewHelpers/Format/CurrencyViewHelperTest.php
Adds ``prependCurrency``, ``separateCurrency`` and ``decimals`` as optional arguments to the ``CurrencyViewHelper``.
> FEATURE: Add more optional arguments to currency viewhelper

- .github/ISSUE_TEMPLATE.md
> TASK: Fix a small typo in github issue template

- Neos.FluidAdaptor/Classes/Core/Parser/SyntaxTree/ResourceUriNode.php
- Neos.FluidAdaptor/Classes/Core/Parser/TemplateProcessor/EscapingFlagProcessor.php
Just two small fixes sponsored by phpstan/phpstan.
> TASK: Some namespace fixes

- Neos.Flow/Classes/Mvc/Dispatcher.php
Removes a check for an old configuration value that was deprecated
since several versions.
> TASK: Remove deprecated configuration check in ``Dispatcher``

- Neos.Utility.Files/composer.json
- Neos.Utility.Lock/composer.json
- Neos.Utility.Schema/composer.json
- Neos.Utility.Unicode/composer.json
> TASK: Adjust Neos.Utility* paths in composer.json

- Neos.Flow/Documentation/Quickstart/index.rst
fix some typos in `updateAction` chapter
> TASK: Correct Flow Quickstart docs

- Neos.Cache/Tests/BaseTestCase.php
- Neos.Flow/Tests/BaseTestCase.php
We no longer support PhpUnit 4.8 so some code could be removed.
> TASK: Remove PhpUnit 4.8 support code

- Neos.Cache/Classes/Backend/RequireOnceFromValueTrait.php
- Neos.Flow/Classes/Http/Uri.php
- Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php
- Neos.Flow/Tests/Functional/Mvc/ViewsConfiguration/Fixtures/TemplateView.php
- Neos.Flow/Tests/Functional/ObjectManagement/DependencyInjectionTest.php
- Neos.Flow/Tests/Functional/Persistence/PersistenceTest.php
- Neos.Flow/Tests/Unit/Cache/CacheManagerTest.php
- Neos.Flow/Tests/Unit/Configuration/ConfigurationManagerTest.php
- Neos.Flow/Tests/Unit/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriverTest.php
- Neos.Flow/Tests/Unit/Persistence/Fixture/Repository/NonstandardEntityRepository.php
- Neos.Flow/Tests/Unit/Persistence/Generic/DataMapperTest.php
- Neos.Flow/Tests/Unit/Persistence/RepositoryTest.php
- Neos.Flow/Tests/Unit/Security/Authentication/AuthenticationProviderResolverTest.php
- Neos.Flow/Tests/Unit/Security/Authentication/Token/PasswordTokenTest.php
- Neos.Flow/Tests/Unit/Security/Authorization/Interceptor/PolicyEnforcementTest.php
- Neos.Flow/Tests/Unit/Security/Authorization/InterceptorResolverTest.php
- Neos.Flow/Tests/Unit/Security/RequestPatternResolverTest.php
- Neos.FluidAdaptor/Classes/Core/ViewHelper/TemplateVariableContainer.php
- Neos.FluidAdaptor/Classes/Service/AbstractGenerator.php
- Neos.FluidAdaptor/Classes/View/AbstractTemplateView.php
- Neos.FluidAdaptor/Classes/ViewHelpers/Form/SelectViewHelper.php
- Neos.FluidAdaptor/Tests/Unit/View/AbstractTemplateViewTest.php
- Neos.Utility.Files/Classes/Files.php
Mostly fixes comments, but some use statements as well.
> TASK: Fix "undefined class" warnings

- TYPO3.Flow/Classes/TYPO3/Flow/Command/TypeConverterCommandController.php
> BUGFIX: Adjust typeconverter:list to getTypeConverters() return value

- Neos.Cache/composer.json
- Neos.Eel/composer.json
- Neos.Flow/Configuration/Objects.yaml
- Neos.Flow/composer.json
- Neos.FluidAdaptor/composer.json
- Neos.Kickstarter/composer.json
- Neos.Utility.Files/composer.json
- Neos.Utility.Lock/Classes/FlockLockStrategy.php
- Neos.Utility.Lock/composer.json
- Neos.Utility.MediaTypes/composer.json
- Neos.Utility.ObjectHandling/composer.json
- Neos.Utility.Pdo/Configuration/Objects.yaml
- composer.json
Additionally move an Object configuration to the right place.
> TASK: Declare transitive dependencies

- Neos.Eel/Classes/Helper/StringHelper.php
- Neos.Eel/Tests/Unit/Helper/StringHelperTest.php
Return number of words in a string. Good for calculation of reading duration of an article
> FEATURE: Add wordCount Eel Helper

- Neos.Flow/Scripts/setfilepermissions.sh
File permission script checks that the command line user is a member of the webserver group
> FEATURE: webserver group membership check

- Neos.Flow/Documentation/TheDefinitiveGuide/PartV/ReleaseNotes/410.rst
> TASK: Add release notes for 4.1

- TYPO3.Flow/Resources/Private/Installer/Distribution/Essentials/Upgrading.rst
> TASK: Fix link to support page

- TYPO3.Flow/Classes/TYPO3/Flow/Configuration/Source/YamlSource.php
The symfony yaml parser deprecated handing in a file path and
instead expects the yaml content as string. As that is the same
behavior as for the PHP YAML extension the code was adapted to
read the file in all cases and pass the content to the respective
parser.
Fixes: #824
> TASK: Remove usage of deprecated ``Yaml::parse`` with file path

- Neos.Flow/Documentation/TheDefinitiveGuide/PartV/ReleaseNotes/400.rst
> TASK: Add release notes for 4.0.0

- TYPO3.Flow/Classes/TYPO3/Flow/Object/Proxy/ProxyMethod.php
> BUGFIX: Return type declaration should be FQCN

- Neos.FluidAdaptor/Classes/ViewHelpers/Format/Base64DecodeViewHelper.php
- Neos.FluidAdaptor/Classes/ViewHelpers/Format/CaseViewHelper.php
- Neos.FluidAdaptor/Classes/ViewHelpers/Format/CropViewHelper.php
- Neos.FluidAdaptor/Classes/ViewHelpers/Format/IdentifierViewHelper.php
- Neos.FluidAdaptor/Classes/ViewHelpers/Format/JsonViewHelper.php
- Neos.FluidAdaptor/Classes/ViewHelpers/Format/Nl2brViewHelper.php
- Neos.FluidAdaptor/Classes/ViewHelpers/Format/RawViewHelper.php
- Neos.FluidAdaptor/Classes/ViewHelpers/Format/StripTagsViewHelper.php
- Neos.FluidAdaptor/Classes/ViewHelpers/Security/CsrfTokenViewHelper.php
- Neos.FluidAdaptor/Classes/ViewHelpers/Uri/ResourceViewHelper.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/CaseViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/StripTagsViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Security/CsrfTokenViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Uri/ResourceViewHelperTest.php
Adds compilation and static rendering to a couple of ViewHelpers
that were either easy to change or used quite a lot.
The modified ViewHelpers should all render faster in all scenarios.
> FEATURE: ViewHelper compilation for increased speed

- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Target/FileSystemSymlinkTarget.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Target/FileSystemTarget.php
`unpublishFile()` in the `FileSystemTarget` does not remove symlinks
correctly, thus the method is adjusted in the `FileSystemSymlinkTarget`
to check using `is_link()` instead of `file_exists()`.
Fixes #972
> BUGFIX: Check for link in unpublishFile()

- Neos.Utility.Files/Classes/Files.php
> TASK: Add PHP 7.0 scalar type hints to method arguments and return types

- Neos.Flow/Classes/Error/AbstractExceptionHandler.php
This change hide the "Open Data/Logs/Exceptions/20170617104058ccd0f5.txt
for a full stack trace." link for the nexted exceptions.
> TASK: Output a single link to the exception file in CLI

- Neos.Eel/Classes/Helper/StringHelper.php
- Neos.Eel/Tests/Unit/Helper/StringHelperTest.php
This pull request add the Eel String helper `String.pregMatchAll`
> FEATURE: Add Eel String helper pregMatchAll

- Neos.FluidAdaptor/Classes/ViewHelpers/FlashMessagesViewHelper.php
> TASK: Make FlashMessageViewHelper use `hasTitle()` to check for existence

- Neos.Flow/Classes/Core/Bootstrap.php
Use correct version within Bootstrap.php
> BUGFIX: Fix FLOW_VERSION_BRANCH value

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/PackageManagement.rst
Adjusted documentation to current status quo regarding package
management and third party packages.
Fixes: #751
> TASK: Describe use of 3rd party packages correctly in docs

- Neos.Flow/Classes/Http/Client/CurlEngine.php
`Neos\Flow\Http\Client\CurlEngine` will now attach cookies to an outgoing request.
> FEATURE: Add cookie support on curl request

- .travis.yml
- Neos.Flow/Classes/Persistence/Generic/LazySplObjectStorage.php
- Neos.Flow/Tests/Unit/Mvc/Controller/ActionControllerTest.php
- Neos.Flow/Tests/Unit/Mvc/Routing/IdentityRoutePartTest.php
- Neos.Flow/Tests/Unit/Persistence/Generic/DataMapperTest.php
- Neos.Flow/Tests/Unit/Persistence/Generic/SessionTest.php
- Neos.Flow/Tests/Unit/Validation/ValidatorResolverTest.php
- Neos.FluidAdaptor/Tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/FlashMessagesViewHelperTest.php
This enables PHP 7.2 testing on Travis CI, fixes a few unit tests that broke and adjust one actual code error.
> TASK: Adjust Flow to work with PHP 7.2

- Neos.Flow/Classes/Core/ApplicationContext.php
- Neos.Flow/Classes/Package.php
- Neos.Flow/Classes/Package/Package.php
- Neos.Flow/Classes/Security/Authorization/InterceptorResolver.php
- Neos.Flow/Classes/Security/RequestPatternResolver.php
- Neos.Flow/Tests/Unit/Security/Authorization/InterceptorResolverTest.php
- Neos.Flow/Tests/Unit/Security/RequestPatternResolverTest.php
Some small improvements in the code base that should all improve
runtime speed.
> TASK: Code and speed optimizations

- Neos.Flow/Classes/ObjectManagement/Exception/CannotBuildObjectException.php
- Neos.Flow/Classes/ObjectManagement/Exception/UnknownObjectException.php
- Neos.Flow/Classes/ObjectManagement/ObjectManager.php
- Neos.Flow/composer.json
- composer.json
PSR-11 is the container interface and it is rather easy to make the
ObjectManager compatible with it, so here we are.
> FEATURE: Make ObjectManager compatible to PSR-11

- Neos.Eel/Classes/Helper/FileHelper.php
- Neos.Eel/Tests/Unit/Helper/FileHelperTest.php
Adds a basic FileHelper to allow reading files and getting
file metadata from EEL.
> FEATURE: FileHelper to read files and metadata about files

- Neos.FluidAdaptor/Classes/ViewHelpers/DebugViewHelper.php
Fixes a typo that was introduced in #1036
> BUGFIX: Fix typo in `DebugViewHelper`

- Neos.Flow/Tests/Behavior/Features/Bootstrap/SecurityOperationsTrait.php
This allows for defining users by identifier and then using them in behavioral test cases
> FEATURE: Allow authentication of specified user in behavior tests

- Neos.Utility.Unicode/Classes/TYPO3/Flow/Utility/Unicode/Functions.php
- Neos.Utility.Unicode/Tests/Unit/FunctionsTest.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Component/TrustedProxiesComponent.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Uri.php
- TYPO3.Flow/Tests/Unit/Http/Component/TrustedProxiesComponentTest.php
- TYPO3.Flow/Tests/Unit/Http/UriTest.php
> BUGFIX: IPv6 support in Uri, parse_url and TrustedProxiesComponent

- Neos.Flow/Documentation/TheDefinitiveGuide/PartII/Validation.rst
- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Internationalization.rst
- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/ModelViewController.rst
- Neos.Flow/Documentation/TheDefinitiveGuide/PartV/FluidAdaptorViewHelperReference.rst
fixes a part of https://github.com/neos/neos-development-collection/issues/2010
> BUGFIX: update documentation

- Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php
As constructor arguments and injections should not be automatically
resolved when either the whole class or the respective method has
autowiring false, we should skip any processing of those as early
as possible to avoid any unnecessary or even wrong checks for
possible autowiring
This should improve compile performance slightly and prevent errors
with constructors of singletons with autowiring false.
Those would previously throw an exception due to non autowired
constructor arguments..
> TASK: Object configuration skips objects with autowiring false

- Neos.Flow/Tests/Unit/ResourceManagement/ResourceTypeConverterTest.php
This shows that #542 is no longer relevant.
Resolves #542
> TASK: Add test for empty resource upload

- Neos.Flow/Classes/Error/ProductionExceptionHandler.php
Simplifies the production exception message to match the current CI more.
> TASK: Update production exception page

- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Resource.php
- TYPO3.Flow/Migrations/Mysql/Version20180622074421.php
- TYPO3.Flow/Migrations/Postgresql/Version20180622074422.php
This adds an index to the `PersistentResource` table drastically
improving the performance of `ResourceManager::getResourceBySha1()`
calls (= public API).
> Improve performance of ResourceManager::getResourceBySha1()

- composer.json
> BUGFIX: Add ext-xml as composer dependency

- Neos.Utility.MediaTypes/Scripts/updatemediatypes.php
Updates the script to automatically update the mime-types to also include pkpass (iOS Wallet) and provides a unique place to add other formats if needed.
> TASK: Add support for pkpass mime type

- Neos.Flow.Log/Classes/Backend/JsonFileBackend.php
- Neos.Flow.Log/Tests/Unit/Backend/JsonFileBackendTest.php
This logger writes the log message as JSON which is easy parsable for log processing
but also readable.
> FEATURE: Logger backend to write the log in JSON format

- Neos.FluidAdaptor/Classes/View/Exception/InvalidSectionException.php
- Neos.FluidAdaptor/Classes/View/Exception/InvalidTemplateResourceException.php
Reverts neos/flow-development-collection#1348
> Revert "BUGFIX: Extend the expected exceptions for missing templates and sections"

- Neos.FluidAdaptor/Tests/Functional/View/Fixtures/TestTemplateWithFormField.txt
- Neos.FluidAdaptor/Tests/Functional/View/StandaloneViewTest.php
> TASK: Verify that FormViewHelpers outside of Form work

- TYPO3.Flow/Tests/Unit/I18n/LocaleTypeConverterTest.php
> TASK: Fix phpunit coverage reports

- Neos.Flow/Classes/Http/RequestHandler.php
This should increase performance in cases version output is configured
(which is the default) as that requires accessing the composer.lock
file and parsing for the respective version.
> TASK: Make HTTP application token static compiled

- TYPO3.Flow/Resources/Private/Installer/Distribution/Defaults/.editorconfig
> BUGFIX: Correct naming for setting

- Neos.FluidAdaptor/Classes/ViewHelpers/Form/TextareaViewHelper.php
This adds support for the maxlength property to TextArea.
Related to https://github.com/neos/form/issues/87
> FEATURE: Add maxlength to TextArea view helper

- Neos.Flow/Classes/Aop/Builder/ProxyClassBuilder.php
- Neos.Flow/Classes/Http/Client/InternalRequestEngine.php
- Neos.Flow/Classes/Mvc/Dispatcher.php
- Neos.Flow/Classes/ObjectManagement/ObjectManager.php
- Neos.Flow/Classes/ObjectManagement/Proxy/Compiler.php
- Neos.Flow/Classes/Package/PackageManager.php
- Neos.Flow/Classes/Persistence/Doctrine/Service.php
- Neos.Flow/Classes/Reflection/ReflectionService.php
- Neos.Flow/Classes/ResourceManagement/ResourceManager.php
Removes settings injection when the settings are actually not used
and keep only necessary subset of settings and not all of it.
> TASK: Economize use of settings

- Neos.Flow/Classes/Aop/Builder/ProxyClassBuilder.php
- Neos.Flow/Classes/Cache/CacheManager.php
- Neos.Flow/Classes/Cli/SlaveRequestHandler.php
- Neos.Flow/Classes/Command/DoctrineCommandController.php
- Neos.Flow/Classes/Http/ContentStream.php
- Neos.Flow/Classes/I18n/Xliff/Service/XliffReader.php
- Neos.Flow/Classes/Mvc/Controller/ActionController.php
- Neos.Flow/Classes/Mvc/Dispatcher.php
- Neos.Flow/Classes/Mvc/Routing/Router.php
- Neos.Flow/Classes/Persistence/Doctrine/PersistenceManager.php
- Neos.Flow/Classes/Persistence/Doctrine/Query.php
- Neos.Flow/Classes/ResourceManagement/ResourceManager.php
- Neos.Flow/Classes/ResourceManagement/ResourceTypeConverter.php
- Neos.Flow/Classes/Security/Aspect/LoggingAspect.php
- Neos.Flow/Classes/Security/Context.php
- Neos.Flow/Classes/Session/Aspect/LoggingAspect.php
- Neos.Flow/Classes/Session/Session.php
Enriches log messages of severity > debug with log environment.
> TASK: Enrich log messages with environment

- Neos.Flow/Classes/Cli/ConsoleOutput.php
- Neos.Flow/Tests/Unit/Cli/ConsoleOutputTest.php
Fix description for ``select`` method and return type an therefore tests for ``askAndValidate``.
> BUGFIX: Fix console helpers

- Neos.Utility.ObjectHandling/Classes/TypeHandling.php
- Neos.Utility.ObjectHandling/Tests/Unit/TypeHandlingTest.php
This reverts commit f92ec4094b70dc74ba44afec8052bc2ca05e6b11, reversing
changes made to a00a7512f50a3806857223e8d61d69c86232cdb2.
See https://github.com/neos/flow-development-collection/pull/1442
> BUGFIX: Revert merge #1442 from neos/albe-typehandling-fix

- Neos.Flow/Classes/Http/Client/Browser.php
> BUGFIX: Fix browser to be able to handle relative URLs

- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Validation.rst
This is a direct copy of https://github.com/neos/flow/pull/19 - thanks @kaystrobach
> TASK: add pushResult for Property example

- Neos.Flow/Configuration/Settings.yaml
Fixes: #1529
**What I did**
Added new annotation tags used by Doctrine to ignoredTags list
Just run any Flow command.
**Checklist**
> BUGFIX: add `template` and `psalm` to ignoredTags

- TYPO3.Flow/Configuration/Settings.yaml
Fixes #1529 by adjusting the configuration.
> BUGFIX: Ignore template/psalm annotations

- Neos.Flow/Classes/Command/RoutingCommandController.php
> BUGFIX: Replace missing getResolvedUriPath in getPathCommand

- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Validation.rst
> TASK: Add documentation info for validation groups

- Neos.Flow/Classes/Command/RoutingCommandController.php
- Neos.Flow/Classes/Error/AbstractExceptionHandler.php
- Neos.Flow/Classes/Http/AbstractMessage.php
- Neos.Flow/Classes/Http/Helper/ResponseInformationHelper.php
- Neos.Flow/Classes/Http/Response.php
- Neos.Flow/Classes/Mvc/ActionResponse.php
- Neos.Flow/Classes/Mvc/Controller/AbstractController.php
- Neos.Flow/Classes/Mvc/Controller/ActionController.php
- Neos.Flow/Classes/Mvc/Controller/ControllerContext.php
- Neos.Flow/Classes/Mvc/DispatchComponent.php
- Neos.Flow/Classes/Mvc/Dispatcher.php
- Neos.Flow/Classes/Mvc/Response.php
- Neos.Flow/Classes/Mvc/ResponseDeprecationTrait.php
- Neos.Flow/Tests/Unit/Mvc/Controller/AbstractControllerTest.php
- Neos.Flow/Tests/Unit/Mvc/DispatchComponentTest.php
- Neos.FluidAdaptor/Classes/Core/Widget/AbstractWidgetViewHelper.php
- Neos.FluidAdaptor/Classes/Core/Widget/AjaxWidgetComponent.php
- Neos.FluidAdaptor/Classes/View/StandaloneView.php
- Neos.FluidAdaptor/Tests/Unit/Core/Widget/AjaxWidgetComponentTest.php
- Readme.rst
Just to run tests, do not merge
> WIP: Merge 5.3 to master

- Neos.Flow/Classes/I18n/Service.php
Do not merge, just for testing
> WIP: Merge 4.3 into 5.0

- Neos.Cache/Classes/Frontend/AbstractFrontend.php
- Neos.Flow/Classes/I18n/Service.php
Do not merge, just for testing
> WIP: Merge 5.0 into  5.1

- Neos.Cache/Classes/Frontend/AbstractFrontend.php
- Neos.Flow/Classes/I18n/Service.php
Do not merge, just for testing
> WIP: Merge 5.1 into 5.2

- Neos.Cache/Classes/Frontend/AbstractFrontend.php
- Neos.Flow/Classes/I18n/Service.php
- Neos.Flow/Classes/Package/PackageManager.php
- Neos.Flow/Classes/Security/Aspect/LoggingAspect.php
- Neos.Flow/Classes/Session/Aspect/LoggingAspect.php
Do not merge, just for testing
> WIP: Merge 5.2 into 5.3

- Neos.Flow/Tests/Functional/Security/Authentication/Provider/PersistedUsernamePasswordProviderTest.php
> BUGFIX: Fix non-deterministic functional test

- Neos.Flow/Classes/Aop/Pointcut/PointcutFilterComposite.php
- Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php
- Neos.Flow/Classes/ObjectManagement/ObjectManager.php
- Neos.Flow/Tests/Unit/Aop/Pointcut/PointcutFilterCompositeTest.php
Instead of getSettingsByPath(…) use settings injection or the
ConfigurationManager to get settings.
> !!! TASK: Remove ObjectManager.getSettingsByPath()

- .github/stale.yaml
Add Stalebot configuration.
See https://discuss.neos.io/t/rfc-introduce-stale-bot-on-dev-collections/4371
> TASK: Add StaleBot configuration file

- Neos.Flow/Classes/I18n/AbstractXmlParser.php
Workaround for https://bugs.php.net/bug.php?id=62577
Fixes #1598
> BUGFIX: Avoid problem loading files in SimpleXML

- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Http.rst
> TASK: Fix formatting of note

- Neos.Flow/composer.json
- Neos.Utility.MediaTypes/Tests/Unit/MediaTypesTest.php
- Neos.Utility.MediaTypes/composer.json
- Neos.Utility.ObjectHandling/Classes/ObjectAccess.php
- Neos.Utility.ObjectHandling/Classes/TypeHandling.php
- Neos.Utility.ObjectHandling/Tests/Unit/ObjectAccessTest.php
- Neos.Utility.ObjectHandling/Tests/Unit/TypeHandlingTest.php
- composer.json
See https://github.com/neos/flow-development-collection/pull/1584
> TASK: Tweak dev dependencies

- Neos.Flow/Classes/Core/Booting/Scripts.php
See https://github.com/neos/flow-development-collection/pull/1391 and
the comment https://github.com/neos/flow-development-collection/pull/1391#issuecomment-502635553
> BUGFIX: Remove exception import breaking compile step

- Neos.Kickstarter/Resources/Private/Generator/Controller/CommandControllerTemplate.php.tmpl
> BUGFIX: Escape curly braces in CommandController template

- Neos.Utility.Arrays/Tests/Unit/ArraysTest.php
- Neos.Utility.ObjectHandling/composer.json
The more restrictive require-dev dependency here was holding back and causing issues when installing master.
> TASK: Bring dependencies in line with main dependencies

- Neos.Eel/Classes/Helper/StringHelper.php
- Neos.FluidAdaptor/Classes/View/TemplatePaths.php
> TASK: Fix some findings of the psalm static code analysis

- Neos.Flow/Classes/Cli/CommandManager.php
- Neos.Flow/Tests/Unit/Cli/CommandManagerTest.php
Relax command name resolution in order to make
it easier to find commands.
Resolves: #1691
> FEATURE: Improve CLI command name resolution

- psalm-baseline.xml
Removes fixed errors from the psalm baseline.
> TASK: Update psalm baseline

- Neos.Flow/Configuration/Development/Settings.yaml
- Neos.Flow/Configuration/Testing/Settings.yaml
> BUGFIX: Logs properly split per application context

- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Http.rst
Adjust regarding `ComponentContext`, immutability and added http components.
> TASK: Some slight adjustments to the Http documentation

- Neos.Flow/Classes/Command/CacheCommandController.php
See https://github.com/neos/flow-development-collection/pull/1046
> TASK: Make use of `hasTitle` method to check message title existence

- .github/main.workflow
Just type `/rebase` in the comment and this workflow will attempt a rebase.
Uses https://github.com/cirrus-actions/rebase
> FEATURE: Allow rebasing PR via comment

- Neos.Flow/Configuration/Settings.yaml
- Neos.Flow/Resources/Private/Schema/Settings/Neos.Flow.object.schema.yaml
This is needed to be able to generate a XSD schema for the TYPO3 Fluid default ViewHelpers.
Depends on #1638
> TASK: Include TYPO3Fluid for reflection

- Neos.Flow/Documentation/TheDefinitiveGuide/PartI/ConceptsOfModernProgramming.rst
sensible = vernünftig
sensitive = sensibel
> TASK: Update ConceptsOfModernProgramming.rst

- Neos.Cache/Classes/Backend/AbstractBackend.php
- Neos.Cache/Classes/Backend/ApcuBackend.php
- Neos.Cache/Classes/Backend/BackendInterface.php
- Neos.Cache/Classes/Backend/FileBackend.php
- Neos.Cache/Classes/Backend/FreezableBackendInterface.php
- Neos.Cache/Classes/Backend/MemcachedBackend.php
- Neos.Cache/Classes/Backend/MultiBackend.php
- Neos.Cache/Classes/Backend/NullBackend.php
- Neos.Cache/Classes/Backend/PdoBackend.php
- Neos.Cache/Classes/Backend/RedisBackend.php
- Neos.Cache/Classes/Backend/RequireOnceFromValueTrait.php
- Neos.Cache/Classes/Backend/SimpleFileBackend.php
- Neos.Cache/Classes/Backend/TaggableBackendInterface.php
- Neos.Cache/Classes/Backend/TaggableMultiBackend.php
- Neos.Cache/Classes/Backend/TransientMemoryBackend.php
- Neos.Cache/Classes/Frontend/AbstractFrontend.php
- Neos.Cache/Classes/Frontend/CacheEntryIterator.php
- Neos.Cache/Classes/Frontend/FrontendInterface.php
- Neos.Cache/Classes/Frontend/PhpFrontend.php
- Neos.Cache/Classes/Frontend/StringFrontend.php
- Neos.Cache/Classes/Frontend/VariableFrontend.php
- Neos.Cache/Classes/Psr/Cache/CacheFactory.php
- Neos.Cache/Classes/Psr/Cache/CacheItem.php
- Neos.Cache/Classes/Psr/Cache/CachePool.php
- Neos.Cache/Classes/Psr/SimpleCache/SimpleCache.php
- Neos.Cache/Classes/Psr/SimpleCache/SimpleCacheFactory.php
- Neos.Cache/Tests/Unit/Backend/AbstractBackendTest.php
- Neos.Flow/Classes/Persistence/Doctrine/Logging/SqlLogger.php
- Adds missing type declarations, especially void types.
- The remaining methods are implementing the untyped PSR interface
> TASK: Add type declaration to Neos cache classes

- Neos.Flow/Configuration/Settings.Http.yaml
> BUGFIX: Fix position for SessionRequestComponent

- Neos.Flow/Classes/Command/DoctrineCommandController.php
- Neos.Flow/Classes/Command/RoutingCommandController.php
- Neos.Flow/Classes/I18n/EelHelper/TranslationParameterToken.php
- Neos.Flow/Classes/I18n/Translator.php
- Neos.Flow/Classes/Mvc/Controller/MvcPropertyMappingConfigurationService.php
- Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php
- Neos.Flow/Classes/Package/PackageManager.php
- Neos.FluidAdaptor/Classes/ViewHelpers/Form/SelectViewHelper.php
- Neos.FluidAdaptor/Classes/ViewHelpers/Validation/IfHasErrorsViewHelper.php
- Neos.Kickstarter/Classes/Service/GeneratorService.php
- Neos.Utility.Unicode/Classes/TextIterator.php
- psalm-baseline.xml
Please have a look at the single commits where I documented what I have done and why.
> TASK: Improve code / fix psalm issues

- Neos.Http.Factories/Classes/ServerRequestFactory.php
> TASK: Use "Flow/FLOW_VERSION_BRANCH" as default user agent

- Neos.Flow/Classes/Aop/Pointcut/PointcutMethodNameFilter.php
- Neos.Flow/Classes/Persistence/Doctrine/DataTypes/JsonArrayType.php
- Neos.Flow/Classes/Persistence/Doctrine/DataTypes/ObjectArray.php
- Neos.Flow/Classes/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php
- Neos.Flow/Classes/Property/TypeConverter/AbstractTypeConverter.php
- Neos.Flow/Classes/Property/TypeConverter/ObjectConverter.php
- Neos.Flow/Classes/Property/TypeConverter/PersistentObjectConverter.php
- psalm-baseline.xml
This corrects some false positives
> TASK: Set psalm baseline

- Readme.rst
This should help people onboard for contribution, as it is not obvious that one has to install the development-distribution and the information for that is not that easy to find and then very elaborate. This is the perfect place to have it in a TL;DR style
> TASK: Mention the basic development setup steps in the readme

- Neos.Flow/Classes/Http/RequestHandler.php
This allows sending large files to the browser without running into memory issues, by using `fpassthrough` with disabled output buffering.
Related to #1800
> BUGFIX: Handle file streams in response better

- Neos.Flow/Documentation/TheDefinitiveGuide/PartII/Controller.rst
**What I did**
Removed unnecessary colons that broke the markup.
~**How I did it**~
~**How to verify it**~
**Checklist**
~- [ ] Code follows the PSR-2 coding style~
~- [ ] Tests have been created, run and adjusted as needed~
> BUGFIX: Remove unnecessary colons

- Neos.Flow/Classes/Validation/Validator/AggregateBoundaryValidator.php
> TASK: Use isUninitializedProxy() (adjust to #1611)

- Neos.Eel/Classes/Helper/ArrayHelper.php
- Neos.Eel/Tests/Unit/Helper/ArrayHelperTest.php
> FEATURE: Add array ksort eel helper

- Neos.Eel/Classes/Helper/StringHelper.php
- Neos.Eel/Tests/Unit/Helper/StringHelperTest.php
> FEATURE: Add optional limit parameter to String.pregReplace

- Readme.rst
Adds badges on commits sine release, % open issues and resolution
time to Readme.rst.
> TASK: Add some more statistics badges

- Neos.Flow/Classes/Mvc/Routing/Dto/UriConstraints.php
Related to https://github.com/neos/flow-development-collection/issues/1866
> BUGFIX: Fix string offset access syntax with curly braces

- Neos.Cache/Classes/Backend/PdoBackend.php
**What I did**
* Use the table names from the configuration in all places.
> BUGFIX: PDOBackend doesn't respect configuration

- psalm-baseline.xml
The new errors look like false positives, at least so much I wouldn't
risk a change for them…
> TASK: Update psalm-baseline.xml

- Neos.Flow/Classes/Http/Client/Browser.php
- Neos.Flow/Classes/Http/Helper/UploadedFilesHelper.php
> BUGFIX: Browser correctly builds uploaded files from form

- Neos.Flow/Classes/Core/Booting/Scripts.php
- Neos.Flow/Classes/Log/ThrowableStorage/FileStorage.php
Reverts neos/flow-development-collection#1920
> Revert "BUGFIX: Fix output of request and response in throwable storage"

- Neos.Flow/Classes/Core/Booting/Scripts.php
- Neos.Flow/Classes/Log/ThrowableStorage/FileStorage.php
Follow up to: #1920 which was reverted in #1925
> BUGFIX: Fix output of request and response in throwable storage

- Neos.FluidAdaptor/Classes/ViewHelpers/Format/Nl2brViewHelper.php
Use correct description of the nl2br functionality from php.net/nl2br
Resolves #1831
> TASK: Use correct description for nl2br ViewHelper

- Neos.Flow/Classes/Command/PackageCommandController.php
- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/PackageManagement.rst
> Task: Update documentation on packages and activating/deactivating

- Neos.Eel/Classes/Helper/FileHelper.php
The EEL helper determines if a file exists. This is eg helpful, if file like templates are generated, and should only be rendered, if the template file exists, for example for generated favicon templates like this:
```
prototype(Neos.Neos:Page) {
head.favicons = Neos.Fusion:Template {
resource = ${'resource://' + site.context.currentSite.siteResourcesPackageKey + '/Private/Templates/Page/Favicon.html'}
templatePath = ${this.resource}
@if.fileExists = ${File.exists(this.resource)}
}
```
> FEATURE: Add EEL Helper File.exists(filename)

- Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php
Follow-up to #1967 together with #1969
> BUGFIX: Use argument for factory if static factory method is configured

- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Http.rst
Start of fixing/improving the HTTP docs to match actual implementation as of Flow 6.0 / PSR-7
> TASK: Bring HTTP docs up to date with actual implementation

- Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php
> BUGFIX: Fix typo

- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Configuration.rst
> TASK: Change used variable TRUE into true

- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/ObjectManagement.rst
> FIX: Fixing documentation to give real working examples of disabling auto wiring

- Neos.Eel/Classes/ProtectedContext.php
- Neos.Eel/Classes/Utility.php
- Neos.Eel/Tests/Unit/AbstractEvaluatorTest.php
- Neos.Eel/Tests/Unit/ProtectedContextTest.php
- Neos.Flow/Classes/Aop/Builder/ProxyClassBuilder.php
- Neos.Flow/Classes/Aop/Pointcut/RuntimeExpressionEvaluator.php
- Neos.Flow/Classes/Error/Debugger.php
- Neos.Flow/Classes/ObjectManagement/Proxy/Compiler.php
- Neos.Flow/Classes/Persistence/AbstractPersistenceManager.php
- Neos.Flow/Classes/Persistence/Doctrine/PersistenceManager.php
- Neos.Flow/Classes/Persistence/Generic/PersistenceManager.php
- Neos.Flow/Classes/Persistence/PersistenceManagerInterface.php
- Neos.Flow/Classes/Property/PropertyMappingConfiguration.php
- Neos.Flow/Classes/ResourceManagement/ResourceManager.php
- Neos.Flow/Classes/ResourceManagement/ResourceRepository.php
- Neos.Flow/Classes/ResourceManagement/Target/FileSystemSymlinkTarget.php
- Neos.Flow/Classes/ResourceManagement/Target/FileSystemTarget.php
- Neos.Flow/Classes/Security/Authentication/Provider/PersistedUsernamePasswordProvider.php
- Neos.Flow/Classes/Security/Authorization/FilterFirewall.php
- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Eel.rst
- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Internationalization.rst
- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Persistence.rst
- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Security.rst
- Neos.Flow/Resources/Private/Translations/ja/ValidationErrors.xlf
- Neos.Flow/Tests/Functional/Persistence/PersistenceTest.php
- Neos.Flow/Tests/Unit/Persistence/Doctrine/PersistenceManagerTest.php
- Neos.Flow/Tests/Unit/Property/PropertyMappingConfigurationTest.php
Those old wordings have no place and they are also objectively worse than the replacements.
> TASK: Improve wording of include/exclude concepts where possible

- Neos.Flow/Classes/Command/RoutingCommandController.php
> BUGFIX: Use serverRequestFactory to create server request with path

- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Security.rst
When I stumbled over "anonyous", I had a closer look at the hole section. I'm not a native speaker though.
> Fix some typos

- Neos.Flow/Documentation/TheDefinitiveGuide/PartII/ModelAndRepository.rst
This adds basic documentation for how to properly model unidirectional OneToMany relations in Flow and slightly extends the "Getting Started" guide.
Related to #2053
> TASK: Add documentation to model unidirectional OneToMany and ManyToMany

- Neos.Flow/Classes/Configuration/ConfigurationSchemaValidator.php
- Neos.Flow/Resources/Private/Translations/en/Main.xlf
**What I did**
added translation to schemaValidationError
added translator and translation unit
> FEATURE: add translation to SchemaValidationException

- Neos.Flow/Tests/Functional/I18n/Cldr/Reader/DatesReaderTest.php
- Neos.Flow/Tests/Functional/I18n/Cldr/Reader/NumbersReaderTest.php
- Neos.Flow/Tests/Functional/I18n/Cldr/Reader/PluralsReaderTest.php
Adds functional tests to Plurals, Number and DateReader
See #2116
> TASK: Add tests for reader objects

- Neos.Flow/Tests/Functional/I18n/Cldr/Reader/PluralsReaderTest.php
> TASK: Use correct class names in PluralsReaderTest

- Neos.Flow/Documentation/TheDefinitiveGuide/PartII/ModelAndRepository.rst
Follow-up to #2056 and #2053 which makes use of the remapped ``OneToMany`` annotation for Post->Comment relation in the starting guide.
> TASK: Update starting guide for #2056

- Neos.Flow/Classes/ResourceManagement/Target/FileSystemTarget.php
Use early returns instead of nested conditions.
> TASK: Simplify getRelativePublicationPathAndFilename

- Neos.FluidAdaptor/Classes/ViewHelpers/Form/SelectViewHelper.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Form/SelectViewHelperTest.php
> BUGFIX: Handle array options in SelectViewHelper

- .travis.yml
Related to #2188
t.b.d. should this land in all supported branches to make builds potentially faster?
> TASK: Use composer 2 in travis build

- Neos.Cache/composer.json
- Neos.Eel/composer.json
- Neos.Error.Messages/composer.json
- Neos.Flow.Log/composer.json
- Neos.Flow/composer.json
- Neos.FluidAdaptor/composer.json
- Neos.Kickstarter/composer.json
- Neos.Utility.Arrays/composer.json
- Neos.Utility.Files/composer.json
- Neos.Utility.MediaTypes/composer.json
- Neos.Utility.ObjectHandling/composer.json
- Neos.Utility.OpcodeCache/composer.json
- Neos.Utility.Pdo/composer.json
- Neos.Utility.Schema/composer.json
- Neos.Utility.Unicode/composer.json
- composer.json
Require PHP 7.3 in composer.json
> TASK: Raise minimum PHP version to 7.3

- Neos.Flow/Classes/Security/Authorization/Privilege/Entity/Doctrine/SqlFilter.php
- Neos.Flow/composer.json
- composer.json
- psalm-baseline.xml
- psalm.xml
> TASK: Update to vimeo/psalm 4.1

- Neos.Flow/Classes/Composer/InstallerScripts.php
See https://github.com/neos/flow-development-collection/pull/2188#pullrequestreview-534660935
> BUGFIX: Fix use of deprecated method called in exception handling

- Neos.Flow/Classes/Annotations/ValueObject.php
- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Persistence.rst
Follow-up to #1718 with promised documentation
> TASK: Update documentation for default embedded ValueObjects

- Neos.Flow/Classes/Persistence/Doctrine/Service.php
> BUGFIX: Auto-generate DoctrineMigrations folder if needed

- Neos.Flow/Documentation/TheDefinitiveGuide/PartII/Requirements.rst
> TASK: Reflect minimum required PHP version in documentation

- Neos.FluidAdaptor/composer.json
- composer.json
See https://github.com/neos/flow-development-collection/issues/2260
> TASK: Restrict typo3fluid/fluid to versions before signature change

- Neos.Flow/Classes/Reflection/ClassReflection.php
- Neos.Flow/Classes/Reflection/Exception/ClassLoadingForReflectionFailedException.php
- Neos.Flow/Classes/Reflection/ReflectionService.php
> TASK: Show a helpful message when a class still implements ComponentInterface

- Neos.Flow/Classes/Core/Bootstrap.php
Updates `MINIMUM_PHP_VERSION` and `FLOW_VERSION_BRANCH` PHP constants
> Update MINIMUM_PHP_VERSION and FLOW_VERSION_BRANCH constants

- Neos.Flow/Classes/Core/Bootstrap.php
> BUGFIX: Update MINIMUM_PHP_VERSION constant

- composer.json
Reverts neos/flow-development-collection#2324
> Revert "TASK: Fix composer dependencies"

- Neos.Flow/Migrations/Code/Version20201207104500.php
Fixes the migration added with #2320
> BUGFIX: Fix invalid regex in migration

- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Http.rst
> TASK: Extend HTTP documentation by additional middleware examples

- Neos.Flow/Classes/Command/DoctrineCommandController.php
- Neos.Flow/Classes/Persistence/Doctrine/Service.php
- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Persistence.rst
See https://github.com/neos/flow-development-collection/issues/2244
> TASK: Further adjustments to Doctrine Migrations integration

- Neos.Flow/Documentation/TheDefinitiveGuide/PartV/ChangeLogs/700.rst
Order by !!!FEATURE, FEATURE, !!!BUG, BUG, !!!TASK, TASK and remove unhelpful "Apply fixes from StyleCI".
Also removed the Easy injection of request feature and it's revert.
> TASK: Redact the 7.0 changelog

- Neos.Flow/Classes/Command/CacheCommandController.php
- Neos.Flow/Classes/Persistence/QueryInterface.php
- Neos.Flow/Classes/Property/TypeConverter/AbstractTypeConverter.php
- Neos.Flow/Classes/Property/TypeConverter/ArrayConverter.php
- Neos.Flow/Classes/Property/TypeConverter/ArrayFromObjectConverter.php
- Neos.Flow/Classes/Property/TypeConverter/BooleanConverter.php
- Neos.Flow/Classes/Property/TypeConverter/CollectionConverter.php
- Neos.Flow/Classes/Property/TypeConverter/DateTimeConverter.php
- Neos.Flow/Classes/Property/TypeConverter/FloatConverter.php
- Neos.Flow/Classes/Property/TypeConverter/IntegerConverter.php
- Neos.Flow/Classes/Property/TypeConverter/MediaTypeConverter.php
- Neos.Flow/Classes/Property/TypeConverter/ObjectConverter.php
- Neos.Flow/Classes/Property/TypeConverter/PersistentObjectConverter.php
- Neos.Flow/Classes/Property/TypeConverter/PersistentObjectSerializer.php
- Neos.Flow/Classes/Property/TypeConverter/SessionConverter.php
- Neos.Flow/Classes/Property/TypeConverter/StringConverter.php
- Neos.Flow/Classes/Property/TypeConverter/TypedArrayConverter.php
- Neos.Flow/Classes/Property/TypeConverter/UriTypeConverter.php
- Neos.Flow/Classes/Property/TypeConverterInterface.php
- Neos.Flow/Classes/ResourceManagement/Collection.php
- Neos.Flow/Classes/ResourceManagement/CollectionInterface.php
- Neos.Flow/Classes/ResourceManagement/PersistentResource.php
- Neos.Flow/Classes/ResourceManagement/ResourceTypeConverter.php
- Neos.Flow/Classes/ResourceManagement/Storage/FileSystemStorage.php
- Neos.Flow/Classes/ResourceManagement/Storage/PackageStorage.php
- Neos.Flow/Classes/ResourceManagement/Storage/StorageInterface.php
- Neos.Flow/Classes/ResourceManagement/Storage/WritableFileSystemStorage.php
- Neos.Flow/Classes/ResourceManagement/Storage/WritableStorageInterface.php
- Neos.Flow/Tests/Unit/Core/Booting/ScriptsTest.php
This only fixes a couple of docblock typehints primarily in the ResourceManagement and TypeConverters.
> TASK: Fix some docblock typehints

- Neos.Flow/composer.json
- composer.json
This is a backport of #2251
Resolves #2248
> TASK: Allow to install with composer 2.0

- Neos.Flow/Classes/I18n/Translator.php
- Neos.Flow/Classes/Persistence/Doctrine/PersistenceManager.php
- Neos.Flow/Classes/Persistence/Doctrine/QueryResult.php
- Neos.Flow/Classes/Persistence/Doctrine/Repository.php
- Neos.Flow/Classes/Persistence/Generic/PersistenceManager.php
- Neos.Flow/Classes/Persistence/PersistenceManagerInterface.php
- Neos.Flow/Classes/Persistence/QueryResultInterface.php
- Neos.Flow/Classes/Persistence/Repository.php
- Neos.Flow/Classes/Persistence/RepositoryInterface.php
- Neos.Flow/Classes/ResourceManagement/ResourceRepository.php
Fixed a couple of places where null was a possible return value, but wasn't added to the docblock typehint.
> TASK: Fix incomplete docblock typehints

- Neos.Eel/Classes/Helper/ArrayHelper.php
- Neos.Eel/Tests/Unit/Helper/ArrayHelperTest.php
related to: https://github.com/neos/neos-development-collection/issues/3287
> FEATURE: Expose array_values() in Array eelHelper

- Neos.Flow/Classes/Security/Authentication/Token/BearerToken.php
- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Security.rst
Adds the bearer token class to extract a rfc6750 bearer token
from the HTTP header.
> FEATURE: Add rfc6750 bearer token

- Neos.Flow/Classes/Mvc/View/JsonView.php
* Some code cleanup
* usage of NullCoalescing
* Hardening the JSON encoding
no further functional changes
> TASK: JsonView code cleanup

- .github/workflows/build.yml
Followup for #1960 adjusted to our GH actions builds. Needs to check the pushing, as that probably doesn't work as expected yet.
> TASK: Automatically update psalm baseline after merge

- Neos.Flow/Classes/Http/Client/CurlEngine.php
- Neos.Flow/Classes/Http/Helper/ResponseInformationHelper.php
- Neos.Flow/Classes/Http/Helper/UploadedFilesHelper.php
- Neos.Flow/Classes/Mvc/ActionResponse.php
- Neos.Flow/Classes/Security/Authentication/EntryPoint/HttpBasic.php
- Neos.Flow/Classes/Security/Authentication/EntryPoint/WebRedirect.php
- Neos.Flow/Tests/Unit/Http/Helper/ResponseInformationHelperTest.php
> TASK: Replace deprecated Guzzle functions

- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Configuration.rst
I've added an updated documentation for the new configuration loader implemeted via https://github.com/neos/flow-development-collection/pull/2449
> FEATURE: Update documentation for new configuration loader

- Neos.Flow/Documentation/TheDefinitiveGuide/PartII/ModelAndRepository.rst
New pull request with new base on 6.3 for pull request #2589.
> BUGFIX: Fix missing initialization for tags and missing imports

- Neos.Flow/Classes/Http/Client/CurlEngine.php
- Neos.Flow/Classes/Http/InvalidArgumentException.php
- Neos.Flow/Tests/Functional/Http/Client/CurlEngineTest.php
> Throw exception if headers are set through curl options.

- Neos.Flow/Documentation/TheDefinitiveGuide/PartV/ReleaseNotes/730.rst
> TASK: Add release notes for 7.3 [skip ci]

- .github/FUNDING.yml
We use the organization wide .github repository and can share the FUNDING.yml with all repositories.
We updated the URL already.
> TASK: Delete FUNDING.yml

- Neos.Flow/Documentation/TheDefinitiveGuide/PartV/ChangeLogs/730.rst
The automatic changelog from the Jenkins job was just a GitHub comparison link for detailed information.
This adds the output from our changelog script.
> BUGFIX: Add correct changelog for 7.3.0

- Neos.Flow/Classes/ObjectManagement/Proxy/ObjectSerializationTrait.php
- Neos.Flow/Tests/Functional/Persistence/PersistenceTest.php
Reverts neos/flow-development-collection#2517
> Revert "BUGFIX: Do not remove related entities during persistence"

- Neos.Flow/Classes/Mvc/ActionRequest.php
solves #2655
I dont know what branch to target, so i go for master. But it should be compatible with 6.3 too. What do you say?
> TASK code cleanup ActionRequest

- Neos.Flow/Classes/ObjectManagement/ObjectManagerInterface.php
- Neos.Flow/Classes/Property/PropertyMappingConfiguration.php
- Neos.Flow/Classes/Security/Authorization/Privilege/AbstractPrivilege.php
Adds/fixes type hints and annotations to satisfy static code analysis
> Adjust types where necessary for the ESCR

- Neos.Eel/Classes/Helper/ArrayHelper.php
- Neos.Eel/Tests/Unit/Helper/ArrayHelperTest.php
- Neos.Flow/Classes/Http/Client/InternalRequestEngine.php
- Neos.Flow/Classes/Mvc/Controller/ActionController.php
- Neos.Flow/Tests/Functional/Mvc/ActionControllerTest.php
> 7.0 - just to test upmerges - ignore

- Neos.Flow/Classes/Persistence/AllowedObjectsContainer.php
Adds PHP typehints to some places.
> !!!TASK: Add method argument and return type hints

- Neos.Flow/Classes/Command/DatabaseCommandController.php
- Neos.Flow/Classes/Core/LockManager.php
- Neos.Utility.ObjectHandling/Classes/ObjectAccess.php
- Neos.Utility.ObjectHandling/Tests/Unit/Fixture/ProxiedClassWithPrivateProperty.php
- Neos.Utility.ObjectHandling/Tests/Unit/ObjectAccessTest.php
> 7.0 - test upmerges do not merge

- Neos.Flow/Classes/Command/DatabaseCommandController.php
- Neos.Flow/Classes/Core/LockManager.php
- Neos.Flow/Classes/Mvc/Routing/Dto/UriConstraints.php
- Neos.Flow/Tests/Unit/Mvc/Routing/Dto/UriConstraintsTest.php
- Neos.Utility.ObjectHandling/Classes/ObjectAccess.php
- Neos.Utility.ObjectHandling/Tests/Unit/Fixture/ProxiedClassWithPrivateProperty.php
- Neos.Utility.ObjectHandling/Tests/Unit/ObjectAccessTest.php
> 7.1  - test upmerges do not merge

- Neos.Flow/Classes/Command/DatabaseCommandController.php
- Neos.Flow/Classes/Core/LockManager.php
- Neos.Flow/Classes/Mvc/Routing/Dto/UriConstraints.php
- Neos.Flow/Tests/Unit/Mvc/Routing/Dto/UriConstraintsTest.php
- Neos.Utility.ObjectHandling/Classes/ObjectAccess.php
- Neos.Utility.ObjectHandling/Tests/Unit/Fixture/ProxiedClassWithPrivateProperty.php
- Neos.Utility.ObjectHandling/Tests/Unit/ObjectAccessTest.php
> 7.2 - test upmerges do not merge

- Neos.Flow/Classes/Command/DatabaseCommandController.php
- Neos.Flow/Classes/Core/LockManager.php
- Neos.Flow/Classes/Mvc/Routing/Dto/UriConstraints.php
- Neos.Flow/Tests/Unit/Mvc/Routing/Dto/UriConstraintsTest.php
- Neos.Utility.ObjectHandling/Classes/ObjectAccess.php
- Neos.Utility.ObjectHandling/Tests/Unit/Fixture/ProxiedClassWithPrivateProperty.php
- Neos.Utility.ObjectHandling/Tests/Unit/ObjectAccessTest.php
> 7.3  - test upmerges do not merge

- Neos.Flow/Classes/Persistence/AbstractPersistenceManager.php
- Neos.Flow/Classes/Persistence/Doctrine/PersistenceManager.php
- Neos.Flow/Classes/Persistence/PersistenceManagerInterface.php
- Neos.Flow/Classes/Security/Authentication/Provider/PersistedUsernamePasswordProvider.php
> !!! TASK: Remove whitelistObject() / add allowObject() in PersistenceManagerInterface

- Neos.Cache/Classes/Psr/Cache/CacheItem.php
- Neos.Cache/Classes/Psr/Cache/CachePool.php
- Neos.Cache/Classes/Psr/SimpleCache/SimpleCache.php
- Neos.Cache/composer.json
- Neos.Flow/composer.json
- composer.json
Raise the versions of the cache interfaces and add type annotations.
- psr/simple-cache: "^1.0" > "^3.0",
- psr/cache: "^1.0" > "^2.0",
> !!!TASK: Update PSR Cache and SimpleCache Interfaces to 3.0

- Neos.Flow.Log/Classes/Psr/Logger.php
- Neos.Flow.Log/composer.json
- Neos.Flow/Tests/Unit/Error/AbstractExceptionHandlerTest.php
- Neos.Flow/Tests/Unit/Persistence/Doctrine/PersistenceManagerTest.php
- Neos.Flow/composer.json
- composer.json
This updates the psr/log interface to version 2.0 with type hints.
> !!!TASK: Update psr/log to 2.0

- .github/workflows/build.yml
- Neos.Cache/composer.json
- Neos.Flow/Classes/Reflection/ReflectionService.php
- Neos.Flow/composer.json
- Neos.Utility.Arrays/composer.json
- Neos.Utility.Files/composer.json
- Neos.Utility.MediaTypes/composer.json
- Neos.Utility.Schema/composer.json
- Neos.Utility.Unicode/composer.json
- composer.json
This reenables the lowest dependencies build that was deactivated with https://github.com/neos/flow-development-collection/commit/cf8d28d87af78e71cc7cb6656172dfe6904f37db#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R38-R41
> TASK: Reenable lowest dependencies build

- Neos.Cache/Classes/Psr/Cache/CacheFactory.php
- Neos.Eel/Classes/Context.php
- Neos.Eel/Classes/FlowQuery/OperationResolver.php
- Neos.Eel/Classes/FlowQuery/OperationResolverInterface.php
- Neos.Flow/Classes/Configuration/RouteConfigurationProcessor.php
- Neos.Flow/Classes/Http/UriTemplate.php
- Neos.Flow/Classes/I18n/AbstractXmlParser.php
- Neos.Flow/Classes/I18n/Xliff/V12/XliffParser.php
- Neos.Flow/Classes/ObjectManagement/Configuration/Configuration.php
- Neos.Flow/Classes/Property/TypeConverter/DateTimeConverter.php
- Neos.Flow/Classes/ResourceManagement/Target/FileSystemTarget.php
- Neos.Flow/Classes/Security/Authorization/Privilege/Entity/Doctrine/ConditionGenerator.php
- Neos.Flow/Classes/Security/Authorization/Privilege/Entity/Doctrine/PropertyConditionGenerator.php
- Neos.Flow/Classes/Security/Authorization/Privilege/Entity/EntityPrivilegeInterface.php
- Neos.Flow/Classes/Security/Authorization/Privilege/Method/MethodPrivilegePointcutFilter.php
- Neos.Flow/Classes/Session/CookieEnabledInterface.php
- Neos.Flow/Scripts/Migrations/Git.php
- Neos.Flow/Tests/Functional/Aop/Fixtures/SubClassOfAbstractClass.php
For good measure… 🤷‍♂️
This doesn't change anything, but it's cleaner.
> TASK: Tweak some @param annotations

- Neos.Flow/composer.json
- composer.json
As explained in https://github.com/symfony/polyfill#design
> TASK: Add versions to symfony/polyfill replacements

- Neos.Flow/Classes/Mvc/Routing/Dto/UriConstraints.php
> BUGFIX: Uri must not be constructed with empty string

- Neos.Eel/Classes/Helper/MathHelper.php
- Neos.Flow/Classes/Http/Cookie.php
- Neos.Flow/Classes/Http/Headers.php
- Neos.Flow/Classes/Session/Aspect/LoggingAspect.php
- Neos.Flow/Classes/Validation/Validator/CountValidator.php
- Neos.Utility.Arrays/Classes/PositionalArraySorter.php
Use type casting instead of slower function calls.
> TASK: Use type casting instead of intval/floatval

- Neos.Flow/Configuration/Settings.DocTools.yaml
See https://github.com/neos/doctools/pull/4
**Checklist**
> TASK: Adjust Neos.DocTools settings
