neos/flow-development-collection

- .composer.json
Adds the template composer.json used to autogenerate
the joined composer.json for this joined repository.
Releases: master, 3.0, 2.3
> [TASK] Add composer manifest template

- TYPO3.Flow/Classes/TYPO3/Flow/Error/AbstractExceptionHandler.php
The ExceptionHandler includes the Flow Exception class directly by using
the relative path. This might not work out if at some point we decide to
combine autoloaded classes as this class is autoloaded and the relative
path will be wrong then. Using the FLOW_PATH_FLOW constant we can easily
construct a full path to the file.
Change-Id: I1154677458afc1633994158479fe8b3f18763d90
Releases: master
> [TASK] Include Exception class in ExceptionHandler with full path

- TYPO3.Flow/Classes/TYPO3/Flow/Security/Context.php
In TYPO3/Flow/Security/Context class SessionManagerInterface should be injected
to follow the Objects configuration. This breaks projects where a custom
SessionManager is implemented and switched using Objects configuration.
However in the Unit test for security context SessionManagerInterface is mocked.
PS: This issue is already handled in Flow 3.0 so need a HotFix for 2.3
Fixes: FLOW-380
Releases: 2.3
> [BUGFIX] SecurityContext does not inject SessionManagerInterface

- TYPO3.Flow/Configuration/Settings.yaml
As Flow 2.3 still uses a blacklist approach for reflection and proxybuilding the neos composer plugin needs to be excluded instead of the composer installers package.
> [BUGFIX] Remove neos composer plugin from reflection

- TYPO3.Eel/Readme.rst
- TYPO3.Flow/Readme.rst
- TYPO3.Fluid/Readme.rst
- TYPO3.Kickstart/Readme.rst
This adds a Readme.rst to each package, so that the read-only subplit
repositories have a readme file for GitHub to show and for the users
to read.
> [TASK] Add Readme.rst files for individual packages

- CodeOfConduct.rst
This adds a reStructuredText version of the Contributor Covenant
code of conduct, to make it clear the project is governed by that.
See also http://contributor-covenant.org/version/1/2/0/
> [TASK] Add Code of Conduct

- TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php
Improves the exception output in development context when a command executed
in a subprocess fails with fatal error. Previously the actual error could only
be found by looking in the system log or in some cases by running a CLI command.
Resolves: FLOW-382
> [TASK] Improve exception output for subprocesses failing with fatal error

- TYPO3.Flow/Tests/Unit/I18n/LocaleCollectionTest.php
The MIT change had introduced a stray block comment end marker.
> [BUGFIX] Fix a syntax error caused by a broken file header

- TYPO3.Flow/Classes/TYPO3/Flow/Object/DependencyInjection/ProxyClassBuilder.php
Reduce usage of ``ReflectionService`` during Runtime by compiling a list
of transient properties and variable type declarations into proxy classes
to be used during serialisation of objects.
Relates: NEOS-1294
> [TASK] Compile list of properties information into proxy classes

- TYPO3.Flow/Classes/TYPO3/Flow/Configuration/ConfigurationSchemaValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Storage/PackageStorage.php
- TYPO3.Flow/Classes/TYPO3/Flow/Utility/Files.php
- TYPO3.Flow/Migrations/Code/Version20140511114700.php
- TYPO3.Flow/Scripts/Migrations/AbstractMigration.php
- TYPO3.Flow/Scripts/Migrations/Manager.php
This implements ``Files::readDirectoryRecursively`` in a way
that is using a stack instead of recursive calls. This prevents
``too many files open errors`` as only one directory will be
opened at a time.
Additionally adds a new method ``getRecursiveDirectoryGenerator()``
if you don't need an array of files to manipulate but just want to
iterate the results. This reduces memory consumption.
Usage of ``readDirectoryRecursively`` was changed to
``getRecursiveDirectoryGenerator`` were possible.
Speed should also slightly improve in both cases.
Change-Id: I8b8928e7e5c7449c38d3cff4121fc682e1b4c5a9
Releases: master
> [FEATURE] Refactor Files::readDirectoryRecursively

- TYPO3.Fluid/Classes/TYPO3/Fluid/ViewHelpers/IfViewHelper.php
This adds another example for the if view helper inline syntax,
explaining the format for conditions when using comparisons.
Releases: 2.3, 3.0, master
> [TASK] Add example for if view helper inline syntax

- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/AnnotatedIdEntity.php
The auto-generated name of a sequence exceeds the maximum length, is
truncated and thus duplicates an already existing name in the schema.
This is solved by manually giving a name to the sequence.
This bug affects only PostgreSQL and is triggered by a functional test
fixture.
> [BUGFIX] Fix functional test by explicitly naming sequence

- TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/ResourceManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Streams/ResourceStreamWrapper.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Streams/StreamWrapperAdapter.php
- TYPO3.Flow/Tests/FunctionalTestCase.php
The ``ResourceManager`` creates a bunch of objects and iterates over
the whole resource configuration on initialization. In some cases this
initialisation might not even be necessary so with this change we defer
it until the information is really needed.
> [TASK] Lazily initialize ResourceManager

- TYPO3.Flow/Classes/TYPO3/Flow/Aop/Pointcut/RuntimeExpressionEvaluator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package.php
As the runtime expressions are generated while evaluating the
method privileges in the ``MethodPrivilegePointcutFilter`` both
should be saved at the same point in time, so instead of saving
the expressions via lifecycle methods they are now saved on the
same signal as the method permission cache entry.
This can prevent race conditions that might happen between
writing the permission cache and the expression cache.
> [BUGFIX] Bind expression storing closer to privilege data

- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ObjectAccess.php
- TYPO3.Flow/Tests/Unit/Package/PackageManagerTest.php
- TYPO3.Flow/Tests/Unit/Reflection/Fixture/Model/EntityWithDoctrineProxy.php
- TYPO3.Flow/Tests/Unit/Reflection/ObjectAccessTest.php
This change adjusts ObjectAccess to use getTypeForValue() instead of
get_class() so Doctrine proxies are handled correctly.
> [BUGFIX] Make ObjectAccess use TypeHandling (FLOW-397)

- TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php
- TYPO3.Flow/Classes/TYPO3/Flow/Core/Bootstrap.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package.php
- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/PersistenceManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/PersistenceManagerInterface.php
- TYPO3.Flow/Configuration/Objects.yaml
Removes initialization of the PersistenceManager from the bootstrap as
that can be done lazily. For backwards compatibility the
``PersistenceManagerInterface::initialize`` method was removed but is
still called when available. All existing code should work as expected
but it is advisable to switch to using ``initializeObject`` instead. As
the ``initialize`` method will no longer be called starting from the next
major Flow version.
A separate breaking change will remove the backwards compatibility layer.
Before ``persistAll`` is called after a runtime run finished it is first
checked if there is a ``PersistenceManagerInterface`` instance registered
because otherwise  an unnecessary initialization of the PersistenceManager
would be triggered.
> [TASK] Defer initialization of PersistenceManager

- TYPO3.Eel/Classes/TYPO3/Eel/Helper/DateHelper.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Headers.php
- TYPO3.Flow/Classes/TYPO3/Flow/I18n/Formatter/DatetimeFormatter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Mvc/Routing/IdentityRoutePart.php
- TYPO3.Flow/Classes/TYPO3/Flow/Mvc/View/JsonView.php
- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/DataTypes/JsonArrayType.php
- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Generic/Backend/AbstractBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Generic/Query.php
- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Generic/Session.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/IntegerConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/StringConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Utility/Now.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/DateTimeRangeValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/DateTimeValidator.php
- TYPO3.Fluid/Classes/TYPO3/Fluid/ViewHelpers/Format/DateViewHelper.php
- TYPO3.Fluid/Classes/TYPO3/Fluid/ViewHelpers/GroupedForViewHelper.php
Since Flow requires PHP 5.5 it should use and support the ``\DateTimeInterface``.
With support for it the ``Now`` class can extend from ``DateTimeImmutable`` to
prevent changes to the singleton throughout a request.
> [TASK] Use DateTimeInterface in Flow

- apigen.yml
The todo and deprecated options have been deprecated in favour of the
annotation-groups feature. This adjusts apigen.yml to comply.
> [TASK] Remove use of deprecated apigen options

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Persistence.rst
- TYPO3.Flow/Tests/Functional/Persistence/PersistenceTest.php
The object we assign in the test is `Persistence\Fixtures\CommonObject`,
containing a protected property. Doctrine stores `object` as
`serialize()`d PHP data in a text column. Which doesn't work on
PostgreSQL, since the string is truncated at the first `null` byte,
used in the serialised data to mark the protected property.
The official fix is to use a custom datatype if you need it, for the
test I decided to skip it if on PostgreSQL.
Related: FLOW-396
> [BUGFIX] Skip commonObjectIsPersistedAndIsReconstituted() on PgSQL

- TYPO3.Flow/Documentation/index.rst
This fixes pointers to the forum and chat and some mentions of "TYPO3" in the index.rst of the Flow documentation.
> [TASK] Fixing the most obvious references to TYPO3

- TYPO3.Flow/Classes/TYPO3/Flow/Command/RoutingCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Client/InternalRequestEngine.php
- TYPO3.Flow/Classes/TYPO3/Flow/Mvc/Routing/Router.php
- TYPO3.Flow/Classes/TYPO3/Flow/Mvc/Routing/RoutingComponent.php
- TYPO3.Flow/Tests/Functional/Mvc/RoutingTest.php
- TYPO3.Flow/Tests/Unit/Mvc/Routing/RouterTest.php
- TYPO3.Flow/Tests/Unit/Mvc/Routing/RoutingComponentTest.php
The Router should be able to initialize configured routes lazily
except when explicitly told not to do so.
This change allows the Router to get the configuration directly
from the ``ConfigurationManager`` if no other routing configuration
exists. If some routing configuration was set, this is used.
Fixes: FLOW-192
Fixes: FLOW-205
> [BUGFIX] Initialize Router lazily

- TYPO3.Flow/Classes/TYPO3/Flow/Core/ClassLoader.php
Since 2787b2a3216deb188c4cd1c9b2b823e6e3a10da3 Flow creates a
map for available proxy classes stored in ``AvailableProxyClasses.php``
within the temporary directory.
The ``ClassLoader`` failed to include that file though when run in
a nested Application Context. That is fixed with this change.
> [BUGFIX] Fix lookup path for ``AvailableProxyClasses.php``

- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Target/FileSystemSymlinkTarget.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Target/FileSystemTarget.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Target/TargetInterface.php
Currently some methods use the Collection class instead of the
CollectionInterface.
> [BUGFIX] Use CollectionInterface in resource management

- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/PdoBackend.php
`$this->has($entryIdentifier)` returns false for expired cache entries
which leads to duplicate key violations. Remove existing entries,
including expired ones, before creating new cache entry.
Fixes: FLOW-193
Releases: master, 3.0, 2.3
> [BUGFIX] Make sure expired cache entries get deleted in PdoBackend

- TYPO3.Flow/Classes/TYPO3/Flow/Utility/Algorithms.php
- TYPO3.Flow/composer.json
- composer.json
Uses php-uuid extension if available and otherwise the
https://github.com/ramsey/uuid library which is a complete
solution for generating and working with UUIDs.
> [FEATURE] Use more sophisticated UUID generator

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/Service.php
Backport from 9823ae980e803 (Author: Laurent Cherpit @lcherpit )
Currently the check for the existence of migration files is delegated
to the doctrine/migration third party library.
The behavior has changed and an exception is thrown if the folder doesn't
exist. To not let the third party library handle that and to prevent this,
the check is done upstream in Flow.
> [BUGFIX] Check if migrations exist before trying to register them

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Persistence.rst
When implementing a Doctrine filter the proxy building of Flow can cause problems. This change documents this and explains a solution.
> [TASK] Document issues with final SQLFilter constructor

- TYPO3.Flow/Tests/Unit/Http/RequestTest.php
- TYPO3.Flow/Tests/Unit/Persistence/Generic/DataMapperTest.php
- TYPO3.Flow/Tests/Unit/Persistence/Generic/PersistenceManagerTest.php
This fixes some notices about undefined array indexes with PHPUnit,
removes some (wrong) risky test warnings and brings one skipped and one
incomplete test back to life.
> [TASK] Some tweaks to unit tests

- TYPO3.Flow/Classes/TYPO3/Flow/Resource/ResourceTypeConverter.php
The given source can either be an array or a string and in both cases
an empty value would signify a value that cannot be converted and
probably stems from an empty input. In this case the converter
should return null immediately, otherwise it will go on with processing
the empty value and eventually ends up in returning a conversion error
which would be wrong.
> [BUGFIX] ResourceTypeConverter should return null for empty source

- TYPO3.Flow/Classes/TYPO3/Flow/Log/Logger.php
When logException() is used to log an exception that has been caught,
the log will still say "Uncaught exception". This is misleading.
> [TASK] Fix misleading log message in logException()

- TYPO3.Flow/Classes/TYPO3/Flow/Http/Request.php
- TYPO3.Flow/Tests/Unit/Http/RequestTest.php
This fixes an issue resulting in wrong rendered URLs if Flow is accepting
request from a load balancer or proxy which is accessed via https
externally, sends the X-Forwarded-Proto header to Nginx but does not
specify the X-Forwarded-Port header.
For example, a load balancer (for example Google HTTP/HTTPS load
balancer) is accessible via https and terminates SSL. The load balancer
communicates with Nginx via http on port 80. Google only sends the
X-Forwarded-Proto header ("https") but not the port. URLs, for example
in an action URI of a form, are rendered wrongly.
An expected URL would be https://example.com/foo.html, however, the
rendered URL is https://example.com:80/foo.html
This change changes the behavior in `Request` so that if the
X-Forwarded-Proto header is set, but the …
> [BUGFIX] Set correct request port if X-Forwarded-Proto is set

- TYPO3.Flow/Classes/TYPO3/Flow/Command/HelpCommandController.php
- TYPO3.Flow/Configuration/Settings.yaml
- TYPO3.Flow/composer.json
This change introduces a new setting which allows developers to display
a custom application name and version in the ./flow help commands and
potentially elsewhere. For example, ./flow will display "Neos" and the
version number of the Neos package, when the command is run in a Neos
distribution.
The setting does not refer to the application name directly, but to a
package key. The specified package's meta data (Composer manifest) is
used to determine the application name and version. Since it is best
practice to use the "description" property of the Composer manifest for
specifying the application name, that field is used as the application
name in ./flow too (see also comments by Jordi at
https://github.com/composer/composer/issues/1140).
> [FEATURE] Setting for application name

- TYPO3.Flow/Resources/Private/Schema/Settings/TYPO3.Flow.core.schema.yaml
This adds the recently added ``applicationPackageKey`` setting to the YAML
schema for the core settings, to avoid false error reports when using
``configuration:validate``.
> [TASK] Add ``applicationPackageKey`` to settings schema

- TYPO3.Flow/Classes/TYPO3/Flow/Security/Authentication/AuthenticationProviderManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Security/Context.php
Otherwise getRoles() might act on the wrong value of the overall
authentication status stored in the authentication manager.
> [BUGFIX] Roles are refreshed after setting authentication status

- TYPO3.Flow/Resources/Private/Installer/Distribution/Defaults/Web/_Resources/.htaccess
The ``.htaccess`` file in ``Web/_Resources`` contained php_flag,
which requires the ``mod_php`` module to be installed. Since FastCGI
setups don't have this module, an invalid command error is thrown.
In this change the flag is wrapped in ``IfModule`` tags to avoid that error,
and the ``SetHandler`` statement is added a second time in a ``Files`` tag
to avoid it being overwritten in certain cases.
> [BUGFIX] FastCGI compatible resources ``.htaccess`` file

- TYPO3.Flow/Classes/TYPO3/Flow/Error/AbstractExceptionHandler.php
- TYPO3.Flow/Classes/TYPO3/Flow/Error/DebugExceptionHandler.php
- TYPO3.Flow/Classes/TYPO3/Flow/Error/ExceptionHandlerInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Error/ProductionExceptionHandler.php
This change adjusts the non-public API of Flow's exception handling to
fit the new exception types in PHP 7 (`\Throwable`). It does not yet
take advantage of the new possibilities, but rather makes the existing
code compatible with both, PHP 5 and PHP 7.
> [TASK] Adjust exception handling for compatibility with PHP 7

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Aspect/PersistenceMagicAspect.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/TestValueObjectWithTransientProperties.php
When injecting properties into a value object, an exception was thrown that
a closure is tried to be serialized. This was due to the hash generation
in PersistenceMagicAspect only skipping properties that are annotated as
transient.
This change makes the value hash generation resort to the class schema instead
of directly iterating all properties, since the class schema is already focused
on persistence relevant properties and hence contains no injected properties.
> [BUGFIX] Ignore injected properties for value hash generation

- TYPO3.Flow/Classes/TYPO3/Flow/Configuration/ConfigurationManager.php
- TYPO3.Flow/Tests/Unit/Configuration/ConfigurationManagerTest.php
It can happen that the cache include file was already removed
by a subrequest before getting to the unlink. The warning that
would follow can safely be ignored.
> [BUGFIX] Ignore race condition on cached Configuration include

- TYPO3.Flow/Classes/TYPO3/Flow/Object/DependencyInjection/ProxyClassBuilder.php
This change contains a fix in the "related entities" proxy class code
which makes the generated code PHP 7 compatible.
Related: NEOS-1608
> [TASK] Adjust generated proxy code to PHP 7 uniform variable syntax

- TYPO3.Flow/Classes/TYPO3/Flow/Aop/Pointcut/PointcutExpressionParser.php
- TYPO3.Flow/Tests/Unit/Aop/Pointcut/PointcutExpressionParserTest.php
The pointcut designator „methodTaggedWith“ has been deprecated for 2.0 already.
This removes some leftover reference to this method.
Fixes: FLOW-417
> [BUGFIX] Remove references to „methodTaggedWith“ pointcut designator

- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/SimpleFileBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/CoreCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php
- TYPO3.Flow/Classes/TYPO3/Flow/Core/Bootstrap.php
- TYPO3.Flow/Classes/TYPO3/Flow/Core/ClassLoader.php
- TYPO3.Flow/Classes/TYPO3/Flow/Core/LockManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Security/Authentication/AuthenticationProviderManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Security/Context.php
- TYPO3.Flow/Configuration/Settings.yaml
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartII/Configuration.rst
- TYPO3.Flow/Resources/Private/Schema/Settings/TYPO3.Flow.utility.schema.yaml
- TYPO3.Flow/Tests/Behavior/Features/Bootstrap/SubProcess/SubProcess.php
- TYPO3.Flow/Tests/Unit/Security/Authentication/AuthenticationProviderManagerTest.php
As soon as an authentication process completes, roles might
have changed. Therefore we have to reinitialize the roles
first level cache in the security context.
Fixes: FLOW-415
> [BUGFIX] Refresh first level roles cache on authentication

- TYPO3.Flow/Classes/TYPO3/Flow/Utility/Lock/FlockLockStrategy.php
The FlockLockStrategy creates files to apply the lock on.
These files reside in the temporary folder but are never cleaned
on releasing the Lock that means the amount of files in this folder
will increase over time unless the folder is cleared manually.
Additionally cleans the code a bit and reduces chance of race
conditions while creating the lock.
> [BUGFIX] FlockLockStrategy should clean up lock files

- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/SimpleFileBackend.php
The ``generateTemporaryPathAndFilename`` is no longer in use
since the introduction of locking last year, it can therefore
be removed.
> [TASK] Remove unused method in SimpleFileBackend

- TYPO3.Flow/Classes/TYPO3/Flow/Http/Headers.php
Formally a Cookie header should consist of semi-colon separated pairs
of ``key=value`` but some clients might sent invalid cookie headers
resulting in a notice raised when there was no equals sign to split a
pair on.
> Prevent invalid Cookie pairs from raising errors

- .travis.yml
- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/DataTypes/JsonArrayType.php
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Persistence.rst
The `JsonArrayType` in Flow inherits from the same type in Doctrine DBAL.
That type uses the `json` format, which is not comparable in PostgreSQL,
something that leads to issues if you want to use `DISTINCT` in a query.
Starting with PostgreSQL 9.4 the `jsonb` type is available, and the DB
knows how to compare it, making distinct queries possible.
Neos uses that, so the easiest way to fix this is to always use `jsonb`
for our custom type. The downside: the minimum supported version is
raised to 9.4.
Related: FLOW-396
Related: NEOS-1627
> [BUGFIX] Use jsonb in JsonArrayType on PostgreSQL

- TYPO3.Flow/Classes/TYPO3/Flow/Utility/Lock/FlockLockStrategy.php
Prevents opening lock files twice, first in read then in
write mode. Only one open should happen if successful.
The change fixes that.
> [BUGFIX] Lock files shouldn't be opened twice

- .travis.yml
This uses a wrapper around the unit tests to handle an exit code of 139
as a non-error.
This happens when testing on Travis CI and while those error happen, we
cannot do much else about it.
> [TASK] Use wrapper for phpunit to catch segfaults

- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/FileBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/SimpleFileBackend.php
- TYPO3.Flow/Tests/Unit/Cache/Backend/FileBackendTest.php
The SimpleFileBackend did a check for maximum path length
on construction but reserved an arbitrary length of 23 for cache
entry identifiers. Many identifiers are longer though and so even
if the exception was not triggered cache entries could fail to be
written.
This change moves the check to after a failed cache writing attempt
to check against the actual cache entry path.
> [TASK] Adjust check for maximum path length

- TYPO3.Flow/composer.json
The Json column type is support in doctrine DBAL only from
version 2.5.0 onwards. The current dependencies allow
installing it but it won't happen automatically, this
change makes sure that dbal is installed in the right
version.
> [TASK] Add DBAL minimum version to make JSON type work

- TYPO3.Flow/Classes/TYPO3/Flow/Object/Proxy/ObjectSerializationTrait.php
Fixes a leftover place which didn't use the uniform variable syntax
and therefore caused notices with PHP7.
> [BUGFIX] Uniform variable syntax for proxy trait

- TYPO3.Flow/Classes/TYPO3/Flow/Utility/Now.php
This partially reverts ``6b1448d2c540d79e882f527449e05660bc5095e3``
which changed ``\TYPO3\Flow\Utility\Now`` to extend the
``DateTimeImmutable`` class introduced with PHP 5.5.
As this is potentially breaking this part of the change is reverted
and will be reintroduced as breaking change in the next major
version.
> [BUGFIX] Now extends DateTime for backwards compatibility

- TYPO3.Flow/Classes/TYPO3/Flow/Security/Account.php
- TYPO3.Flow/Classes/TYPO3/Flow/Security/Authentication/Provider/PersistedUsernamePasswordProvider.php
- TYPO3.Flow/Migrations/Mysql/Version20151110113650.php
- TYPO3.Flow/Migrations/Postgresql/Version20151110113651.php
- TYPO3.Flow/Tests/Functional/Security/Authentication/Provider/PersistedUsernamePasswordProviderTest.php
- TYPO3.Flow/Tests/Unit/Security/Authentication/Provider/PersistedUsernamePasswordProviderTest.php
To improve security, it is helpful to show the last successful authentication
and the failed authentication count since last successful authentication to the
user.
> [!!!][FEATURE] Monitor successful authentication date and failed authentications

- TYPO3.Flow/Classes/TYPO3/Flow/Utility/PositionalArraySorter.php
- TYPO3.Flow/Tests/Unit/Utility/PositionalArraySorterTest.php
When using the ``PositionalArraySorter`` one can position keys
relative to other keys with ``before/after <key>``.
But for the ``<key>`` only ``[a-zA-Z0-9]`` were allowed limiting the
functionality especially when dealing with package keys that contain
a dot.
This change adjusts the regular expression to allow any string to be
referenced.
Fixes: FLOW-422
> [BUGFIX] Support for special characters in ``PositionalArraySorter`` keys

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/EntityManagerFactory.php
- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php
- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/Service.php
- TYPO3.Flow/composer.json
- composer.json
Prevents segmentation faults caused by Doctrine.
Excludes support for ``EntityListeners`` annotation introduced for 3.0
> [TASK] Update ``doctrine/orm`` to 2.4 for PHP 7 compatibility

- TYPO3.Flow/Classes/TYPO3/Flow/Object/Configuration/Configuration.php
- TYPO3.Flow/Tests/Unit/Object/Configuration/ConfigurationTest.php
The Configuration class relied on type hints to enforce the validity
of user-supplied data. This was explicitly tested, so the assumption is,
this was supposed to be tested properly. An instanceof check is now used
and a proper exception is thrown (instead of a PHP error).
Along the way this fixes some failing unit tests on PHP 7, since the old
assertion in the tests no longer holds.
> [BUGFIX] Use instanceof instead of relying on typed parameter

- TYPO3.Flow/Classes/TYPO3/Flow/Utility/Lock/FlockLockStrategy.php
We check if the stat call in ``FlockLockStrategy`` returned false anyway and
can safely suppress the generated warning.
> [BUGFIX] Ignore warning on failed stat

- TYPO3.Flow/Classes/TYPO3/Flow/Utility/Lock/FlockLockStrategy.php
The ``FlockLockStrategy`` should at some point always be able
to aquire a lock even if it takes a while. But to prevent really
long running processes that interlock each other a natural
boundary to the amount of lock attempts is introduced.
The strategy will throw an exception after 10000 tries to aquire
the lock file. Depending on the results of random the maximum time
to reach this upper boundary is about 2 seconds.
> [TASK] Break after 10000 lock attempts

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Internationalization.rst
The documentation example for translating error messages has to use parameter 'id' instead of 'key'.
> BUGFIX: Fix documentation example

- TYPO3.Flow/Classes/TYPO3/Flow/Object/CompileTimeObjectManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/ObjectManager.php
Because the order of shutdown methods being executed by the Object
Manager is undetermined, it may happen that `shutdownObject()` methods
relying on an initialized security context will fail because that
context is not available anymore. Additionally, Flow's own shutdown
object methods might fail because security checks are still active
even though the security framework is not available anymore.
This change makes sure that
1. shutdown methods of any other than the Flow package are executed first
2. Flow's own shutdown methods are called last, and without security checks
Due to the special nature of the CompileTimeObjectManager
we need to call the shutdown as before, but security will not
be used during compile time.
> BUGFIX: Security context not available in shutdown lifecycle objects

- TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php
Windows SET command does not parse out quotes of the variable value but rather treats them as part of the value, which currently results in an error on windows since the fix for FLOW-381:
Flow could not create the directory
""C:/workspace/Flow/Data/Temporary"/Development/".
Note the extra quotes around the temporary base path.
This change fixes that by properly escaping the SET command arguments on windows by using escapeshellcmd instead of escapeshellarg.
FLOW-381 #comment Regression fix for compilation on Windows
> BUGFIX: Properly escape sub process variables on windows

- TYPO3.Flow/Classes/TYPO3/Flow/Http/AbstractMessage.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Request.php
- TYPO3.Flow/Tests/Unit/Http/RequestTest.php
Currently the ``Http\Request`` defaults to php://input for
content. This is good for a request coming in to Flow, but rather
error prone for outbound requests as it can lead to different behavior
depending if the Request is created during a GET, POST or even CLI
call. So sometimes outbound requests might work and other times they
won't work. This change adjusts the defaul to have the Request an
empty ``Content`` (body) and sets it to NULL (which will trigger the
fallback to php://input) just if the Request is created by using
``Request::createFromEnvironment()``
Resolves: FLOW-235
> TASK: Make Http\Request easier to use for outbound Requests

- TYPO3.Flow/Classes/TYPO3/Flow/Error/DebugExceptionHandler.php
The ``DebugExceptionHandler`` renders "more information" links
pointing to  wiki.typo3.org. This was never really used to document
exceptions and with the departure from the TYPO3 project this should
be removed. A possible replacement can be readded later.
FLOW-421 #close
> TASK: Remove typo3.org reference for exception codes

- TYPO3.Flow/Classes/TYPO3/Flow/Resource/ResourceManager.php
- TYPO3.Fluid/Classes/TYPO3/Fluid/ViewHelpers/Uri/ResourceViewHelper.php
- TYPO3.Fluid/Tests/Unit/ViewHelpers/Uri/ResourceViewHelperTest.php
This change introduces two new methods in the ResourceManager.
The method ``getPackageAndPathByPublicPath`` returns an array with package and
path. This method is useful to avoid duplication of this logic. The second method ``getPublicPackageResourceUriByPath`` is syntactic sugar.
This change also adapts the ``ResourceViewHelper`` to use the new methods.
> TASK: Add method to get public URI by path

- TYPO3.Flow/Classes/TYPO3/Flow/Error/Debugger.php
This change replaces the usage of ReflectionClass in the Debugger
class by ReflectionObject. This allows for debugging properties which
are set on the object during runtime but are not defined as property
on the class. Without this change those properties are ignored in the
var_dump command.
> TASK: Use ReflectionObject in the Debugger to dump dynamic properties

- TYPO3.Flow/Classes/TYPO3/Flow/Cli/CommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cli/CommandManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Cli/RequestBuilder.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/HelpCommandController.php
- TYPO3.Flow/Tests/Unit/Cli/CommandManagerTest.php
- TYPO3.Flow/Tests/Unit/Cli/RequestBuilderTest.php
- TYPO3.Flow/Tests/Unit/Mvc/Controller/CommandControllerTest.php
Instead of using the ReflectionService at runtime to determine
arguments for commands they will be compiled statically and just
read from the array. Additionally this was centralized into the
``CommandManager`` as ``CommandController``, ``RequestBuilder`` and
``CommandManager`` all fetched similar information from the
``ReflectionService``.
NEOS-1294
> TASK: Compile CommandController arguments statically

- TYPO3.Flow/Classes/TYPO3/Flow/Validation/ValidatorResolver.php
- TYPO3.Flow/Tests/Unit/Validation/ValidatorResolverTest.php
For cases where an entity A references entity B and B in turn
references A (as first property), the validator chain would not
validate the reference to A inside B, even though those might be
different instances.
This is due to the newly created ObjectValidator for B not being added
to the CollectionValidator inside A - so when B again visits A, the
returned validator collection is empty and hence not added to the
validator chain.
This change fixes that, by adding the new ObjectValidator to the chain
early, and only removing it later on, if it is still empty after all
properties being checked. This could potentially lead to a deeper
validator chain than would be necessary (cycle of empty ObjectValidators),
but should not break anything or degrade performance.
Fixes: FLOW-352
> [BUGFIX] Validator chain is built correctly for cyclic relations

- TYPO3.Flow/Tests/Behavior/Features/Bootstrap/SecurityOperationsTrait.php
If this is violated, very funny error will appear because proxy
classes have already been built without taking the new Policy.yaml
into account.
This change has been re-targeted for 3.0 from https://github.com/neos/flow-development-collection/pull/27
> [TASK] Behat: ensure that "Given I have the following policies" is executed first

- TYPO3.Flow/Classes/TYPO3/Flow/Core/LockManager.php
In the method "unlockSite" the order for unlocking a file is wrong. Under Windows you first have to flock/fclose and then unlink (otherwise the lockfile is locked by OS and can not be removed). Then you get in Context Production the Errormessage "Site is currently locked, exiting.". The above reordering will fix this.
> BUGFIX: Unlocking site breaks on Windows

- TYPO3.Flow/Classes/TYPO3/Flow/Object/Configuration/ConfigurationBuilder.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/DependencyInjection/ProxyClassBuilder.php
So far all constructor arguments were treated as autowired unless
configured otherwise. This can result in problems and one example
is seen with the constructor of ArrayObject starting from PHP 7.0.2.
Unfortunately PHP does not allow Reflection of built-in functions
arguments. This includes methods of built-in classes like ArrayObject.
This results in our ReflectionService to report null as default for
those arguments which will then be autowired. Since PHP 7.0.2 all three
arguments of the ArrayObject constructor are reported correctly by
Reflection but due to our autowiring the third argument will be given
as null in the proxy class which results in a fatal error.
The solution is to mark configured arguments that use the default or null
to be not autowired and do not give them to the …
> BUGFIX: Default constructor arguments only autowired if needed

- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Streams/ResourceStreamWrapper.php
- TYPO3.Flow/Tests/Functional/Resource/ResourceTest.php
- TYPO3.Flow/Tests/Unit/Resource/Streams/ResourceStreamWrapperTest.php
Trying to use file_get_contents("resource://yourhashhere") led to an exception in the StreamWrapper.
This fix addresses the issue by correctly setting the StreamWrapper handle to the opened resource.
Additionally a test is provided to demonstrate the problem.
FLOW-302 #close
> BUGFIX: ResourceStreamWrapper now saves handles for resource:// - URIs

- TYPO3.Flow/Classes/TYPO3/Flow/Aop/Builder/ProxyClassBuilder.php
The usage of method_exists() checks inside the proxy class code was wrong by checking
the existance on the parent class of $this, which might in some circumstances not be
the current proxy class (ie. when checking method was originally called from a doctrine proxy).
This change fixes the method_exists calls by using the get_parent_class() without
parameter. Also, the method_exists check is added to the remaining method checks, that
currently only rely on is_callable, which in turn is always true on hierarchies that implement
__call magic method.
> BUGFIX: AOP Proxies properly check method existance before upward delegation

- TYPO3.Eel/Classes/TYPO3/Eel/Helper/StringHelper.php
- TYPO3.Eel/Tests/Unit/Helper/StringHelperTest.php
In case the search string appeared multiple times in the haystack
startsWith would not correctly report the occurance at the beginning
as it used the same code as endsWith. This is now fixed by using
``mb_strpos`` instead ``mb_strrpos``.
FLOW-423 #close
> BUGFIX: StringHelper::startsWith broken with multiple occurance

- TYPO3.Flow/Classes/TYPO3/Flow/Command/HelpCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/PackageCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Composer/ComposerUtility.php
- TYPO3.Flow/Classes/TYPO3/Flow/Composer/Exception/MissingPackageManifestException.php
- TYPO3.Flow/Classes/TYPO3/Flow/Composer/InstallerScripts.php
- TYPO3.Flow/Classes/TYPO3/Flow/Composer/Utility.php
- TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php
- TYPO3.Flow/Classes/TYPO3/Flow/Core/ClassLoader.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/CompileTimeObjectManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/Package.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageFactory.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageManagerInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageOrderResolver.php
- TYPO3.Flow/Tests/Unit/Core/ClassLoaderTest.php
- TYPO3.Flow/Tests/Unit/Object/CompileTimeObjectManagerTest.php
- TYPO3.Flow/Tests/Unit/Package/PackageFactoryTest.php
- TYPO3.Flow/Tests/Unit/Package/PackageManagerTest.php
- TYPO3.Flow/Tests/Unit/Package/PackageOrderResolverTest.php
- TYPO3.Flow/Tests/Unit/Package/PackageTest.php
This is a major refactoring of the package management.
With this change the structure of the ``PackageStates`` file
is overhauled now using the composer key for consistency to
avoid problems if namespace or autoload information changes
as that would change the (Flow) package key.
Additionally makes the resolution mechanism for Flow package
keys more robust and stores additional metadata in the
``PackageStates.php`` to avoid loading all composer manifests
at runtime.
Furthermore the package loading order generation was improved by
using a more sophisticated algorithm to get the order right.
All the changes together lead to a noticeable speed improvement
in runtime situations.
Deactivating packages now results in the package being moved out
of regular package paths into an ``Inactive`` …
> !!!TASK: Refactor package management

- TYPO3.Flow/Classes/TYPO3/Flow/Composer/InstallerScripts.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageManager.php
In order to update package states when composer changes packages
the PackageManager must work with minimal dependencies.
To make that possible all neccessary initialisations are moved to
the constructor and ``InstallerScripts`` define necessary
constants.
> BUGFIX: InstallerScripts can run ``rescanPackages``

- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageManager.php
Missing refactoring after 30b326a9735c80cd88c0acebcde127c02d6a198b
Method getComposerPackageNameFromPackageKey was moved from PackageManager to ComposerUtility but method call was still pointing to PackageManager.
> BUGFIX: Fix missing refactoring

- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/UniqueEntityValidator.php
Run the given validator value through TypeHandling::getTypeForValue()
to make sure doctrine proxies are resolved to the actual domain
model type.
Resolves: FLOW-433
> BUGFIX: Resolve type in UniqueEntityValidator

- TYPO3.Flow/Classes/TYPO3/Flow/Security/Context.php
The example for usage of ``withoutAuthorizationChecks`` in the docblock
is wrong in as it shows variables used inside the closure as closure
arguments but that is impossible. Instead they must be added to the
closure context via ``use``.
> BUGFIX: Make withoutAuthorizationChecks example realistic

- TYPO3.Flow/Classes/TYPO3/Flow/Log/EarlyLogger.php
The ``EarlyLogger`` was explicitly meant for the ``PackageManager``
which is not using it anymore. Therefore the EarlyLogger is deprecated
and bound for removal in the next major Flow version.
To underline the fact that it was never meant for user land code the
``@api`` annotations were removed.
> TASK: Deprecate EarlyLogger

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php
- TYPO3.Flow/Tests/Functional/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriverTest.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/CompositeKeyTestEntity.php
Currently, the implementation of the FlowAnnotationDriver prevents
composite primary keys including an foreign entity reference to
work, as in the example of doctrine:
http://docs.doctrine-project.org/en/latest/tutorials/composite-primary-keys.html#identity-through-foreign-entities
This change adds the required mapping informations, which is only
a first step towards full composite key support.
FLOW-259 #close
> BUGFIX: Allow composite keys over foreign entities

- TYPO3.Flow/Classes/TYPO3/Flow/Core/Bootstrap.php
The ``requestHandlers`` property of the Bootstrap is used as an
array but is never initialized. For sake of cleanliness it should be.
> BUGFIX: Initialize Bootstrap::requestHandlers with empty array

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/PersistenceManager.php
When flushing fails with Doctrine, we try to reconnect and flush again,
to work around dropped connections.
If the disconnection was caused by a "real" error, the cause was lost.
This change logs the exception that caused the reconnection to ease
debugging.
> TASK: When reconnecting to DB, log preceding exception

- TYPO3.Flow/Tests/Functional/Http/Client/CurlEngineTest.php
This change uses www.neos.io instead of typo3.org for testing the CurlEngine.
> TASK: Change typo3.org reference to neos.io

- TYPO3.Flow/Classes/TYPO3/Flow/Http/Client/InternalRequestEngine.php
To correctly simulate a real http request, the internal request engine should clear the state
of the persistence manager after a request.
> TASK: InternalRequestEngine should clear persistence after request

- TYPO3.Flow/Classes/TYPO3/Flow/Command/PackageCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package.php
To mitigate problems with packages not being loaded while creating
proxies the ``package:rescan`` command now becomes a compile time 
command, so it must be called via ``typo3.flow:package:rescan``.
> TASK: The ``package:rescan`` command is callable without proxies

- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/PersistentObjectConverter.php
The identifier is unset from the submitted properties for Value Objects, because
they should use constructor arguments to be reconstituted. However, in forms
value objects are currently submitted by identifier, which will make property
mapping fail with an error.
This change fixes that by only unsetting the identifier if there are other
properties submitted.
> BUGFIX: Value objects can be property mapped when submitted by identifier only

- TYPO3.Flow/Classes/TYPO3/Flow/Command/PackageCommandController.php
The condition to check for a valid Flow package type in
the ``package:create`` command was not negated correctly and
so didn't allow creation of any flow package type.
This is now fixed and creation of packages works again.
> BUGFIX: package:create allows flow package typep

- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageManager.php
The deprecated package metadata can contain a type but we should
use it for generating a composer manifest only if the type was
actually set otherwise the given type should be used.
> BUGFIX: PackageManager only uses MetaData type if it was set

- TYPO3.Flow/Classes/TYPO3/Flow/Http/AbstractMessage.php
- TYPO3.Flow/Tests/Unit/Http/BrowserTest.php
With adding the `Content-Type` header to the automatic headers of a virtual browser, the request fails every time.
The given value is cast to an array by the `Http\Headers::set()` method. When setting this header in a `Header` (!) instance (`Http\AbstractMessage::setHeader()`) of the request, a string is expected especially for `Content-Type`, but an array is given.
`BrowserTest` extended especially for this header field.
FLOW-305 #close
> BUGFIX: 'Content-Type' (automatic) header fails in virtual browser

- TYPO3.Flow/Configuration/Settings.yaml
Leaving the name empty will not work as advertised.
> TASK: Fix comment on Flow.session.name setting

- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageManager.php
- TYPO3.Flow/Configuration/Settings.yaml
- TYPO3.Flow/Tests/Unit/Package/PackageManagerTest.php
After the package manager refactoring several inconsistencies with
inactive packages and moving them to a separate directory arose.
The code was adapted to make this more consistent and allow loading
of composer manifests from deactivated packages.
> BUGFIX: Inactive packages are handled correctly

- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/PersistentObjectConverter.php
- TYPO3.Flow/Tests/Unit/Fixtures/ClassWithSettersAndConstructor.php
- TYPO3.Flow/Tests/Unit/Property/TypeConverter/PersistentObjectConverterTest.php
The PersistentObjectConverter does not evaluate constructor arguments
when determining the type of its children.
This patch adds the check and now constructor arguments that are not
also a property are mapped again.
FLOW-371 #close
> BUGFIX: Respect constructor arguments that are no properties during property mapping

- TYPO3.Flow/Classes/TYPO3/Flow/Security/Authorization/Privilege/Entity/Doctrine/PropertyConditionGenerator.php
The PropertyConditionGenerator for entity privileges allows the use of
global objects from the configured global context. If those in turn
may be secured, the system runs into an endless loop.
To avoid this, the fetching of the value for the operand is done without
security checks after this change.
> BUGFIX: Evaluate property conditions without security checks

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartI/EssentialDesignPatterns.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartII/Introduction.rst
The dot was one to much, and the link didn't render because of formatting
issue.
Beside that, `EssentialDesignPatterns.rst` was not posix conform as the last
line was missing new line character. Some leftover "TYPO Flow" uses have
been removed as well.
> BUGFIX: Fix two small formatting issues in docs

- TYPO3.Flow/Classes/TYPO3/Flow/Session/Session.php
I would expect a session garbageCollection.probability of zero would never
trigger garbage collection.
Previously it actually did with a probability 1 / 101 as a it results in the
equation rand(0, 100) <= 0.
> BUGFIX: Fix session garbageCollector probability of 0

- TYPO3.Flow/Migrations/Mysql/Version20160212111357.php
- TYPO3.Flow/Migrations/Postgresql/Version20160212112848.php
The use of Doctrine 2.5 (instead of 2.4) exposes the fact that some
(old) index names in the Flow database schema do not match the names
that are generated currently.
This adjusts those index names, something that is a one-time adjustment.
FLOW-427 #close Adjusts indexes as needed
FLOW-222 #close Adjusts indexes as needed
> BUGFIX: Adjust index names to match Doctrine DBAL 2.5

- TYPO3.Flow/Configuration/Settings.yaml
- TYPO3.Flow/composer.json
- composer.json
Pulling in doctrine/migrations 1.3 works fine, but it comes with some
new dependencies that need to be excluded from reflection.
> TASK: Exclude classes pulled in by doctrine/migrations 1.3

- TYPO3.Flow/Configuration/Settings.yaml
- TYPO3.Flow/composer.json
- composer.json
Reverts neos/flow-development-collection#251
Flow 2.3 still runs on PHP 5.3 but doctrine/migrations 1.3 requires at least 5.5, therefore
we need to revert this requirement to make Flow 2.3 work smoothly with PHP 5.3.
> Revert "TASK: Exclude classes pulled in by doctrine/migrations 1.3"

- TYPO3.Flow/Classes/TYPO3/Flow/Command/PackageCommandController.php
`$packageType` is used in the error message if is is not a valid Flow package tpye.
> Corrected error message in package:create command

- TYPO3.Flow/Classes/TYPO3/Flow/Command/PackageCommandController.php
$packageType is used in the error message if is is not a valid Flow package
type.
> BUGFIX: Correct error message in package:create command

- TYPO3.Flow/Classes/TYPO3/Flow/Package/Package.php
This change add a missing ending slash in the autoload path for PSR4 package.
> BUGFIX: Missing ending slash for PSR4 package

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Configuration.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/ErrorAndExceptionHandling.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Templating.rst
As the used syntax was invalid to sphinx, and `'` are recommended in
yaml anyway.
> BUGFIX: All rst errors and warnings

- TYPO3.Flow/Documentation/Quickstart/index.rst
- TYPO3.Flow/Documentation/StyleGuide/About.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartII/Validation.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartII/View.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/ErrorAndExceptionHandling.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Templating.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/CodingGuideLines/PHP.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/ReleaseNotes/300.rst
Removed all possible errors and warnings from documentation. This will
allow new errors to be visible as soon as they occur and to reduce the
overall errors.
Some errors lead to non working links or syntax highlighting.
Also fixed indentation at some places. As the indentation wasn't the
same everywhere.
> BUGFIX: Rendering docs produced errors and warnings

- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ReflectionService.php
The ReflectionService would be still initialized before having an early
return in the saveToCache() method. This change makes sure to not
initialize the ReflectionService which results in less cache entries
being loaded and therefore less memory consumption and I/O.
NEOS-571 #comment Optimize ReflectionService shutdown
> TASK: Do not initialize ReflectionService on shutdown if not needed

- TYPO3.Flow/Migrations/Mysql/Version20141015125841.php
- TYPO3.Flow/Migrations/Mysql/Version20150206114820.php
- TYPO3.Flow/Migrations/Mysql/Version20150309181635.php
- TYPO3.Flow/Migrations/Postgresql/Version20141118174722.php
- TYPO3.Flow/Migrations/Postgresql/Version20150216124452.php
- TYPO3.Flow/Migrations/Postgresql/Version20150309184456.php
There have been cleanup migrations added in the past that interact in
breaking ways with each other. This changes the index renaming to only
happen if needed.
> BUGFIX: Avoid cross influence in schema migrations

- TYPO3.Flow/composer.json
- composer.json
This may bring a massive speedup and avoids an issue with composer.json
not being included with the 1.0.0 archives.
> TASK: Raise doctrine/migrations version to 1.3

- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ReflectionService.php
The commit 409a45aaf9550b2df790c9730b7f002bd609624b introduced a change
for early return inside the reflection service that did not catch a case
where the context was not initialized from the environment.
> BUGFIX: Fix regression with frozen reflection service

- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/CollectionValidator.php
- TYPO3.Flow/Tests/Unit/Validation/Validator/CollectionValidatorTest.php
The element validators configured for a collection validator couldn't
accept options so far, with this change it is possible to set the
``elementValidatorOptions`` option on the ``CollectionValidator`` to
give options to the element validator.
FLOW-435 #resolve
> FEATURE: Allow setting validator options for element validators

- TYPO3.Fluid/Classes/TYPO3/Fluid/ViewHelpers/Form/UploadViewHelper.php
Removes a duplicate "htmlspecialchars" on the
id-Attribute of the "orginallySubmittedResource"
hidden-field.
> BUGFIX: Remove duplicate "htmlspecialchars"

- Neos.Utility.Unicode/Classes/TYPO3/Flow/Utility/Unicode/Exception.php
- Neos.Utility.Unicode/Classes/TYPO3/Flow/Utility/Unicode/Functions.php
- Neos.Utility.Unicode/Classes/TYPO3/Flow/Utility/Unicode/TextIterator.php
- Neos.Utility.Unicode/Classes/TYPO3/Flow/Utility/Unicode/TextIteratorElement.php
- Neos.Utility.Unicode/Classes/TYPO3/Flow/Utility/Unicode/UnsupportedFeatureException.php
- Neos.Utility.Unicode/Readme.rst
- Neos.Utility.Unicode/Tests/Unit/FunctionsTest.php
- Neos.Utility.Unicode/Tests/Unit/TextIteratorTest.php
- Neos.Utility.Unicode/composer.json
- TYPO3.Flow/composer.json
- composer.json
Moves the unicode utilities of Flow to a separate package
retaining the original class namespace for backwards compatibility.
Additionally a few dependencies were cut without changing functionality.
> Split unicode utilities

- TYPO3.Flow/Classes/TYPO3/Flow/Composer/ComposerUtility.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageFactory.php
- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageManager.php
- TYPO3.Flow/Tests/Unit/Package/PackageFactoryTest.php
- TYPO3.Flow/Tests/Unit/Package/PackageManagerTest.php
- TYPO3.Flow/Tests/Unit/Package/PackageTest.php
Flow packages with a PSR-4 and a PSR-0 autoload path will only search for a ``Package.php``
file in the PSR-4 class path, which breaks if the ``Package.php`` is actually in the PSR-0 path.
With this change Flow will search in both paths with a preference on the PSR-4 path as PSR-0
is deprecated. Additionally only Flow package types will be searched for ``Package.php`` files.
If both paths contain a ``Package.php`` file Flow will throw an Exception because we cannot
know which one to load.
> BUGFIX: Accept multiple autoload paths for Flow packages

- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/MemcachedBackend.php
- TYPO3.Flow/Tests/Unit/Cache/Backend/MemcacheBackendTest.php
- TYPO3.Flow/Tests/Unit/Cache/Backend/MemcachedBackendTest.php
Adds support for the "memcached" extension in addition to the existing
support for the "memcache" extension.
"memcached" is a newer version with several improvements and often both
extensions aren't available simultaneously.
FLOW-440 #close
> TASK: Memcached cache backend compatibility with memcached

- TYPO3.Flow/Classes/TYPO3/Flow/Core/Bootstrap.php
- TYPO3.Flow/Classes/TYPO3/Flow/Core/ClassLoader.php
The Flow autoloader relied on much of the autoload information
that composer provides anyway. With this change we initialize
the composer autoloader first thing in the bootstrap and later
our own on top of that. That means the responsibility is kept
in the composer autoloader and we can get rid of many early include
statements which the composer autoloader fullfills instead.
> TASK: Use composer autoloader as fallback to Flow autoloader

- TYPO3.Flow/Classes/TYPO3/Flow/Command/HelpCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/RequestHandler.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Response.php
- TYPO3.Flow/Configuration/Settings.yaml
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Http.rst
- TYPO3.Flow/Tests/Unit/Fixtures/RawResponse-1.txt
- TYPO3.Flow/Tests/Unit/Http/HeadersTest.php
- TYPO3.Flow/Tests/Unit/Http/ResponseTest.php
This change introduces two news setting. One which allows for configuring
what is exposed via the default "X-Powered-By" HTTP header and a
second one which allows for configuring a human-readable application
name.
Previously, the header ("X-Flow-Powered") exposed the full version number
of Flow which may be undesirable in certain setups. Through the new
setting `core.applicationToken` now one of three options can be chosen:
- "Off" (no X-Powered-By header is sent)
- "ApplicationName" (the application name only, determined via the core.applicationKey setting)
- "MajorVersion" (the application name + major version, e.g. "Neos/2"
- "MinorVersion" (the application name + minor version, e.g. "Neos/2.1"
The new `core.applicationName` setting is used for defining a human-
friendly name, like …
> FEATURE: Configurable application token and application name

- TYPO3.Flow/Classes/TYPO3/Flow/Configuration/ConfigurationManager.php
- TYPO3.Flow/Tests/Unit/Configuration/ConfigurationManagerTest.php
The Objects configuration was never checked against the loaded
configuration cache but still saved sometimes. If a specific configuration type
was saved depended on the fact that it was loaded at the time of writing the
configuration cache. We now make sure that Objects configurations are also used
if they are cached and that we load all configuration types before writing the
cache.
> TASK: Fix Configuration cache usage

- TYPO3.Flow/Classes/TYPO3/Flow/Error/AbstractExceptionHandler.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Client/InternalRequestEngine.php
- TYPO3.Flow/Classes/TYPO3/Flow/Log/EarlyLogger.php
- TYPO3.Flow/Classes/TYPO3/Flow/Log/Logger.php
- TYPO3.Flow/Classes/TYPO3/Flow/Log/ThrowableLoggerInterface.php
- TYPO3.Flow/Tests/Unit/Aop/Pointcut/PointcutMethodNameFilterTest.php
Throwable errors (``TypeError``, ``ParseError``, ..) introduced in PHP 7.0
are not logged in the system log. Which means these errors can only
be shown using the debug exception handler.
To fix this a new logger interface ``ThrowableLoggerInterface``
that extends the existing ``LoggerInface`` is introduced,
which adds supports throwables in addition to exceptions.
To support PHP7 in custom logger interfaces, the new interface needs
to be implemented. Otherwise throwables won't get logged.
FLOW-441 #close
> BUGFIX: Log throwable errors in PHP 7

- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ReflectionService.php
The Flow class loader is registered in doctrines annotation reader twice.
First in ``Booting\Scripts::registerClassLoaderInAnnotationRegistry()``
then again in the ReflectionService. As this is unnecessary and is not
directly related to the ReflectionService the second registration is
removed with this change.
> BUGFIX: Remove duplicate registration of ClassLoader

- TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/ObjectManager.php
With this change the amount of monitored class files is massively reduced
by only monitoring class files of packages that have active object
configurations.
This improves request time in development context noticeably.
> TASK: Monitor only classes of packages with registered objects

- TYPO3.Flow/Classes/TYPO3/Flow/Command/DoctrineCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/Service.php
This does some code style cleanup in the codebase and makes use of the improvements in Doctrine Migrations 1.3.
The output of `doctrine:migrationstatus` is improved vastly (shows executed but no longer available migrations, shorter default output, can show migration descriptions, color support).
Migration generation has been improved and the error handling and output of `doctrine:migrate` have been improved.
FLOW-292 #close
> TASK: Improve Doctrine CLI tooling

- TYPO3.Flow/Tests/Unit/Cache/Frontend/AbstractFrontendTest.php
- TYPO3.Flow/Tests/Unit/Cache/Frontend/StringFrontendTest.php
- TYPO3.Flow/Tests/Unit/Cache/Frontend/VariableFrontendTest.php
- TYPO3.Flow/Tests/Unit/Mvc/Routing/RouteTest.php
- TYPO3.Flow/Tests/Unit/Object/Proxy/ProxyMethodTest.php
- TYPO3.Flow/Tests/Unit/Persistence/Generic/PersistenceManagerTest.php
- TYPO3.Flow/Tests/Unit/Resource/ResourceManagerTest.php
- TYPO3.Flow/Tests/Unit/Security/ContextTest.php
- TYPO3.Flow/Tests/Unit/Security/Policy/PolicyExpressionParserTest.php
- TYPO3.Flow/Tests/Unit/Security/Policy/PolicyServiceTest.php
- TYPO3.Flow/Tests/Unit/Validation/Validator/CollectionValidatorTest.php
- TYPO3.Fluid/Tests/Unit/ViewHelpers/Form/AbstractFormFieldViewHelperTest.php
Since ``phpunit-mock-objects`` 3.1.0 errors are thrown when a mocked
method is not allowed, non-existing, final or private.
This change adjusts to that change by getting rid of such mistakes in
the tests, which are made visible due to the change.
> TASK: Adjust unit tests mocks to new errors

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Persistence.rst
Doctrine expects a true integer instead of a string (true in double quots) for the orphanRemoval property.
> BUGFIX: orphanRemoval must be a true integer

- TYPO3.Flow/Classes/TYPO3/Flow/Http/Request.php
This change trim the query string, without this change the condition to build the request URI is wrong when the query is null and the URI contains a question mark without request arguments.
> BUGFIX: If query is null the condition break

- TYPO3.Flow/Classes/TYPO3/Flow/Mvc/Controller/AbstractController.php
- TYPO3.Flow/Tests/Unit/Mvc/Controller/AbstractControllerTest.php
The subpackage key is directly derived from the package key in the forward
method. Previously, if the subpackage key was not provided, it would not be
set in the next request.
Therefore to forward to a non-subpackage from a subpackage it was required
to specify the package key with trailing backslashes, so the subpackage key
would resolve to an empty string.
With this change it is possible by just specifying the actual package key
to forward to.
> BUGFIX: Always set subpackage key when setting package key in forward

- TYPO3.Flow/Classes/TYPO3/Flow/Property/PropertyMapper.php
- TYPO3.Flow/Configuration/Caches.yaml
- TYPO3.Flow/Configuration/Development/Caches.yaml
- TYPO3.Flow/Configuration/Objects.yaml
The source and target types as well as priorities for all registered
``TypeConverters`` can be cached in Production context as they are not
changing. That avoids instantiating all ``TypeConverters`` on each
request saving some time.
NEOS-1288 #resolve
> TASK: Cache TypeConverterMap to avoid instantiating all TypeConverters

- TYPO3.Flow/Classes/TYPO3/Flow/Mvc/DispatchComponent.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/MediaTypeConverterInterface.php
- TYPO3.Flow/Tests/Unit/Mvc/DispatchComponentTest.php
- TYPO3.Fluid/Tests/Unit/Core/Widget/AjaxWidgetComponentTest.php
Instead of trying to convert an empty string we return early in
the ``DispatchComponent`` if the request body was empty, which
avoids initializing type conversion needlessly.
> TASK: Initialize MediaTypeConverter only if request has body content

- TYPO3.Flow/Classes/TYPO3/Flow/Configuration/ConfigurationManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php
- TYPO3.Flow/Tests/Unit/Configuration/ConfigurationManagerTest.php
The ConfigurationManager needs only the temporary path to store cached
configurations so we can inject just that and get rid of the dependency
to the ``Environment`` Utility.
> TASK: Remove Environment dependency of ConfigurationManager

- TYPO3.Flow/Scripts/flow.php
Using the ``setfilepermissions.sh`` script fails due to wrong file permissions left by the composer installation (missing executable bit). Added the checking of the file's permissions, and correcting the file's permissions if needed. Mode 0700 is set as the ``setfilepermissions.sh`` script sets it's own permissions to that mode.
FLOW-400 #close
> TASK: Add permissions check for setfilepermissions.sh

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Templating.rst
- TYPO3.Fluid/Classes/TYPO3/Fluid/Core/Parser/SyntaxTree/ObjectAccessorNode.php
- TYPO3.Fluid/Tests/Functional/Core/ParserIntegrationTest.php
- TYPO3.Fluid/Tests/Functional/Form/Fixtures/Domain/Model/Post.php
This changeset adds support for accessor methods is* and has* to be
used directly for property access.
This allows to use such accessors in Fluid templates, which makes
the template code more readable and avoids getIs* and getHas* methods
in domain models.
Example::
<f:if condition="{someObject.isSomething}"></f:if>
This will call someObject->isSomething() method.
> FEATURE: Allow usage of is*/has* accessors in Fluid templates directly

- TYPO3.Flow/Classes/TYPO3/Flow/Annotations/Introduce.php
- TYPO3.Flow/Classes/TYPO3/Flow/Aop/AspectContainer.php
- TYPO3.Flow/Classes/TYPO3/Flow/Aop/Builder/ProxyClassBuilder.php
- TYPO3.Flow/Classes/TYPO3/Flow/Aop/TraitIntroduction.php
- TYPO3.Flow/Tests/Functional/Aop/Fixtures/Introduced01Trait.php
- TYPO3.Flow/Tests/Functional/Aop/Fixtures/TraitIntroductionTestingAspect.php
- TYPO3.Flow/Tests/Functional/Aop/FrameworkTest.php
This allows to introduce traits in generated proxy classes
via AOP. You can use the ``Introduce`` annotation with the
argument ``traitName`` to introdue the given trait into
generated proxy classes matching the pointcut.
For example::
@Flow\Introduce(
traitName="Vendor\Package\Service\Traits\ExampleTrait"
pointcutExpression="class(TYPO3\Flow\Mvc\Controller\ActionController)"
)
Would introduce the trait ``\Vendor\Package\Service\Traits\ExampleTrait``
into all proxies that either are the class or extend the class
``TYPO3\Flow\Mvc\Controller\ActionController``.
Resolves: FLOW-123
> FEATURE: Trait introduction via AOP

- TYPO3.Flow/Classes/TYPO3/Flow/Log/Backend/AnsiConsoleBackend.php
Uses the severities descriped in \TYPO3\Flow\Log\LoggerInterface
> BUGFIX: Update tagFormats to match defined severities

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Security.rst
'tokenClass' is not referenced in code anymore and
the full qualified name is required for using 'UsernamePasswordHttpBasic':
TYPO3\Flow\Security\Authentication\Token\UsernamePasswordHttpBasic
> BUGFIX: Documentation for 'UsernamePasswordHttpBasic' token outdated

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Persistence.rst
Remove quotes in example, since the option orphanRemoval expects a boolean value
> TASK: Update OneToMany annotation in Persistence.rst

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Security.rst
When using inheritance for entities, privileges will only work with the root entity type. This was not documented before.
> TASK: Add documentation about limitations of entity privileges

- TYPO3.Flow/.phpstorm.meta.php
- TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php
If the user issued a ``typo3.flow:package:rescan`` command this should
happen very early in the compiletime boot sequence as otherwise the
ObjectManager will try to load a non existing package if the rescan was
issued after a package was removed from the installation.
With this change package rescans are possible in all package state
situations in case you manipulate the packages without using composer
or our ``PackageManager``.
Additionally adds a bunch of use statements to the ``Bootstrap``.
> BUGFIX: package:rescan must happen before booting

- TYPO3.Flow/Classes/TYPO3/Flow/Composer/InstallerScripts.php
The CommandEvent and PackageEvent used in InstallerScripts are
deprecated since early 2015.
> TASK: Fix use of deprecated events in InstallerScripts

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/EntityManagerFactory.php
- TYPO3.Flow/Configuration/Settings.yaml
Flow won't work on a server without a running MySQL service because a default host is configured.
This fix will set the default host to an empty string so Flow also runs without a running MySQL service.
FLOW-379 #close
> TASK: Don't set a default host for persistence backend

- Neos.Utility.Arrays/composer.json
- Neos.Utility.Files/composer.json
- Neos.Utility.MediaTypes/composer.json
- Neos.Utility.ObjectHandling/composer.json
- Neos.Utility.OpcodeCache/composer.json
- Neos.Utility.Pdo/composer.json
- Neos.Utility.Schema/composer.json
The package manager derives the packageKey from the class loader configuration
if the package type is ``library``. This leads to problems with the split
libraries that share the namespace ``TYPO3\\Flow\\Utility`` because the
package state configuration for is overwritten.
Depending on the dependency order of the packages this will lead to symptoms
like class loading errors for the ``Neos.Utility.Schema`` package.
This change adds the specific packageKey to use to the composer.json to
load the libraries correctly.
> BUGFIX: Class loading errors because library packageKeys are incorrect

- TYPO3.Fluid/Classes/TYPO3/Fluid/Core/Parser/SyntaxTree/ObjectAccessorNode.php
- TYPO3.Fluid/Tests/Functional/Core/ParserIntegrationTest.php
This fixes the try/catch for undefined Fluid variables which start with "is" or "has".
Currently, exceptions here are not being caught because an `\Error` is being thrown.
Since non-callable method call should not be attempted in the first place, this change
adds a is_callable check. Therefore a try/catch block is no longer necessary, as any exception thrown inside the callable method should bubble up.
Specific example: a fluid section/partial with an optional argument called "isSomething"
- if rendered while defining isSomething in the arguments, there's no problem
- if rendered without isSomething in the arguments (implicit falsy), we then get
`Call to undefined method TYPO3\Fluid\Core\ViewHelper\TemplateVariableContainer::isSomething()`
Related to: #108, #343, #348, …
> BUGFIX: Fix ObjectAccessorNode::getPropertyPath for is/has access in PHP7

- TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php
Packages without configured class files were exempted from monitoring to reduce
the amount of monitored files. This is fine for class files but monitoring of
configuration and xliff files should happen for all packages regardless if they
have configured class files or not.
> BUGFIX: Packages without classes should still monitor configuration and xliff

- TYPO3.Flow/Classes/TYPO3/Flow/Error/DebugExceptionHandler.php
- TYPO3.Flow/Classes/TYPO3/Flow/Error/ProductionExceptionHandler.php
If a custom exception rendering fails, the exception would not be
caught and thus difficult to debug. Instead as a fallback exceptions
thrown during rendering will be rendered statically.
> BUGFIX: Fallback if custom exception rendering fails

- TYPO3.Flow/Classes/TYPO3/Flow/Command/HelpCommandController.php
This fix a regression introduced in 3.2, the use statement for the CommandManager is missing
> BUGFIX: Missing use statement in HelpCommandController

- TYPO3.Flow/Classes/TYPO3/Flow/Command/HelpCommandController.php
This change remove the property ``commandManager`` from the
``HelpCommandController``, because it already defined in the parent class.
> TASK: Don't override CommandManager in HelpCommandController

- TYPO3.Flow/Classes/TYPO3/Flow/Cli/CommandManager.php
If a command controller is declared abstract the cli ignores this class because it cannot be instantiated.
The commands from derived classes will of course be available.
> BUGFIX: Ignore abstract command-controllers

- TYPO3.Flow/Classes/TYPO3/Flow/Package/Package.php
- TYPO3.Flow/Tests/Unit/Package/PackageTest.php
In case of missing the installed version of a package, we provide the given version out of the composer.json of the package.
FLOW-455 #close
> TASK: Use version of composer.json as fallback for installed version of packages

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/ResourceManagement.rst
If a project contains lots of resources, resource:publish might fail if the maximum number of folders is being reached when publishing resources because no more folders can be created.
This part describes how to use the subdivideHashPathSegment target option in order to circumvent this error.
> TASK: Document handling a large number of Resources

- TYPO3.Flow/Classes/TYPO3/Flow/Mvc/Controller/ActionController.php
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/PropertyMapping.rst
- TYPO3.Flow/Tests/Functional/Mvc/ActionControllerTest.php
- TYPO3.Flow/Tests/Functional/Mvc/Fixtures/Controller/EntityController.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/SubEntity.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/TestEntity.php
- TYPO3.Flow/Tests/FunctionalTestCase.php
Before, when specifying a PropertyMappingConfiguration with a wildcard inside the initializeAction() of
a controller, this configuration would not be taken into account when a Fluid form was submitted, that
set configuration for specific properties.
This change makes the trustedProperties configuration happen *after* the user configuration, which in turn
will lead to trustedProperties always only extend the user configuration and wildcard configurations to
be used as the template configuration for the following specific trustedProperties configurations.
> TASK: Allow wildcard propertymapping configuration to set defaults for trustedProperties configuration

- TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php
Fixes a bug with statcaches that would lead to Flow trying to delete
configuration files that no longer existed.
> BUGFIX: Clear opcode cache before compiling proxy classes

- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageManager.php
After creating a package only a rescan of existing packages was triggered
but not a resorting. That would lead to arbitrary package loading order
which only depended on the way the filesystem would find the packages.
This has been changed to trigger a full rescan including sorting of packages.
> BUGFIX: After creating a package all packages should be sorted

- TYPO3.Flow/Classes/TYPO3/Flow/Mvc/Controller/Argument.php
Some methods haven't been removed or deprecated earlier but are in fact
no longer used in the Flow core and therefore deprecated to be removed
in the next major Flow version.
> !!!TASK: Deprecate unused methods in ``Argument`` class

- TYPO3.Flow/Classes/TYPO3/Flow/Utility/SchemaValidator.php
- TYPO3.Flow/Tests/Unit/Utility/SchemaValidatorTest.php
If an error is created in some cases the value was added to the result-message without checking for the type beforehand, that could lead to php errors if the value could not be casted to a string.
This change centralizes the rendering of the value in a  'renderValue' - method.
> BUGFIX: Avoid type-casting errors if the validation of complex types fails

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/PropertyMapping.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/ResourceManagement.rst
- TYPO3.Flow/Tests/Functional/Mvc/ActionControllerTest.php
- TYPO3.Flow/Tests/Functional/Mvc/Fixtures/Controller/EntityController.php
This change fixes the usage of class names as strings that were necessary in 2.3 branch for PHP backwards compatibility in #333 and replaces them with the recommended ::class calls.
> TASK: Followup cleanup for #333 to make use of ::class

- TYPO3.Flow/Classes/TYPO3/Flow/Validation/Validator/AggregateBoundaryValidator.php
- TYPO3.Flow/Classes/TYPO3/Flow/Validation/ValidatorResolver.php
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Validation.rst
- TYPO3.Flow/Tests/Functional/Validation/ValidationTest.php
- TYPO3.Flow/Tests/Unit/Validation/ValidatorResolverTest.php
This is one specific attempt at optimizing entity hierarchy validation, by stopping validation at unloaded Aggregate boundaries.
It is based on the idea that unloaded aggregates (doctrine proxy instances) do not carry changes, and since aggregates form a natural consistency boundary validation should not change and therefore can be stopped.
This will improve performance noticeably if you designed relatively small aggregates, but have lots of aggregate relations in your domain model.
FLOW-17 #comment This optimizes validation performance for well designed Aggregates
[snip] the following can be removed for merging: [/snip]
See also https://discuss.neos.io/t/rfc-optimized-validation-of-entities/340/5
Pro:
- simple implementation
- makes sense from a DDD perspective
- it's easy to define …
> FEATURE: Validate only up to Aggregate boundaries

- TYPO3.Flow/Classes/TYPO3/Flow/Core/Bootstrap.php
Previously Flow would just fail with an error message:
`Warning: ksort() expects parameter 1 to be array, null given`
when for some reason no suitable request handler can be found for the current request.
This change will instead throw a useful exception and hint the user at a setup problem.
> TASK: Provide proper error message when no request handler can be resolved

- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/PdoBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/DoctrineCommandController.php
- TYPO3.Flow/Configuration/Settings.yaml
This pull request contains two features:
1. Make PdoBackend iterable so it can be used for caches
2. Use default filter expression to ignore other packages when generating migrations
I tested this with PostgreSQL as a backend for sessions.
> FEATURE: Allow use of PDO backend for caches

- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/PersistentObjectConverter.php
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/PropertyMapping.rst
Currently it is impossible to edit value objects without explicitly
allowing creation. This is because value objects are always
created, never loaded from persistence.
This change alters the PersistentObjectConverter to allow creation
of value objects by default.
FLOW-373 #close
> BUGFIX: Allow creation of value objects during property mapping by default

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/CommandLine.rst
In the method signature, all (mandatory) arguments must be placed in front of the options. If not, all options placed in front of the last argument become mandatory, too in the command line prompt. This should be stated explicitely in the documentation.
> TASK: Clarify positioning of arguments and options in CommandController

- TYPO3.Flow/Configuration/Settings.yaml
This fixes reflection failures caused by some classes in those libraries:
phpunit/phpunit depends on phpspec/prophecy, which depends on phpdocumentor/reflection-docblock.
Now prophecy changed that dependency from `~2.0` to `^2.0|^3.0.2` when going from 1.6.0 to 1.6.1.
reflection-docblock 3.x includes (new) code which fails reflection (namespace does not match file path).
> BUGFIX: Exclude sebastian.* and phpdocumentor.* from reflection

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/ObjectManagement.rst
The examples contain namespace and full class body, so they seem to be complete and executable. But for usage of `@Flow` the use statement is necessary.
> Complete code examples with necessary use statement

- TYPO3.Flow/Classes/TYPO3/Flow/Http/Request.php
- TYPO3.Flow/Classes/TYPO3/Flow/Security/RequestPattern/Ip.php
- TYPO3.Flow/Classes/TYPO3/Flow/Utility/Ip.php
- TYPO3.Flow/Configuration/Settings.yaml
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Http.rst
- TYPO3.Flow/Resources/Private/Schema/Settings/TYPO3.Flow.http.schema.yaml
- TYPO3.Flow/Tests/Unit/Http/BrowserTest.php
- TYPO3.Flow/Tests/Unit/Http/RequestTest.php
This change introduces a configuration setting `TYPO3.Flow.http.trustedProxies.proxies`
for so called "Trusted Proxies", which is a list of IP address ranges that are trusted
to provide header overrides for some import request meta informations like the host,
port, protocol and client IP.
proxies:
- '216.246.40.0/24'
- '216.246.100.0/24'
Also the header names that are trusted for those informations can be set via the configuration
option `TYPO3.Flow.http.trustedProxies.headers` and default to this:
headers:
clientIp: 'X-Forwarded-For'
host: 'X-Forwarded-Host'
port: 'X-Forwarded-Port'
proto: 'X-Forwarded-Proto'
To get the most trusted client IP adress, the Http Request provides a new method
`getTrustedClientIpAddress()` which resolves the clientIp header, matching against
trusted proxy …
> FEATURE: Add support for configuring trusted proxies

- TYPO3.Flow/Classes/TYPO3/Flow/I18n/FormatResolver.php
- TYPO3.Flow/Tests/Unit/I18n/FormatResolverTest.php
If placeholders will be replaced by arguments containing chars "{}",
replacing led to an exception.
This fix solves this behaviour by not visiting replaced content again.
This helps a lot translating error messages from Validators which give
their content back to their error messages - and can contain literally
anything.
> BUGFIX: Improving argument handling of FormatResolver::resolvePlaceholders

- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Storage/WritableFileSystemStorage.php
The temporary file used to be gone after importing, but since it only is
moved when the target does not yet exist, this changed. Now the file is
unlinked in that case.
FLOW-378 #close
> BUGIX: Remove temporary file in importTemporaryFile()

- TYPO3.Flow/Classes/TYPO3/Flow/I18n/EelHelper/TranslationParameterToken.php
- TYPO3.Flow/Classes/TYPO3/Flow/I18n/Translator.php
- TYPO3.Flow/Tests/Functional/I18n/TranslatorTest.php
- TYPO3.Flow/Tests/Unit/I18n/TranslatorTest.php
- TYPO3.Fluid/Classes/TYPO3/Fluid/ViewHelpers/Form/SelectViewHelper.php
- TYPO3.Fluid/Classes/TYPO3/Fluid/ViewHelpers/TranslateViewHelper.php
- TYPO3.Fluid/Tests/Unit/ViewHelpers/Form/SelectViewHelperTest.php
- TYPO3.Fluid/Tests/Unit/ViewHelpers/TranslateViewHelperTest.php
This patch adjusts the behavior of id-based translations in order to make it deterministic and consistent.
It mainly adjusts `Translator::translateById()` to return `NULL` if the given `id` couldn't be translated. Previously it returned the `id` making it impossible to detect that case.
This has an effect to the two related Fluid ViewHelpers in certain conditions:
`{f:translate(id: 'some.id', value: 'default')}`:
previously returned the *translated* default value if the `id` wasn't translated, possibly leading to unexpected behavior.
Now it will just return the raw default value ("default" in the example above instead of "translatedDefault").
Besides the `TranslateViewHelper` has been tweaked to always return an empty string rather than `NULL` if neither id nor value could be resolved. …
> !!! TASK: More consistent translation behavior

- TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/CommandLine.rst
Adds a new convenience method `Scripts::executeCommandAsync()` that can be
used to execute commands without waiting for their result.
This is especially useful for time-consuming tasks whose result is not
(instantly) required.
Example::
Scripts::executeCommandAsync('my.package:registration:sendconfirmationmail', $this->flowSettings, ['email' => $emailAddress]);
FLOW-458 #close
> FEATURE: Allow asynchronous execution of commands

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Security.rst
Fixes the `Policy.yaml` examples in the Privilege Parameters section of the Security chapter.
FLOW-459 #close
> TASK: Fix documentation about Privilege Parameters

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/DataTypes/JsonArrayType.php
- TYPO3.Flow/Tests/Unit/Persistence/Doctrine/DataTypes/JsonArrayTypeTest.php
Prevent an exception to be thrown if the array passed for conversion is ``null``.
> BUGFIX: Check if array is ``null`` at the beginning of JSON conversion

- TYPO3.Eel/Classes/TYPO3/Eel/FlowQuery/Operations/SliceOperation.php
The Eel slice operation only works with arrays so far. Since the FlowQuery
context can be anything that implements `\Iterator`, we now convert iterators
to arrays if they are passed in as the context.
> BUGFIX: Allow SliceOperation to work on \Iterator

- TYPO3.Flow/Classes/TYPO3/Flow/Composer/InstallerScripts.php
The Files utility used by InstallerScripts will use these constants
to transform an absolute path to a relative one. As the compared path
will always be a Unix path, the path to replace needs to be completely
Unix as well to make replacing working. This prevents "mkdir(): invalid
arguments" errors on Windows.
> BUGFIX: Use Unix paths in InstallerScripts

- TYPO3.Fluid/Classes/TYPO3/Fluid/ViewHelpers/Form/AbstractFormFieldViewHelper.php
- TYPO3.Fluid/Classes/TYPO3/Fluid/ViewHelpers/Form/CheckboxViewHelper.php
- TYPO3.Fluid/Resources/Private/Templates/Tests/Functional/Form/Fixtures/Form/Edit.html
- TYPO3.Fluid/Tests/Functional/Form/Fixtures/Domain/Model/Post.php
- TYPO3.Fluid/Tests/Functional/Form/Fixtures/Domain/Model/Tag.php
- TYPO3.Fluid/Tests/Functional/Form/FormObjectsTest.php
Checkboxes that were bound to collection properties or had the `multiple` attribute set,
were generating invalid input field names like this:
<input type="checkbox" name="post[tags][__identity][]" ...>
Since the internal identity is not required for checkboxes, it is stripped from the generated name.
Also, any such checkboxes now avoid generating an empty value hidden field, as this will at most
lead to empty values being additionally submitted to the collection property.
FLOW-419 #close
> BUGFIX: Input field name for multiple checkbox is generated correctly

- TYPO3.Flow/Classes/TYPO3/Flow/Command/PackageCommandController.php
Very helpful parameter to debug loading order of packages.
`package:list --loading-order`
> FEATURE: New parameter to keep output ordered by loading order instead of name

- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/ObjectConverter.php
- TYPO3.Flow/Tests/Unit/Property/TypeConverter/ObjectConverterTest.php
When mapping a plain object with the ``ObjectConverter``, root namespace 
properties like ``\DateTime`` do not find a converter. This is because
the leading backslash is not removed by the ``ObjectConverter`` (i.e. we
looked for a ``\DateTimeConverter`` instead of the ``DateTimeConverter``
> BUGFIX: Fix Property Mapper determination for the ObjectConverter

- TYPO3.Flow/composer.json
- composer.json
Require version 2.x of the ``composer-plugin`` package. Previous versions
use the ``excludeClasses`` setting which has been deprecated with Flow 3.0.
> BUGFIX: Require latest version of neos/composer-plugin

- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/ObjectConverter.php
- TYPO3.Flow/Tests/Functional/Property/Fixtures/TestClassWithSingletonConstructorInjection.php
- TYPO3.Flow/Tests/Functional/Property/TypeConverter/ObjectConverterTest.php
- TYPO3.Flow/Tests/Unit/Property/TypeConverter/PersistentObjectConverterTest.php
This allows to omit singleton constructor arguments when using the
``PropertyMapper`` to convert objects.
Background:
Constructor arguments can already be omitted if there is a default
value specified in the class to convert to:
```
class SomeClass {
public function __construct($optionaArgument = null) {
// ..
}
}
```
With this change this will also work for (singleton) classes:
```
class SomeClass {
public function __construct(SomeService $someService) {
// ..
}
}
$someInstance = $this->propertyMapper->convert([], SomeClass::class);
```
FLOW-463 #close
> FEATURE: Allow automatic injection of singleton constructor arguments

- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/ObjectConverter.php
- TYPO3.Flow/Tests/Functional/Property/Fixtures/TestClassWithThirdPartyClassConstructorInjection.php
- TYPO3.Flow/Tests/Functional/Property/TypeConverter/ObjectConverterTest.php
This adds an additional check to ``ObjectConverter::buildObject()``
in order to prevent misleading errors when trying to convert objects
with constructor injections that are unknown to the ``ObjectManager``.
FLOW-463 #related
> BUGFIX: Safeguard for unmananged constructor injections

- TYPO3.Flow/Classes/TYPO3/Flow/Object/Proxy/ProxyMethod.php
- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/MethodReflection.php
- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ParameterReflection.php
- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ReflectionService.php
- TYPO3.Flow/Tests/Functional/Aop/Fixtures/BaseFunctionalityTestingAspect.php
- TYPO3.Flow/Tests/Functional/Aop/Fixtures/TargetClassWithPhp7Features.php
- TYPO3.Flow/Tests/Functional/Aop/FrameworkTest.php
- TYPO3.Flow/Tests/Unit/Object/Proxy/ProxyMethodTest.php
Adds methods to the reflection service to access declared types in
a backwards compatible way (returning null for PHP < 7.0) and extends
the proxy builder to add type declarations if they were used on the
original method. This allows to use type declarations for parameters
(scalar values) or return type declarations even for advised methods.
FLOW-460 #fixes
> BUGFIX: Support PHP 7.0 type declarations on parameters and return types

- Neos.Utility.ObjectHandling/composer.json
- composer.json
As the doctrine classes are only used for type checks in
``instanceof`` and ``is_subclass_of`` and both work with
non existing classes we can drop the dependency on
``doctrine/orm`` in this package.
> TASK: Remove doctrine/orm dependency

- TYPO3.Flow/Classes/TYPO3/Flow/Command/DoctrineCommandController.php
The doctrine controller checked for correct configuration of a database
before calling the doctrine methods. As the drivers all have different
options the ``host`` is a not a conclusive check. The only thing that
can be checked is if a driver was set.
> BUGFIX: Doctrine controller should allow empty host for database

- Neos.Utility.ObjectHandling/Classes/TYPO3/Flow/Utility/TypeHandling.php
- Neos.Utility.ObjectHandling/Tests/Unit/TypeHandlingTest.php
- TYPO3.Flow/Tests/Unit/Reflection/ClassSchemaTest.php
While underscores in class names are not used in Flow code itself, it might
happen that TypeHandling is used outside Flow - where having underscores
in class names is perfectly valid.
This change ensures that underscores in class names are recognized properly.
> BUGFIX: Type Handling should not break when classnames contain underscores, or when classnames are lowerCamelCase

- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/ArrayFromObjectConverter.php
- TYPO3.Flow/Tests/Unit/Property/TypeConverter/ArrayFromObjectConverterTest.php
Before the ``ArrayFromObjectConverter`` lost the property name of object properties when converting child properties.
> BUGFIX: ArrayFromObjectConverter correctly converts object properties with property name

- TYPO3.Flow/Classes/TYPO3/Flow/Annotations/ValueObject.php
- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Aspect/EmbeddedValueObjectPointcutFilter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Aspect/PersistenceMagicAspect.php
- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php
- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ReflectionService.php
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartI/ConceptsOfModernProgramming.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Persistence.rst
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/TestEmbeddedValueObject.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/TestEntity.php
- TYPO3.Flow/Tests/Functional/Persistence/PersistenceTest.php
- TYPO3.Flow/Tests/Functional/Property/Fixtures/TestEmbeddedValueobject.php
- TYPO3.Flow/Tests/Functional/Property/PropertyMapperTest.php
- TYPO3.Fluid/Resources/Private/Templates/Tests/Functional/Form/Fixtures/Form/Edit.html
- TYPO3.Fluid/Tests/Functional/Form/Fixtures/Domain/Model/Location.php
- TYPO3.Fluid/Tests/Functional/Form/Fixtures/Domain/Model/User.php
- TYPO3.Fluid/Tests/Functional/Form/FormObjectsTest.php
This change adds support for embedded ValueObjects by using the Embeddable features
of Doctrine ORM 2.5.
All ValueObjects can be made embedded by setting the annotation option
`embedded=true`.
Depends on FLOW-260
FLOW-257 #close
> FEATURE: Add support for embedded ValueObjects

- TYPO3.Flow/Classes/TYPO3/Flow/Mvc/Controller/ActionController.php
The ``ActionController::redirectToReferringRequest`` method was
deprecated in 3.0 and therefore removed for 4.0.
> !!!TASK: Remove deprecated ``redirectToReferringRequest``

- TYPO3.Flow/Classes/TYPO3/Flow/Http/Component/TrustedProxiesComponent.php
- TYPO3.Flow/Tests/Unit/Http/Component/TrustedProxiesComponentTest.php
Before the port of the request URI was not set correctly if the Trusted Proxy would 
send an `X-Forwarded-Proto: HTTPS` header without also specifying a forwarded port.
This resulted in generated URLs like "https://acme.com:80".
The change fixes that by doing a case insensitive check for the protocol to be
'https' and set port 443 accordingly.
> BUGFIX: Port is set correctly when Trusted Proxy only sends protocol override

- TYPO3.Eel/Classes/TYPO3/Eel/Helper/StringHelper.php
- TYPO3.Eel/Tests/Unit/Helper/StringHelperTest.php
Adds a new helper method to the string helper for splitting strings with
a PREG pattern.
Example::
String.pregSplit("foo bar   baz", "/\s+/") == ['foo', 'bar', 'baz']
> FEATURE: Add String.pregSplit Eel helper

- TYPO3.Flow/Classes/TYPO3/Flow/Command/CacheCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/ConfigurationCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/CoreCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/DatabaseCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/DoctrineCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/HelpCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/PackageCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/ResourceCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/RoutingCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/SecurityCommandController.php
- TYPO3.Flow/Classes/TYPO3/Flow/Command/TypeConverterCommandController.php
Additionally refactor legacy array syntax.
> TASK: Refactor absolute namespaces in  Flow / Command classes

- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Storage/WritableFileSystemStorage.php
PHP throws a operation not permitted warning when using rename across
volumes, which happens e.g. if you have FLOW_PATH_TEMPORARY_BASE pointing
to a different (more performant) volume.
From the php documentation:
> More explicitly, rename() may still return (bool) true, despite the warnings that result from the underlying calls to chown() or chmod(). This behavior can be misleading absent a deeper understanding of the underlying mechanics. To rename across filesystems, PHP "fakes it" by calling copy(), unlink(), chown(), and chmod() (not necessarily in that order). See PHP bug #50676 for more information.
> On UNIX-like operating systems, filesystems may be mounted with an explicit uid and/or gid (for example, with mount options "uid=someuser,gid=somegroup"). Attempting to call rename() …
> BUGFIX: Temporary files are correctly moved across volumes

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Security.rst
The indentation of the examples are wrong. They cause an exception if they are copied without the knowledge of the right indentation.
> BUGFIX: Wrong indentation in policy examples

- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ObjectAccess.php
- TYPO3.Flow/Tests/Unit/Reflection/Fixture/DummyClassWithGettersAndSetters.php
Before any class that would implement any of the methods `get()`, `has()`, `set()` or `is()` would make
ObjectAccess fail when attempting to get/set empty propertyNames. Those methods are commonly
used when implementing the propertyBag pattern.
This change fixes that by making sure that the accessor methods are actually longer than the plain prefixes.
> BUGFIX: ObjectAccess supports property bag implementation classes

- TYPO3.Flow/Classes/TYPO3/Flow/Http/Component/ComponentContext.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/RequestHandler.php
Before the Http RequestHandler would always return the initial instance of the `Request` and `Response`
before the ComponentChain.
Since the ComponentChain is supposed to possibly replace the Request and Response instances, this
lead to cases where retrieving the current Request from the RequestHandler would not match the actual
Request that is in place inside the MVC Controller for example.
This change fixes that by always delegating the request and response getters to the ComponentContext.
Also, this change fixes a regression introduced with 3.3 when generating URLs behind a https offload proxy. The UriBuilder was using the untouched Request instance ending up with generating URLs like `https://acme.com:80`.
> BUGFIX: Http RequestHandler returns correct instance of Request and Response

- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/TypedArrayConverter.php
- TYPO3.Flow/Tests/Unit/Property/TypeConverter/TypedArrayConverterTest.php
In some cases the TypedArrayConverter::getSourceChildPropertiesToBeConverted() was not returning an array.
It is somewhat related to https://github.com/neos/neos-development-collection/pull/102 change in Neos 2.3. PropertyMapper is now used for handling all node properties and it calls `getSourceChildPropertiesToBeConverted()` method and supplies its result to `foreach()`, which could result in nasty `Warning: Invalid argument supplied for foreach()`.
> BUGFIX: TypedArrayConverter correctly returns array in all cases

- TYPO3.Fluid/Classes/TYPO3/Fluid/ViewHelpers/Form/CheckboxViewHelper.php
To prevent a recursive comparison which can lead to this error, strict comparison is used which only compares the reference.
> BUGFIX: Prevent nesting level too deep error in checkbox view helper

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/DataTypes/JsonArrayType.php
- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/DataTypes/ObjectArray.php
Since 3.3 the doctrine types often ended up being proxied, due to a change in proxy generation
on aspected parent classes. This would throw an exception because the DBAL\Types base classes
constructor is private and hence cannot be called from the proxied constructor.
This works around that issue by making sure the custom DBAL Types are not proxied.
Fixes #516
> BUGFIX: Doctrine DataTypes should not be proxied

- TYPO3.Eel/Classes/TYPO3/Eel/Helper/StringHelper.php
- TYPO3.Eel/Tests/Unit/Helper/StringHelperTest.php
Now the ``stripTags`` string eel helper will accept a second optional argument in form of a list of allowed tags which will not be stripped from the string.
> FEATURE: Support allowable tags in ``stripTags`` Eel String helper

- TYPO3.Flow/Resources/Private/Core/LockHoldingStackPage.html
- TYPO3.Flow/Resources/Private/Mvc/StandardView_Template.html
Hi there,
the fallback MVC view contained three invalid links and a couple of `TYPO3` labels and css class names, that are replaced with this PR. Not sure about the wording though, so please have a look if it's okay :)
(BTW: Just for completeness, I applied the same to the LockHoldingStackPage.html)
> TASK: Update standard view

- Neos.Utility.Files/Classes/TYPO3/Flow/Utility/Files.php
The `createDirectoryRecursively()` method now checks for an existing symlink before
trying to create a directory. Before it only checked for an existing directory, sometimes
leading to false negatives.
Fixes #647
> BUGFIX: Check for existing symlink in createDirectoryRecursively()

- TYPO3.Flow/Classes/TYPO3/Flow/Http/Client/InternalRequestEngine.php
- TYPO3.Flow/Tests/FunctionalTestCase.php
- TYPO3.Flow/Tests/FunctionalTestRequestHandler.php
Before the functional test request handler would always return the `Request`
and `Response` instances that it got injected independent of any Http
Components that might have run in between.
Likewise the InternalRequestEngine would only work on the `Response` object
it creates when sending, which could not be the instance that is actually
returned from the ComponentChain.
This change makes both use a ComponentContext to allow the ComponentChain to
override instances of the `Request` and `Response` safely without unexpected
results.
Also, this marks the `FunctionalTestRequestHandler` methods `setHttpRequest`
and `setHttpResponse` as deprecated.
Related to #499
> BUGFIX: InternalRequestEngine and functional tests respect ComponentContext

- TYPO3.Fluid/Classes/TYPO3/Fluid/ViewHelpers/TranslateViewHelper.php
Small change for `$source` parameter documentation. We can set path to the source file but it was not clear if we should use `.` or `/` as a directory separator. This change adds information that slash should be used.
> TASK: Improve TranslateViewHelper documentation

- TYPO3.Kickstart/Resources/Private/Generator/Controller/ActionControllerTemplate.php.tmpl
- TYPO3.Kickstart/Resources/Private/Generator/Controller/CommandControllerTemplate.php.tmpl
Hi there,
This PR is just to make the kickstart code generators more in tune with the usage of fully qualified class names throughout the rest of the codebases of Neos and Flow.
> TASK: Turn fq class names to use statements in kickstart templates

- TYPO3.Flow/Classes/TYPO3/Flow/Object/DependencyInjection/ProxyClassBuilder.php
- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ReflectionService.php
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/ObjectManagement.rst
With this change static methods annotated `@Flow\CompileStatic` can now
be `protected` allowing for more concise public APIs.
If the annotated method is `private` or not `static` an exception is
thrown during compile time in `Production` context.
As a side-effect this change adds a new API method `ReflectionService:: getMethodsAnnotatedWith()`
that allows for retrieval of all method names of a class that are annotated with a
given annotation.
Related: #662
> FEATURE: Support for protected static compiled methods

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/SessionHandling.rst
Since memcache backend does not implement the IterableBackendInterface it can not be used for session handling
> TASK: Don’t list memcache as possible backend for Session handling

- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/DateTimeConverter.php
- TYPO3.Flow/Classes/TYPO3/Flow/Property/TypeConverter/StringConverter.php
- TYPO3.Flow/Tests/Unit/Property/TypeConverter/DateTimeConverterTest.php
- TYPO3.Flow/Tests/Unit/Property/TypeConverter/StringConverterTest.php
This extends `DateTimeConverter` and `StringConverter` so that they support
any class implementing the `\DateTimeInterface` (including `\DateTimeImmutable`).
Resolves: #677
> FEATURE: Allow property mapping of DateTimeImmutables

- TYPO3.Flow/Classes/TYPO3/Flow/Annotations/Inject.php
- TYPO3.Flow/Classes/TYPO3/Flow/Object/Configuration/ConfigurationBuilder.php
- TYPO3.Flow/Tests/Functional/Object/DependencyInjectionTest.php
- TYPO3.Flow/Tests/Functional/Object/Fixtures/ClassWithInjectedConfiguration.php
This removes the deprecated injection of settings via the @Flow\Inject annotation.
> !!! TASK: Remove deprecated setting injection

- TYPO3.Flow/Documentation/Quickstart/index.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartII/Installation.rst
Changing the web group name for the installation instructions on linux from the mac web group name to a more common linux one.
> TASK: Update Installation Doc

- TYPO3.Flow/Scripts/Migrations/Manager.php
Without this change PHP can print a warning message in the CLI output: PHP Warning:  Attempt to assign property of non-object in Manager.php on line 265.
This change fix access to currentPackageData['composerManifest']['extra'] to use the array
syntax and not the stdClass, used by the previous package manager.
> BUGFIX: Adapt the core migration manager for the new package manager

- TYPO3.Flow/Resources/Private/Installer/Distribution/Defaults/Configuration/Routes.yaml
As a followup to https://github.com/neos/flow-welcome/pull/4 this change removes the routing rules and have them included if the TYPO3.Welcome package is active.
All this to avoud `The SubRoute Package "TYPO3.Welcome" referenced in Route "Welcome" is not available.` when you start a new installation
Solves neos/flow-development-collection#698
> TASK: Remove TYPO3.Welcome Subroutes

- TYPO3.Flow/Classes/TYPO3/Flow/Property/PropertyMapper.php
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/PropertyMapping.rst
- TYPO3.Flow/Tests/Unit/Property/PropertyMapperTest.php
Creating a new TypeConverter can have major side-effects on existing applications.
This change allows TypeConverters to have a negative priority in order to mark them
"internal".
Internal TypeConverters will be skipped from PropertyMapping by default.
To use them explicitly the ``PropertyMappingConfiguration`` can be used::
$configuration = new PropertyMappingConfiguration();
$configuration->setTypeConverter(new SomeInternalTypeConverter());
$this->propertyMapper->convert($source, $targetType, $configuration);
Resolves: #695
> FEATURE: Internal TypeConverters

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/EntityManagerFactory.php
- TYPO3.Flow/Configuration/Caches.yaml
- TYPO3.Flow/Configuration/Settings.yaml
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Persistence.rst
- TYPO3.Flow/Resources/Private/Schema/Settings/TYPO3.Flow.persistence.schema.yaml
This change introduces the configuration settings `TYPO3.Flow.persistence.doctrine.secondLevelCache`
which allows configuring the second level cache that is available since Doctrine ORM 2.5
Currently, this allows for enabling the second level cache, setting default lifetime and region specific
lifetimes.
The used cache can be configured as `Flow_Persistence_Doctrine_SecondLevel`.
> TASK: Allow configuration of doctrine second level cache

- TYPO3.Flow/Classes/TYPO3/Flow/Http/RequestHandler.php
Since the Request and Response instances are supposed to change inside the ComponentChain,
it is error-prone to keep a reference to the initial instances inside the RequestHandler.
This change removes the class properties $request and $response and instead uses local variables.
This is marked breaking only for the reason that some RequestHandler implementations could
exist that still somehow depend on this internal detail. It is not really breaking as those properties
were never part of the public api though.
> !!! TASK: Remove internal properties request and response from RequestHandler

- TYPO3.Flow/Classes/TYPO3/Flow/Utility/Files.php
- TYPO3.Flow/Tests/Unit/Utility/FilesTest.php
Fixes a race condition where concurrent emptying of a directory causes
errors because files were already unlinked by another process.
FLOW-283 #close
FLOW-345 #close
> BUGFIX: Do not throw exception when concurrently unlinking files

- TYPO3.Flow/Classes/TYPO3/Flow/Mvc/ViewConfigurationManager.php
- TYPO3.Flow/Configuration/Testing/Views.yaml
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/ModelViewController.rst
- TYPO3.Flow/Tests/Unit/Mvc/ViewConfigurationManagerTest.php
Before this the higher weighted requestFilters were merged into the lower-weighted ones which placed the array-properties of the higher weighted filters last in the merged configuration. This made it impossible to add a new path templatePath that would be considered before.
This patch removes the merging of view-configurations entirely since this lead to confusion in the integration because the merging was unexpected.
This is breaking if you have multiple configurations with filters that apply to the same request and expect some option from one of the configurations to still be present despite another configuration having a higher weight.
> !!!TASK: ViewConfiguration use only the settings of highest weighted request filter

- TYPO3.Flow/composer.json
Despite the fact that Flow technically doesn't depend
on Fluid anymore we require it as the majority of projects
including Neos uses it anyway. Otherwise developers would
need to require it themselves in Flow projects.
> TASK: Require Fluid Adaptor in Flow

- Neos.FluidAdaptor/Classes/ViewHelpers/Link/ActionViewHelper.php
- Neos.FluidAdaptor/Classes/ViewHelpers/Uri/ActionViewHelper.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Link/ActionViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Uri/ActionViewHelperTest.php
With this change it is possible to use the main Request instead of the current Request.
Note: using this argument can be a sign of undesired tight coupling, use with care
> TASK: Add `useMainRequest` to the ActionViewHelpers

- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/ViewHelperBaseTestcase.php
It seems like that during the switch to the Fluid Adaptor, some namespaces in test were not properly adapted
> BUGFIX: Use correct namespaces in ViewHelperBaseTestCase

- TYPO3.Flow/Classes/TYPO3/Flow/Security/RequestPattern/ControllerObjectName.php
- TYPO3.Flow/Configuration/Policy.yaml
- TYPO3.Flow/Configuration/Testing/Settings.yaml
- TYPO3.Flow/Resources/Private/Schema/Objects.schema.yaml
- TYPO3.Flow/Resources/Private/Schema/Settings/TYPO3.Flow.mvc.schema.yaml
- TYPO3.Flow/Resources/Private/Schema/Settings/TYPO3.Flow.persistence.schema.yaml
- TYPO3.Flow/Resources/Private/Schema/Settings/TYPO3.Flow.security.schema.yaml
- TYPO3.Flow/Tests/Functional/Configuration/ConfigurationValidationTest.php
- TYPO3.Flow/Tests/Functional/Configuration/Fixtures/RootDirectoryIgnoringYamlSource.php
Add functional test that validates the different configuration-types of the neos-core in different contexts.
The packages where the validated configuration is loaded from are limited to avoid failing of functional tests if the local configuration has errors. Also the list of packages that is used to find schema files is limited: 
- contexts: ``Development``, ``Production``, ``Testing``
- configurationTypes: = ``Caches``, ``Objects``, ``Policy``, ``Routes``, ``Settings`` 
- configurationPackageKeys:  ``TYPO3.Flow``, ``TYPO3.Fluid``, ``TYPO3.Eel``, ``TYPO3.Kickstart``
- schemaPackageKeys: ``TYPO3.Flow``
The supported contexts, configurationTypes, configurationPackageKeys and schemaPackageKeys are defined as class variables to be overwritten in tests-classed derived from this one.
> TASK: Add test case for configuration validation

- Neos.FluidAdaptor/Tests/Unit/Core/ViewHelper/AbstractConditionViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/BaseViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/FlashMessagesViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Form/AbstractFormViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Form/FormFieldViewHelperBaseTestcase.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/FormViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/BytesViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/CaseViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/CropViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/HtmlentitiesDecodeViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/HtmlentitiesViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/IdentifierViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/JsonViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/Nl2brViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/PaddingViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/StripTagsViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/UrlencodeViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Link/ActionViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Link/EmailViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Link/ExternalViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/RenderChildrenViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Security/IfAccessViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Security/IfHasRoleViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/TranslateViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Uri/ActionViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Uri/EmailViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Uri/ExternalViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Uri/ResourceViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Validation/IfHasErrorsViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Validation/ResultsViewHelperTest.php
In neos/flow-development-collection#722 the namespace was changed but
the classes extending it were not adjusted. Cough, cough.
This fixes that.
> BUGFIX: Fix regression introduced by test namespace change

- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ReflectionService.php
- TYPO3.Flow/Classes/TYPO3/Flow/Security/Authorization/AccessDecisionVoterInterface.php
- TYPO3.Flow/Classes/TYPO3/Flow/Security/Policy/PolicyService.php
- TYPO3.Flow/Classes/TYPO3/Flow/Utility/Unicode/TextIterator.php
- TYPO3.Flow/Configuration/Settings.yaml
A change in dependencies pulled in psr/log which contains a trait,
causing failures with PHP 5.3
> BUGFIX: Exclude psr/log from reflection

- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageOrderResolver.php
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/PackageManagement.rst
Adds a way to configure packages to be loaded before via `composer.json`
besides using require in a backwards compatible way.
The configuration option is documented and additionally package key
configuration is clarified.
> TASK: Add option to sort packages by extra configuration

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/EntityManagerFactory.php
This reverts the use of the `::class` constant for the ORM proxy
namespace configuration, since that is not "real" and is not
even a "class" but just a "namespace prefix".
> TASK: Use string for "virtual" namespace name

- TYPO3.Flow/Migrations/Code/Version20120920111200.php
This changes the old core migration 20120920111200 to not
cause any trouble with newer code using PSR-4.
> TASK: de-corruptify old PSR-0 core migration

- TYPO3.Flow/Classes/TYPO3/Flow/Object/DependencyInjection/ProxyClassBuilder.php
- TYPO3.Flow/Tests/Functional/Object/Fixtures/PrototypeClassG.php
- TYPO3.Flow/Tests/Functional/Object/ObjectManagerTest.php
- TYPO3.Flow/Tests/Functional/Persistence/Doctrine/LazyLoadingTest.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/CleanupObject.php
- TYPO3.Flow/Tests/Functional/Persistence/Fixtures/Image.php
This change fixes #613 by creating the code to also call `shutdownObject()` on Doctrine Proxies. The proxy generation did not took into account that in `__wakeup()` the current Object can be an Instance of a Doctrine Proxy and therefore did not registered the `shutdownObject()` method on the ObjectManager.
As stated in #613 the temporary files from `Resource::createTemporaryLocalCopy()` where not removed, but with this fix they will be removed as expected.
Thanks to @monofone and @hlubek for support in finding the bug and implementing the solution and tests.
> BUGFIX: Fix calling shutdownObject() on doctrine proxy

- Neos.Flow/Migrations/Code/Version20131003152300.php
- Neos.Flow/Migrations/Code/Version20161115140400.php
- Neos.Flow/Migrations/Code/Version20161115140430.php
This fixes a problem with old core migrations which were touched
accidentally during the Neos vendor namespace change. These migrations
shouldn't have been touched since they are executed before the
vendor name change.
Now the old migrations may rest in peace with their old vendor name.
> BUGFIX: Undead core migrations unearthed and renamed

- .travis.yml
Now that PHP 7.1 is released, we should make sure we are compatible.
> TASK: Add PHP 7.1 to .travis.yml

- TYPO3.Flow/Classes/TYPO3/Flow/Http/Response.php
- TYPO3.Flow/Tests/Unit/Http/ResponseTest.php
The method setHeader accepts a value or an array of values, but until now if an arrays of values was given the renderHeaders method correctly rendered a seperate header for each value but during sending the ``header`` php-method overwrote the previously send headers because the replace argument was not given and defaults to ``true``.
> BUGFIX: Enable flow to send multiple http-headers of the same type

- Neos.Flow/Classes/Property/TypeConverter/ScalarTypeToObjectConverter.php
- Neos.Flow/Tests/Unit/Fixtures/ClassWithIntegerConstructor.php
- Neos.Flow/Tests/Unit/Fixtures/ClassWithStringConstructor.php
- Neos.Flow/Tests/Unit/Property/TypeConverter/ScalarTypeToObjectConverterTest.php
This introduces a simple type converter which can convert
a scalar value (string, integer, float or boolean) into an
object by passing that value to the class constructor.
This converter helps developers using Value Objects (not
managed by the persistence framework) or other Data
Transfer Objects in places where type conversion is
supported. One common case is to use Value Object class
names as a type hint for arguments in a command line
controller method.
> FEATURE: Scalar to object converter

- Neos.Cache/Classes/Frontend/FrontendInterface.php
- Neos.Flow/Classes/Cache/CacheManager.php
The ``CacheManager::getClassTag`` method was unused since
quite some time and became deprecated in previous releases.
It is therefore bound for removal in this major version.
Additionally the unused tagging constants in the ``FrontendInterface``
are removed as they are also no longer needed.
> !!! TASK: Remove deprecated ``getClassTag`` and constants

- Neos.Flow/Classes/Http/Request.php
The media type methods in the HTTP request class
have been deprecated since Flow 2.1 and are bound
to be removed in this release.
They were replaced by the dedicated MediaTypes utility.
> TASK: Remove deprecated media type methods

- Neos.Flow/Classes/Http/Request.php
- Neos.Flow/Tests/Unit/Http/RequestTest.php
- Neos.Flow/Tests/Unit/Security/RequestPattern/HostTest.php
The static method was deprecated since Flow 2.3 and is due for
removal.
Instead create an instance of ``ActionRequest`` via the ``new``
keyword.
> TASK: Remove deprecated ``Http\Request::createActionRequest``

- Neos.Flow/Classes/Mvc/Controller/Argument.php
- Neos.Flow/Tests/Unit/Mvc/Controller/ArgumentTest.php
The ``Argument::isValid`` method has been deprecated since
some time and is no longer in use.
It is therefore removed without replacement. Instead check
the validation result returned by ``Argument::getValidationResults``
for possible errors.
> TASK: Remove deprecated ``Argument::isValid`` method

- Neos.Flow/Classes/Core/Bootstrap.php
- Neos.Flow/Classes/Persistence/Generic/PersistenceManager.php
- Neos.Flow/Classes/Persistence/PersistenceManagerInterface.php
- Neos.Flow/Configuration/Objects.yaml
- Neos.Flow/Tests/Unit/Persistence/Generic/PersistenceManagerTest.php
The method was deprecated and removed from the interface some time
ago and now will finally not be called anymore. That also allows
removal of the PersistenceManager factory method in ``Bootstrap``.
> TASK: Cleanup removed ``PersistenceManagerInterface::initialize``

- Neos.Flow/Classes/ResourceManagement/ResourceManager.php
The method was deprecated with the rewrite for Flow 3.0 and is
now bound for removal.
> TASK: Remove ``ResourceManager::createResourceFromContent``

- Neos.Flow/Classes/Reflection/ReflectionService.php
In earlier versions of Flow the setting
``Neos.Flow.reflection.ignoredTags`` allowed for a simple list
of tags. Due to merging and unset issues this was changed to a
key/value list, with the key being the tag name and values being
boolean to indicate ignorance of the tag.
The old format is now no longer taken into account.
> TASK: Remove handling for deprecated ignoreTags format

- Neos.FluidAdaptor/Classes/ViewHelpers/Form/AbstractFormFieldViewHelper.php
``\Neos\FluidAdaptor\ViewHelpers\Form\AbstractFormFieldViewHelper``
has a ``hasMappingErrorOccured`` which was replaced with corrected
spelling as ``hasMappingErrorOccurred`` and is deprecated since
quite some time.
The wrongly spelled method is removed by this.
> TASK: Remove deprecated ``hasMappingErrorOccured`` method

- Neos.Flow/Classes/ResourceManagement/PersistentResource.php
The ``PersistentResource`` object retained a couple of getters
and setters from 2.x versions of Flow that were deprecated and
are now bound for removal.
> TASK: Remove deprecated hash getter and setter from Resource

- TYPO3.Flow/Configuration/Objects.yaml
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Http.rst
The documentation still recommended to create Requests through the `createFromEnvironment`
factory method, but that completely bypasses the HTTP components and hence leads to unexpected
results.
This change adjusts documentation and clearly states, that the factory method should not be used
to access the **current** request and response. Instead it is suggested to use the `RequestHandler`
for that purpose only.
> TASK: Adjust documentation recommendations to ComponentChain

- Neos.Flow/Classes/ObjectManagement/Configuration/ConfigurationBuilder.php
Currently the behaviour of a `Scope` annotation on an interface depends
on the amount of implementations. If there are multiple implementations
for the interface, then the configured interface scope is used all the time.
When there is only a single implementation, then that implementation will
override the configured interface scope.
This breaks for example in case of the `SystemLoggerInterface`. This
interface is marked singleton but the implementation is not because it is
reused for other loggers. The expected result is that the configured scope
of the interface is kept.
This change adjusts the behaviour and makes sure the `Scope` defined in
an interface is always respected.
> BUGFIX: Configured scope for interfaces is not overwritten

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Routing.rst
- TYPO3.Flow/Resources/Private/Installer/Distribution/Essentials/Configuration/Development/Caches.yaml.example
A follow-up to Ibc55b5a4939b42b7cf2a08ada52985aa04bb7b04
adjusting the Routing documentation and example configuration
to the Routing Cache that was renamed with Iac1bd27cd1f2869e597b696c896633f14703ec40
> BUGFIX: Adjust Documentation to renamed routing cache

- Neos.Flow/Classes/Property/TypeConverter/ScalarTypeToObjectConverter.php
This check if the current target type is an entity or a value object
and skip the type converter in this case to avoid nasty side effect.
> BUGFIX: ScalarTypeToObjectConverter should not convert entities

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartV/TypeConverterReference.rst
> TASK: Typo in the description of BooleanConverter

- Neos.Flow/Classes/Cache/CacheManager.php
- Neos.Flow/Classes/Configuration/ConfigurationManager.php
- Neos.Flow/Tests/Unit/Cache/CacheManagerTest.php
- Neos.Flow/Tests/Unit/Configuration/ConfigurationManagerTest.php
Since the changes to the ``ConfigurationManager``, using
``flushConfigurationCache`` leaves an empty configuration behind
which is only helpful when you really only want to flush caches.
In case a change was detected ``refreshConfiguration`` is more
appropriate as it leaves the ConfigurationManager in a usable
state afterwards.
> TASK: Use ``refreshConfiguration`` to refresh for compile run

- Neos.Flow/Tests/Unit/Cache/CacheFactoryTest.php
The ``CacheFactoryTest`` left a folder behind because it didn't
use the virtual file system because the mocked environment configuration
didn't return the right path.
This change fixes it and prevents the folder being created in the
actual filesystem.
> BUGFIX: Tests shouldn't leave folder behind

- Neos.FluidAdaptor/Classes/Core/Rendering/FlowAwareRenderingContextInterface.php
- Neos.FluidAdaptor/Classes/ViewHelpers/Validation/IfHasErrorsViewHelper.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Security/IfHasRoleViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Validation/IfHasErrorsViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/ViewHelperBaseTestcase.php
With the move to TYPO3Fluid the behavior of the `AbstractConditionViewHelper`
has been changed (see #746).
This fix adjusts the `validation.ifHasErrors` ViewHelper accordingly and adds
some minor cosmetic fixes.
Other condition ViewHelpers have been adjusted already.
Fixes: #747
> BUGFIX: Fix IfHasErrorsViewHelper

- Neos.Flow/Classes/Package/PackageManager.php
- Neos.Flow/Tests/Unit/Package/PackageManagerTest.php
This fix makes sure that the package type is always set in
composer manifests created via `PackageManager::createPackage()`
in order to prevent newly created packages (i.e. via the Kickstarter)
to be ignored from Flows object management.
Fixes: #782
> BUGFIX: Always set package type in newly created packages

- Neos.FluidAdaptor/Classes/Core/ViewHelper/AbstractViewHelper.php
- Neos.FluidAdaptor/Tests/Unit/Core/ViewHelper/AbstractViewHelperTest.php
ViewHelper render method arguments with multiple type
defintions in the docblock are now correctly registered
as mixed type arguments.
Fixes: #748
> BUGFIX: Fix support for multi-type render arguments

- Neos.Flow/Resources/Public/Error/Exception.css
This changes the CSS styling of exceptions screens to be better
readable (less contract).
> TASK: Improve styles for exception screen

- TYPO3.Flow/Classes/TYPO3/Flow/Command/HelpCommandController.php
And exception was thrown when a non existing core command was being
invoked, eg. due to a spelling mistake.
The exception stems from the fact that all core commands are considered
compiletime commands but handling of non existing command calls is
done by the ``HelpCommandController`` which itself was not compiletime
compatible. This change adapts it to use inject methods which resolves
the problem.
Note that in upmerges the injections must be adapted to changing dependencies.
Fixes: #794
> BUGFIX: Call of non existing core command issues proper error

- Neos.FluidAdaptor/Classes/Core/Rendering/RenderingContext.php
This allows to fetch the parser configuration after creating
a view to configure interceptors.
> TASK: Store ``Parser\Configuration`` in rendering context

- Neos.Cache/Classes/EnvironmentConfiguration.php
As mentioned in the github/neos/cache is the decalaration of the property maximumPathLength with a value and then requiring a value for that property inside the constructor that overwrites the declared value EVERY time a minor bug. So the parameter for the constructor should be changed to an optional with the deault value as set for declaration
> TASK: Change default value for maximumPathLength in EnvironmentConfiguration

- Neos.Flow/Classes/Cache/CacheFactory.php
in the environmental class "Neos\Cache\EnvironmentConfiguration" is a minor bug (PR #810). in the moment the bug is fixed the parameter $maximumPathLength has not to be set if its equal to the php constant PHP_MAXPATHLEN. In this case it can be removed from the constructor call
> TASK: Simplify EnvironmentConfiguration object instantiation

- Neos.Flow/Migrations/Mysql/Version20170110130149.php
- Neos.Flow/Migrations/Postgresql/Version20170110133146.php
This adds doctrine migrations for MySQL and Postgresql to adjust
foreign key and index names to the renamed package `Neos.Flow`.
Background:
Apparently the renamed indexes/keys were not catered for in
neos/flow-development-collection@3b6d38c1b5aa5ab8a51d3f657a720d0d17ae8700
Related: neos/neos-development-collection#1374
> BUGFIX: Add missing migrations after package renamings

- TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php
In case the configured exception handler class dies not exist,
the `ProductionExceptionHandler` is used instead. This allows
(force-)flushing the caches to work in more cases.
> BUGFIX: Use fallback if exception handler configured wrong

- Neos.FluidAdaptor/Classes/View/AbstractTemplateView.php
We used our own workaround to render a section directly without rendering
the surrounding template. Now that this is implemented in Fluid core we
can remove the code, but still need some small adaption code in order to
have assigned view variables available in the section when no variables
were given to the ``renderSection`` method.
In the future we should probably deprecate this behaviour and give the
necessary variables directly to the method.
> BUGFIX: Adapt to standalone section rendering in Fluid

- Neos.Flow/Classes/Mvc/Routing/UriBuilder.php
- Neos.Flow/Configuration/Settings.yaml
- Neos.Flow/Tests/Unit/Mvc/Routing/UriBuilderTest.php
Removed the long-deprecated compat flag for relative uri paths and the according code in the UriBuilder and UriBuilder test.
> !!! TASK: Remove deprecated support for relative uri paths

- Neos.Flow/Classes/Persistence/Doctrine/Query.php
- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Persistence.rst
- Neos.Flow/Tests/Functional/Persistence/Doctrine/QueryTest.php
- Neos.Flow/Tests/Functional/Persistence/Fixtures/SubEntity.php
Previously a query object like
`$query->logicalAnd($query->equals('related.property', 'foo'), $query->equals('related.otherProperty', 'bar'));`
would generate an SQL statement with two joins to the `related` entity, one for each condition, translating to
"get all objects that have any related entity with a `property` 'foo' and any related entity with `otherProperty` 'bar'".
With this change, it will only generate a single join and reuse the join for multiple conditionals, therefore translating the above query object to the more common
"get all objects that have a related entity with both a `property` 'foo' and `otherProperty` 'bar'"
This also improves performance of such queries by avoiding unnecessary joins.
> !!! BUGFIX: Reuse join aliases on same property paths

- Neos.Flow/Classes/Security/Authentication/Controller/AbstractAuthenticationController.php
- Neos.Flow/Classes/Security/Authentication/Token/PasswordToken.php
- Neos.Flow/Classes/Security/Authentication/Token/UsernamePassword.php
- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Security.rst
- Neos.Flow/Migrations/Code/Version20170125103800.php
- Neos.Flow/Tests/Functional/Security/AuthenticationTest.php
- Neos.Flow/Tests/Functional/Security/CsrfProtectionTest.php
- Neos.Flow/Tests/Unit/Security/Authentication/Token/PasswordTokenTest.php
- Neos.Flow/Tests/Unit/Security/Authentication/Token/UsernamePasswordTest.php
This change adjusts the path used for the POST argument
used for authentication with username and password to the
new vendor namespace.
Any application - and especially its Fluid templates and
JavaScript - relying on the old path needs to be updated.
This change provides a core migration which carries out
these changes.
Resolves #837
> !!! TASK: Rename [TYPO3][Flow][Security][Authentication]

- Neos.Utility.Files/Classes/Files.php
This change set the offset to 0 (default value in `file_get_contents`.)
PHP 7.1 changed the behaviour of `file_get_contents` regarding
negative offset (support for negative offsets has been added.)
Without this change the sites `Root.fusion` is not loaded, so that
`Files::getFileContents` return an empty string. Tested on PHP 7.1.0
and 7.0.12 (worked without this fix).
> BUGFIX: Files::getFileContents broken in PHP 7.1

- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Caching.rst
- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Http.rst
- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Security.rst
- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Templating.rst
- Neos.Flow/Tests/Unit/Security/Authorization/FilterFirewallTest.php
- Neos.FluidAdaptor/Tests/Unit/View/TemplatePathsTest.php
- Neos.FluidAdaptor/Tests/Unit/View/TemplateViewTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Form/AbstractFormFieldViewHelperTest.php
- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Form/AbstractFormViewHelperTest.php
This change removes some further TYPO3 occurrences and replaces
them by Neos.
Relates to #823
> TASK: Remove TYPO3 occurrences in docs and tests

- Neos.Flow/Migrations/Code/Version20170127183102.php
Replaces boot step names starting with `typo3.flow` with the renamed ones
starting with `neos.flow` in all PHP files.
> TASK: Add migration for renamed boot steps

- TYPO3.Flow/Classes/TYPO3/Flow/Object/ObjectManager.php
- TYPO3.Flow/Tests/Unit/Object/ObjectManagerTest.php
This fix allowes to build prototypes using factories by configuring
`scope: prototype` in the Objects.yaml
Before the object manager ignores the configuration and generates singletons everytime.
> BUGFIX: Allow factories to build prototypes

- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ReflectionService.php
Getting a class schema from the reflection service should work
when giving a doctrine proxy object instead of the actual entity.
Fixes: #561
> BUGFIX: ``ReflectionService::getClassSchema`` works with Proxies

- Neos.Flow/Classes/Command/DoctrineCommandController.php
- Neos.Flow/Classes/Persistence/Doctrine/Service.php
It is generally undesired to create migrations if there are still migrations
that could be migrated. This is now prevented in the command controller
unless the ``force`` argument is set to circumvent this security measure.
Fixes: #478
> TASK: Prevent generating migrations if new migrations available

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/PackageManagement.rst
Adds a note about the package type prefixes support.
Fixes: #503
> BUGFIX: Add documentation about package types

- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Resource.php
- TYPO3.Flow/Tests/Unit/Resource/ResourceTest.php
This change fixes an issue with the Resource object's
`setSha1()` method which fails if the given hexadecimal
number uses uppercase characters for A-F.
On some operating systems or third party services,
uppercase hashes may be used. `setSha1()` now accepts
values containing uppercase characters and normalizes
them to lowercase. Therefore, when you set a SHA1
with an uppercase hexadecimal string, `getSha1()`
will return it in lowercase.
Related to https://github.com/flownative/flow-google-cloudstorage/issues/4
> BUGFIX: Resource setSha1() fails on uppercase hash

- Neos.FluidAdaptor/Classes/Core/ViewHelper/AbstractConditionViewHelper.php
With the introduction of standalone Fluid the correct way to implement
custom condition ViewHelpers has changed but this was not reflected in
the doc block of the ``AbstractConditionViewHelper``. This change finally
adds the missing explanation.
Fixes: #746
> BUGFIX: Documented correct implementation of condition ViewHelpers

- TYPO3.Eel/Classes/TYPO3/Eel/AbstractParser.php
- TYPO3.Eel/Classes/TYPO3/Eel/EelParser.php
- TYPO3.Eel/Classes/TYPO3/Eel/FlowQuery/FizzleParser.php
- TYPO3.Eel/Resources/Private/Grammar/AbstractParser.peg.inc
- TYPO3.Eel/Resources/Private/Grammar/Eel.peg.inc
- TYPO3.Eel/Resources/Private/Grammar/Fizzle.peg.inc
The generated parsers ``AbstractParser``, ``EelParser`` and ``FizzleParser``
are excluded from proxy building as the include statement and the general
structure of these make them unsuitable for proxy-ing. This was only a bug
before if an AOP advice targeted the mentioned classes, now this cannot
happen anymore.
Fixes: #796
> BUGFIX: Peg generated parsers are excluded from proxy building

- Neos.Flow/Documentation/TheDefinitiveGuide/PartII/Requirements.rst
- Neos.Flow/Scripts/Migrations/Git.php
- Neos.Flow/Scripts/flow.php
Instead of using both, the Flow core uses the ``exec`` function throughout
now and the requirements documentation is updated accordingly.
Fixes: #634
> BUGFIX: Use ``exec`` everywhere instead of ``system``

- TYPO3.Flow/Classes/TYPO3/Flow/Object/Proxy/Compiler.php
As any original class might end on a comment line without newline we need to
add a newline as part of the proxy building to avoid putting the proxy
namespace declaration within a comment. Additionally adds a marker comment
declaring the beginning of the proxy code.
Fixes: #779
> BUGFIX: Proxy Compiler adds newline after end of original code

- TYPO3.Flow/Classes/TYPO3/Flow/Core/ClassLoader.php
If you have an old version of the AvailableProxyClasses in FLOW_PATH_DATA
and you change FLOW_PATH_TEMPORARY_BASE, always the old proxy classes
get loaded.
Resolves: #866
> BUGFIX: ClassLoader should load AvailableProxies from TEMPORARY_BASE

- Neos.FluidAdaptor/Classes/View/AbstractTemplateView.php
- Neos.FluidAdaptor/Classes/View/StandaloneView.php
- Neos.FluidAdaptor/Tests/Functional/View/StandaloneViewTest.php
The refactoring of Fluid to the Adaptor left some places with invalid handling
of request and format inside of Views. The code couldn't work in it's current
state and is now adapted.
Fixes: #848
> BUGFIX: Use request correctly in Fluid Views

- Neos.Flow/Classes/Security/Authorization/Interceptor/CsrfTokenMissing.php
- Neos.Flow/Configuration/Settings.yaml
Adds a custom Interceptor implementation for CSRF protection errors making
it easier to debug such errors.
Fixes: #531
Fixes: #660
> TASK: Improve exception message for AccessDeny interceptor

- Neos.Flow/Classes/Core/Booting/Scripts.php
- Neos.Flow/Classes/Reflection/ReflectionService.php
The reflection freezing process still used a removed method from packages,
this has been refactored as the information needed is already available and
just needed to be cached.
Additionally a bit of clean up was done while looking at it.
Fixes: #743
> BUGFIX: Cleanup of reflection freezing

- TYPO3.Flow/Classes/TYPO3/Flow/Security/Account.php
- TYPO3.Flow/Tests/Functional/Security/AccountTest.php
**What I did**
I fixed ``Account::isActive()`` behavior when an expirationDate is set.
The "Now" injection is now non-lazy, thus the comparison of DateTime objects works.
Run the new functional test ``TYPO3.Flow/Tests/Functional/Security/AccountTest.php``
**Checklist**
Resolves #873
> BUGFIX: Consider accounts with ``expirationDate`` in the future as active

- Neos.FluidAdaptor/Classes/Core/ViewHelper/ViewHelperResolver.php
Due to the way the namespace to ViewHelpers in packages was constructed
it resulted in rather strange errors trying to use one of the automatically
prepared namespaces in a template.
The namespaces are now constructed accordingly depending on the autoload type.
> BUGFIX: Automatic fluid namespace work with PSR-4 autoload paths

- Neos.Flow/Classes/Property/PropertyMapper.php
- Neos.Flow/Classes/Property/TypeConverter/ObjectConverter.php
- Neos.Flow/Tests/Functional/Property/PropertyMapperTest.php
- Neos.Flow/Tests/Functional/Property/TypeConverter/ObjectConverterTest.php
This change enables the ObjectConverter (for simple PHP objects)
to acknowledge the `skipUnknownProperties` flag of the property
mapping configuration and thus ignore properties from the source
which don't exist in the target.
If a source array contains properties "foo" and "bar" and the
target class constructor only contains "foo", the array can now
be mapped if `skipUnknownProperties` is set in the respective
property mapping configuration.
> FEATURE: Skip unknown properties for ObjectConverter

- Neos.Flow/Documentation/TheDefinitiveGuide/PartI/Object-OrientedProgramming.rst
- Neos.Flow/Documentation/TheDefinitiveGuide/PartII/Configuration.rst
Two small typo
1. doubled «is is» to «it is»
2. doubled «our our» to «our»
> TASK: Improve documentation on Object-OrientedProgramming

- TYPO3.Flow/Resources/Private/Cache/SQL/DDL.sql
When not using SQLite for the `PdoBackend` and manually creating
the cache tables by using the `DDL.sql`, the content column of the
cache table with type `TEXT` could easily lead to cropped
caching entries because of the length restriction.
Using `MEDIUMTEXT` practically prevents this issue.
See also: neos/flow-development-collection#884 and
neos/flow-development-collection#885
> TASK: Increase max-length for cache entries in PdoBackend

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Caching.rst
When using the PdoBackend with MySQL for caching,
the needed caching tables have to be created manually.
This adds a hint on creating the tables to the documentation
on the PdoBackend.
Solving the documentation part of neos/flow-development-collection#884
This depends on #886
> TASK: Add documentation for using PdoBackend with MySQL

- TYPO3.Flow/Classes/TYPO3/Flow/Property/PropertyMapper.php
As ``$this->typeConverters`` is not filled during this method, as this method will provide the necessary information, we need to access ``$typeConverterMap`` which contains the class name already.
**What I did**
Fix accessing empty array.
Accessing method internal existing array containing the necessary information.
Register two TypeConverters for same conersion with same priority.
**Checklist**
I could not find any information about Flow at the given url.
> Bugfix accessing empty array

- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/ResourceManagement.rst
The ``PersistentResource`` no longer provides a ``__toString()``, so adjust
documentation to that.
> BUGFIX: Update docs to code changes

- Neos.Flow/Classes/Package/PackageManager.php
- Neos.Flow/Classes/Package/PackageManagerInterface.php
This was originally scheduled for 4.0 but forgotten. It is added now,
excuse the inconvenience. But you should really not be implementing
your own PackageManager.
> !!! TASK: Add rescanPackages() to PackageManagerInterface

- Neos.Flow/Classes/Core/Booting/Scripts.php
This is legacy code in such a bad way...
> TASK: Remove requireAutoloaderForPhpUnit() from Booting\Scripts

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/ResourceManagement.rst
- Without this annotation it will not be possible to generate doctrine
migration.
> TASK: Add missing model annotation in documentation

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/EntityManagerFactory.php
#When using more than one doctrine backend, you have to make sure to set TYPO3.Flow.persistence.doctrine.secondLevelCache, or else you will get "An error occurred in the Database Abstraction Layer." as an exception which doesn't tell you much. By throwing an approriate exception we make clearer what the problem is.
> TASK: throw InvalidConfigurationException if there are no secondLevelCache settings for doctrine

- Neos.Eel/Classes/AbstractParser.php
- Neos.Eel/Classes/FlowQuery/FizzleParser.php
- Neos.Eel/Classes/FlowQuery/Operations/Object/FilterOperation.php
- Neos.Eel/Resources/Private/Grammar/AbstractParser.peg.inc
- Neos.Eel/Resources/Private/Grammar/Fizzle.peg.inc
- Neos.Eel/Tests/Unit/FlowQuery/FizzleParserTest.php
- Neos.Eel/Tests/Unit/FlowQuery/FlowQueryTest.php
**What I did**
Implements #899. I extended the FlowQuery grammar to filter nested object properties.
It was not possible to just extend the `Identifier` rule in `AbstractParser.peg.inc` since that led to a lot of regressions in the Eel parser. Thus, a new rule `PropertyPath` was necessary.
Unit-Tests in Neos.Eel run successfully.
> TASK: #899 Make Fizzle filter nested object properties

- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ReflectionService.php
Injected properties were always ignored in the persistence class schema as
it makes no sense to persist injected properties. Same is obviously true for
injected configuration, but this was never done so this change ignores
properties with a ``InjectConfiguration`` annotation.
This may be breaking if you use ``InjectConfiguration`` on a property that you
actually want to persist (which is not a good idea anyway). You would need to
add another property with the inject annotation and pass the value over to the
persisted property in ``initializeObject`` for example.
> BUGFIX: Injected configuration should also be ignored in class schema

- TYPO3.Flow/Configuration/Settings.yaml
The cookie domain was allowed to be set with a leading dot to signal
that it should be valid for all subdomains. This was later changed in
the current RFC 6265. Our ``Session`` implementation checks for domains
without leading dot, while the comment suggested to use it. This is now
matched.
Fixes: neos/neos-development-collection#813
> BUGFIX: Correctly document usage of ``...cookie.domain`` setting

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/EntityManagerFactory.php
- TYPO3.Flow/Classes/TYPO3/Flow/Security/Context.php
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Persistence.rst
- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Security.rst
If you had used entity security and wanted to secure entities not just
based on the user's role, but on some property of the user (like the company
he belongs to), entity security did not work properly together with doctrine
caching.
If you had Entity Constraints which did not only rely
on different user roles, but needed the domain model to build up SQL 
constraints (through entity security), the query
cache in production cached the SQL queries "wrongly", so you were able to
see data from other accounts.
Inside the Doctrine CacheAdapter, we already namespace the full Doctrine
cache with the SecurityContext's ContextHash. However, only roles were
the source of the ContextHash.
We now make it possible to add custom sources to the calculation of the
ContextHash, by making aop.globalObjects …
> !!! BUGFIX: fix Entity Security depending on more than just roles

- TYPO3.Flow/Classes/TYPO3/Flow/Aop/Builder/ProxyClassBuilder.php
- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Generic/Backend/AbstractBackend.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/ResourceManager.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Storage/WritableFileSystemStorage.php
- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Target/FileSystemSymlinkTarget.php
- TYPO3.Flow/Classes/TYPO3/Flow/Security/Cryptography/RsaWalletServicePhp.php
- TYPO3.Flow/Classes/TYPO3/Flow/Security/Cryptography/SaltedMd5HashingStrategy.php
- TYPO3.Flow/Classes/TYPO3/Flow/Session/TransientSession.php
This reduces the risk of collision on temporary filenames and other
identifiers and data.
> TASK: Use generateRandomString() instead of uniqid()

- Neos.Utility.Files/Classes/TYPO3/Flow/Utility/Files.php
With PHP 7.1 the behavior of `file_get_contents()` has been changed
allowing negative offsets to be specified.
This change adjusts the signature of `TYPO3\Flow\Utility\Files::getFileContents()`
accordingly.
*Note:* This is a backport of #821 which has only been applied to the 4.0 branch
Fixes: neos/neos-development-collection#1301, #847
> BUGFIX: Fix support for PHP 7.1

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/PersistenceManager.php
- TYPO3.Flow/Tests/Unit/Persistence/Doctrine/PersistenceManagerTest.php
If a `\Doctrine\DBAL\DBALException` is thrown in `persistAll()`, a reconnect will be attempted,
but only if `EntityManager->isOpen()` returns true. Otherwise the exception is re-thrown.
Before the connection to the server was sometimes never re-established, since only the specific
Flow\Error\Exception was caught.
Also this will prevent hiding exceptions that result in a closed EntityManager.
Fixes #870
> BUGFIX: Attempt reconnect only if EntityManager is open

- Neos.Flow/Classes/ResourceManagement/Storage/WritableFileSystemStorage.php
This is a follow-up to 35a02528d8aec53f0769a9f16c3dabbca690fbf8
> BUGFIX: really fix wrong namespace after merge

- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Validation.rst
The case that a form displaying action is not annotated to ignore validation of domain models
leads to infinite dispatch loops when validation fails. This was not documented well enough.
This change adds an explicit section inside the Validation documentation about this scenario.
> TASK: Improve validation documentation to avoid infinite loops

- TYPO3.Flow/Classes/TYPO3/Flow/Core/Bootstrap.php
This misleading message was introduced in a0a1453d87053e2c17b954804c61c5c03fa00c89
due to too much javascript work being done.
> TASK: Fix error message to correctly refer to composer.json

- Neos.Flow/Classes/Configuration/ConfigurationManager.php
- Neos.Flow/Tests/Unit/Configuration/ConfigurationManagerTest.php
Custom configuration types of processing type settings could break
the compile process as the array wouldn't have the custom configuration
name as key set because it was never initialized in this processing
type.
This change initializes any configuration type with an empty array in
the beginning and provides a test to proof the behavior.
Fixes: #934
> BUGFIX: ConfigurationManager should never have empty configuration

- TYPO3.Flow/Resources/Private/Schema/Routes.schema.yaml
Previously the route parts were evaluated correct regardless of the configured keys because the schema used the configuration `additionalAttributes = FALSE` instead of `additionalProperties = FALSE`. This is fixed and the schema is updated 
- validate the keys in route parts strictly
- allow configuration of `objectType` and  `uriPattern ` instead of `handler`
- allow `options` and `toLowerCase` for all routeParts
> TASK: Adjust schema of routes configuration

- TYPO3.Flow/Tests/Unit/Resource/Target/FileSystemTargetTest.php
The test would create a Flow package in the current installation as the
package manager in the test was not prepared with a virtual filesystem.
> BUGFIX: FileSystemTargetTest shouldn't have side effects

- TYPO3.Flow/Classes/TYPO3/Flow/Http/Headers.php
- TYPO3.Flow/Tests/Unit/Http/HeadersTest.php
This prevents the exception that is thrown when a cookie has an invalid name.
See the discussion here: https://discuss.neos.io/t/ignore-invalid-cookies-instead-of-throwing-an-exception/2234
> TASK: Ignore invalid cookie names instead of throwing an exception

- Neos.Flow/Classes/Persistence/Doctrine/Service.php
This fixes a regression introduced with #857 that made the
`doctrine:migrationstatus` CLI command fail with a PHP notice
if the `--show-migrations` flag was used.
Fixes: #976
> BUGFIX: Fix `doctrine:migrationstatus` command

- Neos.Flow/Tests/Unit/Package/PackageOrderResolverTest.php
- Neos.FluidAdaptor/Classes/View/TemplatePaths.php
Changes some package names used in a test and a comment in a class
to no longer mention TYPO3, TypoScript or TYPO3CR.
> TASK: Remove TYPO3 and TypoScript uses from code

- Neos.Flow/Classes/Composer/ComposerUtility.php
- Neos.Flow/Classes/Composer/Exception/InvalidPackageManifestException.php
Since I just ran into that one and it took me a while to figure out why Flow was throwing a "Composer Manifest does not contain a "name" field", I added a distinct exception for the case when a composer manifest does exist, but cannot be parsed from JSON.
> TASK: Add a distinct exception for existing, but invalid composer manifests

- TYPO3.Flow/Classes/TYPO3/Flow/Aop/Builder/ProxyClassBuilder.php
When introducing a trait using AOP it now works if the class only has traits introduced via AOP.
> BUGFIX: Trait AOP works when only introduces traits to class

- TYPO3.Flow/Migrations/Mysql/Version20130319131400.php
- TYPO3.Flow/Migrations/Mysql/Version20141015125841.php
- TYPO3.Flow/Migrations/Mysql/Version20141113173712.php
- TYPO3.Flow/Migrations/Mysql/Version20150611154419.php
- TYPO3.Flow/Migrations/Postgresql/Version20130319131500.php
- TYPO3.Flow/Migrations/Postgresql/Version20141118174722.php
- TYPO3.Flow/Migrations/Postgresql/Version20150611154421.php
This adds `TABLE EXISTS` checks to all places where doctrine
migrations directly executes SQL queries in order to prevent
`./flow doctrine:migrate` to fail with `--dry-run` or `--output`
flag set.
Background:
Doctrine needs to execute the migrations in order to determine
the SQL they generate - even during "dry run".
In some migrations we access the database directly in order to
migrate data.
To avoid that these queries fail if the corresponding tables haven't
been created yet, this patch adds safeguards respectively.
NOTE: There are still a few places where we perform *mutations* in
the `postUp()`/`postDown()` hooks. Those will still be executed in
"dry run" mode if the table in question exists in the database!
Fixes: #974
> BUGFIX: Doctrine migration SQL query safeguards

- TYPO3.Flow/Tests/Functional/Security/Authentication/Provider/PersistedUsernamePasswordProviderTest.php
- TYPO3.Flow/Tests/Unit/Persistence/Generic/DataMapperTest.php
This adjusts one unit test and two functional tests that
were comparing two `\DateTime` instances which, since PHP 7.1,
are not equal if the microsecond portion differs.
Background:
This is a backport of 4d77de57481c05a5018a8cc947e9da4adc9ab52c
which was only applied to branch 4.0+
> BUGFIX: Fix DateTime tests for PHP 7.x

- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageManager.php
Without this change a package (defined by composer name eg. "neos/party")
that exists two times in the installation would be silently ignored and added
with the second path found.	This could still result in strange effects
happening as autoload and Flow internal paths (configuration, resources) could
diverge.
With this change an exception is thrown when the package states are resolved
and a package is found a second time.
Fixes: #611
> TASK: Throw error if package exists two times

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/AspectOrientedProgramming.rst
Trait introduction is available since some time, but it was never
documented. This change adds a short explanation with a code
example to fix that.
> TASK: Add missing documentation for trait introduction

- TYPO3.Flow/Classes/TYPO3/Flow/Package.php
Previously the `bootstrapShuttingDown` signal was connected with the
`CacheManager::flushCaches()` method directly passing arguments of the
signal on. The first parameter, being the Boostrap `runLevel` flag was
casted to `true`, so that all caches were flushed.
This is fixed by explicitly calling `CacheManager::flushCaches()` in
a closure.
Fixes: #994
> BUGFIX: Don't flush persistent caches when package state changes

- TYPO3.Flow/Classes/TYPO3/Flow/Aop/Pointcut/RuntimeExpressionEvaluator.php
This improves the error message on missing AOP runtime expressions
just a little.
> TASK: Better message on missing runtime expression

- TYPO3.Flow/Classes/TYPO3/Flow/Http/Client/CurlEngine.php
Extended CurlEngine for request-type HEAD to set the option to not expect a body.
resolves #992
> BUGFIX: Add handling of HTTP HEAD-request with curl

- Neos.Flow/Classes/Package/PackageManager.php
Otherwise an undefined Exception is thrown.
> BUGFIX: Add missing ``PackageManager`` use statement

- TYPO3.Flow/Tests/Unit/Resource/Target/FileSystemTargetTest.php
The FileSystemTargetTest was fixed earlier to no longer create a stub
of a package during test runs in the real filesystem see PR #966.)
The test still created a stub package, because the FileSystemTarget
was told to publish to a vfs location - but that option is only used
if initializeObject() is called, which in unit tests does not happen
automagically.
> BUGFIX: FileSystemTargetTest shouldn't create package stub

- TYPO3.Flow/Classes/TYPO3/Flow/Mvc/Routing/UriBuilder.php
- TYPO3.Flow/Tests/Unit/Mvc/Routing/UriBuilderTest.php
Adds handling for the `@format` argument when merging arguments
from the request hierarchy to keep the format when building
URIs from a sub request.
Fixes neos/neos-development-collection#1596
> BUGFIX: Keep format for URIs built in subrequests

- Neos.Kickstarter/Classes/Command/KickstartCommandController.php
You can now do `./flow kickstart:package Foo.Bar --packageType neos-plugin`, like in the PackageCommandController.
A question regarding the docs: Is the "Command Reference" part of the documentation autogenerated? If so, it seems to be outdated, because there are still some mentions of typo3 in there.
> FEATURE: Allow setting the package type when kickstarting a package

- TYPO3.Flow/Classes/TYPO3/Flow/Mvc/ActionRequest.php
- TYPO3.Flow/Tests/Unit/Mvc/ActionRequestTest.php
This prevents an exception in case an argument name is evaluated to
another simple type (integer) but can be converted to string easily.
Fixes: #612
> BUGFIX: Integer argumentName should not result in an exception

- Neos.Flow/Classes/Command/CoreCommandController.php
- Neos.Flow/Tests/Behavior/Features/Bootstrap/SubProcess/SubProcess.php
On Windows, the `PHP_BINDIR` constant will resolve to "C:\php" no matter what the actual php directory is, because this constant is decided at compile time. However, the `PHP_BINARY` constant will resolve to the current executable that runs the script at runtime, which at least for CLI will be the PHP executable.
> BUGFIX: Make CLI subprocesses work on Windows

- Neos.Eel/Classes/Helper/ArrayHelper.php
- Neos.Eel/Tests/Unit/Helper/ArrayHelperTest.php
The range method is a wrapper around the php range function that creates a sequence of integers or characters as array. This is especially helpful to create paginations in pure fusion.
> FEATURE: Add `range` method to Eel Array-helper

- TYPO3.Flow/Classes/TYPO3/Flow/Security/Authentication/Controller/AbstractAuthenticationController.php
Sometimes (especially in Neos) on logout the CSRF token is missing (`CsrfTokenMissing` interceptor). No harm in ignoring it here.
> BUGFIX: Annotate logoutAction with SkipCsrfProtection

- Neos.Utility.ObjectHandling/Classes/ObjectAccess.php
By using `array_key_exists()` instead of `isset()`, properties set to `null` will be detected as existing.
> BUGFIX: ObjectAccess should care for properties set to NULL

- Neos.Flow/Classes/Mvc/Controller/ActionController.php
- Neos.Flow/Tests/Functional/Mvc/ActionControllerTest.php
- Neos.Flow/Tests/Functional/Mvc/Fixtures/Controller/ActionControllerTestBController.php
- Neos.Utility.ObjectHandling/Classes/TypeHandling.php
- Neos.Utility.ObjectHandling/Tests/Unit/TypeHandlingTest.php
This change allows action arguments to be annotated "|null" or "null|" when they are optional with default value `null`. Before the type conversion would fail because no matching type converter would be found.
Resolves #927
> FEATURE: Allow Nullable action params to be annotated

- Neos.Utility.Files/Tests/Unit/FilesTest.php
On windows it is not unlikely that symlinking does not work due to missing access rights.
In that case a lot of the Files tests fail without any helpful notice and eventually lead
to the developer ignoring the failures, possibly overlooking real failures.
This change makes such symlink failures on Windows skip the test instead.
> TASK: Skip symlink tests on windows when symlinking fails

- Neos.Flow/Tests/Functional/Mvc/RoutingTest.php
The functional tests for the Router haven't been adjusted to the
Package renaming `TYPO3.Flow` => `Neos.Flow`.
> BUGFIX: Fix RoutingTests

- Neos.Flow/Classes/ObjectManagement/ObjectManager.php
- Neos.Utility.ObjectHandling/Classes/ObjectAccess.php
This static method allows instantiating a given class with
and array of arguments in an efficient way.
Most of this method was previously hidden in the ``ObjectManager``
of Flow but as the same code is replicated in other packages it
makes sense to open it as generic method for re-use.
> FEATURE: Introduce ``ObjectAccess::instantiate``

- TYPO3.Eel/Classes/TYPO3/Eel/EelParser.php
- TYPO3.Eel/Resources/Private/Grammar/Eel.peg.inc
- TYPO3.Eel/Tests/Unit/AbstractEvaluatorTest.php
This change allows expressions like:
{ foo: "bar", bar: "baz" }
or
{
foo: "bar",
bar: "baz"
}
to be parsed correctly in EEL
The change extends the EEL PEG grammar (in `Eel.peg.inc`) to be tolerant towards
whitespace (as well as line wraps) in object and array literals.
This fixes #986
> BUGFIX: Allow array and object literals to be padded with whitespace in Eel

- Neos.FluidAdaptor/Tests/Unit/ViewHelpers/Format/CaseViewHelperTest.php
A data provider named testSomething() is seen as a test, leading to
a warning about a test not doing any assertions.
Don't do that.
> TASK: Remove a "risky test" warning

- Neos.Cache/Tests/Unit/Backend/RedisBackendTest.php
Some tests failed with
Return value of Neos\Cache\Backend\RedisBackend::isFrozen() must
be of the type boolean, null returned
after the introduction of return type declarations.
> BUGFIX: Fix TypeError in RedisBackendTest

- Neos.Flow/Classes/Property/PropertyMappingConfiguration.php
This changes `allowProperties()`, `skipProperties()` and `allowAllPropertiesExcept()`
to declare a string-typed `$propertyNames` argument instead of using `func_get_args()`.
> TASK: Remove use of func_get_args() in PropertyMappingConfiguration methods

- Neos.Flow/Classes/Command/ResourceCommandController.php
Implement a separate try/catch blog for each collection so as many collections as possible get published. Fixes could then be done for just the broken collection without running the full command once again.
Extends the Issue: Catch errors while publishing invalid resources #958 (Error Handing for each Resource needs to be done in each Target Class. The native Flow Target Classes already take care about continuing to publish resources)
> TASK: Catch exceptions separately for published resource collections

- Neos.Error.Messages/Classes/Message.php
The `getCode()` method declares int as return type, but it can happen
that the internal code is `null`, leading to a type error.
This adjusts the code so the internal code is always an integer.
> BUGFIX: Avoid type error with Message->getCode()

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/PersistenceManager.php
- TYPO3.Flow/Tests/Unit/Persistence/Doctrine/PersistenceManagerTest.php
This adds a `try/catch` block around the `$connection->ping()` call that
throws an exception if no database credentials are configured (which is
the case when you do a fresh install of Flow or Neos).
Fixes: #1663
> BUGFIX: Catch ConnectionExceptions in `PersistenceManager::persistAll()`

- Neos.Eel/Classes/Helper/DateHelper.php
- Neos.Eel/Tests/Unit/Helper/DateHelperTest.php
This change adds CLDR formatting capability to the Date Eel helper, to match
the functionality of the `format.date` Fluid ViewHelper.
**P.S.** This PR has taken over from https://github.com/neos/flow-development-collection/pull/920
All the history can be found the. The original code was written by @litovchenko1, I
(@zaveryukha) have added the unit tests.
> FEATURE: Add Date.formatCldr helper

- Neos.Error.Messages/Classes/Message.php
Also, this allow the code of the message to be null in `getCode()`, since
that is the more sane behaviour from an API point of view.
Fixes neos/neos-development-collection#1666
> TASK: Error Message accepts null as message title

- TYPO3.Flow/Classes/TYPO3/Flow/Cache/Backend/RedisBackend.php
This adds the (already documented) password option to the `RedisBackend` class.
> BUGFIX: Add password option to RedisBackend

- TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageManager.php
The error code for the Package Manager error on duplicate packages was
a millisecond timestamp. Since this is larger than MAX_INT PHP parses
this as float, which in turn is not accepted as parameter for an
exception code.
> BUGFIX: Avoid a syntax error from hiding the intended error message

- TYPO3.Flow/Classes/TYPO3/Flow/Command/ConfigurationCommandController.php
During development it's a common requirement to output
the configuration for a given path.
Previously that always required the configuration *type*
to be specified like::
./flow configuration:show --type Settings
With this change the type is optional and defaults to "Settings"
which is commonly the most interesting type for this command.
> TASK: Make "type" argument optional in "configuration:show" CLI command

- TYPO3.Flow/Classes/TYPO3/Flow/Http/Component/TrustedProxiesComponent.php
- TYPO3.Flow/Tests/Unit/Http/Component/TrustedProxiesComponentTest.php
Some proxies like apache's mod_proxy set the port from the forwarded
connection in the `X-Forwarded-Host` header, e.g. `acme.com:443`.
This change adjusts the TrustedProxy component to allow setting the
forwarded port inside the Host header.
If the `X-Forwarded-Port` header is also present, that one will take
precedence though.
Fixes #1054
> BUGFIX: Support proxies forwarding the port in the Forwarded-Host header

- Neos.Cache/Classes/Backend/RedisBackend.php
The scalar type hint for `compress()` forced the return value of uncompress() to an emtpy string if there is no value in redis. This has to be false.
> BUGFIX: Don’t use scalar type hint string for RedisBackend

- Neos.Utility.Unicode/Classes/Functions.php
The `int` type hint of `strpos(string $haystack, string $needle, int $offset = 0): int` casts a `FALSE` result of `mb_strpos` to `0`, which leads to a wrong result if `$haystack` does not contain `$needle`.
**Checklist**
> BUGFIX: Result type hint leads to wrong function result

- Neos.Cache/Classes/Backend/RedisBackend.php
This fixes another small error in the return typehints introduced in 4.2
> BUGFIX: RedisBackend key() method return typehint was wrong

- Neos.Flow/Classes/Http/Request.php
I created an image upload for our Flow application. After updating Flow, it stopped working, because two array keys do not exist. To fix this error I suggest making these keys optional.
`$argumentsForValue['originallySubmittedResource']` and `$argumentsForValue['__collectionName']` must not exist. The file upload should not break, if these array keys are missing.
**Checklist**
> BUGFIX: Allow file uploads without arguments for value

- Neos.Flow/Classes/Http/Request.php
**What I did**
Change the condition to ``!empty``, so that NULL-values get catched and will not tried to be set, which causes further errors.
> BUGFIX:  Use ``!empty`` instead of ``empty`` in condition

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php
The `FlowAnnotationDriver` uses a wrong property of a loaded `Index` annotation object, preventing partial indexes being created on DB platforms supporting it.
Retargeted follow-up to #1074
> BUGFIX: Annotation reader breaks partial index creation

- TYPO3.Flow/Classes/TYPO3/Flow/Http/Client/CurlEngine.php
- TYPO3.Flow/Classes/TYPO3/Flow/Http/Response.php
- TYPO3.Flow/Tests/Functional/Http/Client/CurlEngineTest.php
Under some circumstances, curl will return all the headers of the request
chain, for example when the CURLOPT_FOLLOWLOCATION option is set.
This change will make the CurlEngine follow the chain of response headers
until the final response.
Fixes #1044,  #849, #570
> BUGFIX: CurlEngine follows chain of Http headers

- Neos.Flow/Classes/Property/PropertyMapper.php
- Neos.Flow/Classes/Property/TypeConverter/ScalarTypeToObjectConverter.php
- Neos.Flow/Classes/Property/TypeConverter/StringConverter.php
- Neos.Flow/Tests/Functional/Property/Fixtures/TestClass.php
- Neos.Flow/Tests/Functional/Property/PropertyMapperTest.php
- Neos.Flow/Tests/Unit/Fixtures/ClassWithBoolConstructor.php
- Neos.Flow/Tests/Unit/Property/PropertyMapperTest.php
- Neos.Flow/Tests/Unit/Property/TypeConverter/ScalarTypeToObjectConverterTest.php
- Neos.Flow/Tests/Unit/Property/TypeConverter/StringConverterTest.php
**What I did**
Found a bug in the propertymapping when mapping from scalar bool to object. Fixed it in the Typeconverter and added tests 
Fixed the ScalarTypeToObjectConverter for bool scalar type.
A ValueObject with the constructor signature containing `__construct(bool $value)` can be build from a scalar boolean value.
**Checklist**
> BUGFIX: Force PropertyMapper to correctly handle bool in constructor

- Neos.Kickstarter/Classes/ViewHelpers/Format/UcfirstViewHelper.php
The example lacks the `format` prefix.
> BUGFIX: Fix code example in UcfirstViewHelper docblock

- TYPO3.Kickstart/Resources/Private/Generator/Controller/ActionControllerTemplate.php.tmpl
- TYPO3.Kickstart/Resources/Private/Generator/Controller/CommandControllerTemplate.php.tmpl
- TYPO3.Kickstart/Resources/Private/Generator/Controller/CrudControllerTemplate.php.tmpl
- TYPO3.Kickstart/Resources/Private/Generator/Model/EntityTemplate.php.tmpl
- TYPO3.Kickstart/Resources/Private/Generator/Repository/RepositoryTemplate.php.tmpl
The PSR2 standard says: Opening braces for classes MUST go on the next line, and **closing braces MUST go on the next line after the body.**
This is currently not implemented by the Templates and this commit is fixing it.
**Checklist**
> TASK: Make PHP-Templates PSR2-compatible

- Neos.Flow/Classes/Property/TypeConverter/ScalarTypeToObjectConverter.php
**What I did**
Fixed the ScalarTypeToObjectConverter to expose boolean as supported sourceType instead of bool
Used the keyboard
The TypeConverter now works for boolean values
**Checklist**
> BUGFIX: The ScalarTypeToObjectConverter should expose boolean instead of bool

- TYPO3.Eel/Classes/TYPO3/Eel/FlowQuery/Operations/Object/FilterOperation.php
- TYPO3.Eel/Tests/Unit/FlowQuery/FlowQueryTest.php
This fixes #1048 by making sure that `strpos()` recieves two strings instead of a
string and a number in a Fizzle filter operation (`*=`, `^=`, `$=`), making sure that
it will look for the actual number in the string it is comparing the operand to instead
of looking for the char that is represented by the number as a unicode ordinal number.
It does this by casting the variable in which the operand is saved to string where it
is given to the strpos/strrpos function as a parameter.
> BUGFIX: Make string-based Fizzle filters treat numbers as strings

- TYPO3.Eel/Tests/Unit/FlowQuery/FlowQueryTest.php
The newly added test in https://github.com/neos/flow-development-collection/pull/1085 made the test fail in PHP 7.1 due to wrongly trying to concat strings with `+`.
> TASK: Fix FlowQuery Tests for PHP 7.1

- TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Security.rst
This fixes markup for some numbered lists in the security documentation.
> TASK: Fix some numbered lists in security documentation

- TYPO3.Flow/Resources/Private/Installer/Distribution/Defaults/.editorconfig
This introduces a default ``.editorconfig`` file in the root of the freshly created project.
It ensures that php follows the PSR-2 coding-style, yaml gets 2 spaces indentation and md files doesn't trim trailing whitespace.
> TASK: Add a default .editorconfig

- TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ReflectionService.php
As `void` was not on the list of return types that would be
normalized to include a leading backslash in the reflection
data it would be output wrongly in proxy classes and so break
applications that used it.
Fixes: #1065
> BUGFIX: Correct use of `void` return type in proxy classes

- Neos.Flow/Classes/Property/PropertyMapper.php
- Neos.Flow/Classes/Property/TypeConverter/ScalarTypeToObjectConverter.php
- Neos.Flow/Tests/Functional/Property/Fixtures/BoolToIntConverter.php
- Neos.Flow/Tests/Functional/Property/Fixtures/TestClass.php
- Neos.Flow/Tests/Functional/Property/PropertyMapperTest.php
- Neos.Flow/Tests/Unit/Fixtures/ClassWithBoolConstructor.php
- Neos.Flow/Tests/Unit/Property/TypeConverter/ScalarTypeToObjectConverterTest.php
This re-applies the original fix (#1083) with some adjustments
in order to prevent regressions:
* The `StringConverter` is no longer incorrectly adjusted
* The `PropertyMapper` now normalizes source and target types
to build the "typeConverterMap"
As a result, TypeConverters can now specify short and long version
in the source/target type definition.
Background:
The original fix was mainly an adjustment to `ScalarTypeToObjectConverter`
to normalize the constructor param type in order to allow simple types
to be mapped to classes with a single `bool` or `int` constructor argument.
But it also adjusted the `StringConverter` breaking the Neos export (see
neos/neos-development-collection#1732).
Credits to @monofone for the original patch!
Related: #1083
Related: #1109
> BUGFIX: Allow TypeConverters to use the short name for bool and int

- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Persistence.rst
The behaviour of `doctrine:migrationgenerate` has changed, this updates
the documentation accordingly.
> TASK: Update section on generating migrations

- TYPO3.Flow/Classes/TYPO3/Flow/Resource/Storage/PackageStorage.php
- TYPO3.Flow/Configuration/Settings.yaml
Due to the defined resource paths (which are not taken into account
for the FileSystemSymlinkTarget) only files in subdirectories of
the public resource path were published. This change adds the public
path itself and adjusts the PackageStorage to take into account
an empty relative publication path. Additionally does a slight
refactoring to make the whole class easier to follow.
Fixes: #1055
> BUGFIX: FileSystemTarget publishes resources in public root

- Neos.Flow/Classes/I18n/Xliff/Service/XliffFileProvider.php
This modification fixes the translation fallback mechanism and the ability to read regionalized language variants.
Issues fixed:
* Translation fallback did not work. `Neos.Flow.i18n.fallbackRule.order` was ignored when looking for XLIFF files
* When using a regional `Neos.Flow.i18n.defaultLocale` (e.g. `de_AT` for an Austrian version of `de`), XLIFF files were never read from  a directory with the full `defaultLocale` name, but only from the base language directory. In the example, files in `Packages/Application/Vendor.Package/Resources/Private/Translations/de_AT` were never read, only from`Packages/Application/Vendor.Package/Resources/Private/Translations/de`.
> BUGFIX: Restore XLIFF translation fallback

- TYPO3.Flow/Classes/TYPO3/Flow/Property/PropertyMapper.php
The exception message was way too technical and in a lot of cases contained the useless addition `, at property path ""`.
> TASK: Improve property mapping exception message

- Neos.Eel/Classes/Helper/StringHelper.php
With the introduction of literal type declarations in the unicode
functions class in Flow the behaviour of the StringHelper changed in
subtle ways. Previously, when a null value was used as input for e.g.
the crop function, it would silently cast to string and return an
empty string. Now an error is raised, breaking e.g. the use of node
properties that are lacking an empty string as default value (which
probably is true for 99% of string properties on nodes.)
This changes makes the StringHelper be tolerant towards non-string
input by adding explicit typecasts. Even in places where the implicit
casts are still in effect, simply to be very clear on the intention.
Fixes #1116
> BUGFIX: Handle non-string input in StringHelper

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/EntityManagerFactory.php
When specifying a unix socket for mysql connection, no host parameter must be given. As the code enforces a default value for host connection parameter, this simply adds a check to skip this if a unix socket is configured.
> BUGFIX: Allow using a unix socket for mysql connection

- TYPO3.Flow/Classes/TYPO3/Flow/Command/ResourceCommandController.php
**What I did**
`./flow resource:clean` was broken (`Call to a member function getName() on null`) because it could not remove a resource that referenced a file that didn't exist -> ends up in an exception.
`AssetRepository.removeWithoutUsageChecks()` was introduced in Neos 2.3/Flow 3.3.
> BUGFIX: Remove broken assets w/o executing usage checks (``flow resource:clean``)

- TYPO3.Fluid/Classes/TYPO3/Fluid/View/StandaloneView.php
If no request is passed to a freshly created ``StandaloneView`` it is now retrieved from the  ``RequestHandler`` instead of the old method which called ``createFromEnvironment`` (now used as fallback if ``RequestHandler`` is not an instance of ``HttpRequestHandlerInterface``).
The old implementation can lead to faulty behaviour if the current Request is needed within the view, especially when running Flow behind proxies.
> BUGFIX: Get current request for ``StandaloneView`` from ``RequestHandler``

- TYPO3.Flow/Classes/TYPO3/Flow/Error/Debugger.php
This fixes a warning in PHP 7.2
> BUGFIX: Debugger must not count uncountable

- TYPO3.Flow/Migrations/Mysql/Version20130319131400.php
- TYPO3.Flow/Migrations/Postgresql/Version20130319131500.php
The migration to adjust Role persistence reads YAML files to learn
about existing roles. It picked up "too much" sometimes, which would
lead to errors, e.g. if some YAML could not be parsed but was not at
all relevant for the task.
This change makes the check on the path of found files stricter to
avoid that.
> BUGFIX: No longer pick up too much YAML in migration

- Neos.Flow/Classes/ObjectManagement/Proxy/ProxyMethod.php
- Neos.Flow/Classes/Reflection/ClassReflection.php
- Neos.Flow/Classes/Reflection/MethodReflection.php
- Neos.Flow/Classes/Reflection/PropertyReflection.php
- Neos.Flow/Classes/Session/Session.php
- Neos.Flow/Classes/Session/SessionInterface.php
- Neos.Flow/Classes/Session/TransientSession.php
This is a (cosmetic) follow-up to #1126 reverting some
doc comment changes that were introduced by accident.
Related: #1120
> TASK: Revert some accidental doc comment changes

- Neos.Flow/Classes/Mvc/Routing/UriBuilder.php
- Neos.Flow/Classes/Security/Authentication/EntryPoint/WebRedirect.php
This partly reverts #1126 by casting the resolved URI so that
`UriBuilder::uriFor()` and `UriBuilder::build()` returns a
`string` again rather than an instance of `UriInterface`.
Background:
Even though `UriInterface` is mostly casted to a string implicitly,
this change was considered "too dangerous" for a minor release
because it breaks code that relies on the previous return type
(i.e. when serializing the resolved URI).
For the next major release we can re-consider this change.
Related: #1120
> TASK: Revert changed return type of `UriBuilder`-resolved URIs

- Neos.Flow/Scripts/PhpDevelopmentServerRouter.php
Removes usage of Files utility in ``PhpDevelopmentServerRouter.php``
in favor of the same code to determine the root of the installation
which is used in the command line init ``flow.php``.
> BUGFIX: Flow server init should not rely on Files utility

- Neos.Flow/Classes/Mvc/Routing/RouterCachingService.php
- Neos.Flow/Tests/Unit/Mvc/Routing/RouterCachingServiceTest.php
This is a follow up to #1126 fixing the automatic tagging of
routes in `RouterCachingService::storeResolvedUriConstraints()` that
no longer included the UUIDs of entities in route values.
Related: #1120
> BUGFIX: Tag routes with UUIDs of entities in route values

- Neos.Flow/Tests/Functional/Security/AuthenticationTest.php
This fixes the wrong order of expected and actual parameters to an
`assertSame()` call. Can be confusing if you check test results…
> TASK: Correct expected/actual order in assertion

- Neos.Flow/Classes/Mvc/Routing/RoutingComponent.php
**What I did**
When no route is found the NoMatchingRouteException is now thrown, which breaks up the http component chain, so the RedirectHandlerComponent is never reached.
This change swallows the exception.
Install the redirect handler extension and make sure the redirects work.
**Checklist**
> BUGFIX: catch NoMatchingRouteException to fix the RedirectHandler

- Neos.Flow/Classes/Command/RoutingCommandController.php
Before this fix, calling `./flow routing:routepath /somePath` will result in something like
```
Argument 1 passed to Neos\Flow\Mvc\Routing\Route_Original::matches() must be an instance of Neos\Flow\Mvc\Routing\Dto\RouteContext, instance of Neos\Flow\Http\Request given, called in /flowRootPath/Data/Temporary/Development/SubContextFritjofBohm/Cache/Code/Flow_Object_Classes/Neos_Flow_Command_RoutingCommandController.php on line 179
```
With this fix, the command uses the right DTOs that were introduced with 4.3.
> BUGFIX: routing:routepath command does not use routing DTOs

- Neos.Utility.Lock/Classes/FlockLockStrategy.php
- Neos.Utility.Lock/Classes/Lock.php
- Neos.Utility.Lock/Classes/LockManager.php
- Neos.Utility.Lock/Classes/LockStrategyInterface.php
- Neos.Utility.Lock/Tests/Unit/LockTest.php
This is only breaking for classes implementing `LockStrategyInterface`, whose signature now requires scalar typehints.
> !!!TASK: Add PHP 7.0 scalar type hints to method arguments and return types

- TYPO3.Flow/Classes/TYPO3/Flow/Object/Proxy/ProxyMethod.php
This is a follow-up to #1091 that didn't entirely fix the bug
mentioned in #1065.
Background:
When using the `void` return type annotation the corresponding
method must not return anything but by default the proxy method
is rendered like:
```
// ...
$result = parent::originalMethod();
return $result;
// ...
```
> BUGFIX: Respect `void` return type annotation in proxy method

- Neos.Flow/Resources/Private/Schema/Settings/Neos.Flow.persistence.schema.yaml
- Neos.Flow/Resources/Private/Schema/Settings/Neos.Flow.security.schema.yaml
The latest symfony yaml parser is much more strict. This PR fixes duplicate keys in schema files.
> BUGFIX: Fix duplicate configuration keys in schema files

- Neos.Flow/Classes/Persistence/Doctrine/EntityManagerConfiguration.php
If you instantiate an additional entityManager in order to connect
to a second database the mappingTypes are added again
which leads to an error.
> BUGFIX: Add doctrine mapping type only once

- .travis.yml
- Neos.Cache/composer.json
- Neos.Error.Messages/composer.json
- Neos.Flow.Log/composer.json
- Neos.Flow/Documentation/Quickstart/index.rst
- Neos.Flow/Documentation/TheDefinitiveGuide/PartII/Requirements.rst
- Neos.Flow/composer.json
- Neos.Utility.Arrays/composer.json
- Neos.Utility.Files/composer.json
- Neos.Utility.Lock/composer.json
- Neos.Utility.MediaTypes/composer.json
- Neos.Utility.ObjectHandling/composer.json
- Neos.Utility.OpcodeCache/composer.json
- Neos.Utility.Pdo/composer.json
- Neos.Utility.Schema/composer.json
- Neos.Utility.Unicode/composer.json
- composer.json
This raises the PHP version requirement for framework packages to
PHP 7.1 to be able to use a bunch of useful features for us in the
future.
Eg. iterable pseudo type, nullable types, void returns and more.
> !!!TASK: Require PHP 7.1

- TYPO3.Flow/Tests/Unit/Security/Cryptography/RsaWalletServicePhpTest.php
This change fixes `RsaWalletServicePhpTest` on recent Alpine Linux with
PHP 7.2 (at least, maybe other system can be affected too). I didn't find
a clear documentation about the reason of this failure:
1) Neos\Flow\Tests\Unit\Security\Cryptography\RsaWalletServicePhpTest::encryptingAndDecryptingBasicallyWorks
openssl_pkey_new(): private key length is too short; it needs to be at least 384 bits, not 0
/…/Classes/Security/Cryptography/RsaWalletServicePhp.php:92
/…/Tests/Unit/Security/Cryptography/RsaWalletServicePhpTest.php:49
This configuration is as light as possible to not slow down the test suite too much.
> BUGIFX: RsaWalletServicePhpTest broken depends on PHP configuration

- Neos.Flow/Classes/Property/TypeConverter/DateTimeConverter.php
- Neos.Flow/Tests/Unit/Property/TypeConverter/DateTimeConverterTest.php
This fixes support for mapping of `DateTimeImmutable` properties introduced
with #677.
Background:
If the source is an array (for example when specifying `date` as well as
`dateFormat`) the conversion fails because `DateTimeConverter::overrideTimeIfSpecified()`
still used the `DateTime` type hint.
This change adjusts the code so that it works with `DateTimeImmutable`
instances as well.
Related: #677
> BUGFIX: Fix DateTimeImmutable property mapping for custom date formats

- TYPO3.Flow/Classes/TYPO3/Flow/SignalSlot/Dispatcher.php
Signals can pass arguments to slots. These are amended with signal information,
if desired.
Because slots are hadled in a loop, and the passed signal arguments array was
used in that loop, the addition of the signal information was done mutliple
times, if requested.
This change makes sure that the signal information is only added once.
> BUGFIX: Pass signal information once, not once more for each slot

- Neos.Flow/Documentation/Quickstart/index.rst
The option --dev is deprecated. Dev packages are installed by default.
> DOCUMENTATION: Removed dev composer option since it's deprecated

- TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php
Sometimes a subcommand execution fails without a proper error message. And
it may happen that even the PHP error is empty at this point.
The error may be "Argument list too long", but this cannot be debugged
easily.
This change dumps the command that was to be executed into a file, if the
length of the command exceeds a threshhold. One can then run it manually
and hopefully see a helpful error message.
> TASK: Allow debugging of "silent command failures"

- Neos.Flow/Classes/Mvc/Routing/Dto/ResolveContext.php
- Neos.Flow/Classes/Mvc/Routing/Router.php
- Neos.Flow/Classes/Mvc/Routing/UriBuilder.php
- Neos.Flow/Tests/Functional/Mvc/RoutingTest.php
- Neos.Flow/Tests/Unit/Mvc/Routing/RouterTest.php
- Neos.Flow/Tests/Unit/Mvc/Routing/UriBuilderTest.php
This fixes a regression intdroduced with #1126 that prevented
the configured `baseUri` from being respected when building
URIs using the `UriBuilder`.
Background:
Instead of using the *Request URI* as base for generated URIs
this fix uses the *Request Base URI*.
Usually the result is the same, but not if a different `baseUri` is
configured from the one being requested.
Fixes: #1184
> BUGFIX: Respect configured baseUri when resolving URIs

- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Validation.rst
- Add code-block syntax to format php code as php code.
- Fix indentation in code example 
- Indent using spaces instead of tabs.
- Fix position of curly braces.
> TASK: Fix code format in docs

- Neos.Flow/Classes/Command/CacheCommandController.php
- Neos.Flow/Classes/Command/PackageCommandController.php
- Neos.Flow/Classes/Command/ResourceCommandController.php
- Neos.Flow/Classes/Command/SchemaCommandController.php
- Neos.Flow/Classes/Composer/InstallerScripts.php
- Neos.Flow/Classes/Configuration/ConfigurationSchemaValidator.php
- Neos.Flow/Classes/Core/Booting/Scripts.php
- Neos.Flow/Classes/I18n/Service.php
- Neos.Flow/Classes/I18n/Xliff/Service/XliffFileProvider.php
- Neos.Flow/Classes/Package.php
- Neos.Flow/Classes/Package/PackageManager.php
- Neos.Flow/Classes/Package/PackageManagerInterface.php
- Neos.Flow/Classes/Persistence/Doctrine/Service.php
- Neos.Flow/Classes/Reflection/ReflectionService.php
- Neos.Flow/Classes/ResourceManagement/Storage/PackageStorage.php
- Neos.Flow/Tests/Functional/Configuration/ConfigurationValidationTest.php
- Neos.Flow/Tests/Functional/Configuration/SchemaValidationTest.php
- Neos.Flow/Tests/Functional/I18n/Xliff/Service/XliffFileProviderTest.php
- Neos.Flow/Tests/Functional/Mvc/RoutingTest.php
- Neos.Flow/Tests/Functional/Mvc/ViewsConfiguration/ViewsConfigurationTest.php
- Neos.Flow/Tests/Unit/I18n/ServiceTest.php
- Neos.Flow/Tests/Unit/Package/PackageManagerTest.php
- Neos.Flow/Tests/Unit/ResourceManagement/Target/FileSystemTargetTest.php
- Neos.FluidAdaptor/Classes/Core/ViewHelper/ViewHelperResolver.php
- Neos.FluidAdaptor/Classes/Package.php
- Neos.FluidAdaptor/Classes/View/TemplatePaths.php
Packages no longer have state, they are either available or not
available entirely depending on the fact if they are installed.
The API is changed accordingly to reflect this change.
The implemented ``PackageManager`` still supports the
``getActivePackages`` and ``isPackageActive`` methods for
backwards compatibility but both are deprecated and removed from
the interface.
This is breaking if you rely on the functionality and requires
future changes if you use the deprecated methods.
> !!!TASK: Remove deactivating packages from the package manager

- Neos.FluidAdaptor/Classes/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php
- Neos.FluidAdaptor/composer.json
- composer.json
Pulling in the latest improvements in Fluid.
One major improvement is the addition of an escaping toggle: 
```
{escaping off}
```
In a template, layout or partial. When toggled off it causes the template parser to skip escaping of all outputs from ViewHelpers, variable outputs etc.
For legacy reasons the feature is added with backwards compatibility for the original escaping modifier. Therefore, the following values are all equally possible and mean the same:
```
{escaping off}
{escapingEnabled off}
{escaping false}
{escaping=false}
{escaping=off}
{escaping = off}
{escapingEnabled = off}
{escapingEnabled = false}
{escapingEnabled off}
{escapingEnabled false}
```
> TASK: Update standalone Fluid to 2.3.x

- Neos.Flow/Classes/ObjectManagement/ObjectManager.php
- Neos.Flow/Classes/ObjectManagement/ObjectManagerInterface.php
Makes the ``ObjectManagerInterface`` fully compatible with
the PSR-11 ``ContainerInterface``.
This is a breaking change in case you implemented
``ObjectManagerInterface`` because you would have to implement the
``has`` method now in your implementation.
> !!! TASK: Make ObjectManagerInterface a superset of PSR-11

- Neos.Eel/Classes/Helper/JsonHelper.php
This feature adds the possibility to pass option constants to the Json.stringify Eel helper. This is needed for example if you want to have unescaped UTF8 characters in the output.
The usage looks like this:
@process.jsonStringify = ${Json.stringify(value, ['JSON_UNESCAPED_UNICODE', 'JSON_FORCE_OBJECT'])}
It may look a bit weird on the first look to pass PHP options to a Javascript-like function. But its a PHP method in the end that does the encoding, so the PHP constants are the right options here.
> FEATURE: Add PHPs json_encode options to stringify eel helper

- Neos.FluidAdaptor/Classes/ViewHelpers/Security/IfAccessViewHelper.php
- Neos.FluidAdaptor/Classes/ViewHelpers/Security/IfHasRoleViewHelper.php
This change avoid the following exception:
Argument "then" has already been defined, thus it should not be defined again.
> TASK: Adapt Security ViewHelpers to support recent Fluid version

- Neos.Flow/Classes/Cli/ConsoleOutput.php
- Neos.Flow/Tests/Unit/Cli/ConsoleOutputTest.php
Due to the upgrade to symfony/console 4.0 some implementations for utilized CLI helpers changed. 
Unit tests were added for all console output helpers to prevent similar breakdowns in the future.
regression https://github.com/neos/flow-development-collection/pull/1179
> BUGFIX: Fix deprecated Symfony console helper implementations

- Neos.Flow/Classes/Persistence/Doctrine/Repository.php
- Neos.Flow/Classes/Persistence/Repository.php
- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Persistence.rst
- Neos.Flow/Tests/Functional/Persistence/Doctrine/RepositoryTest.php
- Neos.Flow/Tests/Functional/Persistence/Fixtures/SubSubEntityRepository.php
- Neos.Flow/Tests/Functional/Persistence/Fixtures/SuperEntityRepository.php
> If the amount of the stored data increases, receiving all objects using a ``findAll()`` may
> consume a lot more memory than available. In this cases, you should use the ``findAllIterator()``.
> This method returns an ``IterableResult``over which you can iterate, getting only one object at a time.
As this pattern is used a lot in Neos repositories, it would make sense to move it to the base repository class.
> FEATURE: Introduce findAllIterator() method

- Neos.Flow/Tests/Functional/Persistence/Aspect/PersistenceMagicAspectTest.php
These tests were skipped since it was adapted to new namespaces
because a wrong use statement was added back then.
This brings back 14 tests by fixing that.
> TASK: Re-enable PersistenceMagicAspectTest

- Neos.Flow/Classes/Security/Authentication/AuthenticationProviderInterface.php
- Neos.Flow/Classes/Security/Authentication/AuthenticationProviderManager.php
- Neos.Flow/Classes/Security/Authentication/Provider/AbstractProvider.php
- Neos.Flow/Tests/Unit/Security/Authentication/Provider/FileBasedSimpleKeyProviderTest.php
- Neos.Flow/Tests/Unit/Security/Authentication/Provider/PersistedUsernamePasswordProviderTest.php
There was a long standing comment about having the constructor be part
of the interface but that was deactivated back in the day as the proxy
constructor was incompatible with the interface then. A interface
defined way of creating an ``AuthenticationProvider`` makes sense though
therefore we introduce a static ``create`` method that returns a fresh
instance of the class in question. This removes the implicit knowledge
about the constructor in the code.
This is breaking if you implemented your own
``AuthenticationProviderInterface`` without making use of the
``AbstractProvider`` which provides a basic ``create`` method.
You may need to add this create method in your implementation.
> !!! TASK: Add factory method to ``AuthenticationProviderInterface``

- Neos.Cache/Classes/Backend/RedisBackend.php
The `set()` call returns a boolean, so the check `instanceof \Redis` always fails.
That means on every set, the "supported version check" is run.
> BUGFIX: Avoid useless calls to verifyRedisVersionIsSupported()

- Neos.Flow/Classes/Utility/Now.php
This simply replaces Now's base class \DateTime with \DateTimeImmutable as planned since 4.0
> TASK: Make Now immutable

- TYPO3.Flow/composer.json
The `paragonie/random_compat` library could use OpenSSL, and that in turn
could lead to the use of an insecure CSPRNG (openssl_random_pseudo_bytes())
Related Information: https://github.com/paragonie/random_compat/issues/96
This change fixes #1222 by updating the dependency from `^1.0` to `^2.0`.
> SECURITY: Update paragonie/random_compat to 2.x minimum

- Neos.Eel/Classes/FlowQuery/Operations/AddOperation.php
- Neos.Eel/Classes/FlowQuery/Operations/RemoveOperation.php
- Neos.Eel/Tests/Unit/FlowQuery/Operations/RemoveOperationTest.php
The operation removes the given items from the current FlowQuery context. To do so it accepts a single argument that may be an array, an object or a FlowQuery.
> FEATURE: Add `remove` flowQuery operation

- Neos.Flow/Classes/Mvc/Routing/ObjectPathMappingRepository.php
The `ObjectPathMappingRepository.persistEntities()` method looped over
the entities and passed them to `flush()` one-by-one. They can be passed
as the array at hand directly.
> TASK: Pass affected entities to flush as array, not one-by-one

- Neos.Flow/Classes/Command/RoutingCommandController.php
- Neos.Flow/Classes/Http/Client/InternalRequestEngine.php
- Neos.Flow/Classes/Mvc/Routing/RoutingComponent.php
- Neos.Flow/Configuration/Objects.yaml
Currently the concrete `Router` Implementation is used instead of the more flexible `RouterInterface`.
This PR ensures the `RouterInterface` is used.
> TASK: Use RouterInterface instead of concrete implementation

- TYPO3.Flow/Classes/TYPO3/Flow/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php
After fixing the issue #1079, orphan removal is per default false for properties from classes which are no aggregate roots, because the default value for orphan removal in the ManyToMany, OneToOne and OneToMany annotations is "false".
Unfortunately we can not prevent the default value in the annotation, so we can not rely on the property not being set to fall back to our defaults.
This change Fixes that by switching the check for orphanRemoval annotation value fallbacks and always apply our default value for non-aggregate root non-value objects.
Fixes #1127
> BUGFIX: Set orphanRemoval for non-AggregateRoots

- Neos.Flow/Tests/Unit/Log/Backend/FileBackendTest.php
The needed support for touch() and rename() in vfsStream exists by now.
> TASK: Enable test for log rotation in FileBackend

- Neos.Flow/Classes/I18n/Cldr/Reader/CurrencyReader.php
- Neos.Flow/Classes/I18n/Formatter/NumberFormatter.php
- Neos.Flow/Configuration/Caches.yaml
- Neos.Flow/Configuration/Objects.yaml
- Neos.Flow/Tests/Unit/I18n/Cldr/Reader/CurrencyReaderTest.php
- Neos.Flow/Tests/Unit/I18n/Formatter/NumberFormatterTest.php
- Neos.FluidAdaptor/Classes/ViewHelpers/Format/CurrencyViewHelper.php
Some currencies have specific rules for their formatting, overriding
the rules that might be used to format for a given locale. The Japanese
Yen for example never has decimal digits, and the Swiss Franc is rounded
using five decimals.
This change adds support for that. The CurrencyViewHelper accepts an
optional `currencyCode` argument now and passes it down to the method
`formatCurrencyNumber` in `NumberFormatter` doing the actual work.
> FEATURE: Allow to use CLDR to format currency

- Neos.Flow/Classes/Configuration/ConfigurationManager.php
the following happens in Production context, if letting the CLI compile request run through, but abort the web request.
In this case:
- the cached Configurations.php object does *not* contain information for NodeTypes etc.
- thus, node types are loaded on every request
- this leads to a slow system which can only be fixed by removing the cached Configuration file.
To solve this issue, we now check whether the unprocessed configuration contains the right infos before serializing them.
> BUGFIX: if cached configuration does not contain all configuration types, ensure on next run the configuration is cached again

- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Caching.rst
In the caching section the flow package name was still TYPO3.Flow.
So this PR changes the package name to the current Neos.Flow.
> TASK: Change package name to Neos.Flow

- Neos.Flow/Classes/Security/RequestPatternInterface.php
This is a noop as the code was already commented and there
only for reference apparently.
> TASK: Remove commented ``get``/``set`` Pattern

- Neos.FluidAdaptor/Classes/Core/Rendering/RenderingContext.php
This method was deprecated with the switch to standalone Fluid in
Flow 4.0 to get closer to the ``RenderingContext`` in the base
package. It is therefore now removed.
Any calls to ``getTemplateVariableContainer`` can be replaced with calls to
``getVariableProvider``.
> !!! TASK: Remove ``getTemplateVariableContainer`` method

- Neos.Flow/Classes/Configuration/ConfigurationManager.php
Unless someone upgrades straight to 5.0 from versions <3.0 this
configuration shouldn't be in anything anymore. Therefore we
should be able to safely remove the check and safe some resources
in the ``ConfigurationManager``.
> TASK: Remove checks for old (pre 3.0) Policy configuration

- Neos.Flow/Classes/Reflection/ReflectionService.php
- Neos.Flow/Tests/Unit/Package/PackageManagerTest.php
Use static ``TypeHandling::getTypeForValue`` as immediate replacement.
> !!! TASK: Remove deprecated ``getClassNameByObject``

- Neos.FluidAdaptor/Classes/ViewHelpers/Form/AbstractFormFieldViewHelper.php
The ``getValue`` method was deprecated since Flow 3.0 and should be
replaced with calls to ``getValueAttribute()`` and if applicable
to ``addAdditionalIdentityPropertiesIfNeeded()``.
> !!! TASK: Remove ``getValue`` from ``AbstractFormFieldViewHelper``

- Neos.Flow/Configuration/Settings.I18n.yaml
- Neos.Flow/Documentation/TheDefinitiveGuide/PartIII/Internationalization.rst
- Neos.Flow/Tests/Unit/I18n/ServiceTest.php
Before the full `Resources/Private` folder was scanned for available locales, which also included
for example the CLDR, which ended up filling the available locales with much more locales than
are actually considered "available" in a normal Flow application.
This will therefore allow applications to define available locales easily from the Translations
provided.
This is breaking, because it will end up with less available locales by default, since only the
locales of Flow Translations are considered available, instead of all of CLDR locales.
Related to #1232
> !!!TASK: Only scan Private/Translations for available locales
